---
permalink: api-automation/concept_manage_access_endpoint.html 
sidebar: sidebar 
keywords: manage, endpoints, access 
summary: Storage Virtual Machine （ SVM ）、 LUN 、およびファイル共有のプロビジョニングに必要なアクセスエンドポイントまたは論理インターフェイス（ LIF ）を作成する必要があります。Active IQ Unified Manager 環境内の SVM 、 LUN 、またはファイル共有のアクセスエンドポイントを表示、作成、変更、および削除できます。 
---
= アクセスエンドポイントの管理
:icons: font
:imagesdir: ../media/


[role="lead"]
Storage Virtual Machine （ SVM ）、 LUN 、およびファイル共有のプロビジョニングに必要なアクセスエンドポイントまたは論理インターフェイス（ LIF ）を作成する必要があります。Active IQ Unified Manager 環境内の SVM 、 LUN 、またはファイル共有のアクセスエンドポイントを表示、作成、変更、および削除できます。



== アクセスエンドポイントを表示します

Unified Manager 環境のアクセスエンドポイントのリストを表示するには、次のメソッドを使用します。特定の SVM 、 LUN 、またはファイル共有のアクセスエンドポイントのリストを照会するには、 SVM 、 LUN 、またはファイル共有の一意の識別子を入力する必要があります。一意のアクセスエンドポイントキーを入力して、特定のアクセスエンドポイントの詳細を取得することもできます。

[cols="3*"]
|===
| カテゴリ | HTTP 動詞 | パス 


 a| 
ストレージプロバイダ
 a| 
取得
 a| 
「 /storage-provider/access-endpoints 」と入力します

「 /storage-provider/access-endpoints \\{key}` 」と入力します

|===


== アクセスエンドポイントを追加する

カスタムのアクセスエンドポイントを作成して、必要なプロパティを割り当てることができます。作成するアクセスエンドポイントの詳細を、入力パラメータとして指定する必要があります。この API 、または System Manager または ONTAP CLI を使用して、各ノードにアクセスエンドポイントを作成できます。アクセスエンドポイントの作成では、 IPv4 アドレスと IPv6 アドレスの両方がサポートされます。

[NOTE]
====
LUN とファイル共有をプロビジョニングするためには、 SVM にノードあたりの最小アクセスエンドポイント数を設定する必要があります。SVM には、ノードごとに少なくとも 2 つのアクセスエンドポイントを設定する必要があります。 1 つは CIFS プロトコルおよび / または NFS プロトコルをサポートし、もう 1 つは iSCSI プロトコルまたは FCP プロトコルをサポートします。

====
[cols="3*"]
|===
| カテゴリ | HTTP 動詞 | パス 


 a| 
ストレージプロバイダ
 a| 
投稿（ Post ）
 a| 
「 /storage-provider/access-endpoints 」と入力します

|===


== アクセスエンドポイントを削除する

特定のアクセスエンドポイントを削除するには、次のメソッドを使用します。特定のアクセスエンドポイントを削除するには、入力パラメータとしてアクセスエンドポイントキーを指定する必要があります。

[cols="3*"]
|===
| カテゴリ | HTTP 動詞 | パス 


 a| 
ストレージプロバイダ
 a| 
削除
 a| 
「 /storage-provider/access-endpoints \\{key}` 」と入力します

|===


== アクセスエンドポイントを変更します

アクセスエンドポイントを変更し、そのプロパティを更新するには、次のメソッドを使用します。特定のアクセスエンドポイントを変更するには、アクセスエンドポイントキーを指定する必要があります。また、更新するプロパティとその値を入力する必要があります。

[cols="3*"]
|===
| カテゴリ | HTTP 動詞 | パス 


 a| 
ストレージプロバイダ
 a| 
パッチ
 a| 
「 /storage-provider/access-endpoints \\{key}` 」と入力します

|===