---
permalink: api-automation/concept_job_api.html 
sidebar: sidebar 
keywords: jobs, view 
summary: management-server カテゴリのジョブ API を使用すると、非同期処理の実行の詳細を表示できます。 
---
= ジョブとシステムの詳細を表示する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「管理サーバ」カテゴリの「ジョブ」 API を使用して、非同期操作の実行の詳細を表示できます。「管理サーバ」カテゴリの「システム」 API を使用すると、 Active IQ Unified Manager 環境内のインスタンスの詳細を表示できます。



== ジョブを表示

Active IQ Unified Manager では、リソースの追加や変更などの処理は、同期および非同期の API 呼び出しによって実行されます。非同期で実行されるようにスケジュールされている呼び出しは、その呼び出しに対して作成されたジョブオブジェクトによって追跡できます。各ジョブオブジェクトには、識別用の一意のキーがあります。各ジョブオブジェクトはジョブオブジェクト URI を返し、ジョブの進捗状況を確認および追跡できます。この API を使用して、各実行の詳細を取得できます。

この API を使用して、履歴データを含む、データセンターのすべてのジョブオブジェクトを照会できます。デフォルトですべてのジョブを照会すると、 Web UI および API インターフェイスからトリガーされた最新 20 件のジョブの詳細が返されます。組み込みのフィルタを使用して、特定のジョブを表示します。ジョブキーを使用して特定のジョブの詳細を照会し、リソースに対して次の処理セットを実行することもできます。

[cols="4*"]
|===
| カテゴリ | HTTP 動詞 | パス | 説明 


 a| 
management-server
 a| 
取得
 a| 
「 /management-server /jobs 」
 a| 
すべてのジョブのジョブ詳細を返します。ソート順が指定されていない場合は、最後に送信されたジョブオブジェクトが先頭に返されます。



 a| 
management-server
 a| 
取得
 a| 
「 /management-server /jobs/\{key}` 」と入力します

ジョブオブジェクトのジョブキーを入力して、そのジョブの具体的な詳細を表示します。
 a| 
特定のジョブオブジェクトの詳細を返します。

|===


== システムの詳細を表示します

「 /management-server / system 」 API を使用すると、インスタンス固有の Unified Manager 環境の詳細を照会できます。API から返される製品とサービスに関する情報には、システムにインストールされている Unified Manager のバージョン、 UUID 、ベンダー名、ホスト OS 、名前、 概要、および Unified Manager インスタンスで実行されているサービスのステータス。

[cols="4*"]
|===
| カテゴリ | HTTP 動詞 | パス | 説明 


 a| 
management-server
 a| 
取得
 a| 
「 /management-server / system 」
 a| 
この API を実行するために入力パラメータは必要ありません。デフォルトでは、現在の Unified Manager インスタンスのシステムの詳細が返されます。

|===