---
permalink: api-automation/concept_manage_psl.html 
sidebar: sidebar 
keywords: manage, performance, service, level 
summary: Active IQ Unified Manager でストレージプロバイダ API を使用して、パフォーマンスサービスレベルを表示、作成、変更、および削除できます。 
---
= APIを使用してパフォーマンスサービスレベルを管理する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Manager でストレージプロバイダ API を使用して、パフォーマンスサービスレベルを表示、作成、変更、および削除できます。



== パフォーマンスサービスレベルを表示します

ストレージワークロードに割り当てる際にパフォーマンスサービスレベルを表示するには、次のメソッドを使用します。この API は、システム定義およびユーザ作成のすべてのパフォーマンスサービスレベルを表示し、すべてのパフォーマンスサービスレベルの属性を取得します。特定のパフォーマンスサービスレベルを照会する場合は、パフォーマンスサービスレベルの一意の ID を入力して詳細を取得する必要があります。

[cols="3*"]
|===
| カテゴリ | HTTP 動詞 | パス 


 a| 
ストレージプロバイダ
 a| 
取得
 a| 
「 /storage-provider/performion-service-levels 」と入力します

「 /storage-provider/performion-service-levels /\{key} 」のように指定します

|===


== パフォーマンスサービスレベルを追加

システム定義のパフォーマンスサービスレベルがストレージワークロードに必要なサービスレベル目標（ SLO ）を満たしていない場合は、次のメソッドでカスタムパフォーマンスサービスレベルを作成し、ストレージワークロードに割り当てることができます。作成するパフォーマンスサービスレベルの詳細を入力します。IOPS プロパティには、有効な値の範囲を入力してください。

[cols="3*"]
|===
| カテゴリ | HTTP 動詞 | パス 


 a| 
ストレージプロバイダ
 a| 
投稿（ Post ）
 a| 
「 /storage-provider/performion-service-levels 」と入力します

|===


== パフォーマンスサービスレベルを削除します

特定のパフォーマンスサービスレベルを削除するには、次のメソッドを使用します。ワークロードに割り当てられている場合、または他に使用可能なパフォーマンスサービスレベルがない場合、そのパフォーマンスサービスレベルは削除できません。特定のパフォーマンスサービスレベルを削除するには、パフォーマンスサービスレベルの一意の ID を入力パラメータとして指定する必要があります。

[cols="3*"]
|===
| カテゴリ | HTTP 動詞 | パス 


 a| 
ストレージプロバイダ
 a| 
削除
 a| 
「 /storage-provider/performion-service-levels /\{key} 」のように指定します

|===


== パフォーマンスサービスレベルの変更

パフォーマンスサービスレベルを変更してそのプロパティを更新するには、次のメソッドを使用します。システム定義のパフォーマンスサービスレベル、またはワークロードに割り当てられているパフォーマンスサービスレベルは変更できません。特定のパフォーマンスサービスレベルを変更するには、の一意の ID を指定する必要があります。また、更新する IOPS プロパティと有効な値も入力する必要があります。

[cols="3*"]
|===
| カテゴリ | HTTP 動詞 | パス 


 a| 
ストレージプロバイダ
 a| 
パッチ
 a| 
「 /storage-provider/performion-service-levels /\{key} 」のように指定します

|===


== パフォーマンス サービス レベルに基づいて集計機能を表示する

パフォーマンスサービスレベルに基づいてアグリゲート機能を照会するには、次のメソッドを使用します。この API は、データセンターで使用可能なアグリゲートのリストを返し、それらのアグリゲートでサポート可能なパフォーマンスサービスレベルに関する機能を示します。ボリュームでワークロードをプロビジョニングする際に、特定のパフォーマンスサービスレベルをサポートするアグリゲートの機能を表示し、その機能に基づいてワークロードをプロビジョニングできます。アグリゲートを指定できるのは、 API を使用してワークロードをプロビジョニングする場合のみです。この機能は Unified Manager Web UI では使用できません。

[cols="3*"]
|===
| カテゴリ | HTTP 動詞 | パス 


 a| 
ストレージプロバイダ
 a| 
取得
 a| 
「 /storage-provider/aggregate-capabilities' 」のようになります

「 /storage-provider/aggregate-capabilities/\{key} 」のようになります

|===