---
permalink: api-automation/concept_manage_sep.html 
sidebar: sidebar 
keywords: manage, storage, efficiency, policy 
summary: ストレージプロバイダ API を使用して、ストレージ効率化ポリシーを表示、作成、変更、および削除できます。 
---
= APIを使用してストレージ効率ポリシーを管理する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージプロバイダ API を使用して、ストレージ効率化ポリシーを表示、作成、変更、および削除できます。

[NOTE]
====
次の点に注意してください。

* Unified Manager でワークロードを作成する場合、ストレージ効率化ポリシーの割り当ては必須ではありません。
* ポリシーが割り当てられたあとで、ワークロードからストレージ効率化ポリシーの割り当てを解除することはできません。
* 重複排除や圧縮など、 ONTAP で指定されたストレージ設定がワークロードに含まれている場合、 Unified Manager でストレージワークロードを追加するときに適用するストレージ効率化ポリシーの設定で、その設定を上書きすることができます。


====


== ストレージ効率化ポリシーを表示します

ストレージワークロードに割り当てる前にストレージ効率化ポリシーを表示するには、次のメソッドを使用します。この API は、システム定義およびユーザ作成のすべてのストレージ効率化ポリシーを表示し、すべてのストレージ効率化ポリシーの属性を取得します。特定のストレージ効率化ポリシーを照会するには、ポリシーの一意の ID を入力して詳細を取得する必要があります。

[cols="3*"]
|===
| カテゴリ | HTTP 動詞 | パス 


 a| 
ストレージプロバイダ
 a| 
取得
 a| 
「 /storage-provider/storage-efficiency policies 」のように入力します

「 /storage-provider/storage-efficiency policies/\{key}` 」を使用します

|===


== ストレージ効率化ポリシーを追加します

システム定義のポリシーがストレージワークロードのプロビジョニング要件を満たしていない場合は、次のメソッドでカスタムのストレージ効率化ポリシーを作成し、ストレージワークロードに割り当てることができます。作成するストレージ効率化ポリシーの詳細を入力パラメータとして指定します。

[cols="3*"]
|===
| カテゴリ | HTTP 動詞 | パス 


 a| 
ストレージプロバイダ
 a| 
投稿（ Post ）
 a| 
「 /storage-provider/storage-efficiency policies 」のように入力します

|===


== ストレージ効率化ポリシーを削除します

特定のストレージ効率化ポリシーを削除するには、次のメソッドを使用します。ワークロードに割り当てられている場合、または他に使用可能なストレージ効率化ポリシーがない場合、そのストレージ効率化ポリシーは削除できません。特定のストレージ効率化ポリシーを削除するには、ストレージ効率化ポリシーの一意の ID を入力パラメータとして指定する必要があります。

[cols="3*"]
|===
| カテゴリ | HTTP 動詞 | パス 


 a| 
ストレージプロバイダ
 a| 
削除
 a| 
「 /storage-provider/storage-efficiency policies/\{key}` 」を使用します

|===


== ストレージ効率化ポリシーの変更

ストレージ効率化ポリシーを変更し、そのプロパティを更新するには、次のメソッドを使用します。システム定義のストレージ効率化ポリシー、またはワークロードに割り当てられているストレージ効率化ポリシーは変更できません。特定のストレージ効率化ポリシーを変更するには、ストレージ効率化ポリシーの一意の ID を指定する必要があります。また、更新するプロパティとその値を指定する必要があります。

[cols="3*"]
|===
| カテゴリ | HTTP 動詞 | パス 


 a| 
ストレージプロバイダ
 a| 
パッチ
 a| 
「 /storage-provider/storage-efficiency policies/\{key}` 」を使用します

|===