---
permalink: api-automation/concept_provision_workflow.html 
sidebar: sidebar 
keywords: workflow, workload, management 
summary: Active IQ Unified Manager を使用して、ストレージワークロード（ LUN 、 NFS ファイル共有、 CIFS 共有）をプロビジョニングおよび変更できます。プロビジョニングは、 Storage Virtual Machine （ SVM ）の作成から、ストレージワークロードへのパフォーマンスサービスレベルポリシーとストレージ効率化ポリシーの適用まで、複数の手順で構成されます。ワークロードの変更は、特定のパラメータの変更と、パラメータでの追加機能の有効化で構成されます。 
---
= ワークロード管理のワークフロー
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Manager を使用して、ストレージワークロード（ LUN 、 NFS ファイル共有、 CIFS 共有）をプロビジョニングおよび変更できます。プロビジョニングは、 Storage Virtual Machine （ SVM ）の作成から、ストレージワークロードへのパフォーマンスサービスレベルポリシーとストレージ効率化ポリシーの適用まで、複数の手順で構成されます。ワークロードの変更は、特定のパラメータの変更と、パラメータでの追加機能の有効化で構成されます。

次のワークフローについて説明します。

* Unified Manager で Storage Virtual Machine （ SVM ）をプロビジョニングするためのワークフロー
+
[NOTE]
====
このワークフローは、 Unified Manager で LUN またはファイル共有をプロビジョニングする前に実行する必要があります。

====
* ファイル共有のプロビジョニング
* LUN のプロビジョニング
* LUN とファイル共有の変更（ストレージワークロードのパフォーマンスサービスレベルパラメータの更新例を使用）
* CIFS プロトコルをサポートするための NFS ファイル共有の変更
* QoS を AQoS にアップグレードするためのワークロードの変更


[NOTE]
====
各プロビジョニングワークフロー（ LUN およびファイル共有）では、クラスタの SVM を確認するワークフローを完了しておく必要があります。

====
また、ワークフローで各 API を使用する前に、推奨事項と制限事項を確認しておく必要があります。API の詳細については、関連する概念および資料に記載されている個々のセクションを参照してください。
