---
permalink: api-automation/concept_security_apis.html 
sidebar: sidebar 
keywords: manage, user 
summary: セキュリティカテゴリの API を使用して、 Active IQ Unified Manager 内の選択したクラスタオブジェクトへのユーザアクセスを制御できます。ローカルユーザまたはデータベースユーザを追加できます。また、認証サーバに属するリモートユーザやリモートグループを追加することもできます。ユーザに割り当てたロールの権限に基づいて、ストレージオブジェクトを管理したり、 Unified Manager でデータを表示したりできます。 
---
= ユーザの管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「セキュリティ」カテゴリの API を使用して、 Active IQ Unified Manager 内の選択したクラスタオブジェクトへのユーザアクセスを制御できます。ローカルユーザまたはデータベースユーザを追加できます。また、認証サーバに属するリモートユーザやリモートグループを追加することもできます。ユーザに割り当てたロールの権限に基づいて、ストレージオブジェクトを管理したり、 Unified Manager でデータを表示したりできます。

[NOTE]
====
これらの処理を実行するには、アプリケーション管理者ロールが必要です。また、 Unified Manager Web UI を使用してこれらの設定を行うこともできます。

====
「セキュリティ」カテゴリの API では、ユーザパラメータである「ユーザ」パラメータを使用します。キーパラメータはユーザエンティティの一意の識別子ではありません。

[cols="3*"]
|===
| HTTP 動詞 | パス | 説明 


 a| 
「 GET 」

「 POST 」
 a| 
「 /security/users 」と入力します

「 /security/users 」と入力します
 a| 
これらのメソッドを使用して、ユーザの詳細を取得したり、 Unified Manager に新しいユーザを追加したりできます。

ユーザのタイプに基づいて、ユーザに特定のロールを追加できます。ユーザを追加する際には、ローカルユーザ、メンテナンスユーザ、およびデータベースユーザのパスワードを指定する必要があります。



 a| 
「 GET 」

「 PATCH 」

「削除」
 a| 
「 /security/users/\{name}` 」と入力します
 a| 
GET メソッドを使用すると、名前、 E メールアドレス、ロール、認証タイプなど、ユーザのすべての詳細を取得できます。PATCH メソッドで詳細を更新できます。削除メソッドを使用すると、ユーザを削除できます。

|===