---
permalink: api-automation/concept_workflow_intro.html 
sidebar: sidebar 
keywords: common, workflows, storage, management 
summary: この一般的なワークフローは、クライアントアプリケーション開発者向けに、クライアントアプリケーションから Active IQ Unified Manager API を呼び出して一般的なストレージ管理機能を実行する方法を示します。ここでは、これらのサンプルワークフローの一部を紹介します。 
---
= ストレージ管理のための一般的なAPIワークフロー
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
この一般的なワークフローは、クライアントアプリケーション開発者向けに、クライアントアプリケーションから Active IQ Unified Manager API を呼び出して一般的なストレージ管理機能を実行する方法を示します。ここでは、これらのサンプルワークフローの一部を紹介します。

ワークフローごとに、代表的なストレージ管理のユースケースと、使用するサンプルコードを記載します。各タスクについて、 1 つ以上の API 呼び出しで構成されるワークフロープロセスを使用して説明します。



== ワークフローで使用する API 呼び出しについて

Unified Manager インスタンスから、すべての REST API 呼び出しの詳細を含むオンラインドキュメントページを表示できます。このドキュメントでは、オンラインドキュメントの詳細については説明しません。このドキュメントのワークフローサンプルで使用されている各 API 呼び出しには、ドキュメントページで呼び出しを検索するために必要な情報だけが含まれています。特定の API 呼び出しを検索すると、入力パラメータ、出力形式、 HTTP ステータスコード、要求処理タイプなど、呼び出しのすべての詳細を確認できます。

ワークフロー内の各 API 呼び出しについて、ドキュメントページで検索するのに役立つ次の情報が含まれています。

* カテゴリ：ドキュメントページでは、機能的な関連領域またはカテゴリ別に API 呼び出しが分類されています。特定の API 呼び出しを検索するには、ページの一番下までスクロールして、該当する API カテゴリをクリックします。
* HTTP 動詞（呼び出し）： HTTP 動詞は、リソースに対して実行する操作を示します。各 API 呼び出しは、単一の HTTP 動詞を使用して実行されます。
* パス：このパスは、呼び出しの実行中に環境が処理する特定のリソースを指定します。パス文字列がコア URL に追加され、リソースを識別する完全な URL が形成されます。

