---
permalink: api-automation/concept_events_api.html 
sidebar: sidebar 
keywords: view, events, system, details 
summary: イベント API を使用すると、データセンター内の監視対象クラスタに対して生成されたイベントを取得できます。 
---
= イベントとアラートの管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「イベント」、「アラート」、「管理サーバ」カテゴリの「スクリプト」 API を使用すると、 Active IQ Unified Manager 環境でのアラートに関連付けられたイベント、アラート、およびスクリプトを管理できます。



== イベントを表示および変更する

Unified Manager は、 Unified Manager で監視および管理されているクラスタについて ONTAP で生成されたイベントを受信します。これらの API を使用して、クラスタに対して生成されたイベントを表示し、解決および更新することができます。

「 /management-server/events 」 API の「 get 」メソッドを実行すると、履歴データを含むデータセンター内のイベントを照会できます。名前、インパクトレベル、インパクトエリア、重大度などの組み込みフィルタを使用します。 特定のイベントを表示するには、状態、リソース名、およびリソースタイプを指定します。リソースタイプと領域パラメータは、イベントが発生したストレージオブジェクトに関する情報を返し、影響領域は、可用性、容量、構成、セキュリティなど、イベントが発生した問題に関する情報を返します。 保護とパフォーマンス：

この API の PATCH 処理を実行すると、イベントの解決ワークフローを有効にすることができます。イベントを自分または別のユーザに割り当てて、イベントの受信を確認することができます。リソースに対して手順を実行してイベントをトリガーした問題を解決すると、この API を使用してイベントを解決済みとしてマークできます。

イベントの詳細については、を参照してください link:../events/concept_manage_events.html["イベントの管理"]

[cols="4*"]
|===
| カテゴリ | HTTP 動詞 | パス | 説明 


 a| 
management-server
 a| 
取得
 a| 
「 /management-server /events 」「 /management-server /events/{key} 」
 a| 
GET All メソッドを実行すると、応答の本文にはデータセンター内のすべてのイベントの詳細が含まれます。特定のキーを使用してイベントの詳細を取得すると、特定のイベントの詳細を表示し、リソースに対して次の処理を実行できます。応答の本文は、そのイベントの詳細で構成されます。



 a| 
management-server
 a| 
パッチ
 a| 
「 management-server /events/{key}`
 a| 
この API を実行してイベントを割り当てるか、または状態を acknowledged または Resolved に変更します。このメソッドを使用して、自分または別のユーザにイベントを割り当てることもできます。これは同期操作です。

|===


== アラートの管理

イベントは自動的かつ継続的に生成されます。Unified Manager では、イベントが特定のフィルタ条件を満たしている場合にのみアラートが生成されます。アラートを生成するイベントを選択できます。/management-server/alerts API を使用すると ' 特定の重大度タイプのイベントまたはイベントが発生したときに自動的に通知を送信するようにアラートを設定できます

アラートの詳細については、を参照してください link:../events/concept_manage_alerts.html["アラートの管理"]

[cols="4*"]
|===
| カテゴリ | HTTP 動詞 | パス | 説明 


 a| 
management-server
 a| 
取得
 a| 
「 /management-server /alerts 」 /management-server /alerts/{key}`
 a| 
アラートキーを使用して、環境内の既存のすべてのアラートまたは特定のアラートを照会します。環境で生成されたアラートについて、アラート概要、アクション、通知の送信先 E メール ID 、イベント、重大度などの情報を確認することができます。



 a| 
management-server
 a| 
投稿（ Post ）
 a| 
「 /management-server / alerts 」を参照してください
 a| 
このメソッドを使用すると、特定のイベントに対するアラートを追加できます。アラート名、アラートが適用される物理リソースまたは論理リソース、アラートが有効かどうか、および SNMP トラップを発行するかどうかを追加する必要があります。アラートを生成する追加の詳細を追加できます。これには、アラートスクリプトを追加する場合に備えて、アクション、通知 E メール ID 、スクリプトの詳細などの情報が含まれます。



 a| 
management-server
 a| 
パッチと削除
 a| 
「 management-server /events/{key}`
 a| 
これらのメソッドを使用して、特定のアラートを変更および削除できます。概要、名前、アラートの有効化 / 無効化など、さまざまな属性を変更できます。不要になったアラートを削除できます。

|===

NOTE: アラートを追加するリソースを選択する際に、リソースとしてクラスタを選択しても、そのクラスタ内のストレージオブジェクトは自動的には選択されないことに注意してください。たとえば、すべてのクラスタのすべての重大イベントに対するアラートを作成した場合、受信するアラートの対象はクラスタの重大イベントのみです。ノードやアグリゲートなどの重大イベントに対するアラートは受信しません。



== スクリプトの管理

/management-server/scripts'API を使用して ' アラートがトリガーされたときに実行されるスクリプトにアラートを関連付けることもできますUnified Manager で複数のストレージオブジェクトを自動的に変更または更新するスクリプトを作成することができます。スクリプトはアラートに関連付けられます。イベントによってアラートがトリガーされるとスクリプトが実行されます。カスタムスクリプトをアップロードし、アラートが生成されたときの動作をテストすることができます。Unified Manager でイベントに対するアラートが発生したときにスクリプトが実行されるように、スクリプトにアラートを関連付けることができます。

スクリプトの詳細については、を参照してください link:../events/concept_manage_scripts.html["スクリプトの管理"]

[cols="4*"]
|===
| カテゴリ | HTTP 動詞 | パス | 説明 


 a| 
management-server
 a| 
取得
 a| 
「 /management-server /scripts 」にあります
 a| 
この API を使用して、環境内の既存のすべてのスクリプトを照会します。特定のスクリプトのみを表示するには、標準のフィルタと処理順を使用します。



 a| 
management-server
 a| 
投稿（ Post ）
 a| 
「 /management-server /scripts 」にあります
 a| 
この API を使用して、スクリプトの概要を追加し、アラートに関連付けられたスクリプトファイルをアップロードします。

|===