---
permalink: api-automation/concept_manage_fileshares_api.html 
sidebar: sidebar 
keywords: manage, file, share 
summary: /storage-provider/file-shares API を使用して、データセンター環境内の CIFS および NFS のファイル共有ボリュームを表示、追加、変更、および削除できます。 
---
= ファイル共有の管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
/storage-provider/file-shares'API を使用すると、データセンター環境内の CIFS および NFS ファイル共有ボリュームを表示、追加、変更、および削除できます。

ファイル共有ボリュームをプロビジョニングする前に、 SVM が作成され、サポートされるプロトコルでプロビジョニングされていることを確認します。プロビジョニング中にパフォーマンスサービスレベル（ PSL ）またはストレージ効率化ポリシー（ SEP ）を割り当てる場合は、ファイル共有を作成する前に PSL または SEP を作成する必要があります。



== ファイル共有を表示します

Unified Manager 環境で使用可能なファイル共有ボリュームを表示するには、次のメソッドを使用します。Active IQ Unified Manager のデータソースとして ONTAP クラスタを追加すると、それらのクラスタのストレージワークロードが Unified Manager インスタンスに自動的に追加されます。この API は、 Unified Manager インスタンスに自動および手動で追加されたファイル共有を取得します。特定のファイル共有の詳細を表示するには、ファイル共有キーを指定してこの API を実行します。

[cols="3*"]
|===
| カテゴリ | HTTP 動詞 | パス 


 a| 
ストレージプロバイダ
 a| 
取得
 a| 
「 /storage-provider/file-shares 」のようになります

`/storage-provider/file-shares/\{key}`

|===


== ファイル共有を追加

SVM に CIFS および NFS ファイル共有を追加するには、次のメソッドを使用します。作成するファイル共有の詳細を入力パラメータとして指定する必要があります。この API を使用して FlexGroup ボリュームを追加することはできません。

[cols="3*"]
|===
| カテゴリ | HTTP 動詞 | パス 


 a| 
ストレージプロバイダ
 a| 
投稿（ Post ）
 a| 
「 /storage-provider/file-shares 」のようになります

|===
[NOTE]
====
アクセス制御リスト（ ACL ）パラメータまたはエクスポートポリシーパラメータのどちらを指定するかに応じて、 CIFS 共有または NFS ファイル共有が作成されます。ACL パラメータの値を指定しない場合、 CIFS 共有は作成されず、デフォルトで NFS 共有が作成され、すべてのアクセスが提供されます。

====
* データ保護ボリュームの作成 * ： SVM にファイル共有を追加すると、デフォルトでマウントされるボリュームのタイプは「 rw 」（読み取り / 書き込み）になります。データ保護 (DP) ボリュームを作成する場合は 'type パラメータの値として「 d p 」を指定します



== ファイル共有を削除します

特定のファイル共有を削除するには、次のメソッドを使用します。特定のファイル共有を削除するには、入力パラメータとしてファイル共有キーを入力する必要があります。

[cols="3*"]
|===
| カテゴリ | HTTP 動詞 | パス 


 a| 
ストレージプロバイダ
 a| 
削除
 a| 
`/storage-provider/file-shares/\{key}`

|===


== ファイル共有を変更する

ファイル共有を変更し、そのプロパティを更新するには、次のメソッドを使用します。

特定のファイル共有を変更するには、ファイル共有キーを指定する必要があります。また、更新するプロパティとその値を入力する必要があります。

[NOTE]
====
この API の 1 回の呼び出しで更新できるプロパティは 1 つだけです。更新が複数ある場合は、この API を何度でも実行する必要があります。

====
[cols="3*"]
|===
| カテゴリ | HTTP 動詞 | パス 


 a| 
ストレージプロバイダ
 a| 
パッチ
 a| 
`/storage-provider/file-shares/\{key}`

|===