---
permalink: api-automation/concept_verify_svm_workflow.html 
sidebar: sidebar 
keywords: verify, svms, clusters 
summary: ファイル共有または LUN をプロビジョニングする前に、クラスタに Storage Virtual Machine （ SVM ）が作成されているかどうかを確認する必要があります。 
---
= クラスタの SVM の確認
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ファイル共有または LUN をプロビジョニングする前に、クラスタに Storage Virtual Machine （ SVM ）が作成されているかどうかを確認する必要があります。

[NOTE]
====
このワークフローは、 ONTAP クラスタが Unified Manager に追加され、クラスタキーが取得されていることを前提としています。クラスタには、 LUN とファイル共有をプロビジョニングするためのライセンスが必要です。

====
. クラスタに SVM が作成されているかどうかを確認します。
+
[cols="3*"]
|===
| カテゴリ | HTTP 動詞 | パス 


 a| 
データセンター
 a| 
取得
 a| 
「 /datacenter /svm /svms' 」 /datacenter /svm /SVM/\{ key }` 」のように指定します

|===
+
* cURL の例 *

+
[listing]
----
curl -X GET "https://<hostname>/api/datacenter/svm/svms" -H "accept: application/json" -H "Authorization: Basic <Base64EncodedCredentials>"
----
. SVM キーが返されない場合は、 SVM を作成します。SVM を作成するには、 SVM をプロビジョニングするクラスタキーが必要です。SVM 名も指定する必要があります。次の手順を実行します。
+
[cols="3*"]
|===
| カテゴリ | HTTP 動詞 | パス 


 a| 
データセンター
 a| 
取得
 a| 
「 /datacenter /cluster/clusters 」「 /datacenter / cluster/clusters/clusters/\{ key ｝ 」

|===
+
クラスタキーを取得します。

+
* cURL の例 *

+
[listing]
----
curl -X GET "https://<hostname>/api/datacenter/cluster/clusters" -H "accept: application/json" -H "Authorization: Basic <Base64EncodedCredentials>"
----
. 出力からクラスタキーを取得し、 SVM を作成するための入力として使用します。
+
[NOTE]
====
SVM を作成する際には、 LUN およびファイル共有のプロビジョニングに必要なすべてのプロトコル（ CIFS 、 NFS 、 FCP など）をサポートしていることを確認してください。 および iSCSI などです。SVM が必要なサービスをサポートしていないと、プロビジョニングワークフローが失敗することがあります。対応するワークロードタイプのサービスも有効にすることを推奨します。

====
+
[cols="3*"]
|===
| カテゴリ | HTTP 動詞 | パス 


 a| 
データセンター
 a| 
投稿（ Post ）
 a| 
「 /datacenter /svm /SVMs 」のように指定します

|===
+
* cURL の例 *

+
SVM オブジェクトの詳細を入力パラメータとして指定します。

+
[listing]
----
curl -X POST "https://<hostname>/api/datacenter/svm/svms" -H "accept: application/json" -H "Content-Type: application/json" -H "Authorization: Basic <Base64EncodedCredentials>" "{ \"aggregates\": [ { \"_links\": {}, \"key\": \"1cd8a442-86d1,type=objecttype,uuid=1cd8a442-86d1-11e0-ae1c-9876567890123\",
\"name\": \"cluster2\", \"uuid\": \"02c9e252-41be-11e9-81d5-00a0986138f7\" } ],
\"cifs\": { \"ad_domain\": { \"fqdn\": \"string\", \"password\": \"string\",
\"user\": \"string\" }, \"enabled\": true, \"name\": \"CIFS1\" },
\"cluster\": { \"key\": \"1cd8a442-86d1-11e0-ae1c-123478563412,type=object type,uuid=1cd8a442-86d1-11e0-ae1c-9876567890123\" },
\"dns\": { \"domains\": [ \"example.com\", \"example2.example3.com\" ],
\"servers\": [ \"10.224.65.20\", \"2001:db08:a0b:12f0::1\" ] },
\"fcp\": { \"enabled\": true }, \"ip_interface\": [ { \"enabled\": true,
\"ip\": { \"address\": \"10.10.10.7\", \"netmask\": \"24\" },
\"location\": { \"home_node\": { \"name\": \"node1\" } }, \"name\":
\"dataLif1\" } ], \"ipspace\": { \"name\": \"exchange\" },
\"iscsi\": { \"enabled\": true }, \"language\": \"c.utf_8\",
\"ldap\": { \"ad_domain\": \"string\", \"base_dn\": \"string\",
\"bind_dn\": \"string\", \"enabled\": true, \"servers\": [ \"string\" ] },
\"name\": \"svm1\", \"nfs\": { \"enabled\": true },
\"nis\": { \"domain\": \"string\", \"enabled\": true,
\"servers\": [ \"string\" ] }, \"nvme\": { \"enabled\": true },
\"routes\": [ { \"destination\": { \"address\": \"10.10.10.7\",
\"netmask\": \"24\" }, \"gateway\": \"string\" } ],
\"snapshot_policy\": { \"name\": \"default\" },
\"state\": \"running\", \"subtype\": \"default\"}"
----
+
JSON 出力にジョブオブジェクトキーが表示され、作成した SVM の検証に使用できます。

. ジョブオブジェクトキーを使用して照会し、 SVM の作成を確認します。SVM が正常に作成されると、 SVM キーが応答に返されます。
+
[cols="3*"]
|===
| カテゴリ | HTTP 動詞 | パス 


 a| 
management-server
 a| 
取得
 a| 
「 /management-server /jobs/\{key}` 」と入力します

|===

