---
permalink: api-automation/concept_view_workloads.html 
sidebar: sidebar 
keywords: view, storage, workloads 
summary: ここに記載されている API を使用すると、データセンター内のすべての ONTAP クラスタのストレージワークロードをまとめて表示できます。また、 Active IQ Unified Manager 環境でプロビジョニングされているストレージワークロードの数と、その容量とパフォーマンス（ IOPS ）の統計情報も表示されます。 
---
= ストレージワークロードの表示
:icons: font
:imagesdir: ../media/


[role="lead"]
ここに記載されている API を使用すると、データセンター内のすべての ONTAP クラスタのストレージワークロードをまとめて表示できます。また、 Active IQ Unified Manager 環境でプロビジョニングされているストレージワークロードの数と、その容量とパフォーマンス（ IOPS ）の統計情報も表示されます。



== ストレージワークロードを表示します

データセンター内のすべてのクラスタのすべてのストレージワークロードを表示するには、次のメソッドを使用します。特定の列で応答をフィルタリングする方法については、 Unified Manager インスタンスで使用可能な API のリファレンスドキュメントを参照してください。

[cols="3*"]
|===
| カテゴリ | HTTP 動詞 | パス 


 a| 
ストレージプロバイダ
 a| 
取得
 a| 
「 /storage-provider/workloads 」のようになります

|===


== ストレージワークロードの概要を表示します

使用済み容量、使用可能容量、使用済み IOPS 、使用可能 IOPS 、各パフォーマンスサービスレベルで管理されているストレージワークロードの数を評価するには、次のメソッドを使用します。任意の LUN 、 NFS ファイル共有、または CIFS 共有のストレージワークロードを表示できます。この API は、ストレージワークロードの概要、 Unified Manager でプロビジョニングされたストレージワークロードの概要、データセンターの概要、データセンターの合計、使用済み、使用可能なスペースと IOPS の概要を、割り当てられたパフォーマンスサービスレベル別に表示します。この API の応答として受信した情報を使用して、 Unified Manager UI のダッシュボードにデータが表示されます。

[cols="3*"]
|===
| カテゴリ | HTTP 動詞 | パス 


 a| 
ストレージプロバイダ
 a| 
取得
 a| 
「 /storage-provider/workloads - summary 」のようになります

|===