---
permalink: api-automation/concept_api_logs.html 
sidebar: sidebar 
keywords: logs, troubleshooting 
summary: システムログを使用して、 API の実行中に発生する可能性のある障害の原因を分析し、問題のトラブルシューティングを行うことができます。 
---
= トラブルシューティング用のログ
:icons: font
:imagesdir: ../media/


[role="lead"]
システムログを使用して、 API の実行中に発生する可能性のある障害の原因を分析し、問題のトラブルシューティングを行うことができます。

API 呼び出しに関連する問題のトラブルシューティングを行うには、次の場所からログを取得します。

[cols="2*"]
|===
| ログの場所 | 使用 


 a| 
/var/log/ocie/access_log.log
 a| 
API を呼び出しているユーザ名、開始時刻、実行時間、ステータス、 URL など、 API 呼び出しに関するすべての詳細情報が含まれます。

このログファイルを使用して、頻繁に使用される API を確認したり、 GUI ワークフローのトラブルシューティングを行ったりできます。また、実行時間に基づいて分析の規模を調整することもできます。



 a| 
/var/log/ocum/ocumentserver.log' のように表示されます
 a| 
すべての API 実行ログが含まれます。

このログファイルを使用して、 API 呼び出しのトラブルシューティングとデバッグを行うことができます。



 a| 
/var/log/ocie/sserver.log' のようになります
 a| 
すべての Wildfly サーバ構成と、サービスの開始 / 停止に関連するログが含まれています。

このログファイルを使用して、 Wildfly サーバの開始、停止、または導入時に発生する問題のルート原因を見つけることができます。



 a| 
/var/log/mocie /au.log
 a| 
Acquisition Unit 関連のログが含まれます。

このログファイルは、 ONTAP でオブジェクトを作成、変更、または削除したときに使用できますが、 Active IQ Unified Manager REST API には反映されません。

|===