---
permalink: api-automation/reference_authentication_errors.html 
sidebar: sidebar 
keywords: http, status, code, active iq, unified manager 
summary: API の実行時や問題のトラブルシューティング時には、 Active IQ Unified Manager API で使用されるさまざまな HTTP ステータスコードとエラーコードについて理解しておく必要があります。 
---
= Active IQ Unified Manager で使用される HTTP ステータスコード
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
API の実行時や問題のトラブルシューティング時には、 Active IQ Unified Manager API で使用されるさまざまな HTTP ステータスコードとエラーコードについて理解しておく必要があります。

次の表に、認証に関連するエラーコードを示します。

[cols="3*"]
|===
| HTTP ステータスコード | ステータスコードタイトル | 説明 


 a| 
200
 a| 
わかりました
 a| 
同期 API 呼び出しの実行に成功した場合に返されます。



 a| 
201
 a| 
作成済み
 a| 
Active Directory の設定など、同期呼び出しによって新しいリソースが作成されたことを示します。



 a| 
202.
 a| 
承認済み
 a| 
LUN やファイル共有の作成など、プロビジョニング機能の非同期呼び出しの実行が成功したときに返されます。



 a| 
400
 a| 
無効な要求です
 a| 
入力検証に失敗したことを示します。ユーザは、要求の本文に有効なキーを指定するなど、入力を修正する必要があります。



 a| 
401
 a| 
不正な要求です
 a| 
リソースを表示する権限がありません / 権限がありません。



 a| 
403
 a| 
禁止された要求です
 a| 
アクセスしようとしていたリソースへのアクセスは禁止されています。



 a| 
404
 a| 
リソースが見つかりません
 a| 
アクセスしようとしているリソースが見つかりません。



 a| 
405
 a| 
メソッドを使用できません
 a| 
メソッドを使用できません



 a| 
429
 a| 
要求が多すぎます
 a| 
指定した時間内にユーザが送信した要求が多すぎる場合に返されます。



 a| 
500
 a| 
内部サーバエラー。
 a| 
内部サーバエラー。サーバから応答を取得できませんでした。この内部サーバエラーは、永続的な場合とそうでない場合があります。たとえば 'get' または 'get all' 操作を実行してこのエラーを受信した場合 ' この操作を最低 5 回繰り返すことをお勧めします永続的なエラーの場合、引き続きステータスコード 500 が返されます。処理が成功すると、ステータスコード 200 が返されます。

|===