---
permalink: reporting/concept_unified_manager_reporting.html 
sidebar: sidebar 
keywords: unified, manager, reporting 
summary: Active IQ Unified Manager （旧 OnCommand Unified Manager ）では、 ONTAP ストレージシステムのレポートを表示、カスタマイズ、ダウンロード、およびスケジュール設定できます。レポートには、ストレージシステムの容量、健全性、パフォーマンス、保護関係に関する詳細を表示できます。 
---
= Unified Manager のレポート機能
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Manager （旧 OnCommand Unified Manager ）では、 ONTAP ストレージシステムのレポートを表示、カスタマイズ、ダウンロード、およびスケジュール設定できます。レポートには、ストレージシステムの容量、健全性、パフォーマンス、セキュリティ、保護関係に関する詳細を表示できます。

Active IQ Unified Manager 9.6 で導入された新しい Unified Manager レポート作成機能およびスケジュール設定機能は、 Unified Manager バージョン 9.5 で廃止された以前のレポート作成エンジンに代わるものです。

レポート機能は、ネットワークのさまざまなビューを提供し、容量、健全性、パフォーマンス、セキュリティ、保護データに関する実用的な情報を提供します。列の表示、非表示、再配置、データのフィルタリング、データのソート、 検索結果を表示します。カスタムビューは、再利用できるように保存したり、レポートとしてダウンロードしたりできます。また、定期的なレポートとしてスケジュールを設定して、 E メールで配布することもできます。

Microsoft ® Excel 形式のビューをダウンロードしてカスタマイズできます。複雑な並べ替え、レイヤーフィルター、ピボットテーブル、グラフなど、 Excel の高度な機能を使用できます。結果の Excel レポートに問題がなければ、レポートがスケジュールされて共有されるたびに使用する Excel ファイルをアップロードできます。

Unified Manager では、ユーザインターフェイスからレポートを生成する以外にも、次の方法を使用して健常性、セキュリティ、およびパフォーマンスのデータを抽出できます。

* Open Database Connectivity （ ODBC ）および ODBC のツールを使用してデータベースに直接アクセスし、クラスタ情報を取得する
* Unified Manager REST API を使用して確認したい情報を取得する


このリリースの Active IQ Unified Manager では、レポートの機能が次のように拡張されています。

* 設定したスケジュールに従ってレポートの E メールが送信されます。オンデマンドレポートを生成した場合でも、 E メールが送信されます。
* レポートのファイル名とレポートのメタデータには、レポートの生成元のホスト名が含まれます。ファイル名が変更された場合でも、この機能強化によりレポートの生成元のホスト名を特定できます。

