---
permalink: reporting/reference_reporting_limitations.html 
sidebar: sidebar 
keywords: reporting, limitations 
summary: Active IQ Unified Manager の新しいレポート機能には、注意が必要な制限事項があります。 
---
= レポート機能の制限事項
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Manager の新しいレポート機能には、注意が必要な制限事項があります。



== 以前のバージョンの Unified Manager で作成した既存のレポート

スケジュールと受信者を編集できるのは、 Unified Manager 9.5 以前のリリースで作成およびインポートされた既存のレポート（ .rptdesign ファイル）のみです。Unified Manager 9.5 以前の標準レポートをカスタマイズしたレポートは、新しいレポートツールにインポートされません。

.rptdesign ファイルからインポートした既存のレポートを編集する必要がある場合は、次のいずれかの操作を行って、インポートしたレポートを削除します。

* 新しいビューを作成し、そのビューからレポートのスケジュールを設定する（推奨）
* レポートにカーソルを合わせ、 SQL をコピーして、外部ツールを使用してデータを抽出します


デフォルトビューは、カスタマイズすることなくレポートとして生成できます。新しいレポート用解決策を使用して、カスタムレポートを再作成できます。



== スケジュールとレポートの関係

保存したレポートごとに、受信者を任意に組み合わせて複数のスケジュールを作成できます。ただし、スケジュールを複数のレポートで再利用することはできません。



== レポートの保護

適切な権限を持つユーザは、レポートを編集または削除できます。保存したビューやスケジュールを他のユーザが削除または変更できないようにする方法はありません。



== イベントレポート

イベントビューをカスタマイズしてレポートを CSV 形式でダウンロードすることはできますが、イベントレポートを繰り返し生成して配信するようにスケジュール設定することはできません。



== レポートの添付

レポートを E メールの本文として送信することはできません。代わりに、レポートは PDF 、 Excel 、または CSV 形式の添付ファイルとしてのみ送信されます。
