---
permalink: performance-checker/concept_um_interfaces_used_to_manage_storage_system_performance.html 
sidebar: sidebar 
keywords: unified manager, interfaces, used, manage, storage, system, performance, web ui, maintenance, console 
summary: Active IQ Unified Manager では、データストレージのパフォーマンスに関する問題の監視とトラブルシューティング用に、 Web ユーザインターフェイスとメンテナンスコンソールの 2 つのインターフェイスを提供しています。 
---
= ストレージシステムのパフォーマンスを管理するために使用される Unified Manager インターフェイス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ここでは、Active IQ Unified Manager でデータストレージの容量、可用性、保護に関する問題をトラブルシューティングするための2つのユーザインターフェイスについて説明します。2 種類の UI とは、 Unified Manager Web UI とメンテナンスコンソールです。

Unified Manager の保護機能を使用する場合は、 OnCommand Workflow Automation （ WFA ）もインストールして設定する必要があります。



== Unified Manager Web UI

Unified Manager Web UI では、管理者がデータストレージの容量、可用性、保護に関連するクラスタの問題を監視してトラブルシューティングすることができます。

これらのセクションでは、管理者がUnified Manager Web UIに表示されるストレージ容量、データの可用性、または保護に関する問題をトラブルシューティングする際に従う共通のワークフローについて説明します。



== メンテナンスコンソール

Unified Manager のメンテナンスコンソールでは、管理者が Unified Manager サーバ自体に関連するオペレーティングシステムの問題、バージョンアップグレードの問題、ユーザアクセスの問題、およびネットワークの問題を監視し、診断し、対処することができます。Unified Manager Web UI を使用できない場合は、メンテナンスコンソールが Unified Manager にアクセスする唯一の手段となります。

この情報は、メンテナンスコンソールにアクセスしてUnified Managerサーバの機能に関連する問題を解決するために使用します。
