---
permalink: performance-checker/concept_metrocluster_configuration_verification.html 
sidebar: sidebar 
keywords: metrocluster, configuration, verification 
summary: MetroCluster 構成でミラーされたワークロードにパフォーマンスの問題が発生しないようにするには、 MetroCluster 構成が正しくセットアップされていることを確認します。また、構成を変更するか、ソフトウェアまたはハードウェアコンポーネントをアップグレードすることで、ワークロードのパフォーマンスを向上させることもできます。 
---
= MetroCluster 構成の検証
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MetroCluster 構成でミラーされたワークロードにパフォーマンスの問題が発生しないようにするには、 MetroCluster 構成が正しくセットアップされていることを確認します。また、構成を変更するか、ソフトウェアまたはハードウェアコンポーネントをアップグレードすることで、ワークロードのパフォーマンスを向上させることもできます。

を参照してください https://docs.netapp.com/us-en/ontap-metrocluster/index.html["MetroCluster のドキュメント"] Fibre Channel（FC）スイッチ、ケーブル、スイッチ間リンク（ISL）など、MetroCluster 構成のクラスタのセットアップ手順について説明します。また、ローカルクラスタとリモートクラスタがミラーボリュームデータと通信できるように MetroCluster ソフトウェアを設定する際にも役立ちます。

MetroCluster 構成との要件をで比較できます https://docs.netapp.com/us-en/ontap-metrocluster/index.html["MetroCluster のドキュメント"] MetroCluster 構成のコンポーネントを変更またはアップグレードすることでワークロードのパフォーマンスが向上するかどうかを判断する。この比較は、次の点について回答を行う場合に役立ちます。

* コントローラはワークロードに適していますか？
* スループットの処理能力を高めるために、 ISL バンドルをより大きな帯域幅にアップグレードする必要があるか。
* 帯域幅を増やすためにスイッチ上でバッファ間クレジット（ BBC ）を調整できるか。
* ワークロードに SSD ストレージへの大量の書き込みスループットがある場合、そのスループットに対応するために FC-to-SAS ブリッジをアップグレードする必要があるか。


MetroCluster コンポーネントの交換またはアップグレードについては、を参照してください https://docs.netapp.com/us-en/ontap-metrocluster/index.html["MetroCluster のドキュメント"]。
