---
permalink: performance-checker/concept_types_of_workloads_monitored_by_unified_manager.html 
sidebar: sidebar 
keywords: types, workloads, monitored, unified manager 
summary: Unified Manager では、ユーザ定義とシステム定義の 2 種類のワークロードのパフォーマンスを監視できます。 
---
= Unified Manager で監視されるワークロードのタイプ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager では、ユーザ定義とシステム定義の 2 種類のワークロードのパフォーマンスを監視できます。

* * _ ユーザ定義のワークロード _ *
+
アプリケーションからクラスタへの I/O スループット。読み取り要求と書き込み要求に関連するプロセスです。ボリューム、 LUN 、 NFS 共有、 SMB / CIFS 共有、およびワークロードはユーザ定義のワークロードです。

+
[NOTE]
====
Unified Manager は、クラスタ内のワークロードだけを監視します。アプリケーション、クライアント、またはアプリケーションとクラスタ間のパスは監視しません。

====
+
次の条件が 1 つ以上該当するワークロードは、 Unified Manager で監視できません。

+
** 読み取り専用モードのデータ保護（ DP ）コピーである。（ DP ボリュームについてはユーザ生成のトラフィックが監視されます）。
** ボリュームがオフラインデータクローンである。
** ボリュームが MetroCluster 構成のミラーボリュームである。


* * _ システム定義のワークロード _ *
+
次のストレージ効率化、データレプリケーション、およびシステム健全性に関連する内部プロセスです。

+
** 重複排除などのストレージ効率
** ディスクの健常性。 RAID の再構築、ディスクスクラビングなどが含まれます
** SnapMirror コピーなどのデータレプリケーション
** 管理アクティビティ
** ファイルシステムの健全性。さまざまな WAFL アクティビティが含まれます
** WAFL スキャンなどのファイルシステムスキャナ
** VMware ホストからのオフロードされたストレージ効率化処理などのコピーオフロード
** ボリューム移動やデータ圧縮などのシステムヘルス
** 監視対象外のボリューム




システム定義のワークロードのパフォーマンスデータは、これらのワークロードで使用されるクラスタコンポーネントが競合状態の場合にのみ表示されます。たとえば、システム定義のワークロードの名前を検索して、そのパフォーマンスデータを表示することはできません。
