---
permalink: performance-checker/concept_remove_inactive_volumes_and_luns.html 
sidebar: sidebar 
keywords: remove, inactive, volumes, luns 
summary: アグリゲートの空きスペースが問題として識別されている場合は、使用されていないボリュームと LUN を検索してアグリゲートから削除できます。これにより、ディスクスペース不足の問題を軽減できます。 
---
= 非アクティブなボリュームと LUN を削除します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アグリゲートの空きスペースが問題として識別されている場合は、使用されていないボリュームと LUN を検索してアグリゲートから削除できます。これにより、ディスクスペース不足の問題を軽減できます。

アグリゲートでのパフォーマンスイベントの原因がディスクスペースの不足である場合は、使用されなくなったボリュームと LUN をいくつかの方法で特定できます。

使用されていないボリュームを特定する方法

* イベントの詳細ページの * 影響を受けるオブジェクト数 * フィールドには、影響を受けるボリュームのリストを示すリンクが表示されます。
+
リンクをクリックすると、 Performance ： All Volumes ビューにボリュームが表示されます。このページで関連するボリュームを * IOPS * でソートすると、アクティブでないボリュームがわかります。



使用されていない LUN を特定する方法

. イベントの詳細ページで、イベントが発生したアグリゲートの名前を書き留めます。
. 左側のナビゲーションペインで、 * Storage * > * LUNs * をクリックし、表示メニューから * Performance * > * All LUNs * を選択します。
. [*Filtering*] をクリックし、左側のドロップダウンメニューから [*Aggregate*] を選択して、テキストフィールドにアグリゲートの名前を入力し、 [*Apply Filter*] をクリックします。
. 表示された影響を受ける LUN のリストを * IOPS * でソートして、アクティブでない LUN を確認します。


使用されていないボリュームと LUN を特定したら、 ONTAP System Manager または ONTAP コマンドを使用して、それらのオブジェクトを削除できます。
