---
permalink: performance-checker/concept_understand_um_recommendations_to_tier_data_to_cloud.html 
sidebar: sidebar 
keywords: understand, unified manager, recommendations, tier, data, cloud 
summary: Performance ： All Volumes ビューには、ボリュームに格納されているアクセス頻度の低いユーザデータ（コールドデータ）のサイズに関する情報が表示されます。Unified Manager が、特定のボリュームについて、アクセス頻度の低いデータを FabricPool 対応アグリゲートのクラウド階層（クラウドプロバイダまたは StorageGRID ）に階層化することを推奨することがあります。 
---
= Unified Manager によるクラウドへのデータの階層化の推奨について理解していること
:icons: font
:imagesdir: ../media/


[role="lead"]
Performance ： All Volumes ビューには、ボリュームに格納されているアクセス頻度の低いユーザデータ（コールドデータ）のサイズに関する情報が表示されます。Unified Manager が、特定のボリュームについて、アクセス頻度の低いデータを FabricPool 対応アグリゲートのクラウド階層（クラウドプロバイダまたは StorageGRID ）に階層化することを推奨することがあります。

[NOTE]
====
FabricPool は ONTAP 9.2 で導入されたため、 9.2 より前のバージョンの ONTAP ソフトウェアを使用している場合、 Unified Manager によるデータの階層化の推奨を有効にするには、 ONTAP ソフトウェアのアップグレードが必要になります。また '*auto*' 階層化ポリシーは ONTAP 9.4 で導入され '*all *' 階層化ポリシーは ONTAP 9.6 で導入されたため ' 自動階層化ポリシーの使用を推奨する場合は ONTAP 9.4 以降にアップグレードする必要があります

====
Performance ： All Volumes ビューの次の 3 つのフィールドは、アクセス頻度の低いデータをクラウド階層に移動することでストレージシステムのディスク使用率の改善やパフォーマンス階層のスペースの削減が可能かどうかに関する情報を提供します。

* * 階層化ポリシー *
+
階層化ポリシーによって、ボリュームのデータを高パフォーマンス階層に残すか、あるいは一部のデータをパフォーマンス階層からクラウド階層に移動するかが決まります。

+
このフィールドには、ボリュームに対して設定されている階層化ポリシーが、ボリュームが現在 FabricPool アグリゲートにない場合も含めて表示されます。階層化ポリシーが適用されるのは、ボリュームが FabricPool アグリゲートにある場合のみです。

* * コールドデータ *
+
ボリュームに格納されているアクセス頻度の低いユーザデータ（コールドデータ）のサイズが表示されます。

+
ONTAP 9.4 以降のソフトウェアを使用している場合にのみ、ボリュームを導入するアグリゲートに「 * inactive data reporting パラメータ * 」が「 * enabled * 」に設定されている必要があるため、このフィールドに値が表示されます。 最小クーリング日数のしきい値を満たしていることを確認します（「 * snapshot-only * 」または「 * auto * 」階層化ポリシーを使用するボリュームの場合）。それ以外の場合、値は「 N/A 」と表示されます。

* * クラウドの推奨事項 *
+
ボリュームのデータアクティビティに関して十分な情報が収集されると、 Unified Manager は、対処が不要か、またはアクセス頻度の低いデータをクラウド階層に移動することでパフォーマンス階層のスペースを削減できるかを判断することができます。



[NOTE]
====
コールドデータフィールドは 15 分ごとに更新されますが、ボリュームでコールドデータ分析が実行されると、クラウドの推奨事項フィールドが 7 日ごとに更新されます。したがって、コールドデータの正確な量はフィールド間で異なる場合があります。Cloud Recommendation フィールドには、分析が実行された日付が表示されます。

====
Inactive Data Reporting が有効になっている場合は、コールドデータフィールドにはアクセス頻度の低いデータの正確な量が表示されます。Inactive Data Reporting 機能を使用できない場合、 Unified Manager はパフォーマンス統計に基づいてアクセス頻度の低いデータがボリュームにあるかどうかを判断します。アクセス頻度の低いデータの量はこの場合のコールドデータフィールドには表示されませんが、クラウドに関する推奨事項を表示するために「 * ティア * 」という単語にカーソルを合わせると表示されます。

クラウドに関する推奨事項は次のとおりです。

* * 学習中 * 。推奨事項を利用できるだけの十分なデータが収集されていません。
* * 階層 * 。分析の結果、アクセス頻度の低いコールドデータがボリュームにあり、そのデータをクラウド階層に移動するようにボリュームを設定することが推奨されます。一部のケースでは、ボリュームをまず FabricPool 対応アグリゲートに移動する必要があります。ボリュームがすでに FabricPool アグリゲートにあれば、階層化ポリシーの変更だけで済みます。
* * アクションなし * 。ボリュームにアクセス頻度の低いデータがほとんどないか、ボリュームが FabricPool アグリゲートですでに「 auto 」階層化ポリシーに設定されているか、ボリュームがデータ保護ボリュームです。この値は、ボリュームがオフラインの場合や MetroCluster 構成で使用されている場合にも表示されます。


ボリュームを移動したり、ボリュームの階層化ポリシーやアグリゲートの Inactive Data Reporting の設定を変更するには、 ONTAP System Manager 、 ONTAP の CLI コマンド、またはこの 2 つを組み合わせて使用します。

アプリケーション管理者またはストレージ管理者のロールで Unified Manager にログインしている場合は、「 * 階層 * 」にカーソルを合わせるとクラウドに関する推奨事項の「ボリュームの設定 * 」リンクが表示されます。このボタンをクリックすると、 System Manager の Volumes （ボリューム）ページが開き、推奨される変更が行われます。
