---
permalink: performance-checker/concept_understand_events_from_adaptive_qos_policies.html 
sidebar: sidebar 
keywords: understand, events, adaptive, qos, policies, defined, block, size 
summary: アダプティブ QoS ポリシーグループでは、ボリュームサイズに基づいてスループットの上限と下限が自動的に調整され、 TB または GB あたりの IOPS が一定に維持されます。ONTAP 9.5 以降では、 QoS ポリシーにブロックサイズを指定することで MB/s のしきい値も同時に適用できます。 
---
= ブロックサイズの定義を含むアダプティブ QoS ポリシーによるイベントの概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アダプティブ QoS ポリシーグループでは、ボリュームサイズに基づいてスループットの上限と下限が自動的に調整され、 TB または GB あたりの IOPS が一定に維持されます。ONTAP 9.5 以降では、 QoS ポリシーにブロックサイズを指定することで MB/s のしきい値も同時に適用できます。

アダプティブ QoS ポリシーに IOPS のしきい値を割り当てると、各ワークロードで発生する処理数にのみ制限のみが適用されます。ワークロードを生成するクライアントに設定されているブロックサイズによっては、一部の IOPS にはるかに多くのデータが含まれ、処理を実行するノードの負荷がはるかに大きくなることがあります。

ワークロードの MB/s は次の式を使用して算出されます。

[listing]
----
MB/s = (IOPS * Block Size) / 1000
----
平均 IOPS が 3 、 000 のワークロードについて、クライアントのブロックサイズが 32KB に設定されている場合、このワークロードの実効 MB/s は 96 です。平均 IOPS が 3 、 000 の同じワークロードについて、クライアントのブロックサイズが 48KB に設定されている場合は、このワークロードの実効 MB/s は 144 になります。この場合、ブロックサイズが大きい方がノードでの処理データが 50% 多くなることがわかります。

次に、アダプティブ QoS ポリシーにブロックサイズが定義されている場合について、クライアントで設定されているブロックサイズに基づいてどのようにイベントがトリガーされるかを見てみましょう。

ポリシーを作成し、ピークスループットを 2 、 500IOPS/TB 、ブロックサイズを 32KB に設定します。この場合、使用容量が 1TB のボリュームに対する MB/s のしきい値は 80MB/s （（ 2500 IOPS * 32KB ） / 1000 ）に設定されます。Unified Manager では、スループットの値が定義されたしきい値を 10% 下回ると警告イベントが生成されます。イベントは次の状況で生成されます。

|===
| 使用済み容量 2+| イベントが生成されるスループットのしきい値 


|  | IOPS | MB/s 


 a| 
1 TB
 a| 
2 、 250 IOPS
 a| 
72 MB/s



 a| 
2TB
 a| 
4 、 500 IOPS
 a| 
144 MB/s



 a| 
5 TB
 a| 
11 、 250 IOPS
 a| 
360 MB/s

|===
ボリュームの使用可能なスペースが 2TB 、 IOPS が 4 、 000 、クライアントで設定されている QoS ブロックサイズが 32KB である場合、スループットは 128MB/s （（ 4 、 000 IOPS * 32KB ） / 1000 ）になります。この場合、 4 、 000 IOPS と 128MB/s のどちらについても、ボリュームで 2TB のスペースを使用する場合のしきい値を超えていないため、イベントは生成されません。

ボリュームの使用可能なスペースが 2TB 、 IOPS が 4 、 000 、クライアントで設定されている QoS ブロックサイズが 64KB である場合、スループットは 256MB/s （（ 4 、 000 IOPS * 64KB ） / 1000 ）になります。この場合、 4 、 000 IOPS についてはイベントは生成されませんが、 MB/s の値については 256MB/s でしきい値の 144MB/s を超えているためイベントが生成されます。

そのため、アダプティブ QoS ポリシーにブロックサイズを含む MBps の違反が発生してイベントがトリガーされると、イベントの詳細ページのシステム診断セクションに MBps のグラフが表示されます。アダプティブ QoS ポリシーに対する IOPS の違反に基づいてイベントがトリガーされると、システム診断セクションに IOPS チャートが表示されます。IOPS と MBps の両方に違反がある場合は、 2 つのイベントが表示されます。

QoS 設定の調整の詳細については、 ONTAP 9 パフォーマンス管理パワーガイドを参照してください。

http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-perf-mon/home.html["ONTAP 9 パフォーマンス管理パワーガイド"]
