---
permalink: performance-checker/concept_what_expected_range_of_performance_is.html 
sidebar: sidebar 
keywords: expected, range, performance, latency, forecast, formed 
summary: レイテンシ予測とは、特定の時間に想定されるパフォーマンスの上限と下限の値です。ワークロードのレイテンシについては、パフォーマンスしきい値を上回る値です。実測値がパフォーマンスしきい値を超えると、 Unified Manager によって動的なパフォーマンスイベントがトリガーされます。 
---
= パフォーマンスの想定範囲
:icons: font
:imagesdir: ../media/


[role="lead"]
レイテンシ予測とは、特定の時間に想定されるパフォーマンスの上限と下限の値です。ワークロードのレイテンシについては、パフォーマンスしきい値を上回る値です。実測値がパフォーマンスしきい値を超えると、 Unified Manager によって動的なパフォーマンスイベントがトリガーされます。

たとえば、午前 9 時から午後 5 時までの通常の営業時間の間などですほとんどの従業員は、午前 9 時から午後 5 時まで E メールをチェックすることができますチェックするとしますこの期間、 E メールサーバの負荷が増加すると、バックエンドストレージのワークロードアクティビティが増加します。従業員の E メールクライアントからの応答時間が長くなる可能性があります。

昼食の時間は午後 12 時からとなっている午後 1 時までオープン午後 5 時以降の勤務日の終わりには、ほとんどの従業員がコンピュータから離れている可能性があります。一般に、 E メールサーバの負荷は軽減され、バックエンドストレージの負荷も軽減されます。または、ストレージのバックアップやウィルススキャンなどのワークロード処理を午後 5 時以降に実行するようにスケジュールしている場合もありますバックエンドストレージのアクティビティが増加します。

ワークロードアクティビティの増加と減少を数日間にわたって監視した結果から、アクティビティの想定範囲（レイテンシ予測）が特定され、ワークロードの上限と下限が決まります。オブジェクトに対する実際のワークロードアクティビティが上限と下限の範囲から外れ、その状態が一定の期間にわたって続く場合は、オブジェクトの使用率が高すぎるか低すぎる可能性があります。



== レイテンシ予測の生成方法

Unified Manager では、少なくとも 3 日分のワークロードアクティビティを収集して分析してから、 GUI に表示する I/O 応答時間のレイテンシ予測を決定します。この期間で収集されるデータには、ワークロードアクティビティにおける変化がすべて反映されるわけではありません。最初の 3 日間のアクティビティを収集したあと、 Unified Manager はレイテンシ予測を 24 時間ごとに午前 12 時に調整しますワークロードアクティビティの変化を反映し、より正確な動的なパフォーマンスしきい値を設定する。

[NOTE]
====
システム時間が夏時間（ DST ）に切り替わると、監視しているワークロードのパフォーマンスの統計で使用するレイテンシ予測が変わります。Unified Manager は、レイテンシ予測の修正を即座に開始しますが、完了までに 15 日間ほどかかります。その間も Unified Manager の使用は継続できますが、 Unified Manager はレイテンシ予測を使用して動的イベントを検出するため、一部のイベントは正確でなくなる可能性があります。時間の変更前に検出されたイベントは影響を受けません。

====