---
permalink: performance-checker/concept_understand_performance_panels_on_dashboard.html 
sidebar: sidebar 
keywords: understand, performance, panels, dashboard 
summary: Unified Manager のダッシュボードには、環境内の監視対象のすべてのクラスタのパフォーマンスステータスの概要が、複数のパネルに分けて表示されます。すべてのクラスタまたは個々のクラスタのステータスを表示できます。 
---
= ダッシュボードのパフォーマンスパネルについて
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager のダッシュボードには、環境内の監視対象のすべてのクラスタのパフォーマンスステータスの概要が、複数のパネルに分けて表示されます。すべてのクラスタまたは個々のクラスタのステータスを表示できます。

ほとんどのパネルには、パフォーマンス情報に加えて、そのカテゴリのアクティブイベントの数および過去 24 時間に追加された新しいイベントの数が表示されます。この情報から、報告されたイベントを解決するために詳細な分析が必要なクラスタを決定できます。イベントをクリックすると、上位数件のイベントが表示され、そのカテゴリのイベントをフィルタリングして表示するイベント管理インベントリページへのリンクが表示されます。

次のパネルにはパフォーマンスステータスが表示されます。

* * パフォーマンス容量パネル *
+
すべてのクラスタを表示している場合、このパネルには、各クラスタのパフォーマンス容量（過去 1 時間の平均）とパフォーマンス容量が上限に達するまでの日数（日次増加率に基づく）が表示されます。棒グラフをクリックすると、そのクラスタのノードインベントリページが表示されます。ノードのインベントリページには過去 72 時間のパフォーマンス容量の平均が表示されるため、この値がダッシュボードの値と一致しないことがあります。

+
単一のクラスタを表示している場合、このパネルには、そのクラスタのパフォーマンス容量、合計 IOPS 、合計スループットが表示されます。

* * ワークロード IOPS パネル *
+
ワークロードのアクティブ管理が有効になっていて、単一のクラスタを表示している場合、このパネルには、特定の範囲の IOPS で現在実行されているワークロードの総数が表示されます。

* * ワークロードパフォーマンスパネル *
+
ワークロードのアクティブ管理が有効になっている場合、このパネルには、定義された各パフォーマンスサービスレベルに割り当てられている準拠ワークロードと非準拠ワークロードの総数が表示されます。棒グラフをクリックすると、そのポリシーに割り当てられているワークロードがワークロードページに表示されます。

* * 使用状況の概要パネル *
+
すべてのクラスタを表示している場合、 IOPS またはスループット（ MBps ）が高い順にクラスタを表示できます。

+
単一のクラスタを表示している場合は、そのクラスタのワークロードを IOPS またはスループット（ MBps ）が高い順に表示できます。


