---
permalink: performance-checker/concept_collect_data_and_monitor_workload_performance.html 
sidebar: sidebar 
keywords: collect, data, monitor, workload, performance 
summary: Unified Manager では、ワークロードアクティビティを 5 分間隔で収集および分析してパフォーマンスイベントを特定するほか、構成の変更を 15 分間隔で検出します。5 分ごとのパフォーマンスとイベントの履歴データが最大 30 日分保持され、そのデータを使用して監視対象のすべてのワークロードの想定レイテンシ範囲が予測されます。 
---
= データを収集してワークロードのパフォーマンスを監視
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager では、ワークロードアクティビティを 5 分間隔で収集および分析してパフォーマンスイベントを特定するほか、構成の変更を 15 分間隔で検出します。5 分ごとのパフォーマンスとイベントの履歴データが最大 30 日分保持され、そのデータを使用して監視対象のすべてのワークロードの想定レイテンシ範囲が予測されます。

Unified Manager では、少なくとも 3 日分のワークロードアクティビティを収集して分析してから、ワークロードの分析ページおよびイベントの詳細ページに I/O 応答時間のレイテンシ予測を表示する必要があります。このアクティビティを収集して表示されるレイテンシ予測には、ワークロードアクティビティにおける変化がすべて反映されるわけではありません。3 日間のアクティビティを収集したあと、 Unified Manager ではレイテンシ予測を 24 時間ごとに午前 12 時に調整し、ワークロードアクティビティの変化が反映された、より正確で動的なパフォーマンスしきい値を設定します。

Unified Manager でワークロードの監視を開始してから最初の 4 日間に、前回のデータ収集からの経過時間が 24 時間を超える期間がある場合、そのワークロードのレイテンシ予測はレイテンシのグラフに表示されません。前回の収集よりも前に検出されたイベントは引き続き表示されます。

[NOTE]
====
システム時間が夏時間（ DST ）に切り替わると、監視しているワークロードのパフォーマンスの統計で使用するレイテンシ予測が変わります。Unified Manager は、レイテンシ予測の修正を即座に開始しますが、完了までに 15 日間ほどかかります。その間も Unified Manager の使用は継続できますが、 Unified Manager はレイテンシ予測を使用して動的イベントを検出するため、一部のイベントは正確でなくなる可能性があります。時間の変更前に検出されたイベントは影響を受けません。

====