---
permalink: performance-checker/concept_how_storage_qos_can_control_workload_throughput.html 
sidebar: sidebar 
keywords: storage, qos, control, workload, throughput 
summary: QoS ポリシーグループを作成して、ポリシーグループに含まれるワークロードの 1 秒あたりの I/O 処理数（ IOPS ）やスループット（ MBps ）の上限を制御できます。デフォルトのポリシーグループなど、ワークロードに制限が設定されていないポリシーグループに含まれている場合や、設定された制限がニーズに合わない場合は、制限を増やしたり、希望する制限が設定された新しいポリシーグループまたは既存のポリシーグループにワークロードを移動したりできます。 
---
= ストレージ QoS がワークロードスループットを制御する仕組み
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
QoS ポリシーグループを作成して、ポリシーグループに含まれるワークロードの 1 秒あたりの I/O 処理数（ IOPS ）やスループット（ MBps ）の上限を制御できます。デフォルトのポリシーグループなど、ワークロードに制限が設定されていないポリシーグループに含まれている場合や、設定された制限がニーズに合わない場合は、制限を増やしたり、希望する制限が設定された新しいポリシーグループまたは既存のポリシーグループにワークロードを移動したりできます。

「従来の」 QoS ポリシーグループは、単一のボリュームや LUN など、個々のワークロードに割り当てることができます。この場合、ワークロードはスループットを上限まで使用できます。また、 QoS ポリシーグループを複数のワークロードに割り当てることもできます。この場合、ワークロードのスループットの上限は「「「赤」です。たとえば、 3 つのワークロードに 9 、 000 IOPS の QoS 制限を割り当てた場合、 IOPS の合計が 9 、 000 IOPS を超えないように制限されます。

アダプティブ QoS ポリシーグループは、個々のワークロードまたは複数のワークロードに割り当てることもできます。ただし、複数のワークロードに割り当てられている場合も、スループットの値を他のワークロードと共有するのではなく、各ワークロードでスループットが上限まで使用されます。また、アダプティブ QoS ポリシーは、スループットの設定をワークロードごとにボリュームサイズに基づいて自動的に調整し、ボリュームサイズが変わっても容量に対する IOPS の比率を維持します。たとえば、アダプティブ QoS ポリシーでピークが 5 、 000 IOPS/TB に設定されている場合、 10TB のボリュームの最大スループットは 50 、 000 IOPS になります。ボリュームのサイズが 20TB に変更されると、アダプティブ QoS によって最大値が 100 、 000 IOPS に調整されます。

ONTAP 9.5 以降では、アダプティブ QoS ポリシーを定義する際にブロックサイズを指定できます。これにより、ワークロードが非常に大きなブロックサイズを使用していて、その結果スループットの大半を使用しているケースでは、ポリシーのしきい値が IOPS/TB から MBps に変換されます。

グループで QoS ポリシーを共有している場合、ポリシーグループ内のすべてのワークロードの IOPS または MBps が設定された上限を超えると、ワークロードが調整されてそのアクティビティが制限されます。その結果、ポリシーグループ内のすべてのワークロードのパフォーマンスが低下することがあります。ポリシーグループの調整によって動的なパフォーマンスイベントが生成されると、イベント概要に関係するポリシーグループの名前が表示されます。

パフォーマンス：すべてのボリュームビューで、影響を受けたボリュームを IOPS と MBps でソートすると、イベントの原因となった可能性がある使用率が最も高いワークロードを確認できます。Performance/Volumes Explorer ヘエシでは、ボリューム上の他のボリュームまたは LUN を選択して、影響を受けるワークロードの IOPS または MBps スループットの使用率と比較できます。

ノードリソースを過剰に消費しているワークロードは、より制限の厳しいポリシーグループに割り当てます。これにより、ポリシーグループによる調整でワークロードのアクティビティが制限されて、そのノードでのリソースの使用が削減されます。ただし、ワークロードで使用できるノードのリソースを増やす場合は、ポリシーグループの値を大きくすることができます。

System Manager 、 ONTAP コマンド、または Unified Manager のパフォーマンスサービスレベルを使用してポリシーグループを管理できます。これには次のタスクが含まれます。

* ポリシーグループを作成する
* ポリシーグループ内のワークロードの追加または削除
* ポリシーグループ間でワークロードを移動する
* ポリシーグループのスループット制限を変更する
* 別のアグリゲートやノードへのワークロードの移動

