---
permalink: performance-checker/concept_object_monitoring_using_object_inventory_performance_pages.html 
sidebar: sidebar 
keywords: object, monitoring, performance, object, inventory, pages 
summary: パフォーマンスオブジェクトのインベントリページでは、特定のパフォーマンスカウンタの値またはパフォーマンスイベントに基づいてオブジェクトのパフォーマンスを監視できます。パフォーマンスイベントが報告されたオブジェクトを特定することで、クラスタのパフォーマンスの問題について原因を調査できます。 
---
= パフォーマンスオブジェクトのインベントリページを使用したオブジェクトの監視
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
パフォーマンスオブジェクトのインベントリページでは、特定のパフォーマンスカウンタの値またはパフォーマンスイベントに基づいてオブジェクトのパフォーマンスを監視できます。パフォーマンスイベントが報告されたオブジェクトを特定することで、クラスタのパフォーマンスの問題について原因を調査できます。

パフォーマンスオブジェクトのインベントリページには、すべてのクラスタ内のすべてのオブジェクトに関連付けられているカウンタ、関連付けられているオブジェクト、およびパフォーマンスしきい値ポリシーが表示されます。これらのページでは、パフォーマンスしきい値ポリシーをオブジェクトに適用することもできます。任意の列でページをソートしたり、結果をフィルタしてオブジェクトの数を絞り込んだりすることができます。また、すべてのオブジェクト名またはデータに対して検索を実行できます。

これらのページのデータをカンマ区切り値 (`.csv') ファイル、 Microsoft Excel ファイル (`.xlsx') 、または (`.pdf') ドキュメントにエクスポートするには、 *Reports* ボタンを使用します。次に、エクスポートしたデータを使用してレポートを作成します。また、ページをカスタマイズしてから、定期的に作成して E メールで送信するようにレポートをスケジュール設定することもできます。その場合は、 * Scheduled Reports * ボタンを使用します。
