---
permalink: performance-checker/reference_types_of_system_defined_performance_threshold_policies.html 
sidebar: sidebar 
keywords: system-defined, performance, threshold, policies, cluster, node. aggregate, qos 
summary: Unified Manager には、クラスタのパフォーマンスを監視し、イベントを自動生成する標準のしきい値ポリシーがいくつか用意されています。これらのポリシーはデフォルトで有効になっており、監視対象のパフォーマンスしきい値を超えたときに警告イベントまたは情報イベントを生成します。 
---
= システム定義のパフォーマンスしきい値ポリシーのタイプ
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager には、クラスタのパフォーマンスを監視し、イベントを自動生成する標準のしきい値ポリシーがいくつか用意されています。これらのポリシーはデフォルトで有効になっており、監視対象のパフォーマンスしきい値を超えたときに警告イベントまたは情報イベントを生成します。

[NOTE]
====
システム定義のパフォーマンスしきい値ポリシーは、 Cloud Volumes ONTAP 、 ONTAP Edge 、 ONTAP Select の各システムでは無効です。

====
システム定義のパフォーマンスしきい値ポリシーから不要なイベントが送られてくる場合は、 Event Setup ページで個々のポリシーのイベントを無効にすることができます。



== クラスタのしきい値ポリシー

システム定義のクラスタパフォーマンスしきい値ポリシーは、 Unified Manager で監視されている各クラスタにデフォルトで割り当てられます。

* * クラスタ負荷の不均衡 *
+
クラスタ内の 1 つのノードの負荷が他のノードよりもはるかに高く、ワークロードのレイテンシに影響を及ぼす可能性がある状況を特定します。

+
クラスタ内のすべてのノードの使用済みパフォーマンス容量の値が比較され、負荷の差が 30% を超えるノードがないかどうかが確認されます。これは警告イベントです。

* * クラスタ容量の不均衡 *
+
クラスタ内の 1 つのアグリゲートの使用済み容量が他のアグリゲートよりもはるかに多く、その結果、処理に必要なスペースに影響を及ぼす可能性がある状況を特定します。

+
クラスタ内のすべてのアグリゲートの使用済み容量の値が比較され、いずれかのアグリゲート間で 70% の差があるかどうかが確認されます。これは警告イベントです。





== ノードのしきい値ポリシー

システム定義のノードパフォーマンスしきい値ポリシーは、 Unified Manager で監視されているクラスタ内の各ノードにデフォルトで割り当てられます。

* * 使用済みパフォーマンス容量しきい値を超過 *
+
1 つのノードが運用効率の上限を超えて稼働していて、ワークロードのレイテンシに影響を及ぼしている可能性がある状況を特定します。

+
100% 以上のパフォーマンス容量を 12 時間以上使用しているノードが特定されます。これは警告イベントです。

* * 利用率の高いノード HA ペア *
+
HA ペアのノードが HA ペアの運用効率の上限を超えて稼働している状況を特定します。

+
HA ペアの 2 つのノードの使用済みパフォーマンス容量の値が確認されます。2 つのノードの使用済みパフォーマンス容量の合計が 12 時間以上にわたって 200% を超えている場合は、コントローラフェイルオーバーがワークロードのレイテンシに影響を及ぼします。これは情報イベントです。

* * ノードディスクの断片化 *
+
アグリゲート内の 1 つまたは複数のディスクが断片化されていて、主要なシステムサービスの速度が低下し、ノード上のワークロードのレイテンシに影響を及ぼしている可能性がある状況を特定します。

+
ノード上のすべてのアグリゲートで特定の読み取り / 書き込み処理の比率が確認されます。このポリシーは、 SyncMirror の再同期中、またはディスクスクラビング処理中にエラーが検出されたときにもトリガーされることがあります。これは警告イベントです。

+
[NOTE]
====
「ノードディスクの断片化」ポリシーは、 HDD のみのアグリゲートを分析します。 Flash Pool 、 SSD 、および FabricPool の各アグリゲートは分析しません。

====




== アグリゲートのしきい値ポリシー

システム定義のアグリゲートパフォーマンスしきい値ポリシーは、 Unified Manager で監視されているクラスタ内の各アグリゲートにデフォルトで割り当てられます。

* * 利用率の高いアグリゲートディスク *
+
アグリゲートが運用効率の上限を超えて稼働していて、ワークロードのレイテンシに影響を及ぼしている可能性がある状況を特定します。そのために、アグリゲート内のディスクの利用率が 30 分以上にわたって 95% を超えているアグリゲートが特定されます。この複数条件のポリシーでは、次に示す分析を実行して、問題の原因を特定します。

+
** アグリゲート内のディスクがバックグラウンドでメンテナンス作業を実行中かどうか。
+
ディスクに対してバックグラウンドで実行されるメンテナンス作業には、ディスク再構築、ディスクスクラビング、 SyncMirror の再同期、再パリティ化などがあります。

** ディスクシェルフの Fibre Channel インターコネクトに通信のボトルネックはあるか。
** アグリゲートの空きスペースが不足しているか。3 つの下位ポリシーのうちの 1 つ（または複数）にも違反しているとみなされた場合にのみ、このポリシーに対して警告イベントが発行されます。アグリゲート内のディスクの利用率が 95% を超えているだけであれば、パフォーマンスイベントはトリガーされません。




[NOTE]
====
「利用率の高いディスクを集約」ポリシーは、 HDD のみのアグリゲートと Flash Pool （ハイブリッド）アグリゲートを分析します。 SSD アグリゲートと FabricPool アグリゲートは分析しません。

====


== ワークロードレイテンシのしきい値ポリシー

システム定義のワークロード遅延しきい値ポリシーは、「想定レイテンシ」の値が定義されたパフォーマンスサービスレベルポリシーが設定されているワークロードに割り当てられます。

* * パフォーマンスサービスレベル * に定義されたワークロードのボリューム / LUN レイテンシしきい値を超過
+
ボリューム（ファイル共有）と LUN のうち、「想定レイテンシ」の制限を超えていて、ワークロードのパフォーマンスに影響を及ぼしているものを特定します。これは警告イベントです。

+
想定レイテンシの値を超えた時間が過去 1 時間に 30% を超えるワークロードがないかどうかが確認されます。





== QoS のしきい値ポリシー

システム定義の QoS パフォーマンスしきい値ポリシーは、 ONTAP の QoS 最大スループットポリシー（ IOPS 、 IOPS/TB 、または MBps ）が設定されているワークロードに割り当てられます。ワークロードのスループットの値が設定された QoS 値を 15% 下回ると、 Unified Manager はイベントをトリガーします。

* * QoS 最大 IOPS または MBps しきい値 *
+
IOPS または MBps が QoS 最大スループット制限を超えていて、ワークロードのレイテンシに影響を及ぼしているボリュームおよび LUN を特定します。これは警告イベントです。

+
ポリシーグループにワークロードが 1 つしか割り当てられていない場合、割り当てられている QoS ポリシーグループで定義された最大スループットしきい値を超えているワークロードが過去 1 時間の各収集期間にないかどうかが確認されます。

+
複数のワークロードで同じ QoS ポリシーを使用している場合は、ポリシーに割り当てられたすべてのワークロードの IOPS または MBps の合計が求められ、その合計がしきい値を超えていないかどうかが確認されます。

* * QoS ピーク IOPS/TB またはブロックサイズしきい値 *
+
IOPS/TB がアダプティブ QoS ピークスループット制限（またはブロックサイズ指定の IOPS/TB 制限）を超えていて、ワークロードのレイテンシに影響を及ぼしているボリュームを特定します。これは警告イベントです。

+
このポリシーでは、アダプティブ QoS ポリシーで定義された IOPS/TB のピークしきい値を各ボリュームのサイズに基づいて QoS 最大 IOPS の値に変換し、過去 1 時間の各パフォーマンス収集期間に QoS 最大 IOPS を超えているボリュームを探します。

+
[NOTE]
====
このポリシーは、クラスタに ONTAP 9.3 以降のソフトウェアがインストールされている場合にのみボリュームに適用されます。

====
+
アダプティブ QoS ポリシーに「 block size 」要素が定義されている場合、しきい値は各ボリュームのサイズに基づいて QoS の最大 MBps の値に変換されます。過去 1 時間の各パフォーマンス収集期間にこの値を超えているボリュームがないかどうかが確認されます。

+
[NOTE]
====
このポリシーは、クラスタに ONTAP 9.5 以降のソフトウェアがインストールされている場合にのみボリュームに適用されます。

====

