---
permalink: performance-checker/reference_what_performance_metrics_can_be_monitored_using_thresholds.html 
sidebar: sidebar 
keywords: performance, counters, tracked, thresholds 
summary: IOPS や MBps など、一部の共通のパフォーマンスカウンタでは、すべてのストレージオブジェクトを対象にしきい値を設定できます。それ以外のカウンタでは、特定のストレージオブジェクトに対してのみしきい値を設定できます。 
---
= しきい値を使用して追跡可能なパフォーマンスカウンタ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
IOPS や MBps など、一部の共通のパフォーマンスカウンタでは、すべてのストレージオブジェクトを対象にしきい値を設定できます。それ以外のカウンタでは、特定のストレージオブジェクトに対してのみしきい値を設定できます。



== 使用可能なパフォーマンスカウンタ

|===
| ストレージオブジェクト | パフォーマンスカウンタ | 説明 


 a| 
クラスタ
 a| 
IOPS
 a| 
クラスタで処理される 1 秒あたりの平均入出力処理数



 a| 
MB/s
 a| 
このクラスタとの間で転送されたデータの 1 秒あたりの平均メガバイト数。



 a| 
ノード
 a| 
IOPS
 a| 
ノードで処理される 1 秒あたりの平均入出力処理数



 a| 
MB/s
 a| 
このノードとの間で転送された 1 秒あたりの平均データ量（ MB ）。



 a| 
レイテンシ
 a| 
ノードがアプリケーションの要求に応答するまでの平均時間（ミリ秒）。



 a| 
利用率
 a| 
ノードの CPU と RAM の平均使用率



 a| 
使用済みパフォーマンス容量
 a| 
ノードによるパフォーマンス容量の平均消費率



 a| 
使用済みパフォーマンス容量 - テイクオーバー
 a| 
ノードによるパフォーマンス容量の平均消費率とパートナーノードのパフォーマンス容量



 a| 
アグリゲート
 a| 
IOPS
 a| 
アグリゲートで処理される 1 秒あたりの平均入出力処理数



 a| 
MB/s
 a| 
このアグリゲートとの間で転送された 1 秒あたりの平均データ量（ MB ）。



 a| 
レイテンシ
 a| 
アグリゲートがアプリケーションの要求に応答するまでの平均時間（ミリ秒）。



 a| 
利用率
 a| 
アグリゲートのディスクの平均使用率



 a| 
使用済みパフォーマンス容量
 a| 
アグリゲートによるパフォーマンス容量の平均消費率



 a| 
Storage VM
 a| 
IOPS
 a| 
SVM で処理される 1 秒あたりの平均入出力処理数



 a| 
MB/s
 a| 
この SVM との間で転送されたデータの平均メガバイト数 / 秒



 a| 
レイテンシ
 a| 
SVM がアプリケーションの要求に応答するまでの平均時間（ミリ秒）。



 a| 
ボリューム
 a| 
IOPS
 a| 
ボリュームで処理される 1 秒あたりの平均入出力処理数



 a| 
MB/s
 a| 
このボリュームとの間で転送された 1 秒あたりの平均データ量



 a| 
レイテンシ
 a| 
ボリュームがアプリケーションの要求に応答するまでの平均時間（ミリ秒）。



 a| 
キャッシュミス率
 a| 
クライアントアプリケーションからの読み取り要求に対してキャッシュからではなくボリュームからデータが返される割合の平均値



 a| 
LUN
 a| 
IOPS
 a| 
LUN で処理される 1 秒あたりの平均入出力処理数



 a| 
MB/s
 a| 
この LUN との間で転送されたデータの平均メガバイト数 / 秒



 a| 
レイテンシ
 a| 
LUN がアプリケーションの要求に応答するまでの平均時間（ミリ秒）。



 a| 
ネームスペース
 a| 
IOPS
 a| 
ネームスペースで処理される 1 秒あたりの平均入出力処理数



 a| 
MB/s
 a| 
このネームスペースとの間で転送された 1 秒あたりの平均データ量（ MB ）。



 a| 
レイテンシ
 a| 
ネームスペースがアプリケーションの要求に応答するまでの平均時間（ミリ秒）。



 a| 
ポート
 a| 
帯域幅使用率
 a| 
ポートの使用可能な帯域幅の平均使用率



 a| 
MB/s
 a| 
このポートとの間で転送された 1 秒あたりの平均データ量（ MB ）。



 a| 
ネットワークインターフェイス（ LIF ）
 a| 
MB/s
 a| 
この LIF との間で転送されたデータの 1 秒あたりの平均メガバイト数

|===