---
permalink: performance-checker/reference_what_objects_can_be_used_in_threshold_policies.html 
sidebar: sidebar 
keywords: objects, counters, combination, threshold, policies 
summary: 組み合わせポリシーで一緒に使用できるパフォーマンスカウンタには種類に制限があります。プライマリとセカンダリのパフォーマンスカウンタを指定した場合、両方のパフォーマンスカウンタが上限を超えたときにイベントが生成されます。 
---
= 組み合わせしきい値ポリシーで使用できるオブジェクトとカウンタ
:icons: font
:imagesdir: ../media/


[role="lead"]
組み合わせポリシーで一緒に使用できるパフォーマンスカウンタには種類に制限があります。プライマリとセカンダリのパフォーマンスカウンタを指定した場合、両方のパフォーマンスカウンタが上限を超えたときにイベントが生成されます。

|===
| プライマリストレージのオブジェクトとカウンタ | セカンダリストレージのオブジェクトとカウンタ 


 a| 
ボリュームレイテンシ
 a| 
Volume IOPS の略



 a| 
Volume MB/s の略



 a| 
アグリゲート利用率



 a| 
アグリゲート - 使用済みパフォーマンス容量



 a| 
ノード利用率



 a| 
ノード使用済みパフォーマンス容量



 a| 
ノード使用済みパフォーマンス容量 - テイクオーバー



 a| 
LUN レイテンシ
 a| 
LUN の IOPS



 a| 
LUN MBps



 a| 
アグリゲート利用率



 a| 
アグリゲート - 使用済みパフォーマンス容量



 a| 
ノード利用率



 a| 
ノード使用済みパフォーマンス容量



 a| 
ノード使用済みパフォーマンス容量 - テイクオーバー

|===
[NOTE]
====
ボリュームの組み合わせポリシーが FlexVol ボリュームではなく FlexGroup ボリュームに適用される場合、セカンダリ・カウンタとして選択できる属性は「ボリューム IOPS 」と「ボリューム MBps 」のみです。しきい値ポリシーにノードまたはアグリゲートの属性が 1 つでも含まれていると、そのポリシーは FlexGroup ボリュームには適用されず、エラーメッセージが表示されます。これは、 FlexGroup ボリュームは複数のノードまたはアグリゲートに存在できるためです。

====