---
permalink: performance-checker/task_respond_to_cluster_imbalance_performance_events.html 
sidebar: sidebar 
keywords: cluster, imbalance, performance, events 
summary: Unified Manager は、クラスタ内の 1 つのノードの負荷が他のノードよりもはるかに高く、ワークロードのレイテンシに影響を及ぼしている可能性がある場合、クラスタ不均衡警告イベントを生成します。これらのシステム定義のイベントにより、多くのワークロードにレイテンシの影響が及ぶ前に潜在的なパフォーマンスの問題を修正することができます。 
---
= クラスタ不均衡パフォーマンスイベントに対処する
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager は、クラスタ内の 1 つのノードの負荷が他のノードよりもはるかに高く、ワークロードのレイテンシに影響を及ぼしている可能性がある場合、クラスタ不均衡警告イベントを生成します。これらのシステム定義のイベントにより、多くのワークロードにレイテンシの影響が及ぶ前に潜在的なパフォーマンスの問題を修正することができます。

* 必要なもの *

オペレータ、アプリケーション管理者、またはストレージ管理者のロールが必要です。

Unified Manager では、クラスタ内のすべてのノードの使用済みパフォーマンス容量の値を比較し、負荷の差が 30% を超えるノードがないかどうかを確認することで、クラスタ不均衡しきい値ポリシーの違反とみなして警告イベントを生成します。

負荷の高いワークロードを利用率の低いノードに移動するには、以下に示す手順で次のリソースを特定します。

* 同じクラスタ上の利用率の低いノード
* この別のノードで最も利用率の低いアグリゲート
* 現在のノードで最も負荷の高いボリューム


.手順
. イベントの詳細ページを表示して、イベントに関する情報を確認します。
. イベントの原因となったしきい値違反の説明が記載された * 概要 * を確認します。
+
たとえば、「使用済みパフォーマンス容量カウンタは、クラスタ Dallas-1-8 のノード間で負荷に 62% の差があることを示しており、システムしきい値 30% に基づいて警告イベントをトリガーしました」というメッセージは、いずれかのノードのパフォーマンス容量の使用率が高く、ノードのパフォーマンスに影響を及ぼしていることを示しています。

. 使用済みパフォーマンス容量の値が高いノードから使用済みパフォーマンス容量の値が最も低いノードに負荷の高いボリュームを移動するには、「 Suggested Actions 」のテキストを確認します。
. 使用済みパフォーマンス容量の値が最も高いノードと最も低いノードを特定します。
+
.. 「 * イベント情報」セクションで、ソースクラスタの名前をクリックします。
.. [*Cluster/Performance Summary*] ページの [*Managed Objects* ] 領域で [*Nodes* ] をクリックします。
.. ノード * インベントリページで、ノードを * Performance Capacity Used * 列でソートします。
.. 使用済みパフォーマンス容量の値が最も高いノードと最も低いノードを特定し、名前をメモします。


. 使用済みパフォーマンス容量の値が最も高いノードで IOPS が最も高いボリュームを特定します。
+
.. 使用済みパフォーマンス容量の値が最も高いノードをクリックします。
.. ノード / パフォーマンスエクスプローラ * ページで、 * 表示と比較 * メニューからこのノード上のアグリゲートを選択します。
.. 使用済みパフォーマンス容量の値が最も高いアグリゲートをクリックします。
.. アグリゲート / パフォーマンスエクスプローラ * ページで、 * 表示と比較 * メニューから * このアグリゲート上のボリュームを選択します。
.. ボリュームを * IOPS * 列でソートし、 IOPS が最も高いボリュームの名前と、ボリュームが配置されているアグリゲートの名前をメモします。


. 使用済みパフォーマンス容量の値が最も低いノードの利用率が最も低いアグリゲートを特定します。
+
.. Storage * > * Aggregates * をクリックして、 * Aggregates * インベントリページを表示します。
.. パフォーマンス：すべてのアグリゲート * ビューを選択します。
.. [*Filter*] ボタンをクリックして ' フィルタを追加しますここで 'Node' は ' 手順 4 で書き留めたパフォーマンス容量の使用済みの最小値を持つノードの名前です
.. 使用済みパフォーマンス容量の値が最も低いアグリゲートの名前を書き留めます。


. 新しいノードの利用率が低いアグリゲートに過負荷のノードからボリュームを移動します。
+
移動処理は、 ONTAP の System Manager 、 OnCommand Workflow Automation 、 ONTAP コマンド、またはこれらのツールを組み合わせて使用して実行できます。



数日後に、このクラスタから同じクラスタ不均衡イベントを受け取っていないかを確認します。
