---
permalink: performance-checker/task_view_workload_qos_minimum_and_maximum_settings.html 
sidebar: sidebar 
keywords: view, workload, qos, minimum, maximum, settings, performance, explorer 
summary: パフォーマンスエクスプローラのグラフで、ボリュームまたは LUN に対する ONTAP 定義のサービス品質（ QoS ）ポリシーの設定を確認できます。最大スループット設定は、競合するワークロードによるシステムリソースへの影響を抑制するために使用されます。最小スループット設定は、競合するワークロードによる要求に関係なく、重要なワークロードに最小限のスループットを確保するために使用されます。 
---
= パフォーマンスエクスプローラでワークロードの QoS の下限と上限の設定を確認します
:icons: font
:imagesdir: ../media/


[role="lead"]
パフォーマンスエクスプローラのグラフで、ボリュームまたは LUN に対する ONTAP 定義のサービス品質（ QoS ）ポリシーの設定を確認できます。最大スループット設定は、競合するワークロードによるシステムリソースへの影響を抑制するために使用されます。最小スループット設定は、競合するワークロードによる要求に関係なく、重要なワークロードに最小限のスループットを確保するために使用されます。

QoS スループット「最小」および「最大」 IOPS および MBps の設定は、 ONTAP で設定されている場合にのみカウンタチャートに表示されます。最小スループット設定は、 ONTAP 9.2 以降のソフトウェアを実行しているシステムでのみ使用できます。 AFF システムでのみ使用でき、現時点では IOPS についてのみ設定できます。

アダプティブ QoS ポリシーは ONTAP 9.3 以降で使用でき、 IOPS の代わりに IOPS/TB が使用されます。アダプティブポリシーは、 QoS ポリシーの値をワークロードごとにボリュームサイズに基づいて自動的に調整し、ボリュームサイズが変わっても容量に対する IOPS の比率を維持します。アダプティブ QoS ポリシーグループはボリュームにのみ適用できます。QoS の用語 "expected" と "peak" は、最小と最大ではなくアダプティブ QoS ポリシーに使用されます。

Unified Manager では、定義されている QoS 最大ポリシーの設定を超えるワークロードが過去 1 時間の各パフォーマンス収集期間で見つかった場合に、 QoS ポリシーの違反とみなして警告イベントを生成します。ワークロードのスループットが各収集期間に短時間だけ QoS のしきい値を超えることがありますが、 Unified Manager のグラフには収集期間中の「平均」のスループットが表示されます。そのため、 QoS のイベントが表示された場合でも、グラフではワークロードのスループットがポリシーのしきい値を超えていないように見えることがあります。

.手順
. 選択したボリュームまたは LUN の * パフォーマンスエクスプローラ * ページで、次の操作を実行して QoS の上限と下限の設定を表示します。
+
|===
| 状況 | 手順 


 a| 
IOPS の上限（ QoS 最大）を表示する
 a| 
IOPS の合計または内訳グラフで、 * ズームビュー * をクリックします。



 a| 
MBps の上限（ QoS 最大）を表示する
 a| 
MBps の合計または内訳グラフで、 * ズームビュー * をクリックします。



 a| 
IOPS の下限（ QoS 最小）を表示する
 a| 
IOPS の合計または内訳グラフで、 * ズームビュー * をクリックします。



 a| 
IOPS/TB の上限（ QoS ピーク）を表示する
 a| 
ボリュームの場合は、 IOPS/TB チャートで * Zoom View * をクリックします。



 a| 
IOPS/TB の下限（ QoS 想定）を表示する
 a| 
ボリュームの場合は、 IOPS/TB チャートで * Zoom View * をクリックします。

|===
+
横方向の点線は、 ONTAP で設定された最大または最小のスループット値を示します。QoS 値に対する変更がいつ実装されたかを確認することもできます。

. IOPS および MBps の具体的な値を QoS 設定と比較して確認するには、グラフ領域にカーソルを合わせてポップアップウィンドウを参照します。


特定のボリュームまたは LUN の IOPS や MBps が非常に高く、システムリソースを圧迫している場合は、 System Manager または ONTAP CLI を使用して、それらのワークロードが他のワークロードのパフォーマンスに影響しないように QoS 設定を調整することができます。

QoS 設定の調整の詳細については、 ONTAP 9 パフォーマンス管理パワーガイドを参照してください。

http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-perf-mon/home.html["ONTAP 9 パフォーマンス管理パワーガイド"]
