---
permalink: performance-checker/task_view_node_iops_based_on_workloads_on_local_node.html 
sidebar: sidebar 
keywords: view, node, iops, workloads, reside, only, local node 
summary: 'ノードの IOPS カウンタグラフでは、リモートノード上のボリュームに対する読み取り / 書き込み処理を実行するために、処理がネットワーク LIF を使用してローカルノードのみを経由する箇所を特定できます。IOPS の「 Total (Local) 」グラフと「 Breakdown (Local) 」グラフには、現在のノード上にあるローカルボリュームに存在するデータの IOPS が表示されます。' 
---
= ローカルノードにのみ存在するワークロードに基づいてノードIOPSを表示する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ノードの IOPS カウンタグラフでは、リモートノード上のボリュームに対する読み取り / 書き込み処理を実行するために、処理がネットワーク LIF を使用してローカルノードのみを経由する箇所を特定できます。IOPS の「 Total (Local) 」グラフと「 Breakdown (Local) 」グラフには、現在のノード上のみのローカルボリュームに存在するデータの IOPS が表示されます。

これらのカウンタ・チャートの「ローカル」バージョンは ' ローカル・ボリューム上に存在するデータの統計のみを表示するため ' パフォーマンス容量と使用率のノード・チャートに似ています

これらのカウンタグラフの「ローカル」バージョンと、通常の合計バージョンのカウンタグラフを比較することで、ローカルノードを経由してリモートノード上のボリュームにアクセスしているトラフィックが大量にあるかどうかを確認できます。ローカルノードを経由してリモートノード上のボリュームにアクセスしている処理が多すぎると原因のパフォーマンスの問題が報告される可能性があります。このような場合は、ボリュームをローカルノードに移動したり、ホストからそのボリュームにアクセスしているトラフィックを接続可能なリモートノードに LIF を作成したりすることができます。

.手順
. 選択したノードの * パフォーマンス / ノードエクスプローラ * ページで、 IOPS チャートから、ドロップダウンメニューから * 合計 * を選択します。
+
IOPS の合計グラフが表示されます。

. [* ズームビュー * ] をクリックすると、新しいブラウザタブにグラフのより大きなバージョンが表示されます。
. パフォーマンス / ノードエクスプローラ * ページに戻り、 IOPS チャートから、ドロップダウンメニューから * 合計（ローカル） * を選択します。
+
IOPS の合計（ローカル）グラフが表示されます。

. [* ズームビュー * ] をクリックすると、新しいブラウザタブにグラフのより大きなバージョンが表示されます。
. グラフを並べて表示し、 IOPS 値が大きく異なっている領域を特定します。
. これらの領域にカーソルを合わせると、特定の時点におけるローカルと合計の IOPS が比較されます。

