---
permalink: performance-checker/task_view_performance_status_of_all_san_array_clusters.html 
sidebar: sidebar 
keywords: all san, array, performance, clusters 
summary: Performance ： All SAN Array クラスタのパフォーマンスステータスは、 Performance ： All Clusters ビューを使用して表示できます。 
---
= オール SAN アレイクラスタのパフォーマンスの表示
:icons: font
:imagesdir: ../media/


[role="lead"]
Performance ： All SAN Array クラスタのパフォーマンスステータスは、 Performance ： All Clusters ビューを使用して表示できます。

* 必要なもの *

オペレータ、アプリケーション管理者、またはストレージ管理者のロールが必要です。

オール SAN アレイクラスタの概要情報は、パフォーマンス：すべてのクラスタビューで確認できます。詳細については、クラスタ / パフォーマンスエクスプローラのページを参照してください。

.手順
. 左側のナビゲーションペインで、 * Storage * > * Clusters * をクリックします。
. 「パーソナリティ」列が * 正常性：すべてのクラスタ * ビューに表示されていることを確認するか、 * 表示 / 非表示 * コントロールを使用して追加します。
+
この列には ' すべての SAN アレイクラスタのすべての SAN アレイが表示されます

. これらのクラスタのパフォーマンスに関する情報を表示するには、「 * パフォーマンス：すべてのクラスタ * 」ビューを選択します。
+
オール SAN アレイクラスタのパフォーマンス情報を表示します。

. これらのクラスタのパフォーマンスに関する詳細情報を表示するには、オール SAN アレイクラスタの名前をクリックします。
. [* エクスプローラ * ] タブをクリックします。
. [ * クラスタ / パフォーマンスエクスプローラ * ] ページで、 [ * 表示と比較 * ] メニューから [ このクラスタ上のノード * ] を選択します。
+
このクラスタの両方のノードのパフォーマンス統計を比較して、両方のノードの負荷がほぼ同じであることを確認できます。2 つのノードの間に大きな差がある場合は、 2 つ目のノードをグラフに追加し、もっと長い期間の値を比較することで、構成の問題を特定できます。


