---
permalink: performance-checker/task_display_information_about_performance_event.html 
sidebar: sidebar 
keywords: display, information, performance, events 
summary: イベント管理インベントリページを使用して、 Unified Manager で監視されているクラスタ上のすべてのパフォーマンスイベントのリストを表示できます。この情報を表示することで、最も重大なイベントを特定し、詳細情報にドリルダウンしてイベントの原因を確認できます。 
---
= パフォーマンスイベントに関する情報を表示する
:icons: font
:imagesdir: ../media/


[role="lead"]
イベント管理インベントリページを使用して、 Unified Manager で監視されているクラスタ上のすべてのパフォーマンスイベントのリストを表示できます。この情報を表示することで、最も重大なイベントを特定し、詳細情報にドリルダウンしてイベントの原因を確認できます。

* 必要なもの *

* オペレータ、アプリケーション管理者、またはストレージ管理者のロールが必要です。


イベントのリストは検出時刻でソートされ、最新のイベントが最初に表示されます。列ヘッダーをクリックすると、その列でイベントをソートできます。たとえば、 Status 列でソートして、重大度別にイベントを表示できます。特定のイベントまたは特定のタイプのイベントを検索する場合は、フィルタと検索を使用して、リストに表示するイベントを絞り込むことができます。

このページにはすべてのソースのイベントが表示されます。

* ユーザ定義のパフォーマンスしきい値ポリシー
* システム定義のパフォーマンスしきい値ポリシー
* 動的なパフォーマンスしきい値


[ イベントタイプ ] 列には、イベントのソースが一覧表示されます。イベントを選択すると、そのイベントに関する詳細をイベントの詳細ページで確認できます。

.手順
. 左側のナビゲーションペインで、 * イベント管理 * をクリックします。
. [ 表示 ] メニューから、 [ アクティブなパフォーマンスイベント * ] を選択します。
+
このページには、過去 7 日間に生成された「新規」と「確認済み」のすべてのパフォーマンスイベントが表示されます。

. 分析するイベントを特定し、イベント名をクリックします。
+
イベントの詳細ページが表示されます。

+
[NOTE]
====
また、パフォーマンスエクスプローラのページでイベント名のリンクをクリックし、アラート E メールでイベントの詳細ページを表示することもできます。

====

