---
permalink: performance-checker/task_move_workloads_to_node_in_different_ha_pair.html 
sidebar: sidebar 
keywords: move, workloads, node, different, ha pair 
summary: 現在ワークロードが実行されている HA ペアよりも空きパフォーマンス容量が大きい別のハイアベイラビリティ（ HA ）ペアのノード上のアグリゲートを Unified Manager で特定し、その後、選択したボリュームを新しい HA ペア上のアグリゲートに移動できます。 
---
= ワークロードを別のHAペアのノードに移動する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
現在ワークロードが実行されている HA ペアよりも空きパフォーマンス容量が大きい別のハイアベイラビリティ（ HA ）ペアのノード上のアグリゲートを Unified Manager で特定し、その後、選択したボリュームを新しい HA ペア上のアグリゲートに移動できます。

.開始する前に
* オペレータ、アプリケーション管理者、またはストレージ管理者のロールが必要です。
* クラスタが 2 つ以上の HA ペアで構成されている必要があります
+
クラスタに HA ペアが 1 つしかない場合は、この改善策を実施できません。

* 現在パフォーマンス問題がある HA ペアの 2 つのノードの名前を記録しておく必要があります。
* ノードがパフォーマンスイベントを受け取った日付と時刻を記録しておく必要があります。
* Unified Manager で 1 カ月分以上のパフォーマンスデータの収集と分析が行われている必要があります。


空きパフォーマンス容量が大きいノード上のアグリゲートに負荷の高いワークロードを移動すれば、両ノードでのワークロードの効率が向上します。この手順で次のリソースを特定すると、負荷の高いワークロードを別の HA ペアの空きパフォーマンス容量の大きいノードに移動できます。

* 同じクラスタ上の別の HA ペアで最も空きパフォーマンス容量が大きいノード
* 別のノードで最も空きパフォーマンス容量が大きいアグリゲート
* 現在のノードで最も負荷の高いボリューム


.手順
. 同じクラスタ上の別の HA ペアを構成するノードを特定します。
+
.. [ * Event Details * ] ページで、ノードが存在するクラスタの名前をクリックします。
+
パフォーマンス / クラスタランディングページにクラスタの詳細が表示されます。

.. [ * 概要 * ] ページの [ * 管理対象オブジェクト * ] ペインで [ * ノード * ] をクリックします。
+
このクラスタ上のノードのリストは、 Performance ： All Nodes ビューに表示されます。

.. 現在パフォーマンス問題がある HA ペアとは別の HA ペアのノードの名前を書き留めます。


. 別の HA ペアで最も空きパフォーマンス容量が大きいノードを特定します。
+
.. [ パフォーマンス：すべてのノード * ] ビューで、 [ 使用済みパフォーマンス容量 * ] 列をクリックして、使用率が最も低いノードをソートします。
+
これにより、ワークロードの移動先にするノードの候補が一覧表示されます。

.. ワークロードの移動先にする別の HA ペアのノードの名前を書き留めます。


. 別のノードで最も空きパフォーマンス容量が大きいアグリゲートを特定します。
+
.. [* パフォーマンス：すべてのノード * （ * Performance ： All Nodes * ） ] ビューで、ノードをクリックします。
+
ノードの詳細が Performance/NodeExplorer ヘエシに表示されます。

.. View and Compare * メニューで、このノードのアグリゲートを選択します。
+
このノード上のアグリゲートがグリッドに表示されます。

.. 使用済みパフォーマンス容量 * 列をクリックして、アグリゲートを使用量が最も少ない順にソートします。
+
これにより、ワークロードの移動先にするアグリゲートの候補が一覧表示されます。

.. ワークロードの移動先にするアグリゲートの名前を書き留めます。


. イベントを受け取ったノードで負荷の高いワークロードを特定します。
+
.. イベントの * Event * 詳細ページに戻ります。
.. 影響を受けるボリューム * フィールドで、最初のノードのボリューム数のリンクをクリックします。
+
Performance ： All Volumes ビューには、そのノード上のボリュームがフィルタリングされて表示されます。

.. 合計容量 * 列をクリックして、ボリュームを最大割り当てスペースでソートします。
+
これにより、移動するボリュームの候補が一覧表示されます。

.. 移動するボリュームの名前と、そのボリュームが現在配置されているアグリゲートの名前を書き留めます。
.. このイベントに関係した 2 つ目のノードに対して手順 4c と 4d を実行して、そのノードから移動するボリュームの候補を特定します。


. 事前に特定した別のノードで最も空きパフォーマンス容量が大きいアグリゲートにボリュームを移動します。
+
移動処理は、 ONTAP の System Manager 、 OnCommand Workflow Automation 、 ONTAP コマンド、またはこれらのツールを組み合わせて使用して実行できます。



数日後に、このノードまたはアグリゲートから同じタイプのイベントを受け取っていないかどうかを確認します。
