---
permalink: performance-checker/task_add_alerts_for_performance_events.html 
sidebar: sidebar 
keywords: add, alerts, performance, events 
summary: パフォーマンスイベントのアラートは、 Unified Manager で受信する他のイベントと同様に、イベントごとに個別に設定することができます。また、すべてのパフォーマンスイベントを同じように扱い、同じユーザに E メールを送信する場合は、重大または警告のパフォーマンスイベントがトリガーされたときに通知する共通のアラートを作成することもできます。 
---
= パフォーマンスイベントのアラートを追加しています
:icons: font
:imagesdir: ../media/


[role="lead"]
パフォーマンスイベントのアラートは、 Unified Manager で受信する他のイベントと同様に、イベントごとに個別に設定することができます。また、すべてのパフォーマンスイベントを同じように扱い、同じユーザに E メールを送信する場合は、重大または警告のパフォーマンスイベントがトリガーされたときに通知する共通のアラートを作成することもできます。

* 必要なもの *

アプリケーション管理者またはストレージ管理者のロールが必要です。

次の例は、レイテンシ、 IOPS 、および MBps のすべての重大イベントに対するイベントを作成する方法を示しています。同じ方法で、すべてのパフォーマンスカウンタからイベントを選択したり、すべての警告イベントに対してイベントを選択したりできます。

.手順
. 左側のナビゲーションペインで、 * Storage Management * > * Alert Setup * をクリックします。
. [Alert Setup] ページで、 [*Add*] をクリックします。
. ［ アラートの追加 ］ ダイアログボックスで、 ［ * 名前 * ］ をクリックし、アラートの名前と概要を入力します。
. [* リソース ] ページでは、リソースを選択しないでください。
+
リソースを選択していないため、クラスタ、アグリゲート、ボリュームなど、何に対するイベントを受信したかに関係なく、すべてのリソースにアラートが適用されます。

. [* Events （イベント） ] をクリックして、次の操作を実行します。
+
.. イベントの重大度リストで、 * クリティカル * を選択します。
.. [Event Name Contains] フィールドに「 * latency * 」と入力し、矢印をクリックして、一致するすべてのイベントを選択します。
.. [Event Name Contains] フィールドに「 * IOPS* 」と入力し、矢印をクリックして、一致するすべてのイベントを選択します。
.. [Event Name Contains] フィールドに「 *Mbps*] 」と入力し、矢印をクリックして一致するすべてのイベントを選択します。


. [* アクション * ] をクリックし、 [ これらのユーザーに警告 ] フィールドで警告メールを受信するユーザーの名前を選択します。
. SNMP トラップの発行やスクリプトの実行など、このページの他のオプションを設定します。
. [ 保存（ Save ） ] をクリックします。

