---
permalink: performance-checker/task_move_workloads_to_an_aggregate_on_different_node.html 
sidebar: sidebar 
keywords: moving, workloads, aggregate, different, node 
summary: ワークロードが現在実行されているノードよりも負荷の低い別のノード上のアグリゲートを Unified Manager で特定し、選択したボリュームをそのアグリゲートに移動できます。負荷の低いノード上のアグリゲートに負荷の高いワークロードを移動すれば、両ノードでのワークロードの効率が向上します。 
---
= 別のノード上のアグリゲートへのワークロードの移動
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ワークロードが現在実行されているノードよりも負荷の低い別のノード上のアグリゲートを Unified Manager で特定し、選択したボリュームをそのアグリゲートに移動できます。負荷の低いノード上のアグリゲートに負荷の高いワークロードを移動すれば、両ノードでのワークロードの効率が向上します。

* 必要なもの *

* オペレータ、アプリケーション管理者、またはストレージ管理者のロールが必要です。
* 現在パフォーマンス問題があるノードの名前を記録しておく必要があります。
* ノードがパフォーマンスイベントを受け取った日付と時刻を記録しておく必要があります。
* Unified Manager で 1 カ月分以上のパフォーマンスデータの収集と分析が行われている必要があります。


負荷の高いワークロードを利用率の低いノードに移動するには、以下に示す手順で次のリソースを特定します。

* 同じクラスタ上の利用率の低いノード
* この別のノードで最も利用率の低いアグリゲート
* 現在のノードで最も負荷の高いボリューム


.手順
. クラスタ内で最も利用率の低いノードを特定します。
+
.. イベント * の詳細ページで、ノードが配置されているクラスタの名前をクリックします。
+
パフォーマンス / クラスタランディングページにクラスタの詳細が表示されます。

.. [ * 概要 * ] ページの [ * 管理対象オブジェクト * ] ペインで [ * ノード * ] をクリックします。
+
このクラスタ上のノードのリストが表示されます。

.. ノードを利用率が低い順にソートするには、 * Utilization * 列をクリックします。
+
また、最大の * 空き容量 * を持つノードを特定することもできます。これにより、ワークロードの移動先にするノードの候補が一覧表示されます。

.. ワークロードの移動先にするノードの名前を書き留めます。


. この別のノード上の最も利用率の低いアグリゲートを特定します。
+
.. 左側のナビゲーションペインで、 * Storage * > * Aggregates * をクリックし、 View メニューから * Performance * > * All Aggregates * を選択します。
+
Performance ： All Aggregates ビューが表示されます。

.. [*Filtering*] をクリックし、左側のドロップダウンメニューから [*Node] を選択して、テキストフィールドにノード名を入力し、 [*Apply Filter*] をクリックします。
+
Performance ： All aggregates ビューが再表示され、このノードで使用可能なアグリゲートのリストが表示されます。

.. 利用率 * 列をクリックして、アグリゲートを利用率が低い順にソートします。
+
空き容量が最も多いアグリゲートを特定することもできます。これにより、ワークロードの移動先にするアグリゲートの候補が一覧表示されます。

.. ワークロードの移動先にするアグリゲートの名前を書き留めます。


. イベントを受け取ったノードで負荷の高いワークロードを特定します。
+
.. イベントの * Event * 詳細ページに戻ります。
.. [ * 影響を受けるボリューム * ] フィールドで、ボリューム数のリンクをクリックします。
+
Performance ： All Volumes ビューには、そのノード上のボリュームがフィルタリングされて表示されます。

.. 合計容量 * 列をクリックして、ボリュームを最大割り当てスペースでソートします。
+
これにより、移動するボリュームの候補が一覧表示されます。

.. 移動するボリュームの名前と、そのボリュームが現在配置されているアグリゲートの名前を書き留めます。


. 事前に特定した別のノードで最も利用率の低いアグリゲートにボリュームを移動します。
+
移動処理は、 ONTAP の System Manager 、 OnCommand Workflow Automation 、 ONTAP コマンド、またはこれらのツールを組み合わせて使用して実行できます。



数日後に、このノードまたはアグリゲートから同じタイプのイベントを受け取っていないかどうかを確認します。
