---
permalink: storage-mgmt/concept_manage_performance_service_levels.html 
sidebar: sidebar 
keywords: manage, performance, service, levels 
summary: パフォーマンスサービスレベルを使用すると、ワークロードに対してパフォーマンスとストレージの目標を定義できます。ワークロードの作成時または編集時に、パフォーマンスサービスレベルをワークロードに割り当てることができます。 
---
= パフォーマンスサービスレベルの管理
:icons: font
:imagesdir: ../media/


[role="lead"]
パフォーマンスサービスレベルを使用すると、ワークロードに対してパフォーマンスとストレージの目標を定義できます。ワークロードの作成時または編集時に、パフォーマンスサービスレベルをワークロードに割り当てることができます。

ストレージリソースは、サービスレベル目標（ SLO ）に基づいて管理および監視されます。SLO は、必要なパフォーマンスと容量に基づくサービスレベルアグリーメントによって定義されます。Unified Manager では、 SLO と言った場合、ネットアップストレージで実行されているアプリケーションの PSL の定義を表します。ストレージサービスの内容は、基盤となるリソースのパフォーマンスと利用率に基づいて決定されます。PSL はストレージサービス目標の概要です。ストレージプロバイダは、 PSL を使用してワークロードに目標とするパフォーマンスと容量を指定できます。

Unified Manager には、変更できない組み込みのポリシーがいくつか用意されています。事前定義されたパフォーマンスサービスレベルは「最高レベルのパフォーマンス」、「パフォーマンス」、「バリュー」です。Extreme Performance 、 Performance 、および Value PSL は、データセンターの一般的なストレージワークロードのほとんどに該当します。Unified Manager では、データベースアプリケーション用の PSL として「最高レベル」、「データベース共有データ用の最高レベル」、「データベースデータ用の最高レベル」の 3 つの PSL も提供されます。これらは、バースト IOPS をサポートする非常にハイパフォーマンスな PSL であり、スループットの要求が最も高いデータベースアプリケーションに適しています。事前に定義された PSL が要件に合わない場合は、 PSL のニーズを満たす新しいを作成できます。

PSL には、「 * Policies * > * Performance Service Levels * 」ページからアクセスできます。また、ストレージプロバイダ API を使用してアクセスできます。PSL を割り当ててストレージワークロードを管理すると、ストレージワークロードを個別に管理する必要がなくなるため便利です。変更については、個別に管理するのではなく、別の PSL を再割り当てして管理することもできます。

システム定義の PSL またはワークロードに現在割り当てられている PSL は変更できません。ワークロードに割り当てられている PSL 、または他に使用可能な PSL がない PSL は削除できません。

パフォーマンスサービスレベルページには、使用可能な PSL ポリシーが表示されます。このページで、ポリシーを追加、編集、削除することができます。このページには、次の情報が表示されます。

|===
| フィールド | 説明 


 a| 
名前
 a| 
パフォーマンスサービスレベルの名前。



 a| 
を入力します
 a| 
システム定義のポリシーかユーザ定義のポリシーか。



 a| 
想定 IOPS
 a| 
LUN またはファイル共有でアプリケーションが実行すると想定される最小 IOPS 。想定 IOPS は、ストレージオブジェクトの割り当てサイズに基づいて、割り当てられる最小想定 IOPS を指定します。



 a| 
最大 IOPS
 a| 
LUN またはファイル共有でアプリケーションが実行できる最大 IOPS 。ピーク IOPS は、ストレージオブジェクトの割り当てサイズまたは使用済みサイズに基づいて、割り当て可能な最大 IOPS を指定します。

ピーク IOPS は割り当てポリシーを基準にして算出されます。割り当てポリシーは、 allocated-space または used-space のいずれかです。割り当てポリシーが allocated-space の場合は、ストレージオブジェクトのサイズに基づいてピーク IOPS が計算されます。割り当てポリシーが used-space の場合は、 Storage Efficiency 機能の効果を考慮し、ストレージオブジェクトに格納されているデータの量に基づいてピーク IOPS が計算されます。デフォルトでは、割り当てポリシーは used-space に設定されています。



 a| 
絶対最小 IOPS
 a| 
絶対最小 IOPS は、想定 IOPS がこの値より低い場合に使用されます。システム定義の PSL のデフォルト値は次のとおりです。

* 最高レベルのパフォーマンス：想定 IOPS ≧ 6144/TB の場合、絶対最小 IOPS=1000
* パフォーマンス： 6144/TB > 想定 IOPS ≧ 2048/TB の場合、絶対最小 IOPS=500
* バリュー： 2048/TB > 想定 IOPS ≧ 128/TB の場合、絶対最小 IOPS=75


システム定義のデータベース PSL のデフォルト値は次のとおりです。

* データベースログの最高レベル：想定 IOPS ≧ 22528 の場合、絶対最小 IOPS =4000
* データベース共有データの最大 IOPS ：想定 IOPS ≧ 16384 の場合、絶対最小 IOPS=2000
* データベースデータの最高レベル：想定 IOPS ≧ 12288 の場合、絶対最小 IOPS=2000


カスタム PSL の絶対最小 IOPS の値の大きい方には、最大 75000 を指定できます。下の値は、次のように計算されます。

1000/ 想定レイテンシ



 a| 
想定レイテンシ
 a| 
処理あたりのミリ秒（ ms/op ）で表したストレージ IOPS の想定レイテンシ。



 a| 
容量
 a| 
クラスタ内の使用可能容量と使用済み容量の合計。



 a| 
ワークロード
 a| 
PSL が割り当てられているストレージワークロードの数。

|===
ピーク IOPS と想定 IOPS が、 ONTAP クラスタで一貫した差別化されたパフォーマンスを実現するのにどのように役立つかについては、次の技術情報アーティクルを参照してください。

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/Active_IQ_Unified_Manager/What_is_Performance_Budgeting%3F["パフォーマンスの予算編成とは"]

ワークロードが過去 1 時間の想定レイテンシ値の 30% を超えた場合、 Unified Manager は次のいずれかのイベントを生成して、潜在的なパフォーマンス問題をユーザに通知します。 「パフォーマンスサービスレベルポリシーに定義されたワークロードのボリュームレイテンシしきい値を超過」または「パフォーマンスサービスレベルポリシーに定義されたワークロードの LUN レイテンシしきい値を超過」。ワークロードを分析して、レイテンシの値が高くなる原因を確認することができます。

次の表に、システム定義の PSL に関する情報を示します。

|===
| パフォーマンスサービスレベル | 概要とユースケース | 想定レイテンシ（ミリ秒 / 処理） | 最大 IOPS | 想定 IOPS | 絶対最小 IOPS 


 a| 
卓越したパフォーマンス
 a| 
非常に高いスループットを非常に低いレイテンシで実現します

レイテンシの影響を受けやすいアプリケーションに最適です
 a| 
1.
 a| 
12288
 a| 
6144
 a| 
1000



 a| 
パフォーマンス
 a| 
高いスループットを低いレイテンシで実現

データベースや仮想アプリケーションに最適です
 a| 
2.
 a| 
4096
 a| 
2048
 a| 
500



 a| 
価値
 a| 
高いストレージ容量を適度なレイテンシで実現します

E メール、 Web コンテンツ、ファイル共有、バックアップターゲットなどの大容量アプリケーションに最適です
 a| 
17
 a| 
512
 a| 
128
 a| 
75



 a| 
データベースログの「最高レベル」
 a| 
最小のレイテンシで最大スループットを実現

データベースログをサポートするデータベースアプリケーションに最適です。データベースログは非常にバースト性が高く、常にロギングが必要であるため、この PSL は最高のスループットを提供します。
 a| 
1.
 a| 
45056
 a| 
22528
 a| 
4 、 000



 a| 
データベース共有データ用の Extreme
 a| 
非常に高いスループットを最小のレイテンシで実現

共通のデータストアに格納されていて、データベース間で共有されているデータベースアプリケーションデータに最適です。
 a| 
1.
 a| 
32768
 a| 
16384
 a| 
2000 年



 a| 
データベースデータ用の Extreme
 a| 
高いスループットを最小のレイテンシで実現

データベーステーブル情報やメタデータなどのデータベースアプリケーションデータに最適です。
 a| 
1.
 a| 
24576
 a| 
12288
 a| 
2000 年

|===