---
permalink: storage-mgmt/concept_monitor_and_manage_clusters_from_dashboard.html 
sidebar: sidebar 
keywords: monitor, manage, clusters, dashboard 
summary: ダッシュボードには、監視対象の ONTAP システムの現在までの健全性に関する履歴情報がわかりやすく表示されます。ダッシュボードには、監視しているクラスタの全体的な容量、パフォーマンス、およびセキュリティの健全性を評価できる「パネル」があります。 
---
= ダッシュボードからクラスタを監視および管理する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ダッシュボードには、監視対象の ONTAP システムの現在までの健全性に関する履歴情報がわかりやすく表示されます。ダッシュボードには「パネル」が表示され、監視しているクラスタの全体的な容量、パフォーマンス、およびセキュリティの健全性を評価できます。

また、 ONTAP の一部の問題については、 ONTAP System Manager や ONTAP CLI を使用しなくても、 Unified Manager ユーザインターフェイスから直接修正することができます。

ダッシュボードの上部で、すべての監視対象クラスタの情報を表示するか、特定のクラスタの情報を表示するかを選択できます。最初にすべてのクラスタのステータスを表示してから、詳細情報を確認する場合は個々のクラスタにドリルダウンできます。

[NOTE]
====
以下のパネルの一部は、構成に応じてページに表示されない場合があります。

====
|===
| パネル | 説明 


 a| 
管理操作
 a| 
Unified Manager で問題の解決策を診断して特定できる場合、その解決策は「 * Fix it * 」ボタンでこのパネルに表示されます。



 a| 
容量
 a| 
ローカル階層とクラウド階層の合計容量と使用済み容量、およびローカル容量が上限に達するまでの日数が表示されます。



 a| 
パフォーマンス容量
 a| 
各クラスタのパフォーマンス容量とパフォーマンス容量が上限に達するまでの日数が表示されます。



 a| 
ワークロード IOPS
 a| 
特定の IOPS 範囲で現在実行されているワークロードの総数が表示されます。



 a| 
ワークロードのパフォーマンス
 a| 
定義された各パフォーマンスサービスレベルに割り当てられている準拠ワークロードと非準拠ワークロードの総数が表示されます。



 a| 
セキュリティ
 a| 
準拠または非準拠のクラスタ数、準拠または非準拠の SVM 数、暗号化されたボリュームまたはされていないボリュームの数が表示されます。



 a| 
保護
 a| 
SVM-DR関係で保護されているStorage VMの数、SnapMirror関係で保護されているボリューム、Snapshotで保護されているボリューム、およびMetroCluster で保護されているクラスタが表示されます。



 a| 
使用状況の概要
 a| 
IOPS 、スループット（ MBps ）、または使用済み物理容量が大きい順にクラスタが表示されます。

|===