---
permalink: storage-mgmt/concept_assign_policies_on_workloads.html 
sidebar: sidebar 
keywords: assign, policies, workloads, single, multiple, storage, system-recommended, psls 
summary: 各種のナビゲーションオプションを使用して、ストレージ効率化ポリシー（ SEP ）とパフォーマンスサービスレベル（ PSL ）をすべてのワークロードページからストレージワークロードに割り当てることができます。 
---
= ワークロードにポリシーを割り当てます
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
各種のナビゲーションオプションを使用して、ストレージ効率化ポリシー（ SEP ）とパフォーマンスサービスレベル（ PSL ）をすべてのワークロードページからストレージワークロードに割り当てることができます。



== 単一のワークロードにポリシーを割り当てる

1 つのワークロードに PSL または SEP 、またはその両方を割り当てることができます。次の手順を実行します。

. ワークロードを選択します。
. 行の横にある編集アイコンをクリックし、 * 編集 * をクリックします。
+
[ 割り当てられているパフォーマンスサービスレベル * ] フィールドと [ ストレージ効率化ポリシー * ] フィールドが有効になります。

. 必要な PSL または SEP 、またはその両方を選択します。
. チェックマークアイコンをクリックして変更を適用します。


[NOTE]
====
また、ワークロードを選択し、 * その他の操作 * をクリックしてポリシーを割り当てることもできます。

====


== 複数のストレージワークロードにポリシーを割り当てる

複数のストレージワークロードに PSL または SEP を一緒に割り当てることができます。次の手順を実行します。

. ポリシーを割り当てるワークロードのチェックボックスを選択するか、データセンター内のすべてのワークロードを選択します。
. [ * その他のアクション * ] をクリックします。
. PSL を割り当てるには、「 * パフォーマンスサービスレベルの割り当て」を選択してください。SEP を割り当てる場合は、 * ストレージ効率化ポリシーの割り当て * を選択します。ポリシーを選択するためのポップアップが表示されます。
. 適切なポリシーを選択し、 * 適用 * をクリックします。ポリシーが割り当てられているワークロードの数が表示されます。ポリシーが割り当てられていないワークロードも、原因とともに表示されます。
+
[NOTE]
====
選択したワークロードの数によっては、複数のワークロードにポリシーを適用する場合にしばらく時間がかかることがあります。[ * バックグラウンドで実行 * ] ボタンをクリックすると、バックグラウンドで処理を実行しながら他のタスクを続行できます。一括割り当てが完了したら、完了ステータスを確認できます。複数のワークロードに PSL を適用する場合、前のジョブの一括割り当ての実行中に別の要求をトリガーすることはできません。

====




== システム推奨の PSL をワークロードに割り当て中です

PSL が割り当てられていないデータセンター内のストレージワークロードに、システム推奨の PSL を割り当てることができます。または、割り当てられた PSL がシステム推奨の対象と一致しません。この機能を使用するには、 * Assign System Recommended PSL * ボタンをクリックします。特定のワークロードを選択する必要はありません。

推奨構成はシステム分析によって内部的に決定され、 IOPS などのパラメータが使用可能な PSL の定義と一致しないワークロードに対してはスキップされます。「 I/O 待ち」と「学習中」のストレージ・ワークロードも除外されます。

[NOTE]
====
Unified Manager がワークロード名で検索する特殊なキーワードを使用してシステム分析を上書きし、ワークロードに別の PSL を推奨します。ワークロードの名前に「 ora 」という文字が含まれている場合は、 **Extreme Performance ** PSL が推奨されます。ワークロードの名前に「 VM 」という文字が含まれている場合は、 **Performance** PSL を使用することをお勧めします。

====