---
permalink: storage-mgmt/concept_manage_storage_efficiency_policies.html 
sidebar: sidebar 
keywords: manage, storage, efficiency, policies, guidelines, create, custom 
summary: Storage Efficiency ポリシー（ SEP ）を使用して、ワークロードのストレージ効率化特性を定義することができます。ワークロードを最初に作成するとき、またはワークロードを編集して、ワークロードに SEP を割り当てることができます。 
---
= ストレージ効率化ポリシーの管理
:icons: font
:imagesdir: ../media/


[role="lead"]
Storage Efficiency ポリシー（ SEP ）を使用して、ワークロードのストレージ効率化特性を定義することができます。ワークロードを最初に作成するとき、またはワークロードを編集して、ワークロードに SEP を割り当てることができます。

Storage Efficiency では、ストレージ利用率を高めてストレージコストを削減するシンプロビジョニング、重複排除、データ圧縮などのテクノロジを使用します。スペース削減テクノロジを個別に、または組み合わせて使用することで、ストレージ効率を最大限に高めることができます。ポリシーをストレージワークロードに関連付けると、指定されたポリシー設定がストレージワークロードに割り当てられます。Unified Manager では、システム定義とユーザ定義の SEP を割り当てて、データセンターのストレージリソースを最適化することができます。

Unified Manager には、システム定義の 2 つの SEP が「高」と「低」の 2 つあります。これらの SEP はデータセンターのほとんどのストレージワークロードに当てはまりますが、システム定義の SEP が要件に合わない場合は独自のポリシーを作成できます。

システム定義の SEP 、またはワークロードに現在割り当てられている SEP は変更できません。ワークロードに割り当てられている SEP 、または使用可能な SEP のみを削除することはできません。

Storage Efficiency Policies ページには、使用可能な SEP が表示され、カスタマイズした SEP の追加、編集、および削除が可能です。このページには、次の情報が表示されます。

|===
| フィールド | 説明 


 a| 
名前
 a| 
SEP の名前。



 a| 
を入力します
 a| 
システム定義のポリシーかユーザ定義のポリシーか。



 a| 
スペースリザベーション
 a| 
ボリュームがシンプロビジョニングされているか、シックプロビジョニングされているか。



 a| 
重複排除
 a| 
ワークロードで重複排除が有効になっているかどうか。

* インライン：ワークロードへの書き込み中に重複排除が実行されます
* バックグラウンド：ワークロードで重複排除が実行されます
* Disable ：ワークロードで重複排除が無効になります




 a| 
圧縮
 a| 
ワークロードでデータ圧縮を有効にするかどうか。

* Inline ：ワークロードへの書き込み中にデータ圧縮が実行されます
* バックグラウンド：ワークロードでデータ圧縮が実行されます
* disable ：ワークロードでデータ圧縮が無効になります




 a| 
ワークロード
 a| 
SEP が割り当てられているストレージワークロードの数

|===


== カスタムのストレージ効率化ポリシーを作成する場合のガイドラインを次に示します

既存の SEP がストレージワークロードのポリシー要件を満たしていない場合は、カスタム SEP を作成できます。ただし、ストレージワークロードにはシステム定義の SEP を使用して、必要な場合はカスタムの SEP のみを作成することを推奨します。

ワークロードに割り当てられている SEP は、すべてのワークロードページおよびボリューム / 健全性の詳細ページで確認できます。ダッシュボードの容量パネルおよび容量：すべてのクラスタビューで、これらの Storage Efficiency 機能に基づいてクラスタレベルのデータ削減率を表示できます。
