---
permalink: storage-mgmt/concept_provision_and_manage_workloads.html 
sidebar: sidebar 
keywords: provision, manage, workloads 
summary: Active IQ Unified Manager のアクティブ管理機能を使用すると、パフォーマンスサービスレベル、ストレージ効率化ポリシー、およびデータセンターのストレージワークロードをプロビジョニング、監視、管理するためのストレージプロバイダ API を利用できます。 
---
= ワークロードのプロビジョニングと管理
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Manager のアクティブ管理機能を使用すると、パフォーマンスサービスレベル、ストレージ効率化ポリシー、およびデータセンターのストレージワークロードをプロビジョニング、監視、管理するためのストレージプロバイダ API を利用できます。

[NOTE]
====
この機能は Unified Manager にデフォルトで搭載されています。この機能を使用しない場合は、 * Storage Management * > * Feature Settings * で無効にできます。

====
有効にした場合、 Unified Manager のインスタンスで管理される ONTAP クラスタのワークロードをプロビジョニングできます。また、ワークロードにパフォーマンスサービスレベルやストレージ効率化ポリシーなどのポリシーを割り当て、それらのポリシーに基づいてストレージ環境を管理することもできます。

この機能を使用すると、次の機能を実行できます。

* 追加したクラスタでストレージワークロードを自動検出して、ストレージワークロードを簡単に評価して導入できるようにします
* NFS プロトコルと CIFS プロトコルをサポートする NAS ワークロードをプロビジョニングする
* iSCSI および FCP プロトコルをサポートする SAN ワークロードをプロビジョニングする
* 同じファイル共有で NFS プロトコルと CIFS プロトコルの両方がサポートされます
* パフォーマンスサービスレベルとストレージ効率化ポリシーを管理する
* ストレージワークロードにパフォーマンスサービスレベルとストレージ効率化ポリシーを割り当てています


UI の左側のペインで、 * Provisioning * 、 * Storage * > * Workloads * 、 * Policies * の各オプションを使用して、さまざまな設定を変更できます。

これらのオプションを使用して、次の機能を実行できます。

* ストレージワークロードを * Storage * > * Workloads * ページで表示できます
* プロビジョニングワークロードのページからストレージワークロードを作成します
* パフォーマンスサービスレベルの作成と管理はポリシーから行います
* ポリシーからストレージ効率化ポリシーを作成および管理します
* ワークロードページからストレージワークロードにポリシーを割り当てます


* 関連情報 *

link:../config/concept_policy_based_storage_management.html["ポリシーベースのストレージ管理"]
