---
permalink: storage-mgmt/concept_manage_performance_service_levels.html 
sidebar: sidebar 
keywords: manage, performance service level, PSL, User-defined, system-defined PSL, bursty, Database PSL, extreme PSL, beyond extreme PSL 
summary: パフォーマンスサービスレベルの計算と管理： 
---
= パフォーマンスサービスレベル
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
パフォーマンスサービスレベル（PSL）を使用すると、ワークロードに対してパフォーマンスとストレージの目標を定義できます。ワークロードの最初の作成時や編集時に、PSLをワークロードに割り当てることができます。

ストレージリソースは、サービスレベル目標（ SLO ）に基づいて管理および監視されます。SLO は、必要なパフォーマンスと容量に基づくサービスレベルアグリーメントによって定義されます。Unified Manager では、 SLO と言った場合、ネットアップストレージで実行されているアプリケーションの PSL の定義を表します。ストレージサービスの内容は、基盤となるリソースのパフォーマンスと利用率に基づいて決定されます。PSL はストレージサービス目標の概要です。ストレージプロバイダは、 PSL を使用してワークロードに目標とするパフォーマンスと容量を指定できます。ワークロードにPSLを割り当てると、ONTAP 上の対応するワークロードがパフォーマンスと容量の目標で管理されます。各PSLには、ピークIOPS、想定IOPS、絶対最小IOPS、および想定レイテンシが適用されます。

Unified Managerには、次のタイプのPSLがあります。

* *システム定義*：Unified Managerには、変更できない組み込みのポリシーがいくつか用意されています。事前定義されたPSLは次のとおりです
+
** 卓越したパフォーマンス
** パフォーマンス
** 価値
+
Extreme Performance 、 Performance 、および Value PSL は、データセンターの一般的なストレージワークロードのほとんどに該当します。

+
Unified Managerには、データベースアプリケーションのパフォーマンスサービスレベルも3つあります。これらは、バースト IOPS をサポートする非常にハイパフォーマンスな PSL であり、スループットの要求が最も高いデータベースアプリケーションに適しています。

** データベースログの「最高レベル」
** データベース共有データ用の Extreme
** データベースデータ用の Extreme


* *ユーザ定義*：事前定義されたパフォーマンスサービスレベルが要件に合わない場合は、PSLを新たに作成してニーズに対応できます。詳細については、を参照してください link:../storage-mgmt/task_create_and_edit_psls.html["パフォーマンス サービス レベルの作成と編集"]。
* * Extremeを超える場合*：PSLが最高レベルを超えると、PSLがシステム推奨となります。PSLを超えるワークロードには、Extremeよりも高いIOPSが必要です。ワークロードの内部分析はIOPS、容量、レイテンシに基づいて行われ、ストレージ>ワークロード>すべてのワークロード*画面で、これらのワークロードそれぞれについてPSLを超えることが推奨されます。PSLをワークロードに適用することで最適なパフォーマンスを確保できます。
+
ワークロードのIOPSパラメータは、ワークロードの動作に応じて動的に生成され、「Beyond Extreme」PSLの名前に「Beyond Extreme」という形式で追加されます。<number -（peak IOPS/TB）><number（expected IOPS/TB）>。たとえば、ピーク時のIOPSと予測されるIOPSがそれぞれ「106345」と「37929」であるとシステムが判断した場合、ワークロードに対して生成される「Beyond Extreme PSL」は「Exterond Extreme 106345 37929」と名付けられます。これらのPSLはシステムによって推奨されますが、これらのPSLをワークロードに割り当てると、PSLはタイプに「User-defined」とラベルされます。





== PSLを割り当ててワークロードを管理する

PSLには、「* Policies *>* Performance Service Levels *」ページからアクセスできます。また、ストレージプロバイダAPIを使用してアクセスできます。PSL を割り当ててストレージワークロードを管理すると、ストレージワークロードを個別に管理する必要がなくなるため便利です。変更については、個別に管理するのではなく、別の PSL を再割り当てして管理することもできます。Unified Managerでは、内部の評価と推奨事項に基づいてワークロードにPSLを割り当てることができます。

システム推奨のPSLをワークロードに割り当てる方法については、を参照してください。link:..//storage-mgmt/concept_assign_policies_on_workloads.html#assign-system-recommended-psls-to-workloads["システム推奨のPSLをワークロードに割り当てる"]

パフォーマンスサービスレベルページには、使用可能な PSL ポリシーが表示されます。このページで、ポリシーを追加、編集、削除することができます。


NOTE: システム定義の PSL またはワークロードに現在割り当てられている PSL は変更できません。ワークロードに割り当てられている PSL 、または他に使用可能な PSL がない PSL は削除できません。

このページには、次の情報が表示されます。

|===
| フィールド | 説明 


 a| 
名前
 a| 
PSLの名前。



 a| 
を入力します
 a| 
システム定義のポリシーかユーザ定義のポリシーか。



 a| 
想定 IOPS/TB
 a| 
LUN またはファイル共有でアプリケーションが実行すると想定される最小 IOPS 。想定 IOPS は、ストレージオブジェクトの割り当てサイズに基づいて、割り当てられる最小想定 IOPS を指定します。



 a| 
最大 IOPS/TB
 a| 
LUN またはファイル共有でアプリケーションが実行できる最大 IOPS 。ピーク IOPS は、ストレージオブジェクトの割り当てサイズまたは使用済みサイズに基づいて、割り当て可能な最大 IOPS を指定します。

ピーク IOPS は割り当てポリシーを基準にして算出されます。割り当てポリシーは、 allocated-space または used-space のいずれかです。割り当てポリシーが allocated-space の場合は、ストレージオブジェクトのサイズに基づいてピーク IOPS が計算されます。割り当てポリシーが used-space の場合は、 Storage Efficiency 機能の効果を考慮し、ストレージオブジェクトに格納されているデータの量に基づいてピーク IOPS が計算されます。デフォルトでは、割り当てポリシーは used-space に設定されています。



 a| 
絶対最小 IOPS
 a| 
絶対最小 IOPS は、想定 IOPS がこの値より低い場合に使用されます。システム定義の PSL のデフォルト値は次のとおりです。

* 最高レベルのパフォーマンス：想定 IOPS ≧ 6144/TB の場合、絶対最小 IOPS=1000
* パフォーマンス： 6144/TB > 想定 IOPS ≧ 2048/TB の場合、絶対最小 IOPS=500
* バリュー： 2048/TB > 想定 IOPS ≧ 128/TB の場合、絶対最小 IOPS=75


システム定義のデータベース PSL のデフォルト値は次のとおりです。

* データベースログの最高レベル：想定 IOPS ≧ 22528 の場合、絶対最小 IOPS =4000
* データベース共有データの最大 IOPS ：想定 IOPS ≧ 16384 の場合、絶対最小 IOPS=2000
* データベースデータの最高レベル：想定 IOPS ≧ 12288 の場合、絶対最小 IOPS=2000


カスタム PSL の絶対最小 IOPS の値の大きい方には、最大 75000 を指定できます。下の値は、次のように計算されます。

1000/ 想定レイテンシ



 a| 
想定レイテンシ
 a| 
処理あたりのミリ秒（ ms/op ）で表したストレージ IOPS の想定レイテンシ。



 a| 
容量
 a| 
クラスタ内の使用可能容量と使用済み容量の合計。



 a| 
ワークロード
 a| 
PSL が割り当てられているストレージワークロードの数。

|===
ピーク IOPS と想定 IOPS が、 ONTAP クラスタで一貫した差別化されたパフォーマンスを実現するのにどのように役立つかについては、次の技術情報アーティクルを参照してください。https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/Active_IQ_Unified_Manager/What_is_Performance_Budgeting%3F["パフォーマンスの予算編成とは"]



=== PSLによって定義されるしきい値を超えているワークロードに対して生成されるイベント

ワークロードが過去1時間の想定レイテンシの値を30%超えた場合、Unified Managerは次のいずれかのイベントを生成して、潜在的なパフォーマンス問題 をユーザに通知します。

* パフォーマンスサービスレベルポリシーに定義されたワークロードのボリュームレイテンシしきい値を超過
* パフォーマンスサービスレベルポリシーに定義されたワークロードのLUNレイテンシしきい値を超過。


ワークロードを分析して、レイテンシの値が高くなる原因を確認することができます。

詳細については、次のリンクを参照してください。

* link:../events/reference_volume_events.html#impact-area-performance["ボリュームイベント"]
* link:../performance-checker/concept_what_happens_when_performance_threshold_policy_is_breached.html["パフォーマンスしきい値ポリシーを超えた場合の動作"]
* link:..//performance-checker/concept_how_unified_manager_uses_workload_response_time.html["Unified Manager がワークロードのレイテンシを使用してパフォーマンスの問題を特定する仕組み"]
* link:../performance-checker/concept_what_performance_events_are.html["パフォーマンスイベントとは"]




=== システム定義のPSL

次の表に、システム定義の PSL に関する情報を示します。

|===
| パフォーマンスサービスレベル | 概要とユースケース | 想定レイテンシ（ミリ秒 / 処理） | 最大 IOPS | 想定 IOPS | 絶対最小 IOPS 


 a| 
卓越したパフォーマンス
 a| 
非常に高いスループットを非常に低いレイテンシで実現します

レイテンシの影響を受けやすいアプリケーションに最適です
 a| 
1.
 a| 
12288
 a| 
6144
 a| 
1000



 a| 
パフォーマンス
 a| 
高いスループットを低いレイテンシで実現

データベースや仮想アプリケーションに最適です
 a| 
2.
 a| 
4096
 a| 
2048
 a| 
500



 a| 
価値
 a| 
高いストレージ容量を適度なレイテンシで実現します

E メール、 Web コンテンツ、ファイル共有、バックアップターゲットなどの大容量アプリケーションに最適です
 a| 
17
 a| 
512
 a| 
128
 a| 
75



 a| 
データベースログの「最高レベル」
 a| 
最小のレイテンシで最大スループットを実現

データベースログをサポートするデータベースアプリケーションに最適です。データベースログは非常にバースト性が高く、常にロギングが必要であるため、この PSL は最高のスループットを提供します。
 a| 
1.
 a| 
45056
 a| 
22528
 a| 
4 、 000



 a| 
データベース共有データ用の Extreme
 a| 
非常に高いスループットを最小のレイテンシで実現

共通のデータストアに格納されていて、データベース間で共有されているデータベースアプリケーションデータに最適です。
 a| 
1.
 a| 
32768
 a| 
16384
 a| 
2000 年



 a| 
データベースデータ用の Extreme
 a| 
高いスループットを最小のレイテンシで実現

データベーステーブル情報やメタデータなどのデータベースアプリケーションデータに最適です。
 a| 
1.
 a| 
24576
 a| 
12288
 a| 
2000 年

|===