---
permalink: storage-mgmt/concept_workloads_dashboard.html 
sidebar: sidebar 
keywords: workloads, overview, data center, sections 
summary: ワークロードとは、ボリュームや LUN などのストレージオブジェクトの入出力（ I/O ）処理のことです。ストレージのプロビジョニング方法は、想定されるワークロード要件に基づいています。Active IQ Unified Manager は、ストレージオブジェクトとの間にトラフィックが発生した時点でワークロードの統計情報の追跡を開始します。たとえば、ユーザがデータベースまたは E メールアプリケーションの使用を開始した時点で、ワークロードの IOPS とレイテンシを取得できるようになります。 
---
= ワークロードの概要
:icons: font
:imagesdir: ../media/


[role="lead"]
ワークロードとは、ボリュームや LUN などのストレージオブジェクトの入出力（ I/O ）処理のことです。ストレージのプロビジョニング方法は、想定されるワークロード要件に基づいています。Active IQ Unified Manager は、ストレージオブジェクトとの間にトラフィックが発生した時点でワークロードの統計情報の追跡を開始します。たとえば、ユーザがデータベースまたは E メールアプリケーションの使用を開始した時点で、ワークロードの IOPS とレイテンシを取得できるようになります。

ワークロードページには、 Unified Manager で管理されている ONTAP クラスタのストレージワークロードの概要が表示されます。このページには、パフォーマンスサービスレベルに準拠したストレージワークロードと準拠していないストレージワークロードに関する履歴情報が一目でわかるように表示されます。また、データセンター内のクラスタの合計容量、使用可能容量、使用済み容量、およびパフォーマンス（ IOPS ）を評価することもできます。

[NOTE]
====
非準拠、利用不可、またはいずれのパフォーマンスサービスレベルでも管理されていないストレージワークロードの数を評価し、それらが準拠条件を満たし、使用容量、 IOPS が確保されるために必要な措置を講じることを推奨します。

====
ワークロードページには次の 2 つのセクションがあります。

* ワークロードの概要： Unified Manager で管理されている ONTAP クラスタ上のストレージワークロード数を表示します。
* データセンターの概要：データセンター内のストレージワークロードの容量と IOPS を表示します。関連するデータは、データセンターレベルおよび個別に表示されます。




== ワークロードの概要セクション

ワークロードの概要セクションには、ストレージワークロードについての累積情報がわかりやすく表示されます。ストレージワークロードのステータスは、割り当てられているパフォーマンスサービスレベルと割り当てられていないパフォーマンスサービスレベルに基づいて表示されます。

* * Assigned * ：パフォーマンスサービスレベルが割り当てられているストレージワークロードについては、次のステータスが報告されます。
+
** * 準拠 * ：ストレージワークロードのパフォーマンスは、割り当てられているパフォーマンスサービスレベルに基づきます。ストレージワークロードが、関連付けられているパフォーマンスサービスレベルで定義されたしきい値レイテンシの範囲内にある場合、「準拠」とマークされます。準拠しているワークロードは青で表示されます。
** * 非準拠 * ：ストレージワークロードのレイテンシが、関連付けられたパフォーマンスサービスレベルで定義されたしきい値遅延を超えた場合、パフォーマンス監視中にストレージワークロードは「不適合」とマークされます。非準拠のワークロードはオレンジで表示されます。
** * 利用不可 *: ストレージワークロードがオフラインの場合、または対応するクラスタに到達できない場合、ストレージワークロードは「利用不可」とマークされます。利用できないワークロードは赤で表示されます。


* * 未割り当て * ：パフォーマンスサービスレベルが割り当てられていないストレージワークロードは「未割り当て」と報告されます。情報アイコンにその数が表示されます。


合計ワークロード数は、割り当て済みのワークロードと割り当てなしのワークロードの合計です。

このセクションに表示されるワークロードの総数をクリックすると、ワークロードのページに表示できます。

「 Conformance by Performance Service Levels 」サブセクションには、使用可能なストレージワークロードの総数が表示されます。

* 各タイプのパフォーマンスサービスレベルに準拠しています
* 割り当てられているパフォーマンスサービスレベルと推奨されるパフォーマンスサービスレベルが一致していません




== データセンターの概要セクション

データセンターの概要セクションに、データセンター内のすべてのクラスタの使用可能容量と使用済み容量、および IOPS が図で表示されます。このデータを使用して、ストレージワークロードの容量と IOPS を管理します。このセクションには、すべてのクラスタのストレージワークロードに関する次の情報も表示されます。

* データセンター内のすべてのクラスタの合計容量、使用可能容量、使用済み容量
* データセンター内のすべてのクラスタの合計 IOPS 、使用可能 IOPS 、使用済み IOPS
* 各パフォーマンスサービスレベルに基づく使用可能容量と使用済み容量
* 各パフォーマンスサービスレベルに基づく使用可能 IOPS と使用済み IOPS
* パフォーマンスサービスレベルが割り当てられていないワークロードで使用されている合計スペースと IOPS


* パフォーマンスサービスレベル * に基づいて、データセンターの容量とパフォーマンスを計算する方法

使用済み容量と使用済み IOPS は、クラスタ内のすべてのストレージワークロードの合計使用済み容量とパフォーマンスに関して取得されます。

使用可能 IOPS は、ノードの想定レイテンシと推奨されるパフォーマンスサービスレベルに基づいて計算されます。これには、想定レイテンシがノード独自の想定レイテンシ以下であるすべてのパフォーマンスサービスレベルの使用可能 IOPS が含まれます。

使用可能容量は、アグリゲートの想定レイテンシと推奨されるパフォーマンスサービスレベルに基づいて計算されます。これには、想定レイテンシがアグリゲート独自の想定レイテンシ以下であるすべてのパフォーマンスサービスレベルの使用可能容量が含まれます。
