---
permalink: storage-mgmt/concept_all_workloads.html 
sidebar: sidebar 
keywords: view, workloads, add, provision, storage, filter, analyze, performance, capacity, criteria 
summary: すべてのワークロードビューには、データセンター内のクラスタで使用可能なすべてのワークロードのリストが表示されます。 
---
= ワークロードの表示
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
すべてのワークロードビューには、データセンター内のクラスタで使用可能なすべてのワークロードのリストが表示されます。

すべてのワークロードビューには、 Unified Manager で管理されている ONTAP クラスタに関連付けられているストレージワークロードが表示されます。また、ストレージワークロードにストレージ効率化ポリシー（ SEP ）とパフォーマンスサービスレベル（ PSL ）を割り当てることもできます。

Unified Manager にクラスタを追加すると、 FlexGroup ボリュームとそのコンスティチュエントを除く各クラスタのストレージワークロードが自動的に検出されてこのページに表示されます。

Unified Manager は、ストレージワークロードで I/O 処理が開始された時点で、推奨される（推奨される PSL ）に対するワークロードの分析を開始します。新たに検出されたストレージワークロードで I/O 処理が行われていない場合、ステータスは「 I/O を待機中」になります。ストレージワークロードで I/O 処理が開始されると、 Unified Manager が分析を開始し、ワークロードのステータスが「学習中 ... 」に変わります。分析が完了すると（ I/O 処理の開始から 24 時間以内）、ストレージワークロードに推奨される PSL が表示されます。

[* Workloads * > * all workloads * （ * すべてのワークロード * ） ] オプションを使用すると、複数のタスクを実行できます。

* ストレージワークロードを追加またはプロビジョニングする
* ワークロードのリストを表示してフィルタリングします
* PSL をストレージワークロードに割り当てます
* システム推奨の PSL を評価してワークロードに割り当てます
* ストレージワークロードに SEP を割り当てます




== ストレージワークロードを追加またはプロビジョニングする

サポートされる LUN （ iSCSI と FCP の両プロトコルをサポート）、 NFS ファイル共有、 SMB 共有にストレージワークロードを追加またはプロビジョニングできます。



== ワークロードの表示とフィルタリング

All workloads （すべてのワークロード）画面では、データセンター内のすべてのワークロードを表示したり、 PSL または名前に基づいて特定のストレージワークロードを検索したりできます。フィルタアイコンを使用して、検索条件を入力できます。ホストクラスタや Storage VM など、さまざまなフィルタ条件で検索できます。容量の合計 * オプションを使用すると、ワークロードの合計容量（ MB ）でフィルタリングできます。ただしこの場合は、合計容量がバイトレベルで比較されるため、返されるワークロードの数が変わる可能性があります。

各ワークロードについて、ホストクラスタと Storage VM などの情報、および割り当てられている PSL と SEP が表示されます。

また、このページではワークロードのパフォーマンスの詳細を確認することもできます。ワークロードの IOPS 、容量、レイテンシに関する詳細情報を表示するには、「 * 列の選択 / 順序」ボタンをクリックし、表示する列を選択します。パフォーマンスビューの列にはワークロードの平均 IOPS とピーク IOPS が表示され、ワークロードアナライザのアイコンをクリックすると詳細な IOPS 分析を確認できます。IOPS 分析ポップアップの * ワークロードの分析ボタンをクリックすると、ワークロード分析ページが開き、期間を選択して、選択したワークロードのレイテンシ、スループット、容量のトレンドを確認できます。Workload Analyzer の詳細については、 Workload Analyzer を使用したワークロードのトラブルシューティング _ を参照してください



== ワークロードのパフォーマンスと容量の条件を分析します

パフォーマンスビュー * 列の棒グラフアイコンをクリックすると、ワークロードに関するパフォーマンス情報を表示してトラブルシューティングに役立てることができます。ワークロードの分析ページにパフォーマンスと容量のグラフを表示してオブジェクトを分析するには、 * ワークロードの分析 * ボタンをクリックします。
