---
permalink: storage-mgmt/reference_what_ontap_issues_can_unified_manager_fix.html 
sidebar: sidebar 
keywords: ontap issues, fix it action, automatic remediation feature, remediation events, fix-it messages, fix-it events 
summary: この表では、 Unified Manager のユーザインターフェイスで Fix it ボタンまたは Fix All ボタンをクリックして直接解決できる ONTAP の問題について説明します。 
---
= Unified Manager で解決可能な問題
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Manager の自動修復機能を使用すると、 ONTAP の特定の問題を解決したり、ランサムウェア対策の監視などの ONTAP の一部の機能を Unified Manager で効果的に管理したりできます。

この表では、 Unified Manager Web UI の * Fix it * または * Fix All * ボタンを使用して直接管理できる ONTAP の問題と機能について説明します。

|===
| イベント名と概要 | 管理操作 | 「修正」処理 


 a| 
ボリュームスペースがフルです

ボリュームにスペースがほとんど残っておらず、容量の「フル」しきい値を超えています。このしきい値は、デフォルトではボリュームサイズの 90% に設定されています。
 a| 
ボリュームの自動拡張を有効にする
 a| 
Unified Manager はこのボリュームにボリュームの自動拡張が設定されていないことを特定し、必要に応じてボリュームの容量が拡張されるようにこの機能を有効にします。



 a| 
inode がフルです

このボリュームの inode が不足しており、新しいファイルを受け入れることはできません。
 a| 
ボリュームの inode の数を増やします
 a| 
ボリュームの inode の数を 2% 増やします。



 a| 
ストレージ階層ポリシーの不一致が検出されました

ボリュームにアクセス頻度の低いデータが大量にあり、現在の階層化ポリシーが「 snapshot-only 」または「 none 」に設定されている。
 a| 
クラウドの自動階層化を有効化
 a| 
ボリュームはすでに FabricPool に存在するため、階層化ポリシーが「 auto 」に変更され、アクセス頻度の低いデータが低コストのクラウド階層に移動されます。



 a| 
ストレージ階層の不一致が検出されました

アクセス頻度の低いデータがボリュームに大量にありますが、クラウド対応のストレージ階層（ FabricPool ）に配置されていません。
 a| 
ボリュームのストレージ階層を変更します
 a| 
アクセス頻度の低いデータをクラウド階層に移動するには、ボリュームをクラウド対応ストレージ階層に移動し、階層化ポリシーを「自動」に設定します。



 a| 
監査ログが無効です

Storage VM の監査ログが有効になっていません
 a| 
Storage VM の監査ログを有効にしてください
 a| 
Storage VM の監査ログを有効にします。

Storage VM にローカルまたはリモートの監査ログの場所が設定されている必要があります。



 a| 
ログインバナーが無効です

アクセス制限をクリアしてセキュリティを強化するには、クラスタのログインバナーを有効にする必要があります。
 a| 
クラスタのログインバナーを設定します
 a| 
クラスタ・ログイン・バナーを「許可されたユーザーにアクセス制限」に設定します。



 a| 
ログインバナーが無効です

アクセス制限を明確にしてセキュリティを強化するには、 Storage VM のログインバナーを有効にする必要があります。
 a| 
Storage VM のログインバナーを設定します
 a| 
Storage VM のログインバナーを「許可されたユーザだけにアクセス」に設定します。



 a| 
SSH でセキュアでない暗号が使用されています

サフィックスが「 -cbc" の暗号は安全でないとみなされます。
 a| 
セキュアでない暗号をクラスタから削除してください
 a| 
安全でない暗号（ aes192-cbc や aes128-cbc など）をクラスタから削除します。



 a| 
SSH でセキュアでない暗号が使用されています

サフィックスが「 -cbc" の暗号は安全でないとみなされます。
 a| 
セキュアでない暗号を Storage VM から削除してください
 a| 
安全でない暗号（ aes192-cbc や aes128-cbc など）をストレージ VM から削除します。



 a| 
AutoSupport HTTPS 転送が無効です

AutoSupport メッセージのテクニカルサポートへの送信に使用される転送プロトコルを暗号化する必要があります。
 a| 
AutoSupport メッセージの転送プロトコルとして HTTPS を設定します
 a| 
クラスタ上の AutoSupport メッセージの転送プロトコルとして HTTPS を設定します。



 a| 
クラスタ負荷の不均衡しきい値を超過

クラスタ内のノード間で負荷が不均衡になっています。このイベントは、ノード間の使用済みパフォーマンス容量の差が 30% を超えた場合に生成されます。
 a| 
クラスタワークロードを分散します
 a| 
Unified Manager は別のノードに移動することで不均衡が最も解消されるボリュームを特定し、そのボリュームを移動します。



 a| 
クラスタ容量の不均衡しきい値を超過

クラスタ内のアグリゲート間で容量が不均衡になっています。このイベントは、アグリゲート間の使用済み容量の差が 70% を超えた場合に生成されます。
 a| 
クラスタ容量を分散します
 a| 
Unified Manager は別のアグリゲートに移動することで不均衡が最も解消されるボリュームを特定し、そのボリュームを移動します。



 a| 
使用済みパフォーマンス容量のしきい値を超過

1 つ以上のアクティブなワークロードによる利用率を下げないと、ノードの負荷が過剰になる可能性があります。このイベントは、ノードの使用済みパフォーマンス容量の値が 12 時間以上 100% を超えた場合に生成されます。
 a| 
ノードの高負荷を制限します
 a| 
Unified Manager は IOPS が高いボリュームを特定し、想定およびピークの過去の IOPS レベルを使用して QoS ポリシーを適用して、ノードの負荷を軽減します。



 a| 
動的イベントの警告しきい値を超過

一部のワークロードの負荷が異常に高いためにノードがすでに過負荷状態です。
 a| 
ノードの過負荷を軽減します
 a| 
Unified Manager は IOPS が高いボリュームを特定し、想定およびピークの過去の IOPS レベルを使用して QoS ポリシーを適用して、ノードの負荷を軽減します。



 a| 
テイクオーバーを実行できません

フェイルオーバーが無効になっているため、停止中またはリブート中のノードが使用可能な状態に戻るまではノードのリソースへのアクセスが失われます。
 a| 
ノードフェイルオーバーを有効にします
 a| 
Unified Manager が該当するコマンドを送信し、クラスタ内のすべてのノードのフェイルオーバーを有効にします。



 a| 
オプション cf.takeover.on_panic の設定が OFF になっています

ノードシェルオプション「 cf.takeover.on_panic 」が * off * に設定されており、 HA 構成のシステムで問題を原因できます。
 a| 
パニック時のテイクオーバーを有効にする
 a| 
Unified Manager が該当するコマンドを送信し、この設定を * on * に変更します。



 a| 
ノードシェルオプション snapmirror.enable を無効化

古いノードシェルオプション「 snapmirror.enable 」は * on * に設定されており、 ONTAP 9.3 以降へのアップグレード後のブート時に問題を原因することができます。
 a| 
snapmirror.enable オプションを off に設定します
 a| 
Unified Manager が該当するコマンドを送信し、この設定を * off * に変更します。



 a| 
Telnet が有効です

Telnet は安全性が高くなく、暗号化されていない方法でデータが渡されるため、潜在的なセキュリティ問題を示します。
 a| 
Telnet を無効にします
 a| 
Unified Manager が適切なコマンドをクラスタに送信し、 Telnet を無効にします。



 a| 
Storage VM にランサムウェア対策学習を設定する

ライセンスのあるクラスタでランサムウェア対策の監視を定期的にチェックします。Storage VM がこのようなクラスタ内の NFS ボリュームまたは SMB ボリュームのみをサポートするかどうかを検証します。
 a| 
Storage VM を「学習」モードのランサムウェア対策モニタリングにします
 a| 
Unified Manager は、クラスタ管理コンソールを通じて、 Storage VM のアンチランサムウェアモニタリングを「ラーニング」状態に設定します。Storage VM に作成されたすべての新しいボリュームでランサムウェア対策モニタリングが自動的に学習モードに移行されます。ONTAP は、この有効化を通じてボリュームのアクティビティのパターンを学習し、潜在的な悪意のある攻撃による異常を検出します。



 a| 
ボリュームのランサムウェア対策学習を設定する

ライセンスのあるクラスタでランサムウェア対策の監視を定期的にチェックします。ボリュームがこのようなクラスタで NFS サービスまたは SMB サービスのみをサポートするかどうかを検証します。
 a| 
ボリュームをアンチランサムウェア監視の「学習」モードにします
 a| 
Unified Manager は、クラスタ管理コンソールを通じて、ボリュームのアンチランサムウェア監視を「 learning] 状態に設定します。ONTAP は、この有効化を通じてボリュームのアクティビティのパターンを学習し、潜在的な悪意のある攻撃による異常を検出します。



 a| 
ボリュームのアンチランサムウェアを有効化

ライセンスのあるクラスタでランサムウェア対策の監視を定期的にチェックします。ボリュームがアンチランサムウェアモニタリングの「学習」モードになっているかどうかを 45 日以上検出し、アクティブモードにする見込み客を決定します。
 a| 
ボリュームをアンチランサムウェア監視の「アクティブ」モードにします
 a| 
Unified Manager は、クラスタ管理コンソールを通じて、ボリューム上でアンチランサムウェア監視を「アクティブ」に設定します。ONTAP は、この有効化を通じて、ボリュームのアクティビティのパターンを学習し、潜在的な悪意のある攻撃による異常を検出して、データ保護アクションに対するアラートを作成できます。



 a| 
ボリュームのアンチランサムウェアを無効にする

ライセンスのあるクラスタでランサムウェア対策の監視を定期的にチェックします。ボリュームに対するアクティブなアンチランサムウェアの監視中に繰り返し発生する通知を検出します（たとえば、ランサムウェアによる攻撃が発生する可能性があるという複数の警告が 30 日以上返されます）。
 a| 
ボリュームでランサムウェア対策の監視を無効にする
 a| 
Unified Manager では、クラスタ管理コンソールを使用したボリュームでのランサムウェア対策監視が無効になります。

|===