---
permalink: storage-mgmt/reference_dashboard_page.html 
sidebar: sidebar 
keywords: dashboard page, 
summary: Dashboard ページには、監視しているクラスタの容量、パフォーマンス、およびセキュリティの健全性の概要を示すパネルがあります。このページの管理操作パネルには、 Unified Manager が特定のイベントを解決するために実行できる修正が表示されます。 
---
= ダッシュボードページ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ダッシュボードページには、監視しているクラスタの容量、パフォーマンス、セキュリティの健全性の概要がパネルに表示されます。このページの管理操作パネルには、 Unified Manager が特定のイベントを解決するために実行できる修正が表示されます。

ほとんどのパネルには、そのカテゴリのアクティブイベントの数および過去 24 時間に追加された新しいイベントの数も表示されます。この情報から、イベントを解決するために詳細な分析が必要なクラスタを決定できます。イベントをクリックすると、上位のイベントが表示され、そのカテゴリのアクティブなイベントをフィルタリングして表示する Event Management インベントリページへのリンクが表示されます。

ダッシュボードの上部で、すべての監視対象クラスタ（「すべてのクラスタ」）の情報を表示するか、特定のクラスタの情報を表示するかを選択できます。最初にすべてのクラスタのステータスを表示してから、詳細情報を確認する場合は個々のクラスタにドリルダウンできます。

[NOTE]
====
構成に応じて、次のパネルの一部がダッシュボードに表示されます。

====


== [管理操作]パネル

問題によっては、 Unified Manager の詳細な診断によって 1 つの解決策が提供されることがあります。解決策がある場合は、このパネルに * Fix it * または * Fix All * ボタンで表示されます。このような問題は Unified Manager から直接解決できます。 ONTAP System Manager や ONTAP CLI を使用する必要はありません。すべての問題を表示するには、「参照」をクリックします link:concept_fix_ontap_issues_directly_from_unified_manager.html["ONTAP の問題を Unified Manager から直接修正"] を参照してください。



== 容量パネル

すべてのクラスタを表示している場合、このパネルには、各クラスタの使用済み物理容量（Storage Efficiencyによる削減効果の適用後）と使用可能な物理容量（Storage Efficiencyによる削減効果を除く）、ディスクがフルになるまでの予測日数が表示されます。 および、ONTAP のStorage Efficiency設定に基づいたデータ削減率（Snapshotコピーなし）。また、設定されているクラウド階層の使用済み容量も表示されます。棒グラフをクリックすると、そのクラスタのアグリゲートのインベントリページが表示されます。「フルまでの日数」というテキストをクリックすると容量の残り日数が最も少ないアグリゲートを示すメッセージが表示され、そのアグリゲート名をクリックすると詳細が表示されます。

単一のクラスタを表示している場合、このパネルには、データアグリゲートの物理使用容量と使用可能な物理容量がローカル階層とクラウド階層のそれぞれのディスクタイプでソートされて表示されます。ディスクタイプの棒グラフをクリックすると、そのディスクタイプを使用しているボリュームのボリュームインベントリページが表示されます。



== Performance Capacity（パフォーマンス容量）パネル

すべてのクラスタを表示している場合、このパネルには、各クラスタのパフォーマンス容量（過去 1 時間の平均）とパフォーマンス容量が上限に達するまでの日数（日次増加率に基づく）が表示されます。棒グラフをクリックすると、そのクラスタのノードインベントリページが表示されます。ノードインベントリページには、過去 72 時間のパフォーマンス容量の平均が表示されます。フルまでの日数というテキストをクリックするとパフォーマンス容量の残り日数が最も少ないノードを示すメッセージが表示され、そのノード名をクリックすると詳細が表示されます。

単一のクラスタを表示している場合、このパネルには、そのクラスタの使用済みパフォーマンス容量の割合、合計 IOPS 、合計スループット（ MBps ）、およびこれらの 3 つの指標が上限に達するまでの想定日数が表示されます。



== ワークロードのIOPSパネル

単一のクラスタを表示している場合、このパネルには、特定の範囲の IOPS で現在実行されているワークロードの総数、およびグラフにカーソルを合わせると各ディスクタイプの数が表示されます。



== ワークロードのパフォーマンスパネル

このパネルには、各パフォーマンスサービスレベル（ PSL ）ポリシーに割り当てられている準拠ワークロードと非準拠ワークロードの総数が表示されます。また、 PSL が割り当てられていないアグリゲートの数も表示されます。棒グラフをクリックすると、そのポリシーに割り当てられている準拠ワークロードがワークロードページに表示されます。棒グラフの横に表示された数字をクリックすると、そのポリシーに割り当てられている準拠ワークロードと非準拠ワークロードが表示されます。



== セキュリティパネル

Securityパネルには、現在のビューに応じて、すべてのクラスタまたは単一のクラスタのセキュリティステータスの概要が表示されます。このパネルには次の情報が表示

* 過去24時間に受信したセキュリティイベントのリスト。イベントをクリックすると、そのイベントの詳細がイベントの詳細ページに表示されます
* クラスタのセキュリティステータス（準拠クラスタと非準拠クラスタの数）
* Storage VMのセキュリティステータス（準拠Storage VMと非準拠Storage VMの数）
* ボリューム暗号化ステータス（暗号化されているボリュームまたは暗号化されていないボリュームの数）
* ボリュームのランサムウェア対策のステータス（ランサムウェア対策が有効または無効になっているボリュームの数）


準拠クラスタと非準拠クラスタ、Storage VM、暗号化ボリュームと非暗号化ボリューム、およびボリュームのランサムウェア対策ステータスの棒グラフをクリックすると、該当するページに移動し、フィルタリングされたクラスタ、Storage VM、およびボリュームのセキュリティの詳細を表示できます。

準拠はに基づいてい https://www.netapp.com/pdf.html?item=/media/10674-tr4569pdf.pdf["『 ONTAP 9 セキュリティ設定ガイド』"^]ます。パネル上部の右矢印をクリックすると、[セキュリティ]ページにすべてのクラスタのセキュリティの詳細が表示されます。詳細については、を参照してください link:../health-checker/task_view_detailed_security_status_for_clusters_and_svms.html["クラスタと Storage VM の詳細なセキュリティステータスの表示"]。



== データ保護パネル

このパネルには、データセンター内の 1 つまたはすべてのクラスタのデータ保護の概要が表示されます。ONTAP の過去24時間に生成されたデータ保護イベント、MetroCluster イベント、およびアクティブイベントの総数が表示されます。これらの各イベントのリンクをクリックすると、 [ イベントの詳細 ] ページが表示されます。[ すべて表示 *] リンクをクリックすると、 [ イベント管理 ] インベントリページですべてのアクティブな保護イベントを表示できます。パネルに次の情報が表示され

* クラスタ内のボリューム、またはSnapshotコピーで保護されているデータセンター内のすべてのクラスタのボリューム数。
* クラスタ内のボリューム、またはSnapMirror関係で保護されているデータセンター内のすべてのクラスタのボリューム数。SnapMirror関係では、ソースクラスタのボリューム数が考慮されます。
* IPまたはFC経由でMetroCluster 構成で保護されているデータセンター内のクラスタまたはすべてのクラスタの数。
* 遅延ステータスに基づいて、SnapMirrorのRecovery Point Objective（RPO；目標復旧時点）遅延が設定されたボリューム関係の数。


マウスのカーソルを合わせると、それぞれのカウントと凡例を表示できます。パネル上部の右矢印をクリックすると、データ保護ページで1つまたはすべてのクラスタの詳細を確認できます。また、以下をクリックすることもできます。

* 保護されていないボリュームとSnapshotコピーで保護されているボリュームの棒グラフ。ボリュームのページに移動して詳細を確認できます。
* 保護されているクラスタ、またはMetroCluster 構成で保護されていないクラスタの棒グラフ。クラスタページに移動して詳細を確認できます。
* すべての関係の棒グラフが関係ページに表示され、詳細はソースクラスタに基づいてフィルタされます。


詳細については、を参照してください link:../data-protection/view-protection-status.html["ボリュームの保護ステータスを表示しています"]。



== 使用状況の概要パネル

すべてのクラスタを表示している場合、 IOPS 、スループット（ MBps ）、または使用済み物理容量が大きい順にクラスタを表示できます。

単一のクラスタを表示している場合は、 IOPS 、スループット（ MBps ）、または使用済み論理容量が大きい順にワークロードを表示できます。

* 関連情報 *

link:../events/task_fix_issues_using_um_automatic_remediations.html["Unified Manager の自動修正措置を使用した問題の修正"]

link:../performance-checker/task_display_information_about_performance_event.html["パフォーマンスイベントに関する情報を表示する"]

link:../performance-checker/concept_manage_performance_using_perf_capacity_available_iops.html["パフォーマンス容量と使用可能な IOPS の情報を使用してパフォーマンスを管理する"]

link:../health-checker/reference_health_volume_details_page.html["ボリューム / 健全性の詳細ページ"]

link:../performance-checker/reference_performance_event_analysis_and_notification.html["パフォーマンスイベントの分析と通知"]

link:../events/reference_description_of_event_severity_types.html["概要のイベントの重大度タイプ"]

link:../performance-checker/concept_sources_of_performance_events.html["パフォーマンスイベントのソース"]

link:../health-checker/concept_manage_cluster_security_objectives.html["クラスタのセキュリティ目標の管理"]

link:../performance-checker/concept_monitor_cluster_performance_from_cluster_landing_page.html["パフォーマンスクラスタランディングページからのクラスタパフォーマンスの監視"]

link:../performance-checker/concept_monitor_performance_using_object_performance.html["パフォーマンスインベントリページを使用したパフォーマンスの監視"]
