---
permalink: storage-mgmt/task_monitor_metrocluster_replication.html 
sidebar: sidebar 
keywords: monitor, metrocluster, replication 
summary: データのミラーリング中に論理接続の全体的な健常性を監視して診断することができます。アグリゲート、ノード、 Storage Virtual Machine などのクラスタコンポーネントのミラーリングを中断する問題やリスクを特定することができます。 
---
= MetroCluster レプリケーションを監視しています
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
データのミラーリング中に論理接続の全体的な健常性を監視して診断することができます。アグリゲート、ノード、 Storage Virtual Machine などのクラスタコンポーネントのミラーリングを中断する問題やリスクを特定することができます。

* 必要なもの *

MetroCluster 構成のローカルクラスタとリモートクラスタの両方を、 Unified Manager に追加する必要があります

レプリケーションの問題を修正するには、クラスタ / 健常性の詳細ページに表示される情報を使用します。

アイコンにカーソルを合わせると、生成されたイベントに関する詳細情報が表示されます。

Unified Manager では、システムヘルスアラートを使用して、 MetroCluster 構成のコンポーネントおよび接続のステータスを監視します。

.手順
. 左側のナビゲーションペインで、 * Storage * > * Clusters * をクリックします。
+
監視対象のクラスタのリストが表示されます。

. [* Health: All Clusters] ビューで、 MetroCluster レプリケーションの詳細を表示するクラスタの名前をクリックし、 [* MetroCluster Replication*] タブをクリックします。
+
対応するクラスタオブジェクト領域のローカルサイトに、レプリケートされる MetroCluster 設定のトポロジが、データのミラー先であるリモートサイトの情報とともに表示されます。



MetroCluster 構成でミラーリングの問題が見つかった場合は、 System Manager にログインするか ONTAP CLI にアクセスして問題を解決する必要があります。

* 関連情報 *

link:../health-checker/reference_health_cluster_details_page.html["クラスタ / 健全性の詳細ページ"]
