---
permalink: storage-mgmt/task_create_and_edit_psls.html 
sidebar: sidebar 
keywords: create, edit, performance, service, Levels 
summary: システム定義のパフォーマンスサービスレベルがワークロードの要件に合わない場合は、ワークロードに最適化された独自のパフォーマンスサービスレベルを作成できます。 
---
= パフォーマンスサービスレベルの作成と編集
:icons: font
:imagesdir: ../media/


[role="lead"]
システム定義のパフォーマンスサービスレベルがワークロードの要件に合わない場合は、ワークロードに最適化された独自のパフォーマンスサービスレベルを作成できます。

* 必要なもの *

* アプリケーション管理者のロールが必要です。
* パフォーマンスサービスレベル名は一意である必要があります。また、次のリザーブキーワードは使用できません。
+
'prime'`Extreme''Performance 'Value '`Unassigned ', 「 Learning 」、「 Idle 」、「 Default 」、「 None 」。



カスタムのパフォーマンスサービスレベルを作成および編集するには、パフォーマンスサービスレベルページで、ストレージにアクセスするアプリケーションに必要なサービスレベル目標を定義します。

[NOTE]
====
ワークロードに現在割り当てられているパフォーマンスサービスレベルは変更できません。

====
.手順
. 左側のナビゲーションペインの * Settings * で、 * Policies * > * Performance Service Levels * を選択します。
. パフォーマンスサービスレベル * ページで、新しいパフォーマンスサービスレベルを作成するか既存のパフォーマンスサービスレベルを編集するかに応じて、該当するボタンをクリックします。
+
|===
| 目的 | 実行する手順 


 a| 
新しいパフォーマンスサービスレベルを作成します
 a| 
[ 追加（ Add ） ] をクリックします。



 a| 
既存のパフォーマンスサービスレベルを編集します
 a| 
既存のパフォーマンスサービスレベルを選択し、 * 編集 * をクリックします。

|===
+
パフォーマンスサービスレベルを追加または編集するためのページが表示されます。

. パフォーマンスの目標を指定してパフォーマンスサービスレベルをカスタマイズし、 * Submit * をクリックしてパフォーマンスサービスレベルを保存します。


新規または変更したパフォーマンスサービスレベルをワークロード（ LUN 、 NFS ファイル共有、 CIFS 共有）に適用できるのは、ワークロードページから、または新しいワークロードをプロビジョニングするときです。
