---
permalink: storage-mgmt/task_add_space_to_data_disk_of_vmware.html 
sidebar: sidebar 
keywords: add space, data, disk, vmware, virtual, machine 
summary: Unified Manager データベースのデータディスクのスペースを増やす必要がある場合は、インストール後に Unified Manager のメンテナンスコンソールを使用してディスクスペースを増やして容量を追加できます。 
---
= VMware仮想マシンのデータディスクにスペースを追加する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager データベースのデータディスクのスペースを増やす必要がある場合は、インストール後に Unified Manager のメンテナンスコンソールを使用してディスクスペースを増やして容量を追加できます。

.開始する前に
* vSphere Client へのアクセス権が必要です。
* 仮想マシンにスナップショットがローカルに格納されていないことが必要です。
* メンテナンスユーザのクレデンシャルが必要です。


仮想ディスクのサイズを拡張する前に仮想マシンをバックアップすることをお勧めします。

.手順
. vSphere Client で、 Unified Manager 仮想マシンを選択し、データ「ディスク 3 」にディスク容量を追加します。詳細については、 VMware のドキュメントを参照してください。
+
Unified Manager の導入で、「ハードディスク 3 」ではなく「ハードディスク 2 」が使用されることがあります。これが導入環境で発生した場合は、ディスクのサイズを大きくします。データディスクには、常に他のディスクよりも多くの容量があります。

. vSphere Client で、 Unified Manager 仮想マシンを選択し、 * Console * タブを選択します。
. コンソールウィンドウ内をクリックし、ユーザ名とパスワードを使用してメンテナンスコンソールにログインします。
. * メインメニュー * で、 * システム構成 * オプションの番号を入力します。
. システム構成メニュー * で、 [ データディスクサイズの増加 ] オプションの数値を入力します。

