---
permalink: storage-mgmt/task_change_time_um_retains_event_performance_data.html 
sidebar: sidebar 
keywords: change, length, time, unified manager, retains, event, performance, data 
summary: Unified Manager には、すべての監視対象クラスタのイベントデータとパフォーマンスデータが 6 カ月間、デフォルトで格納されます。この期間を過ぎると、新しいデータ用のスペースを確保するために古いデータが自動的に削除されます。このデフォルトの期間はほとんどの構成に対して有効ですが、多数のクラスタとノードを含む非常に大規模な構成では、 Unified Manager が最適に動作するように保持期間を短縮しなければならない場合があります。 
---
= Unified Manager でイベントデータおよびパフォーマンスデータを保持する期間の変更
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager には、すべての監視対象クラスタのイベントデータとパフォーマンスデータが 6 カ月間、デフォルトで格納されます。この期間を過ぎると、新しいデータ用のスペースを確保するために古いデータが自動的に削除されます。このデフォルトの期間はほとんどの構成に対して有効ですが、多数のクラスタとノードを含む非常に大規模な構成では、 Unified Manager が最適に動作するように保持期間を短縮しなければならない場合があります。

* 必要なもの *

アプリケーション管理者のロールが必要です。

この 2 種類のデータの保持期間は、 Data Retention ページで変更できます。これらの設定は、 Unified Manager インスタンスで監視しているすべてのクラスタからのデータの保持に適用されます。

[NOTE]
====
Unified Manager はパフォーマンス統計を 5 分ごとに収集します。毎日、 5 分単位の統計が 1 時間単位のパフォーマンス統計に集計されます。5 分ごとのパフォーマンスデータの履歴は 30 日分、 1 時間ごとの集計パフォーマンスデータは 6 カ月間保持されます（デフォルト）。

====
保持期間を短くする必要があるのは、スペースが不足している場合や、バックアップやその他の処理の完了に時間がかかる場合のみです。保持期間を短くした場合の動作は次のとおりです。

* 古いパフォーマンスデータは、午前 0 時を過ぎた時点で Unified Manager データベースから削除されます。
* 古いイベントデータはただちに Unified Manager データベースから削除されます。
* 保持期間の前に発生したイベントはユーザインターフェイスに表示できなくなります。
* 保持期間の前のデータについては、 1 時間ごとのパフォーマンス統計が表示される場所には何も表示されません。
* イベントの保持期間がパフォーマンスデータの保持期間より長い場合、古いパフォーマンスイベントには関連するグラフに対応するデータが表示されない可能性があることを示すメッセージがパフォーマンススライダの警告の下に表示されます。


.手順
. 左側のナビゲーションペインで、 * ポリシー * > * データ保持 * をクリックします。
. [ * データ保持期間 * ] ページで、 [ イベント保持期間 ] または [ パフォーマンスデータ保持期間 ] 領域のスライダツールを選択し、データを保持する月数に移動して、 [ * 保存 ] をクリックします。

