---
permalink: storage-mgmt/task_edit_user_and_group_quota_email_addresses.html 
sidebar: sidebar 
keywords: edit, user, group, quota, email, addresses 
summary: 'クラスタ、 Storage Virtual Machine （ SVM ）、ボリューム、 qtree 、ユーザ、またはユーザグループに関連付けられたユーザクォータに基づいて、 E メールアドレスを変更することができます。[ ユーザクォータおよびグループクォータの E メールアドレスを生成するルール ] ダイアログボックスで指定したルールによって生成された E メールアドレスを上書きする場合は、 E メールアドレスを変更できます。' 
---
= ユーザーとグループのクォータのメールアドレスを編集する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クラスタ、 Storage Virtual Machine （ SVM ）、ボリューム、 qtree 、ユーザ、またはユーザグループに関連付けられたユーザクォータに基づいて、 E メールアドレスを変更することができます。[ ユーザクォータおよびグループクォータの E メールアドレスを生成するルール ] ダイアログボックスで指定したルールによって生成された E メールアドレスを上書きする場合は、 E メールアドレスを変更できます。

.開始する前に
* オペレータ、アプリケーション管理者、またはストレージ管理者のロールが必要です。
* を確認しておく必要があります link:reference_rules_to_generate_user_and_group_quota.html["ルールの作成に関するガイドライン"]。


E メールアドレスを編集すると、ユーザクォータおよびグループクォータの E メールアドレスを生成するルールがクォータに適用されなくなります。指定したルールに従って生成された E メールアドレスに通知を送信するには、 E メールアドレスを削除して変更を保存する必要があります。

.手順
. 左側のナビゲーションペインで、 * Storage * > * SVMs * をクリックします。
. * Health ： All Storage VMs] ビューで SVM を選択し、 * User クォータと Group Quotas * タブをクリックします。
. タブの行の下にある * 電子メールアドレスの編集 * をクリックします。
. [ 電子メールアドレスの編集 *] ダイアログボックスで、適切なアクションを実行します。
+
|===
| 状況 | 作業 


 a| 
指定したルールに従って生成された E メールアドレスに通知を送信する
 a| 
.. [*Email Address*] フィールドの電子メールアドレスを削除します。
.. [ 保存（ Save ） ] をクリックします。
.. F5 キーを押して E メールアドレスの編集ダイアログボックスをリロードし、ブラウザをリフレッシュします。指定したルールによって生成された E メールアドレスが ［ * E メールアドレス * ］ フィールドに表示されます。




 a| 
指定した E メールアドレスに通知を送信する
 a| 
.. [*Email Address*] フィールドで電子メールアドレスを変更します。
.. [ 保存（ Save ） ] をクリックします。ユーザクォータおよびグループクォータの E メールアドレスを生成するルールがクォータに適用されなくなります。


|===

