---
permalink: storage-mgmt/task_provision_fileshares.html 
sidebar: sidebar 
keywords: provision, file, share, volumes 
summary: CIFS / SMB プロトコルと NFS プロトコルをサポートするファイル共有ボリュームは、既存のクラスタと Storage Virtual Machine （ Storage VM ）のプロビジョニングワークロードページから作成できます。 
---
= ファイル共有ボリュームのプロビジョニング
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
CIFS / SMB プロトコルと NFS プロトコルをサポートするファイル共有ボリュームは、既存のクラスタと Storage Virtual Machine （ Storage VM ）のプロビジョニングワークロードページから作成できます。

* 必要なもの *

* Storage VM にファイル共有ボリュームをプロビジョニングするためのスペースが必要です。
* Storage VM で SMB サービスと NFS サービスのいずれか、または両方を有効にする必要があります。
* ワークロードにパフォーマンスサービスレベル（ PSL ）とストレージ効率化ポリシー（ SEP ）を選択して割り当てる場合は、ワークロードの作成を開始する前にポリシーを作成しておく必要があります。


.手順
. [* Provision Workload* ] ページで、作成するワークロードの名前を追加し、使用可能なリストからクラスタを選択します。
. 選択したクラスタに基づいて、 Storage VM * フィールドで、そのクラスタで使用可能な Storage VM がフィルタリングされます。リストから必要な Storage VM を選択します。
+
Storage VM でサポートされている SMB サービスと NFS サービスに基づいて、 Host Information セクションで NAS オプションが有効になっています。

. ストレージと最適化のセクションで、ストレージ容量と PSL を割り当てます。必要に応じて、ワークロードの SEP を割り当てます。
+
SEP の仕様が LUN に割り当てられ、 PSL の定義が作成時にワークロードに適用されます。

. ワークロードに割り当てた PSL を適用する場合は、「 * パフォーマンス制限を適用する * 」チェックボックスを選択します。
+
ワークロードに PSL を割り当てると、ワークロードが作成されるアグリゲートで、そのポリシーに定義されているパフォーマンスと容量の目標をサポートできることが保証されます。たとえば、ワークロードの PSL に「最高レベルのパフォーマンス」が割り当てられている場合、ワークロードをプロビジョニングするアグリゲートには、 SSD ストレージなど、「最高レベルのパフォーマンス」ポリシーに指定されたパフォーマンスと容量が求められます。

+
[NOTE]
====
このチェックボックスをオンにしないと、 PSL はワークロードに適用されず、ダッシュボードのワークロードのステータスは「未割り当て」と表示されます。

====
. 「 * NAS * 」オプションを選択します。
+
「 * NAS * 」オプションが有効になっていない場合は、選択した Storage VM が SMB 、 NFS 、またはその両方をサポートしているかどうかを確認してください。

+
[NOTE]
====
SMB サービスと NFS サービスの両方に対して Storage VM が有効になっている場合は、「 NFS で共有」チェックボックスと「 SMB で共有」チェックボックスを選択し、 NFS プロトコルと SMB プロトコルの両方をサポートするファイル共有を作成できます。SMB 共有と CIFS 共有のどちらかを作成する場合は、該当するチェックボックスのみを選択します。

====
. NFS ファイル共有ボリュームの場合は、ファイル共有ボリュームにアクセスするホストまたはネットワークの IP アドレスを指定します。複数のホストの値をカンマで区切って入力できます。
+
ホストの IP アドレスを追加すると、ホストの詳細が Storage VM と一致しているかどうかがチェックされ、指定したホストのエクスポートポリシーが作成されるか、または既存のポリシーがある場合はそのポリシーが使用されます。同じホストに対して複数の NFS 共有を作成した場合は、そのホストで使用可能な一致するルールを含むエクスポートポリシーがすべてのファイル共有で再利用されます。API を使用して NFS 共有をプロビジョニングする場合は、個々のポリシーのルールを指定したり、特定のポリシーキーを指定してポリシーを再利用したりすることができます。

. SMB 共有の場合は、アクセスを許可するユーザまたはユーザグループを指定し、必要な権限を割り当てます。ユーザグループごとに、新しい Access Control List （ ACL ；アクセス制御リスト）がファイル共有の作成時に生成されます。
. [ 保存（ Save ） ] をクリックします。
+
ワークロードがストレージワークロードのリストに追加されます。


