---
permalink: storage-mgmt/task_provision_luns.html 
sidebar: sidebar 
keywords: provision, luns 
summary: CIFS / SMB プロトコルと NFS プロトコルをサポートする LUN は、既存のクラスタおよび Storage Virtual Machine （ Storage VM ）上のプロビジョニングワークロードのページで作成できます。 
---
= LUN のプロビジョニング
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
CIFS / SMB プロトコルと NFS プロトコルをサポートする LUN は、既存のクラスタおよび Storage Virtual Machine （ Storage VM ）上のプロビジョニングワークロードのページで作成できます。

* 必要なもの *

* Storage VM に LUN をプロビジョニングするためのスペースが必要です。
* LUN を作成する Storage VM で iSCSI と FCP の両方が有効になっている必要があります。
* ワークロードにパフォーマンスサービスレベル（ PSL ）とストレージ効率化ポリシー（ SEP ）を選択して割り当てる場合は、ワークロードの作成を開始する前にポリシーを作成しておく必要があります。


.手順
. [* Provision Workload* ] ページで、作成するワークロードの名前を追加し、使用可能なリストからクラスタを選択します。
+
選択したクラスタに基づいて、 Storage VM * フィールドで、そのクラスタで使用可能な Storage VM がフィルタリングされます。

. iSCSI サービスと FCP サービスをサポートする Storage VM をリストから選択します。
+
選択に基づいて、ホスト情報セクションで SAN オプションが有効になります。

. 「ストレージと最適化 * 」セクションで、ストレージ容量と PSL を割り当てます。必要に応じて、ワークロードの SEP を割り当てます。
+
SEP の仕様が LUN に割り当てられ、 PSL の定義が作成時にワークロードに適用されます。

. 割り当てられている PSL をワークロードに適用する場合は、「 * パフォーマンス制限を適用する * 」チェックボックスを選択します。
+
ワークロードに PSL を割り当てると、ワークロードが作成されるアグリゲートで、そのポリシーに定義されているパフォーマンスと容量の目標をサポートできることが保証されます。たとえば、ワークロードに「最高レベルのパフォーマンス」 PSL が割り当てられている場合、ワークロードをプロビジョニングするアグリゲートには、 SSD ストレージなど、「最高レベルのパフォーマンス」ポリシーに指定されたパフォーマンスと容量が求められます。

+
[NOTE]
====
このチェックボックスをオンにしない場合、 PSL はワークロードに適用されず、ダッシュボードのワークロードのステータスは「 unassigned 」と表示されます。

====
. [*SAN* ] オプションを選択します。「 * san * 」オプションが有効になっていない場合は、選択した Storage VM で iSCSI と FCP がサポートされているかどうかを確認してください。
. ホスト OS を選択します。
. LUN へのイニシエータのアクセスを制御するホストマッピングを指定します。既存のイニシエータグループ（ igroup ）を割り当てるか、新しい igroup を定義してマッピングできます。
+
[NOTE]
====
LUN のプロビジョニング時に新しい igroup を作成した場合は、次の検出サイクル（最大 15 分）でその igroup が使用されるまで待つ必要があります。したがって、使用可能な igroup のリストから既存の igroup を使用することを推奨します。

====
+
新しい igroup を作成する場合は、「 * 新しいイニシエータグループを作成する * 」ボタンを選択し、 igroup の情報を入力します。

. [ 保存（ Save ） ] をクリックします。
+
LUN がストレージワークロードのリストに追加されます。


