---
permalink: storage-mgmt/task_export_storage_data_as_reports.html 
sidebar: sidebar 
keywords: export, storage, data, reports 
summary: ストレージデータをさまざまな出力形式でエクスポートし、エクスポートしたデータを使用してレポートを作成できます。たとえば、未解決の重大イベントが 10 件ある場合、イベント管理のインベントリページからデータをエクスポートしてレポートを作成し、問題を解決できる管理者にレポートを送信できます。 
---
= ストレージデータをレポートとしてエクスポート
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージデータをさまざまな出力形式でエクスポートし、エクスポートしたデータを使用してレポートを作成できます。たとえば、未解決の重大イベントが 10 件ある場合、イベント管理のインベントリページからデータをエクスポートしてレポートを作成し、問題を解決できる管理者にレポートを送信できます。

*Storage* および *Network* インベントリページから「 .csv 」ファイル、「 .xlsx 」ファイル、または「 .pdf 」ドキュメントにデータをエクスポートし、エクスポートしたデータを使用してレポートを作成できます。製品内には '.csv または '.pdf' ファイルのみを生成できる場所があります

.手順
. 次のいずれかを実行します。
+
|===
| エクスポートする項目 | 手順 


 a| 
ストレージオブジェクトのインベントリの詳細
 a| 
左側のナビゲーションメニューから * Storage * または * Network * をクリックし、ストレージオブジェクトを選択します。システムで提供されているビューのいずれか、または作成したカスタムビューを選択します。



 a| 
QoS ポリシーグループの詳細
 a| 
左側のナビゲーションメニューから、 * Storage * > * QoS Policy Groups * をクリックします。



 a| 
ストレージ容量と保護の履歴の詳細
 a| 
ストレージ * > * アグリゲート * または * ストレージ * > * ボリューム * をクリックして、 1 つまたは複数のアグリゲートまたはボリュームを選択します。



 a| 
イベントの詳細
 a| 
左側のナビゲーションメニューから、 * イベント管理 * をクリックします。



 a| 
上位 10 個のストレージオブジェクトのパフォーマンスの詳細
 a| 
[ * ストレージ * > * クラスタ * > * パフォーマンス：すべてのクラスタ * ] をクリックし、クラスタを選択して [ * パフォーマンストップ * ] タブを選択します。次に、ストレージオブジェクトとパフォーマンスカウンタを選択します。

|===
. [*Reports] ボタン（または一部の UI ページの [*Export*] ボタン）をクリックします。
. 「 * CSV のダウンロード * 」、「 PDF のダウンロード * 」、または「 * Excel のダウンロード * 」をクリックして、エクスポート要求を確認します。
+
Top Performers タブでは、表示している単一のクラスタまたはデータセンター内のすべてのクラスタの統計のレポートをダウンロードできます。

+
ファイルがダウンロードされます。

. 該当するアプリケーションでファイルを開きます。


* 関連情報 *

link:["ケンセンセイ / クラスタインヘントリヘエシ"]

link:../reporting/task_schedule_report.html["レポートのスケジュール設定"]
