---
permalink: health-checker/concept_what_database_restore_is.html 
sidebar: sidebar 
keywords: unified manager, database, restore 
summary: MySQL データベースのリストアとは、既存の Unified Manager バックアップファイルを同じまたは別の Unified Manager サーバにリストアする処理です。リストア処理は Unified Manager メンテナンスコンソールから実行します。 
---
= データベースリストアとは何ですか
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MySQL データベースのリストアとは、既存の Unified Manager バックアップファイルを同じまたは別の Unified Manager サーバにリストアする処理です。リストア処理は Unified Manager メンテナンスコンソールから実行します。

同じ（ローカル）システムでリストア処理を実行する場合、バックアップファイルがすべてローカルに保存されていれば、デフォルトの場所を使用してリストアオプションを実行できます。別の Unified Manager システム（リモートシステム）でリストア処理を実行する場合は、リストアオプションを実行する前に、バックアップファイルをセカンダリストレージからローカルディスクにコピーする必要があります。

リストアプロセス中は Unified Manager からログアウトされます。リストアプロセスが完了したら、システムにログインできます。

バックアップイメージを新しいサーバにリストアする場合は、リストア処理の完了後に新しい HTTPS セキュリティ証明書を生成して Unified Manager サーバを再起動する必要があります。また、バックアップイメージを新しいサーバにリストアするときに、必要に応じて SAML 認証の設定を再設定する必要があります。

[NOTE]
====
Unified Manager ソフトウェアを新しいバージョンにアップグレードしたあとに、古いバックアップファイルを使用してイメージをリストアすることはできません。スペースを節約するために、 Unified Manager をアップグレードすると、最新のファイルを除く古いバックアップファイルがすべて自動的に削除されます。

====
* 関連情報 *

link:../config/task_generate_an_https_security_certificate_ocf.html["HTTPS セキュリティ証明書の生成"]

link:../config/task_enable_saml_authentication_um.html["SAML 認証の有効化"]

link:../config/concept_authentication_with_active_directory_or_openldap.html["Active Directory または OpenLDAP による認証"]
