---
permalink: health-checker/concept_how_scripts_work_with_alerts.html 
sidebar: sidebar 
keywords: scripts, work, alerts 
summary: Unified Manager でイベントに対するアラートが発生したときにスクリプトが実行されるように、スクリプトにアラートを関連付けることができます。スクリプトを使用して、ストレージオブジェクトの問題を解決したり、イベントの生成元のストレージオブジェクトを特定したりできます。 
---
= スクリプトとアラートの連携方法
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager でイベントに対するアラートが発生したときにスクリプトが実行されるように、スクリプトにアラートを関連付けることができます。スクリプトを使用して、ストレージオブジェクトの問題を解決したり、イベントの生成元のストレージオブジェクトを特定したりできます。

Unified Manager でイベントに対するアラートが生成されると、指定した受信者にアラート E メールが送信されます。アラートがスクリプトに関連付けられている場合は、そのスクリプトが実行されます。スクリプトに渡された引数の詳細をアラート E メールから取得できます。

[NOTE]
====
カスタムスクリプトを作成し、そのスクリプトを特定のイベントタイプのアラートに関連付けた場合、そのイベントタイプのカスタムスクリプトに基づいて操作が実行されます。 * Fix it * アクションは、デフォルトでは管理アクションページまたは Unified Manager ダッシュボードで使用できません。

====
スクリプトの実行には次の引数が使用されます。

* -eventID`
* -eventName`
* -eventSeverity
* -eventSourceID`
* --eventSourceName`
* --eventSourceType`
* -eventState
* `-EventArgs


これらの引数をスクリプトで使用して、関連するイベントの情報を収集したり、ストレージオブジェクトを変更したりできます。



== スクリプトから引数を取得する例

[listing]
----
print "$ARGV[0] : $ARGV[1]\n"
print "$ARGV[7] : $ARGV[8]\n"
----
アラートが生成されると、このスクリプトが実行され、次の出力が表示されます。

[listing]
----
-eventID : 290
-eventSourceID : 4138
----