---
permalink: health-checker/concept_common_unified_manager_administrative_workflows_and_tasks.html 
sidebar: sidebar 
keywords: Common, unified, manager, health, workflows, tasks 
summary: Unified Manager に関連する一般的な管理ワークフローと管理タスクには、監視対象のストレージクラスタの選択、データの可用性 / 容量 / 保護に悪影響を及ぼす状態の診断、消失したデータのリストア、ボリュームの設定と管理、診断データのバンドルとテクニカルサポートへの送信（必要時）などがあります。 
---
= Unified Manager の一般的な健常性関連のワークフローとタスク
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager に関連する一般的な管理ワークフローと管理タスクには、監視対象のストレージクラスタの選択、データの可用性 / 容量 / 保護に悪影響を及ぼす状態の診断、消失したデータのリストア、ボリュームの設定と管理、診断データのバンドルとテクニカルサポートへの送信（必要時）などがあります。

Unified Manager では、ストレージ管理者がダッシュボードを表示して管理対象ストレージクラスタの全体的な容量、可用性、保護の状態の健全性を評価できるほか、発生の可能性がある具体的な問題を突き止めて確認し、診断を行い、解決のための割り当てを行うことができます。

管理対象ストレージオブジェクトのストレージ容量やデータ可用性に影響する、クラスタ、 Storage Virtual Machine （ SVM ）、ボリューム、または FlexGroup ボリュームに関連した最も重要な問題が、ダッシュボードページのシステムヘルスグラフおよびイベントに表示されます。重要な問題が特定されると、このページに適切なトラブルシューティングワークフローをサポートするためのリンクが表示されます。

Unified Manager は、 OnCommand Workflow Automation （ WFA ）などの関連管理ツールを含むワークフローにも含まれており、ストレージリソースを直接設定できます。

このドキュメントでは、次の管理タスクに関連する一般的なワークフローについて説明します。

* 可用性の問題を診断および管理する
+
ハードウェア障害やストレージリソース構成に問題がある場合、原因のダッシュボードページにデータ可用性イベントが表示されます。ストレージ管理者は、埋め込まれたリンクに従って、該当するストレージリソースに関する接続情報を確認し、トラブルシューティングのアドバイスを参照し、他の管理者に問題の解決を割り当てることができます。

* パフォーマンスインシデントの設定と監視
+
管理者は、監視対象のストレージシステムリソースのパフォーマンスを監視し、管理することができます。を参照してください link:../performance-checker/concept_introduction_to_unified_manager_performance_monitoring.html["Active IQ Unified Manager ワークフローガイド - クラスタパフォーマンス管理"] を参照してください。

* ボリューム容量の問題を診断および管理する
+
ボリュームストレージ容量の問題がダッシュボードページに表示された場合、ストレージ管理者はリンク先を参照して該当するボリュームのストレージ容量に関連する現在と過去の傾向を確認し、トラブルシューティングのアドバイスを参照して、他の管理者に問題の解決を割り当てることができます。

* 保護関係の設定、監視、問題の診断
+
保護関係を作成して設定したあと、ストレージ管理者は、保護関係に関連する潜在的な問題、保護関係の現在の状態、該当する関係に対して成功した現在と過去の保護ジョブの情報、およびトラブルシューティングのアドバイスを確認できます。を参照してください link:../data-protection/concept_create_and_monitor_protection_relationships.html["Active IQ Unified Manager 保護ガイド"] を参照してください。

* バックアップファイルの作成とバックアップファイルからのデータのリストア
* ストレージオブジェクトへのアノテーションの関連付け
+
ストレージ管理者は、ストレージオブジェクトにアノテーションを関連付けることで、ストレージオブジェクトに関連するイベントをフィルタリングして表示できます。これにより、イベントに関連する問題に優先順位を付けて解決することができます。

* REST API を使用すると、 Unified Manager で収集された健全性、容量、パフォーマンスの情報を確認することができ、クラスタの管理に便利です。を参照してください link:../api-automation/concept_get_started_with_um_apis.html["Active IQ Unified Manager API 開発者ガイド"] を参照してください。
* テクニカルサポートへのサポートバンドルの送信
+
ストレージ管理者は、メンテナンスコンソールを使用して、サポートバンドルを取得し、テクニカルサポートに送信できます。問題で AutoSupport メッセージよりも詳しい診断とトラブルシューティングが必要な場合は、サポートバンドルをテクニカルサポートに送信する必要があります。


