---
permalink: health-checker/concept_introduction_to_unified_manager_health_monitoring.html 
sidebar: sidebar 
keywords: introduction, active iq, unified manager, health, monitor 
summary: Active IQ Unified Manager （旧 OnCommand Unified Manager ）では、 ONTAP ソフトウェアを実行する多数のシステムを一元化されたユーザインターフェイスで監視できます。Unified Manager サーバインフラは拡張性とサポート性に優れ、高度な監視機能と通知機能を備えています。 
---
= Active IQ Unified Manager の健常性監視の概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Manager （旧 OnCommand Unified Manager ）では、 ONTAP ソフトウェアを実行する多数のシステムを一元化されたユーザインターフェイスで監視できます。Unified Manager サーバインフラは拡張性とサポート性に優れ、高度な監視機能と通知機能を備えています。

Unified Manager の主な機能には、クラスタの可用性と容量の監視 / 通知 / 管理、保護機能の管理、診断データの収集とテクニカルサポートへの送信などがあります。

Unified Manager を使用してクラスタを監視できます。クラスタで問題が発生すると、 Unified Manager のイベントを通じて問題の詳細が通知されます。一部のイベントでは、問題を解決するための対応策も提示されます。問題が発生したときに E メールや SNMP トラップで通知されるように、イベントにアラートを設定することができます。

Unified Manager では、アノテーションを関連付けることで環境内のストレージオブジェクトを管理できます。カスタムアノテーションを作成し、ルールに基づいて動的にクラスタ、 Storage Virtual Machine （ SVM ）、およびボリュームを関連付けることができます。

また、それぞれのクラスタオブジェクトについて、容量や健全性のグラフに表示される情報を使用してストレージ要件を計画することもできます。



== 物理容量と論理容量

Unified Manager は、 ONTAP ストレージオブジェクトに使用される物理スペースと論理スペースの概念を利用します。

* 物理容量：物理スペースは、ボリュームで使用されているストレージの物理ブロックを表します。「物理使用容量」は、通常、ストレージ効率化機能（重複排除や圧縮など）からのデータ削減のため、使用済み論理容量よりも小さくなります。
* 論理容量：論理スペースは、ボリューム内の使用可能なスペース（論理ブロック）を表します。論理スペースとは、重複排除や圧縮の結果を考慮せずに、理論上のスペースをどのように使用できるかを指します。「 Logical space used 」は、使用済みの物理スペースに加えて、設定済みの Storage Efficiency 機能（重複排除や圧縮など）による削減量を示します。Snapshot コピー、クローン、その他のコンポーネントが含まれ、データ圧縮やその他の物理スペースの削減が反映されていないため、この測定値は、多くの場合、物理使用容量よりも大きく表示されます。したがって、合計論理容量は、プロビジョニング済みスペースよりも多くなる可能性があります。




== 容量の単位

Unified Manager は、 1024 （ 2^10^ ）バイトのバイナリ単位に基づいてストレージ容量を計算します。ONTAP 9.10.0 以前では、これらの単位は KB 、 MB 、 GB 、 TB 、 PB として表示されていました。ONTAP 9.10.1 以降、 Unified Manager では KiB 、 MiB 、 GiB 、 TiB 、および PiB として表示されます。注：スループットに使用される単位は、すべてのリリースの ONTAP で 1 秒あたりのキロバイト数（ Kbps ）、 1 秒あたりのメガバイト数（ Mbps ）、 1 秒あたりのギガバイト数（ Gbps ）、 1 秒あたりのテラバイト数（ Tbps ）などとなります。

[cols="4*"]
|===
| Unified Manager for ONTAP 9.10.0 以前の容量ユニットが表示されます | Unified Manager for ONTAP 9.10.1 で表示される容量の単位 | 計算 | バイト単位の値 


 a| 
KB
 a| 
KiB
 a| 
1024
 a| 
1024 バイト



 a| 
MB
 a| 
MIB
 a| 
1024 * 1024
 a| 
1 、 048 、 576 バイト



 a| 
GB
 a| 
GIB
 a| 
1024 * 1024 * 1024
 a| 
1,073,741,824 バイト



 a| 
容量
 a| 
TiB
 a| 
1024 * 1024 * 1024 * 1024
 a| 
1 、 099 、 511 、 627 、 776 バイト

|===