---
permalink: health-checker/concept_configure_destination_and_schedule_for_database_dump_backups.html 
sidebar: sidebar 
keywords: configure, destination, schedule, database dump, backups 
summary: Unified Manager のデータベースダンプバックアップ設定で、データベースのバックアップパス、保持数、およびバックアップスケジュールを設定できます。日単位または週単位のスケジュールされたバックアップを有効にすることができますデフォルトでは、スケジュールされたバックアップは無効になっていますが、バックアップスケジュールを設定する必要があります。 
---
= データベースダンプバックアップのデスティネーションの設定とスケジュール設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager のデータベースダンプバックアップ設定で、データベースのバックアップパス、保持数、およびバックアップスケジュールを設定できます。日単位または週単位のスケジュールされたバックアップを有効にすることができますデフォルトでは、スケジュールされたバックアップは無効になっていますが、バックアップスケジュールを設定する必要があります。

* 必要なもの *

* オペレータ、アプリケーション管理者、またはストレージ管理者のロールが必要です。
* バックアップパスとして定義する場所に 150GB 以上の利用可能なスペースが必要です。
+
Unified Manager ホストシステムとは別のリモートの場所を使用することを推奨します。

* Unified Manager を Linux システムにインストールし、 MySQL バックアップを使用する場合は、バックアップディレクトリに対して次の権限と所有権が設定されていることを確認してください。
+
権限： 0750 、所有権： jboss: maintenance

* Unified Manager を Windows システムにインストールし、 MySQL バックアップを使用する場合は、バックアップディレクトリにアクセスできるのが管理者だけであることを確認してください。


初回のバックアップではフルバックアップが実行されるため、 2 回目以降のバックアップよりも時間がかかります。フルバックアップは 1GB を超えることもあり、 3~4 時間かかる場合があります。2 回目以降のバックアップは増分バックアップとなり、所要時間は短くなります。

[NOTE]
====
* 増分バックアップファイルがバックアップ用に割り当てたスペースに対して増えすぎている場合は、新しいフルバックアップを定期的に作成して、古いフルバックアップとそのすべての子増分ファイルを置き換えることができます。Unified Manager が Linux システムにインストールされている場合は、別の方法として NetApp Snapshot のバックアップを開始することもできます。
* 新しいクラスタに追加してから最初の 15 日間に作成されたバックアップは、過去のパフォーマンスデータを取得するのに十分な精度がない可能性があります。


====
.手順
. 左側のナビゲーションペインで、 * General * > * Database Backup * をクリックします。
. [* データベース・バックアップ * ] ページで、 [ * バックアップ設定 * ] をクリックします。
. バックアップパス、保持数、およびスケジュールの値を設定します。
+
保持数のデフォルト値は 10 です。バックアップを無制限に作成する場合は 0 に設定します。

. 「毎日スケジュール」または「毎週スケジュール」 * ボタンを選択し、スケジュールの詳細を指定します。
. [ 適用（ Apply ） ] をクリックします。


スケジュールに基づいてデータベースダンプバックアップファイルが作成されます。使用可能なバックアップファイルは、 [ データベースバックアップ ] ページに表示されます。
