---
permalink: health-checker/concept_how_group_actions_work_on_storage_objects.html 
sidebar: sidebar 
keywords: group actions, work, storage, objects 
summary: グループアクションは、グループ内のすべてのストレージオブジェクトに対して実行される処理です。たとえば、ボリュームしきい値のグループアクションを設定して、グループ内のすべてのボリュームのしきい値を同時に変更できます。 
---
= ストレージオブジェクトでのグループ操作の仕組み
:icons: font
:imagesdir: ../media/


[role="lead"]
グループアクションは、グループ内のすべてのストレージオブジェクトに対して実行される処理です。たとえば、ボリュームしきい値のグループアクションを設定して、グループ内のすべてのボリュームのしきい値を同時に変更できます。

グループは、一意のグループアクションタイプをサポートします。ボリューム健常性しきい値タイプのグループアクションは 1 つのグループに 1 つしか設定できません。ただし、同じグループに別のタイプのグループアクションがある場合は、それを設定できます。グループアクションがストレージオブジェクトに適用される順序はアクションのランクで決まります。ストレージオブジェクトに適用されるグループアクションの情報は、ストレージオブジェクトの詳細ページで確認できます。



== 一意なグループアクションの例

ボリューム A がグループ G1 と G2 に属しており、これらのグループに次のボリューム健常性しきい値グループアクションが設定されているとします。

* 'Change_capacity_threshold' グループ・アクションは ' ボリュームの容量を構成するためにランク 1 を使用します
* 'Change_snapshot_copies ' グループ・アクションは ' ボリュームの Snapshot コピーを構成するためのランク 2 です


'Change_capacity_threshold' グループ・アクションは 'Change_snapshot_copies のグループ・アクションよりも常に優先され ' ボリューム A に適用されますUnified Manager が 1 サイクルの監視を完了すると ' ボリューム A の正常性しきい値関連イベントが 'Change_capacity_threshold' グループアクションごとに再評価されますG1 または G2 のどちらのグループにも、ボリュームしきい値タイプの別のグループアクションを設定することはできません。
