---
permalink: health-checker/reference_cluster_compliance_categories.html 
sidebar: sidebar 
keywords: cluster compliance, categories 
summary: 次の表に、 Unified Manager で評価されるクラスタセキュリティコンプライアンスのパラメータ、ネットアップの推奨事項、およびクラスタが準拠か非準拠かの総合的な判断にパラメータが影響するかどうかを示します。 
---
= クラスタコンプライアンスのカテゴリ
:icons: font
:imagesdir: ../media/


[role="lead"]
次の表に、 Unified Manager で評価されるクラスタセキュリティコンプライアンスのパラメータ、ネットアップの推奨事項、およびクラスタが準拠か非準拠かの総合的な判断にパラメータが影響するかどうかを示します。

クラスタに非準拠の SVM があると、クラスタのコンプライアンスに影響します。そのため、クラスタのセキュリティが準拠とみなされるためには、事前に SVM のセキュリティ問題の修正が必要となる場合があります。

以下のパラメータは、すべてのインストール環境で表示されるわけではありません。たとえば、ピアクラスタがない場合やクラスタで AutoSupport を無効にしている場合、「クラスタピアリング」や「 AutoSupport HTTPS 転送」の項目は表示されません。

[cols="4*"]
|===
| パラメータ | 説明 | 推奨事項 | クラスタコンプライアンスに影響します 


 a| 
グローバル FIPS
 a| 
グローバル FIPS （連邦情報処理標準） 140-2 準拠モードが有効になっているかどうかを示します。FIPS を有効にすると、 TLSv1 と SSLv3 は無効になり、 TLSv1.1 と TLSv1.2 のみが許可されます。
 a| 
有効
 a| 
はい。



 a| 
Telnet
 a| 
システムへの Telnet アクセスが有効になっているかどうかを示します。ネットアップでは、セキュアなリモートアクセスのために Secure Shell （ SSH ）を推奨しています。
 a| 
無効
 a| 
はい。



 a| 
セキュアでない SSH 設定
 a| 
SSH でセキュアでない暗号を使用しているかどうかを示します。たとえば、 CBC で始まる暗号などです。
 a| 
いいえ
 a| 
はい。



 a| 
ログインバナー
 a| 
システムにアクセスするユーザに対してログインバナーが有効になっているかどうかを示します。
 a| 
有効
 a| 
はい。



 a| 
クラスタピアリング
 a| 
ピアクラスタ間の通信が暗号化されているかどうかを示します。このパラメータが準拠とみなされるためには、ソースとデスティネーションの両方のクラスタで暗号化が設定されている必要があります。
 a| 
暗号化
 a| 
はい。



 a| 
Network Time Protocol の略
 a| 
クラスタに NTP サーバが 1 つ以上設定されているかどうかを示します。ネットアップでは、冗長性と最適なサービスを実現するために最低 3 台の NTP サーバをクラスタに関連付けることを推奨しています。
 a| 
を設定します
 a| 
はい。



 a| 
OCSP
 a| 
ONTAP に OCSP （ Online Certificate Status Protocol ）が設定されていないアプリケーションがないか、そのため通信が暗号化されていないかどうかを示します。非準拠のアプリケーションが一覧表示されます。
 a| 
有効
 a| 
いいえ



 a| 
リモート監査ログ
 a| 
ログ転送（ syslog ）が暗号化されているかどうかを示します。
 a| 
暗号化
 a| 
はい。



 a| 
AutoSupport HTTPS 転送
 a| 
ネットアップサポートに AutoSupport メッセージを送信するためのデフォルトの転送プロトコルとして HTTPS が使用されているかどうかを示します。
 a| 
有効
 a| 
はい。



 a| 
デフォルトの管理ユーザ
 a| 
デフォルトの管理ユーザ（組み込み）が有効になっているかどうかを示します。ネットアップでは、不要な組み込みアカウントはすべてロック（無効化）することを推奨しています。
 a| 
無効
 a| 
はい。



 a| 
SAML ユーザ
 a| 
SAML が設定されているかどうかを示します。SAML を使用すると、シングルサインオンのログイン方法として多要素認証（ MFA ）を設定できます。
 a| 
いいえ
 a| 
いいえ



 a| 
Active Directory ユーザ
 a| 
Active Directory が設定されているかどうかを示します。Active Directory と LDAP は、クラスタにアクセスするユーザに対して推奨される認証メカニズムです。
 a| 
いいえ
 a| 
いいえ



 a| 
LDAP ユーザ
 a| 
LDAP が設定されているかどうかを示します。Active Directory と LDAP は、ローカルユーザよりもクラスタを管理するユーザに対して推奨される認証メカニズムです。
 a| 
いいえ
 a| 
いいえ



 a| 
証明書ユーザ
 a| 
証明書ユーザがクラスタにログインするように設定されているかどうかを示します。
 a| 
いいえ
 a| 
いいえ



 a| 
ローカルユーザ
 a| 
ローカルユーザがクラスタにログインするように設定されているかどうかを示します。
 a| 
いいえ
 a| 
いいえ



 a| 
リモートシェル（ Remote Shell ）
 a| 
RSH が有効になっているかどうかを示します。セキュリティ上の理由から、 RSH は無効にする必要があります。セキュアなリモートアクセスを実現するために、 Secure Shell （ SSH ）が推奨されます。
 a| 
無効
 a| 
はい。



 a| 
MD5 使用中です
 a| 
ONTAP ユーザアカウントでセキュアでない MD5 ハッシュ関数を使用しているかどうかを示します。MD5 ハッシュ化されたユーザアカウントは、 SHA-512 などのより安全な暗号化ハッシュ関数への移行が推奨されます。
 a| 
いいえ
 a| 
はい。



 a| 
証明書発行者タイプ
 a| 
使用されているデジタル証明書のタイプを示します。
 a| 
CA 署名
 a| 
いいえ

|===