---
permalink: health-checker/reference_setup_autosupport_page.html 
sidebar: sidebar 
keywords: autosupport, messages, support bundles, technical support 
summary: AutoSupport ページでは、事前定義されたオンデマンドの AutoSupport メッセージをテクニカルサポートチームに送信して、環境の正しい運用や環境の整合性の維持に役立てることができます。AutoSupport はデフォルトで有効になっており、 NetAppActive IQ のメリットを活用するためには無効にしないでください。 
---
= テクニカルサポートに AutoSupport メッセージとサポートバンドルを送信する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AutoSupport ページでは、事前定義されたオンデマンドの AutoSupport メッセージをテクニカルサポートチームに送信して、環境の正しい運用や環境の整合性の維持に役立てることができます。AutoSupport はデフォルトで有効になっており、 NetAppActive IQ のメリットを活用するためには無効にしないでください。

Unified Manager サーバに関する診断用システムの情報と詳細なデータを必要に応じてメッセージで送信したり、メッセージを定期的に送信するようにスケジュールしたり、テクニカルサポートチームにサポートバンドルを生成して送信したりできます。

[NOTE]
====
ストレージ管理者ロールを持つユーザは、 AutoSupport メッセージとサポートバンドルを生成して、テクニカルサポートにオンデマンドで送信できます。ただし、定期的な AutoSupport を有効または無効にしたり、 HTTP プロキシサーバの設定セクションの説明に従って HTTP 設定を設定したりできるのは、管理者またはメンテナンスユーザだけです。HTTP プロキシサーバを使用する必要がある環境では、ストレージ管理者がオンデマンドの AutoSupport メッセージとサポートバンドルをテクニカルサポートに送信する前に設定を完了しておく必要があります。

====


== オンデマンドの AutoSupport メッセージの送信

テクニカルサポート、指定した E メール受信者、またはその両方に宛てたオンデマンドメッセージを生成して送信できます。

.手順
. 「 * 一般 * > * AutoSupport * 」に移動し、次のいずれかまたは両方の操作を実行します。
. AutoSupport メッセージをテクニカルサポートに送信する場合は、 * テクニカルサポートに送信 * チェックボックスをオンにします。
. AutoSupport メッセージを特定の電子メール受信者に送信する場合は、 [* 電子メール受信者に送信 *] チェックボックスをオンにして、受信者の電子メールアドレスを入力します。
. [ 保存（ Save ） ] をクリックします。
. [Generate and Send AutoSupport （生成して送信） ] をクリックします。




== 定期的な AutoSupport の有効化

事前定義された特定のメッセージをテクニカルサポートに送信して、問題の診断と解決を定期的に行うことができます。この機能はデフォルトで有効になっています。無効にした場合、管理者ユーザまたはメンテナンスユーザは設定を有効にできます。

.手順
. 「 * 一般 * > * AutoSupport * 」に移動します。
. [ 定期的なデータ（ Periodic AutoSupport ） ] セクションで、 [ 定期的に AutoSupport データを Active IQ に送信する（ Enable Sending Data Periodically to ） ] チェックボックスをオン
. 必要に応じて、 HTTP プロキシサーバの名前、ポート、および認証情報を定義します。詳細については、「 HTTP プロキシサーバの設定」の項を参照してください。
. [ 保存（ Save ） ] をクリックします。




== オンデマンドサポートバンドルをアップロードしています

トラブルシューティングの要件に基づいて、サポートバンドルを生成し、テクニカルサポートに送信できます。Unified Manager では、生成されたサポートバンドルのうち最新の 2 つだけが保持されます。それよりも古いサポートバンドルはシステムから削除されます。

サポートデータの種類によっては、クラスタリソースを大量に使用したり、完了までに時間がかかることがあるため、完全なサポートバンドルを選択した場合は、特定のデータタイプを追加または除外してサポートバンドルのサイズを縮小できます。また、 30 日分のログと構成データベースのレコードを含む軽量なサポートバンドルを作成することもできます。パフォーマンスデータ、取得記録ファイル、サーバヒープダンプは含まれません。

.手順
. 「 * 一般 * > * AutoSupport * 」に移動します。
. オンデマンドサポートバンドルセクションで、 * サポートバンドルの生成と送信 * をクリックします。
. 簡易サポートバンドルをテクニカルサポートに送信するには、サポートバンドルの生成と送信ポップアップで、 ** 簡易サポートバンドルの生成 ** チェックボックスをオンにします。
. または、完全なサポートバンドルを送信するには、 [*Generate full support Bundle*] チェックボックスをオンにします。サポートバンドルに含めるデータタイプと除外するデータタイプを選択します。
+
[NOTE]
====
データタイプを選択しなかった場合でも、サポートバンドルは他の Unified Manager データで生成されます。

====
. バンドルを生成してテクニカルサポートに送信するには、 * Send the bundle to Technical Support * チェックボックスを選択します。このチェックボックスをオフにすると、バンドルが生成され、 Unified Manager サーバのローカルに格納されます。生成されたサポートバンドルは、あとで VMware システムのサポートディレクトリ、 Linux システムの場合は /opt/NetApp/data/support/ 、 Windows システムの場合は「 ProgramData\NetApp\OnCommandAppData\ocum\support 」で使用できます。
. [ 送信（ Send ） ] をクリックします。




== HTTP プロキシサーバをセットアップしています

Unified Managerサーバからの直接アクセスが環境によって提供されない場合に、AutoSupport のコンテンツをサポートに送信するためのインターネットアクセスを提供するプロキシを指定できます。このセクションは、管理者およびメンテナンスユーザのみが使用できます。

* * HTTP プロキシ * を使用します
+
HTTP プロキシとして使用するサーバを識別するには、このチェックボックスをオンにします。

+
プロキシサーバのホスト名または IP アドレス、およびサーバへの接続に使用するポート番号を入力します。

* * 認証を使用 *
+
HTTP プロキシとして使用するサーバにアクセスするための認証情報を指定する必要がある場合は、このチェックボックスをオンにします。

+
HTTP プロキシでの認証に必要なユーザ名とパスワードを入力します。



[NOTE]
====
ベーシック認証のみを提供する HTTP プロキシはサポートされていません。

====