---
permalink: health-checker/task_generate_and_upload_support_bundle.html 
sidebar: sidebar 
keywords: generate, upload, support bundle 
summary: 診断情報を含むサポートバンドルを生成して、トラブルシューティングのサポートを受けるためにテクニカルサポートに送信することができます。メンテナンスコンソールからネットアップにサポートバンドルをアップロードすることもできます。 
---
= サポートバンドルを生成してアップロードする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
診断情報を含むサポートバンドルを生成して、トラブルシューティングのサポートを受けるためにテクニカルサポートに送信することができます。

Unified Manager 9.8 以降では、 Unified Manager サーバがインターネットに接続されている場合に、メンテナンスコンソールからネットアップにサポートバンドルをアップロードすることもできます。

.開始する前に
メンテナンスコンソールにメンテナンスユーザとしてアクセスできる必要があります。

一部のタイプのサポートデータでは、クラスタリソースを大量に使用したり、完了までに時間がかかったりすることがあります。そのため、完全なサポートバンドルを選択する際には、含めるデータタイプと除外するデータタイプを指定して、サポートバンドルのサイズを縮小できます。また、 30 日分のログと構成データベースのレコードを含む軽量なサポートバンドルを作成することもできます。パフォーマンスデータ、取得記録ファイル、サーバヒープダンプは含まれません。

Unified Manager では、生成されたサポートバンドルのうち最新の 2 つだけが保持されます。それよりも古いサポートバンドルはシステムから削除されます。

.手順
. メンテナンスコンソール * メインメニュー * で、 * サポート / 診断 * を選択します。
. サポートバンドルに含める詳細のレベルに応じて、 [Generate Light Support Bundle] または [*Generate Support Bundle] を選択します。
. フルサポートバンドルを選択した場合は、次のデータタイプを選択または選択解除して、サポートバンドルに含めるか除外します。
+
** * データベースダンプ *
+
MySQL Server データベースのダンプ。

** * ヒープダンプ *
+
メインの Unified Manager サーバプロセスの状態の Snapshot 。このオプションはデフォルトでは無効になっており、カスタマーサポートから要求された場合にのみ選択します。

** * 取得記録 *
+
Unified Manager と監視対象クラスタの間のすべての通信の記録。



+
[NOTE]
====
すべてのデータタイプを選択解除しても、それ以外の Unified Manager データでサポートバンドルが生成されます。

====
. 「 g 」と入力し、 Enter キーを押してサポートバンドルを生成します。
+
サポートバンドルの生成ではメモリが大量に消費されるため、この時点でサポートバンドルを生成するかどうかを確認するメッセージが表示されます。

. 「 y 」と入力し、 Enter キーを押してサポートバンドルを生成します。
+
この時点でサポートバンドルを生成しない場合は、「 n 」と入力してから Enter キーを押します。

. フルサポートバンドルにデータベースダンプファイルを含めるように指定した場合は、パフォーマンス統計の対象期間を指定するように求められます。パフォーマンス統計の追加には多くの時間とスペースが必要になることがあるため、パフォーマンス統計を含めずにデータベースをダンプすることもできます。
+
.. 開始日を「 YYYYMMDD 」の形式で入力します。
+
たとえば、 2021 年 1 月 1 日の「 20210101 」と入力します。パフォーマンス統計情報を含めない場合は 'n' を入力します

.. 対象とする統計の日数を、午前 12 時から入力します指定した開始日の日付にある。
+
1 ～ 10 の数値を入力できます。



+
パフォーマンス統計を含める場合は、収集期間が表示されます。

. サポートバンドルが作成されると、ネットアップにアップロードするかどうかの確認を求められます。「 y 」と入力し、 Enter キーを押します。
+
サポートケース番号の入力を求められます。

. ケース番号がすでにある場合は、その番号を入力して Enter キーを押します。それ以外の場合は、 Enter キーを押します
+
サポートバンドルがネットアップにアップロードされます。



Unified Manager サーバがインターネットに接続されていない場合や、何らかの理由でサポートバンドルをアップロードできない場合は、サーバを取得して手動で送信できます。このリポジトリは、 SFTP クライアントを使用するか、 UNIX または Linux の CLI コマンドを使用して取得できます。Windows 環境では、 Remote Desktop （ RDP ）を使用してサポートバンドルを取得することができます。

生成されたサポートバンドルは、 VMware システムの /support ディレクトリ、 Linux システムの場合は /opt/NetApp/data/support/ 、 Windows システムの場合は ProgramData\NetApp\OnCommandAppData\ocum\support にあります。

* 関連情報 *

link:../config/reference_unified_manager_roles_and_capabilities.html["Unified Manager のユーザロールと機能"]
