---
permalink: health-checker/task_perform_diagnotstic_actions_for_volume_offline_conditions.html 
sidebar: sidebar 
keywords: perform, diagnostic actions, volume, offline, conditions 
summary: オフラインと報告されたボリュームのボリューム / 健全性の詳細ページに移動したら、ボリュームのオフライン状態を診断するのに役立つ追加情報を検索できます。 
---
= ボリュームのオフライン状態に対する診断アクションを実行する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
オフラインと報告されたボリュームのボリューム / 健全性の詳細ページに移動したら、ボリュームのオフライン状態を診断するのに役立つ追加情報を検索できます。

.開始する前に
オペレータ、アプリケーション管理者、またはストレージ管理者のロールが必要です。

オフラインと報告されたボリュームが、意図的にオフラインにされたのではない場合は、いくつかの理由が考えられます。

オフラインボリュームのボリューム / 健全性の詳細ページから他のページやペインに移動して、考えられる原因を確認するかどうかを確認することができます。

* ボリューム / 健全性 * の詳細ページのリンクをクリックして、ボリュームのオフライン状態の原因が、ホストノードの停止およびその HA ペアパートナーへのストレージフェイルオーバーの失敗であるかどうかを確認します。
+
を参照してください link:task_determine_if_volume_offline_condition_is_by_down_cluster_node.html["ボリュームのオフライン状態の原因がノードの停止であるかどうかを判別します"]。

* ボリューム / 健全性 * の詳細ページのリンクをクリックして、ボリュームがオフラインで、その SVM のルートボリュームをホストしているノードが停止したためにホストしている Storage Virtual Machine （ SVM ）が停止していないかを確認します。
+
を参照してください link:task_determine_if_volume_is_offline_and_its_svm_is_stopped.html["ボリュームのオフライン状態と SVM の停止の原因がノードの停止であるかどうかの判別"]。

* ボリューム / 健全性 * の詳細ページのリンクをクリックして、ボリュームがオフラインになっている原因がホストアグリゲート内の破損ディスクであるかどうかを確認します。
+
を参照してください link:task_determine_if_volume_is_offline_because_of_broken_disks.html["ボリュームのオフライン状態の原因がアグリゲート内の破損ディスクであるかどうかを判別しています"]。



* 関連情報 *

link:../config/reference_unified_manager_roles_and_capabilities.html["Unified Manager のユーザロールと機能"]
