---
permalink: health-checker/task_view_cluster_list_and_details.html 
sidebar: sidebar 
keywords: view, cluster list, details 
summary: Health ： All Clusters ビューを使用すると、クラスタのインベントリを表示できます。Capacity ： All Clusters ビューでは、すべてのクラスタのストレージ容量と使用状況についてまとめた情報を表示できます。 
---
= クラスタリストおよび詳細の表示
:icons: font
:imagesdir: ../media/


[role="lead"]
Health ： All Clusters ビューを使用すると、クラスタのインベントリを表示できます。Capacity ： All Clusters ビューでは、すべてのクラスタのストレージ容量と使用状況についてまとめた情報を表示できます。

* 必要なもの *

オペレータ、アプリケーション管理者、またはストレージ管理者のロールが必要です。

個々のクラスタの健全性、容量、構成、 LIF 、ノードなどの詳細を表示することもできます。 クラスタのディスクや健全性の詳細ページで確認できます。

健全性：すべてのクラスタビュー、容量：すべてのクラスタビュー、およびクラスタ / 健全性の詳細ページで、ストレージを計画する際に役立ちます。たとえば、新しいアグリゲートをプロビジョニングする前に、特定のクラスタを Health ： All Clusters ビューで選択し、容量の詳細を取得して必要なスペースがクラスタにあるかどうかを確認できます。

.手順
. 左側のナビゲーションペインで、 * Storage * > * Clusters * をクリックします。
. [ 表示 ] メニューで、 [ * 健全性：すべてのクラスタ * 表示 ] を選択して健全性情報を表示するか、 [ * 容量：すべてのクラスタ * 表示 ] を選択してすべてのクラスタのストレージ容量と使用率に関する詳細を表示します。
. クラスタの名前をクリックし、クラスタ / 健常性 * の詳細ページにクラスタのすべての詳細を表示します。


* 関連情報 *

link:../health-checker/reference_health_cluster_details_page.html["クラスタ / 健全性の詳細ページ"]
