---
permalink: health-checker/task_view_detailed_security_status_for_clusters_and_svms.html 
sidebar: sidebar 
keywords: view, cluster security status, svm security status, volume encryption status 
summary: Security ページには、すべてのクラスタのセキュリティステータスの概要と、個々のクラスタの詳細なセキュリティステータスが表示されます。詳細なクラスタステータスには、クラスタコンプライアンス、 SVM コンプライアンス、ボリューム暗号化コンプライアンスが含まれます。 
---
= クラスタと Storage VM の詳細なセキュリティステータスの表示
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Security ページには、すべてのクラスタのセキュリティステータスの概要と、個々のクラスタの詳細なセキュリティステータスが表示されます。

システム管理者は、セキュリティ * ページを使用して、データセンターレベルとサイトレベルの ONTAP クラスタと Storage VM のセキュリティ強度を可視化できます。

定義されたパラメータに基づいて情報を収集および分析し、監視対象のクラスタおよび Storage VM についての疑わしい動作や不正なシステム変更を検出できます。

詳細なクラスタステータスには、クラスタコンプライアンス、 SVM コンプライアンス、ボリューム暗号化コンプライアンスが含まれます。

クラスタ / セキュリティの詳細ページでは、グローバルな FIPS 、 Telnet 、セキュアでない SSH 設定、ログインバナー、ネットワークタイムプロトコル、 AutoSupport HTTPS 転送、およびデフォルト管理者。

Storage VMs/Security の詳細ページでは、 Storage VM 、クラスタ、ログインバナー、監査ログ、セキュアでない SSH 設定などのセキュリティパラメータを確認することで、 Storage VM のセキュリティコンプライアンスのデフォルトビューが表示されます。

セキュリティコンプライアンスレポートは、クラスタおよび Storage VM の詳細ページから生成、スケジュール、およびダウンロードすることもできます。

セキュリティダッシュボード * で、 * クラスタコンプライアンス * カードおよび * Storage VMS コンプライアンス * カードの * レポートの表示 * をクリックします。

.手順
. 左側のナビゲーションペインで、 * ダッシュボード * をクリックします。
. すべての監視対象クラスタのセキュリティステータスを表示するか、 1 つのクラスタのセキュリティステータスを表示するかに応じて、 * すべてのクラスタ * を選択するか、ドロップダウンメニューから 1 つのクラスタを選択します。
. セキュリティ * パネルの右矢印をクリックします。
+
Security ページには、次の情報が表示されます。

+
** クラスタのセキュリティステータス（準拠または非準拠のクラスタ数）
** SVM のセキュリティステータス（準拠または非準拠の SVM 数）
** ボリューム暗号化ステータス（暗号化されているボリュームまたは暗号化されていないボリュームの数）
** 各クラスタで使用されているクラスタ認証方式


. を参照してください http://www.netapp.com/us/media/tr-4569.pdf["『 ONTAP 9 セキュリティ設定ガイド』"] すべてのクラスタ、 SVM 、およびボリュームを、ネットアップのセキュリティに関する推奨事項に準拠させていただく方法については、を参照してください。

