---
permalink: health-checker/task_determine_if_volume_is_offline_because_of_broken_disks.html 
sidebar: sidebar 
keywords: determine, volume, offline, broken disks, aggregate 
summary: Unified Manager Web UI を使用して、ボリュームがオフラインになっている原因が、 RAID ディスクの問題によりそのホストアグリゲートがオフラインになったためであるかどうかを確認することができます。 
---
= ボリュームのオフライン状態の原因がアグリゲート内の破損ディスクであるかどうかを判別しています
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager Web UI を使用して、ボリュームがオフラインになっている原因が、 RAID ディスクの問題によりそのホストアグリゲートがオフラインになったためであるかどうかを確認することができます。

.開始する前に
オペレータ、アプリケーション管理者、またはストレージ管理者のロールが必要です。

ボリュームのオフライン状態の原因が、 RAID ディスクの問題によりホストアグリゲートがオフラインになったためであるかどうかを判別するには、次の手順を実行します。

.手順
. 「 * Volume/Health * details 」ページの「 Aggregate 」（アグリゲート）に表示されているハイパーテキストリンクを探してクリックします。
+
アグリゲート / 健全性の詳細ページに、ホストアグリゲートのオンラインまたはオフラインのステータスが表示されます。アグリゲートのステータスが「オンライン」の場合、 RAID ディスクの問題は、オフラインになっているボリュームの原因ではありません。

. アグリゲートのステータスがオフラインの場合は、 * ディスク情報 * をクリックし、 * ディスク情報 * タブの * イベント * リストで破損ディスクイベントを探します。
. 破損ディスクをさらに特定するには、 [*Related Devices* （関連デバイス） ] ペインの [Node （ノード） ] に表示されるハイパーテキストリンクをクリックします。
+
クラスタ / 健常性の詳細ページが表示されます。

. [ * ディスク ] をクリックし、 [ * フィルタ * ] ペインで [ * 破損 * ] を選択して、破損状態のすべてのディスクを一覧表示します。
+
破損状態のディスクが原因でホストアグリゲートがオフラインになった場合は、「 Impacted Aggregate 」列にアグリゲートの名前が表示されます。



ボリュームのオフライン状態の原因が、 RAID ディスクの破損とそれによるホストアグリゲートのオフライン状態であることを確認したら、適切な管理者またはオペレータに連絡し、手動による破損ディスクの交換とアグリゲートをオンラインに戻す処理を依頼します。
