---
permalink: health-checker/task_view_aggregate_list_and_details.html 
sidebar: sidebar 
keywords: view, aggregate list, details 
summary: Health ： All aggregates ビューでは、アグリゲートのインベントリを監視できます。Capacity ： All Aggregates ビューでは、すべてのクラスタのアグリゲートの容量と使用状況に関する情報を確認できます。 
---
= アグリゲートリストおよび詳細を表示する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Health ： All aggregates ビューでは、アグリゲートのインベントリを監視できます。Capacity ： All Aggregates ビューでは、すべてのクラスタのアグリゲートの容量と使用状況に関する情報を確認できます。

.開始する前に
オペレータ、アプリケーション管理者、またはストレージ管理者のロールが必要です。

アグリゲートの容量と構成、ディスク情報などの詳細をアグリゲート / 健全性の詳細ページで確認できます。必要に応じて、しきい値を設定する前にこれらの詳細を使用できます。

.手順
. 左側のナビゲーションペインで、 * Storage * > * Aggregates * をクリックします。
. 次のいずれかの方法を選択してアグリゲートの詳細を表示します。
+
** すべてのクラスタ内のすべてのアグリゲートの健常性に関する情報を表示するには、表示メニューで健常性：すべてのアグリゲート表示を選択します。
** すべてのクラスタ内のすべてのアグリゲートの容量と使用状況に関する情報を表示するには、表示メニューで容量：すべてのアグリゲートビューを選択します。
** すべての詳細を表示するには、アグリゲート名をクリックします。
+
詳細を表示するには、 [ 最小詳細 ] ダイアログボックスの [ 詳細の表示 ] をクリックします。



. 最小限の詳細ダイアログボックスで * 関連項目の表示 * をクリックして、アグリゲートに関連するオブジェクトを表示します。


* 関連情報 *

* link:../health-checker/reference_health_aggregate_details_page.html["アグリゲート / 健全性の詳細ページ"]
* link:../performance-checker/performance-view-all.html#performance-all-aggregates-view["パフォーマンス：すべてのアグリゲートが表示されます"]
* link:../reporting/concept_customize_aggregate_capacity_reports.html["アグリゲート容量レポートのカスタマイズ"]

