---
permalink: health-checker/task_add_alerts_for_security_events.html 
sidebar: sidebar 
keywords: add, alerts, security events 
summary: セキュリティイベントのアラートは、 Unified Manager で受信する他のイベントと同様に、イベントごとに個別に設定することができます。また、すべてのセキュリティイベントを同じように扱い、同じユーザに E メールを送信する場合は、セキュリティイベントがトリガーされたときに通知する共通のアラートを作成することもできます。 
---
= セキュリティイベントのアラートを追加する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
セキュリティイベントのアラートは、 Unified Manager で受信する他のイベントと同様に、イベントごとに個別に設定することができます。また、すべてのセキュリティイベントを同じように扱い、同じユーザに E メールを送信する場合は、セキュリティイベントがトリガーされたときに通知する共通のアラートを作成することもできます。

* 必要なもの *

アプリケーション管理者またはストレージ管理者のロールが必要です。

次に 'Telnet Protocol enabled' セキュリティ・イベントのアラートを作成する例を示しますクラスタへのリモート管理アクセス用に Telnet アクセスが設定されると、アラートが送信されます。同じ方法で、すべてのセキュリティイベントに対してアラートを作成できます。

.手順
. 左側のナビゲーションペインで、 * Storage Management * > * Alert Setup * をクリックします。
. [* Alert Setup* ] ページで、 [* Add] をクリックします。
. [ * アラートの追加 * ] ダイアログボックスで、 [ * 名前 * ] をクリックし、アラートの名前と概要を入力します。
. リソースをクリックし、このアラートを有効にするクラスタを選択します。
. [* Events （イベント） ] をクリックして、次の操作を実行します。
+
.. イベントの重大度リストで、 * 警告 * を選択します。
.. [Matching Events] リストで、 [Telnet Protocol Enabled*] を選択します。


. [* アクション * ] をクリックし、 [ これらのユーザーに警告 ] フィールドで警告メールを受信するユーザーの名前を選択します。
. 通知頻度、 SNMP トラップの発行、スクリプトの実行など、このページの他のオプションを設定します。
. [ 保存（ Save ） ] をクリックします。

