---
permalink: health-checker/task_configure_global_aggregate_health_threshold_values.html 
sidebar: sidebar 
keywords: configure, global, aggregate, health, threshold values 
summary: すべてのアグリゲートに対するグローバル健全性しきい値を設定して、しきい値の違反を追跡することができます。しきい値の違反が発生すると該当するイベントが生成されるため、それらのイベントに基づいて予防策を講じることが可能です。監視対象のすべてのアグリゲートに適用されるしきい値について、ベストプラクティスの設定に基づいてグローバルな値を設定することができます。 
---
= アグリゲートのグローバル健全性しきい値を設定します
:icons: font
:imagesdir: ../media/


[role="lead"]
すべてのアグリゲートに対するグローバル健全性しきい値を設定して、しきい値の違反を追跡することができます。しきい値の違反が発生すると該当するイベントが生成されるため、それらのイベントに基づいて予防策を講じることが可能です。監視対象のすべてのアグリゲートに適用されるしきい値について、ベストプラクティスの設定に基づいてグローバルな値を設定することができます。

* 必要なもの *

アプリケーション管理者またはストレージ管理者のロールが必要です。

オプションをグローバルレベルで設定すると、オブジェクトのデフォルト値が変更されます。ただし、オブジェクトレベルでデフォルト値が変更されている場合、グローバルな値は変更されません。

しきい値のオプションは、効果的に監視できるようにデフォルトで値が設定されています。ただし、それぞれの環境の要件に合わせて値を変更することができます。

アグリゲートに配置されているボリュームで自動拡張が有効になっている場合は、元のボリュームサイズではなく、自動拡張で設定された最大ボリュームサイズに基づいて、アグリゲートの容量のしきい値を超えているかどうかが判定されます。

[NOTE]
====
ノードのルートアグリゲートには健全性しきい値の値は適用されません。

====
.手順
. 左側のナビゲーションペインで、 * イベントしきい値 * > * 集計 * をクリックします。
. 容量、増加率、および Snapshot コピーのしきい値を必要に応じて設定します。
. [ 保存（ Save ） ] をクリックします。


* 関連情報 *

link:../config/task_add_users.html["ユーザを追加する"]
