---
permalink: health-checker/task_restore_snapshot_backup.html 
sidebar: sidebar 
keywords: restore, unified manager, snapshot copy, copies, 
summary: データ損失やデータ破損が発生した場合、 Unified Manager を以前の安定した状態にリストアすることでデータ損失を最小限に抑えることができます。Unified Manager の Snapshot データベースは、 Unified Manager メンテナンスコンソールを使用してローカルとリモートのどちらのオペレーティングシステムにもリストアできます。 
---
= Snapshotコピーを使用したUnified Managerのリストア
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
データ損失やデータ破損が発生した場合、 Unified Manager を以前の安定した状態にリストアすることでデータ損失を最小限に抑えることができます。Unified Manager の Snapshot データベースは、 Unified Manager メンテナンスコンソールを使用してローカルとリモートのどちらのオペレーティングシステムにもリストアできます。

.開始する前に
* Unified Manager がインストールされている Windows ホストマシンに対する Linux ホストの root ユーザのクレデンシャルと管理者権限が必要です。
* Unified Manager サーバのメンテナンスコンソールへのログインが許可されているユーザ ID とパスワードが必要です。


リストア機能は、プラットフォームおよびバージョンに固有の機能です。Unified Manager のバックアップは、同じバージョンの Unified Manager にのみリストアできます。

.手順
. Unified Manager システムの IP アドレスまたは完全修飾ドメイン名に接続します。
+
** Linux：Secure Shellの略
** Windows：PowerShell


. root ユーザのクレデンシャルでシステムにログインします。
. コマンド「 maintenance_console' 」を入力し、 Enter キーを押します。
. メンテナンスコンソール*メインメニュー*で、*バックアップリストア*オプションに4を入力します。
. 「* NetApp Snapshotを使用したバックアップとリストア」を選択するには、2を入力します。
+
新しいサーバへのリストアを実行する場合は、 Unified Manager のインストールの完了後に、 UI を起動したり、クラスタ、ユーザ、または認証設定を設定したりしないでください。Configure NetApp Snapshot Backup*を選択するには1を入力し、元のシステムと同様にSnapshotコピーの設定を行います。

. 「3」と入力して、「NetApp Snapshotを使用してリストア」を選択します。
. Unified Managerのリストアに使用するSnapshotコピーを選択します。Enter キーを押します。
. リストアプロセスが完了したら、 Unified Manager ユーザインターフェイスにログインします。


バックアップをリストアしたあとに Workflow Automation サーバが動作しなくなった場合は、次の手順を実行します。

. Workflow Automation サーバで、 Unified Manager サーバの IP アドレスを最新のマシンを参照するように変更します。
. 手順 1 で取得に失敗した場合は、 Unified Manager サーバでデータベースパスワードをリセットします。

