---
permalink: health-checker/task_configure_conditions_for_annotation_rules.html 
sidebar: sidebar 
keywords: unified manager, configure, conditions, annotation rules 
summary: 1 つ以上の条件を設定して、 Unified Manager がストレージオブジェクトに適用するアノテーションルールを作成できます。アノテーションルールに一致するストレージオブジェクトに、ルールで指定した値がアノテートされます。 
---
= アノテーションルールの条件の設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
1 つ以上の条件を設定して、 Unified Manager がストレージオブジェクトに適用するアノテーションルールを作成できます。アノテーションルールに一致するストレージオブジェクトに、ルールで指定した値がアノテートされます。

.開始する前に
アプリケーション管理者またはストレージ管理者のロールが必要です。

.手順
. 左側のナビゲーションペインで、 * Storage Management * > * Annotations * をクリックします。
. [* 注釈ルール * （ * Annotation Rules * ） ] タブで、 [ * 追加（ * Add * ） ] をクリックする
. [ * アノテーションルールの追加 * （ * Add Annotation Rule * ） ] ダイアログボックスで、ルールの名前を入力します。
. ターゲットオブジェクトタイプリストからオブジェクトタイプを 1 つ選択し、リストからアノテーションの名前と値を選択します。
. ダイアログボックスの * 条件 * （ * Conditions * ）セクションで、リストからオペランドと演算子を選択して条件値を入力するか、 * 条件の追加 * （ * Add Condition * ）をクリックして新しい条件を作成します。
. [ 保存して追加 ] をクリックします。




== アノテーションルールの条件の設定例

オブジェクトタイプが SVM で、オブジェクト名に「 'vm_data' 」が含まれている場合は、条件を考慮します。

[Add Annotation Rule] ダイアログボックスで次の手順を実行して、条件を設定します。

.手順
. アノテーションルールの名前を入力します。
. ターゲットオブジェクトタイプとして SVM を選択します。
. アノテーションのリストからアノテーションと値を選択します。
. [ * 条件 * （ * Conditions * ） ] フィールドで、オペランドとして [ * オブジェクト名 * （ * Object Name * ） ] を選択します。
. 演算子として * Contains * を選択します。
. 「 VM_data 」という値を入力します。
. [ 追加（ Add ） ] をクリックします。

