---
permalink: health-checker/task_perform_suggested_remedial_actions_for_full_volume.html 
sidebar: sidebar 
keywords: perform, suggested, remedial actions, volume 
summary: 「ボリュームスペースがフル」エラーイベントを受け取ったら、イベントの詳細ページで推奨される修正策を確認し、推奨されるいずれかの操作を実行します。 
---
= ボリューム全体に対して推奨される修復アクションを実行する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「ボリューム容量がいっぱいです」エラーイベントを受け取った後、イベントの詳細ページで推奨される修正策を確認し、推奨されるアクションのいずれかを実行することにします。

.開始する前に
アプリケーション管理者またはストレージ管理者のロールが必要です。

Unified Manager を使用するこのワークフロー内のタスクは、どのロールのユーザでも実行できます。

この例では、 Unified Manager のイベント管理インベントリページで「ボリュームスペースがフル」エラーイベントが表示されたので、そのイベントの名前をクリックしています。

ボリュームがフルになった場合に実施できる修正策には、次のものがあります。

* ボリュームに対して自動拡張、重複排除、または圧縮を有効にする
* ボリュームをサイズ変更するか、移動しています
* ボリュームからデータを削除または移動する


これらのすべての操作は ONTAP System Manager または ONTAP CLI から実行する必要がありますが、実行する操作を決定するために必要な情報は Unified Manager で確認できます。

.手順
. イベント * の詳細ページで、ソースフィールドのボリューム名をクリックすると、該当するボリュームの詳細が表示されます。
. ボリューム / 健常性 * の詳細ページで * Configuration * をクリックすると、ボリュームで重複排除と圧縮がすでに有効になっていることがわかります。
+
ボリュームのサイズを変更することにします。

. Related Devices * ペインで、ホスティングアグリゲートの名前をクリックすると、アグリゲートがボリュームの拡張に対応できるかどうかがわかります。
. アグリゲート / 健常性 * の詳細ページには、フルボリュームをホストしているアグリゲートにコミットされていない容量が十分にあることが表示されます。そのため、 ONTAP システムマネージャを使用してボリュームのサイズを変更し、容量を拡大します。


* 関連情報 *

link:../events/reference_event_details_page.html["イベントの詳細ページ"]
