---
permalink: health-checker/task_configure_global_health_threshold_settings.html 
sidebar: sidebar 
keywords: configure, global health, threshold settings 
summary: アグリゲート、ボリューム、および qtree のサイズを効果的に監視できるように、容量、増加率、 Snapshot リザーブ、クォータ、および inode について、グローバル健常性しきい値の条件を設定することができます。また、遅延しきい値を超えた場合にイベントを生成する設定を編集することもできます。 
---
= グローバル健全性しきい値を設定します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アグリゲート、ボリューム、および qtree のサイズを効果的に監視できるように、容量、増加率、 Snapshot リザーブ、クォータ、および inode について、グローバル健常性しきい値の条件を設定することができます。また、遅延しきい値を超えた場合にイベントを生成する設定を編集することもできます。

グローバル健全性しきい値の設定は、アグリゲートやボリュームなど、関連付けられているすべてのオブジェクトに適用されます。しきい値を超えるとイベントが生成され、アラートが設定されている場合はアラート通知も送信されます。しきい値はデフォルトで推奨値に設定されていますが、それらの値を変更することでイベントが生成される間隔をニーズに合わせて調整することができます。しきい値を変更した場合、次回の監視サイクルから反映され、その値に基づいてイベントが生成または廃止されます。

グローバル健常性しきい値の設定には、左側のナビゲーションメニューの「イベントしきい値」セクションからアクセスできます。また、個々のオブジェクトのインベントリページまたは詳細ページから、そのオブジェクトのしきい値の設定を変更することもできます。

* 詳細については、を参照してください link:task_configure_global_aggregate_health_threshold_values.html["アグリゲートのグローバル健全性しきい値を設定します"]。
+
すべてのアグリゲートに対する容量、増加率、および Snapshot コピーの健全性しきい値を設定して、しきい値の違反を追跡することができます。

* 詳細については、を参照してください link:task_configure_global_volume_health_threshold_values.html["ボリュームのグローバル健全性しきい値を設定しています"]。
+
容量、 Snapshot コピー、 qtree クォータ、ボリューム増加率、オーバーライトリザーブスペースの健全性しきい値の設定を編集することができます。 しきい値の違反を追跡するには、すべてのボリュームの inode を使用します。

* 詳細については、を参照してください link:task_configure_global_qtree_health_threshold_values.html["qtree のグローバル健全性しきい値を設定しています"]。
+
すべての qtree に対する容量の健全性しきい値の設定を編集して、しきい値の違反を追跡することができます。

* 詳細については、を参照してください link:task_configure_lag_threshold_settings_for_unmanaged_protection.html["管理対象外の保護関係の遅延健常性しきい値の編集"]。
+
警告やエラーの遅延時間の割合を増やしたり減らしたりすることで、イベントが生成される間隔をニーズに合わせて調整することができます。


