---
permalink: health-checker/task_view_fabricpool_capacity_information.html 
sidebar: sidebar 
keywords: view, fabricPool, cloud tier, mirror tier, capacity, information 
summary: クラスタ、アグリゲート、およびボリュームの FabricPool 容量情報は、容量とパフォーマンスのインベントリページおよびこれらのオブジェクトの詳細ページで確認できます。これらのページには、ミラー階層が構成されている場合の FabricPool ミラー情報も表示されます。 
---
= FabricPool の容量情報を表示する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クラスタ、アグリゲート、およびボリュームの FabricPool 容量情報は、容量とパフォーマンスのインベントリページおよびこれらのオブジェクトの詳細ページで確認できます。これらのページには、ミラー階層が構成されている場合の FabricPool ミラー情報も表示されます。

これらのページには、ローカルの高パフォーマンス階層とクラウド階層の使用可能容量、両方の階層で使用されている容量、クラウド階層に接続されているアグリゲート、 また、特定の情報をクラウド階層に移動することで FabricPool 機能を実装しているボリュームもあります。

クラウド階層が別のクラウドプロバイダ（「ミラー階層」）にミラーリングされている場合、両方のクラウド階層がアグリゲート / 健全性の詳細ページに表示されます。

.手順
. 次のいずれかを実行します。
+
[cols="2*"]
|===
| 容量の情報を表示するオブジェクト | 手順 


 a| 
クラスタ
 a| 
.. Capacity ： All Clusters ビューで、クラスタをクリックします。
.. クラスタ / ヘルスの詳細ページで、 * 構成 * タブをクリックします。
+
このクラスタが接続されているクラウド階層の名前が表示されます。





 a| 
アグリゲート
 a| 
.. Capacity ： All Aggregates ビューで、 Type フィールドに「 `S SD （ FabricPool ） ` 」または「 HDD （ FabricPool ）」と表示されているアグリゲートをクリックします。
.. アグリゲート / 健全性の詳細ページで、 * 容量 * タブをクリックします。
+
クラウド階層で使用されている合計容量が表示されます。

.. [ ディスク情報 ] タブをクリックします。
+
クラウド階層の名前と使用済み容量が表示されます。

.. [* 構成 *] タブをクリックします。
+
クラウド階層の名前とクラウド階層に関するその他の詳細情報が表示されます。





 a| 
個のボリューム
 a| 
.. Capacity ： All Volumes （容量：すべてのボリューム）ビューで、「 Tiering Policy 」（階層化ポリシー）フィールドにポリシー名が表示されているボリュームをクリックします。
.. [Volume/Health details] ページで、 [*Configuration*] タブをクリックします。
+
ボリュームに割り当てられている FabricPool 階層化ポリシーの名前が表示されます。



|===
. [* ワークロード分析 *] ページで、 [ 容量の傾向 *] 領域の [ クラウド階層ビュー ] を選択すると、前月のローカルパフォーマンス階層とクラウド階層で使用されている容量を確認できます。


FabricPool アグリゲートの詳細については、を参照してください https://docs.netapp.com/us-en/ontap/disks-aggregates/index.html["ディスクとアグリゲートの概要"]。
