---
permalink: health-checker/task_edit_individual_volume_health_threshold_settings.html 
sidebar: sidebar 
keywords: edit, individual, volume, health, threshold, settings 
summary: 1 つ以上のボリュームの容量、増加率、クォータ、およびスペースリザベーションについての健全性しきい値の設定を編集することができます。しきい値を超えるとアラートが生成され、通知が送信されます。これらの通知は、生成されたイベントに基づいて予防策を講じるのに役立ちます。 
---
= 個々のボリュームの健全性しきい値の設定を編集し
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
1 つ以上のボリュームの容量、増加率、クォータ、およびスペースリザベーションについての健全性しきい値の設定を編集することができます。しきい値を超えるとアラートが生成され、通知が送信されます。これらの通知は、生成されたイベントに基づいて予防策を講じるのに役立ちます。

.開始する前に
アプリケーション管理者またはストレージ管理者のロールが必要です。

しきい値の値を変更すると、次回の監視サイクルから、その値に基づいてイベントが生成または廃止されます。

ボリュームで自動拡張が有効になっている場合は、元のボリュームサイズではなく、自動拡張で設定された最大ボリュームサイズに基づいて、容量のしきい値を超えているかどうかが判定されることに注意してください。

[NOTE]
====
デフォルト値の 1000 は、 ONTAP のバージョンが 9.4 以降である FlexVol ボリューム、および ONTAP のバージョンが 9.8 以降である FlexGroup ボリュームにのみ適用されます。古いバージョンの ONTAP ソフトウェアがインストールされたクラスタの場合、ボリュームあたりの Snapshot コピーの最大数は 250 です。このような古いバージョンでは、 Unified Manager はこの数 1000 （および 1000 ~ 250 の任意の数）を 250 と解釈します。つまり、 Snapshot コピーの数が 250 に達してもイベントは引き続き受信します。これらの古いバージョンでこのしきい値を 250 未満に設定する場合は、しきい値を 250 以下に設定するか、 Health ： All Volumes ビューまたは Volume/Health details ページで設定する必要があります。

====
.手順
. 左側のナビゲーションペインで、 * Storage * > * Volumes * をクリックします。
. * 健全性：すべてのボリューム * 表示で、 1 つ以上のボリュームを選択し、 * しきい値の編集 * をクリックします。
. ボリュームしきい値の編集 * ダイアログボックスで、該当するチェックボックスを選択して値を変更し、容量、 Snapshot コピー、 qtree クォータ、増加率、または inode についてのしきい値の設定を編集します。
. [ 保存（ Save ） ] をクリックします。


* 関連情報 *

link:../config/task_add_users.html["ユーザを追加する"]
