---
permalink: health-checker/task_resolve_volume_offline_issues.html 
sidebar: sidebar 
keywords: resolve, volume, offline issues 
summary: このワークフローでは、 Unified Manager のイベント管理インベントリページに表示されるボリュームオフラインイベントを評価して解決する方法の例を示します。このシナリオでは、管理者が Unified Manager を使用してボリュームオフラインイベントをトラブルシューティングします。 
---
= ボリュームのオフライン状態の問題を解決する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
このワークフローでは、 Unified Manager のイベント管理インベントリページに表示されるボリュームオフラインイベントを評価して解決する方法の例を示します。このシナリオでは、管理者が Unified Manager を使用してボリュームオフラインイベントをトラブルシューティングします。

.開始する前に
オペレータ、アプリケーション管理者、またはストレージ管理者のロールが必要です。

ボリュームがオフライン状態と報告された場合は、いくつかの理由が考えられ

* SVM 管理者が意図的にボリュームをオフラインにした。
* ボリュームをホストしているクラスタノードが停止し、その HA ペアパートナーへのストレージフェイルオーバーも失敗した。
* ボリュームをホストしている SVM のルートボリュームをホストしているノードが停止したために、 SVM が停止した。
* 2 つの RAID ディスクで同時に障害が発生したために、ボリュームをホストしているアグリゲートが停止した。


イベント管理インベントリページおよびクラスタ / 健全性、 Storage VM / 健全性、およびボリューム / 健全性の詳細ページを使用して、これらの可能性を確認したり、それらを除外したりできます。

.手順
. 左側のナビゲーションペインで、 * イベント管理 * をクリックします。
. [ * イベント管理 * ] インベントリページで、 [ アクティブな可用性イベント * ] を選択します。
. 「ボリュームはオフライン」イベントのハイパーテキストリンクをクリックします。
+
可用性インシデントのイベント詳細ページが表示されます。

. このページで、 SVM 管理者が対象のボリュームをオフラインにしたことを示すメモがないか確認します。
. イベント * の詳細ページで、次のタスクの 1 つ以上に関する情報を確認できます。
+
** 原因（診断）フィールドに表示された情報を確認して、考えられる診断ガイダンスを確認します。
+
この例では、原因フィールドの情報から、ボリュームがオフラインであることのみがわかります。

** Notes and Updates 領域で、 SVM 管理者が該当のボリュームを意図的にオフラインにしたかどうかを確認します。
** イベントのソースをクリックすると、オフラインとして報告されるボリュームをクリックすると、そのボリュームに関する詳細情報が表示されます。
** イベントを管理者に割り当てます。
** イベントに応答するか、必要に応じて解決済みとしてマークします。



