---
permalink: health-checker/task_view_volume_list_and_details.html 
sidebar: sidebar 
keywords: view, volume list, details 
summary: Health ： All Volumes ビューでは、ボリュームのインベントリを監視できます。Capacity ： All Volumes ビューでは、クラスタ内のボリュームの容量と使用状況に関する情報を表示できます。 
---
= ボリュームリストおよび詳細を表示します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Health ： All Volumes ビューでは、ボリュームのインベントリを監視できます。Capacity ： All Volumes ビューでは、クラスタ内のボリュームの容量と使用状況に関する情報を表示できます。

* 必要なもの *

オペレータ、アプリケーション管理者、またはストレージ管理者のロールが必要です。

また、ボリューム / 健全性の詳細ページでは、ボリュームの容量、効率、設定、保護など、監視対象のボリュームに関する詳細情報を確認することもできます。また、特定のボリュームに関連するデバイスやアラートに関する情報も参照できます。

.手順
. 左側のナビゲーションペインで、 * Storage * > * Volumes * をクリックします。
. 次のいずれかの方法を選択してボリュームの詳細を表示します。
+
** クラスタ内のボリュームの健常性に関する詳細情報を表示するには、ビューメニューで健常性：すべてのボリュームビューを選択します。
** クラスタ内のボリュームの容量と使用状況に関する詳細情報を表示するには、表示メニューで容量：すべてのボリュームビューを選択します。
** すべての詳細を表示するには、ボリューム名をクリックします。
+
詳細を表示するには、 [ 最小詳細 ] ダイアログボックスの [ 詳細の表示 ] をクリックします。



. * オプション：最小限の詳細ダイアログボックスで * 関連項目を表示 * をクリックして、ボリュームに関連するオブジェクトを表示します。


* 関連情報 *

link:../reporting/task_create_report_to_view_available_volume_capacity_charts.html["使用可能なボリューム容量グラフを表示するレポートの作成"]
