---
permalink: health-checker/task_view_node_list_and_details.html 
sidebar: sidebar 
keywords: view, node list, details 
summary: Health ： All Nodes ビューを使用すると、クラスタ内のノードのリストを表示できます。クラスタ / 健全性の詳細ページを使用して、監視対象のクラスタに含まれるノードに関する詳細情報を表示できます。 
---
= ノードリストおよび詳細の表示
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Health ： All Nodes ビューを使用すると、クラスタ内のノードのリストを表示できます。クラスタ / 健全性の詳細ページを使用して、監視対象のクラスタに含まれるノードに関する詳細情報を表示できます。

.開始する前に
オペレータ、アプリケーション管理者、またはストレージ管理者のロールが必要です。

ノードの状態、ノードを含むクラスタ、アグリゲートの容量の詳細（使用容量と合計容量）、物理容量の詳細（使用可能な容量、スペア容量、合計容量）などの詳細情報を参照できます。HA ペア、ディスクシェルフ、およびポートに関する情報を取得することもできます。

.手順
. 左側のナビゲーションペインで、 * Storage * > * Nodes * をクリックします。
. [ * 正常性：すべてのノード * ] ビューで、詳細を表示するノードをクリックします。
+
選択したノードの詳細情報がクラスタ / 健全性の詳細ページに表示されます。左側のペインには、 HA ペアのリストが表示されます。デフォルトでは、 HA の詳細が表示され、選択した HA ペアに関連する HA 状態の詳細とイベントが表示されます。

. ノードに関するその他の詳細を表示するには、該当する操作を実行します。
+
[cols="2*"]
|===
| 表示する内容 | をクリックします 


 a| 
ディスクシェルフの詳細
 a| 
* ディスクシェルフ * ：



 a| 
ポート関連の情報
 a| 
* ポート * ：

|===


詳細については、を参照してください

* link:../performance-checker/performance-view-all.html#performance-all-nodes-view["Performance：All Nodesビュー"]
* link:../performance-checker/concept_view_node_and_aggregate_available_iops_values.html["ノードとアグリゲートの使用可能な IOPS の値の表示"]
* link:../performance-checker/concept_view_node_and_aggregate_performance_capacity_used_values.html["ノードとアグリゲートの使用済みパフォーマンス容量の値の表示"]

