---
permalink: install-vapp/concept_virtual_infrastructure_or_hardware_system_requirements.html 
sidebar: sidebar 
keywords: virtual, infrastructure, hardware, system, requirements, virtual appliance 
summary: 仮想インフラまたは物理システムに Unified Manager をインストールする場合、メモリ、 CPU 、およびディスクスペースの最小要件を満たす必要があります。 
---
= 仮想インフラおよびハードウェアシステムの要件
:icons: font
:imagesdir: ../media/


[role="lead"]
仮想インフラまたは物理システムに Unified Manager をインストールする場合、メモリ、 CPU 、およびディスクスペースの最小要件を満たす必要があります。

次の表に、メモリ、 CPU 、およびディスクスペースの各リソースについて、推奨される値を示します。これらは、 Unified Manager が許容されるパフォーマンスレベルを達成することが確認されている値です。

[cols="2*"]
|===
| ハードウェア構成 | 推奨設定 


 a| 
RAM
 a| 
12GB （最小要件は 8GB ）



 a| 
プロセッサ
 a| 
CPU × 4



 a| 
CPU サイクル容量
 a| 
合計 9572MHz （最小要件は 9572MHz ）



 a| 
空きディスク容量
 a| 
* 5GB （シンプロビジョニング）
* 152GB （シックプロビジョニング）


|===
Unified Manager はメモリの少ないシステムにもインストールできますが、推奨される 12GB の RAM があれば最適なパフォーマンスが保証されるだけでなく、拡張時にクラスタやストレージオブジェクトの追加にも対応できます。Unified Manager を導入する VM にはメモリの上限などを設定しないでください。また、ソフトウェアがシステムで割り当てられているメモリを利用できなくなる機能（バルーニングなど）は有効にしないでください。

また、 1 つの Unified Manager インスタンスで監視できるノードの数には上限があり、この上限を超える場合は 2 つ目の Unified Manager インスタンスをインストールする必要があります。詳細については、を参照してください link:http://www.netapp.com/us/media/tr-4621.pdf["Unified Manager ベストプラクティスガイド"]

メモリページのスワッピングは、システムや管理アプリケーションのパフォーマンスに悪影響を及ぼします。CPU リソースがホスト全体で競合して使用できなくなると、パフォーマンスが低下する可能性があります。



== 専用使用の要件

Unified Manager をインストールする物理システムまたは仮想システムは、他のアプリケーションとは共有せず、 Unified Manager 専用にする必要があります。他のアプリケーションにシステムリソースが消費されることで、 Unified Manager のパフォーマンスが大幅に低下する可能性があります。



== バックアップ用のスペース要件

Unified Manager のバックアップとリストア機能を使用する場合は、「 data 」ディレクトリまたはディスクに 150GB のスペースがあるように追加の容量を割り当ててください。バックアップはローカルにもリモートにも保存できますが、Unified Manager ホストシステムとは別の、 150GB 以上のスペースがあるリモートの場所に保存することを推奨します。



== ホスト接続の要件

Unified Manager をインストールする物理システムまたは仮想システムは、ホスト自体からホスト名への ping を実行できるように設定する必要があります。IPv6 構成の場合、 Unified Manager を正しくインストールするには、「 ping6 」によってホスト名に到達することを確認する必要があります。

製品の Web UI には、ホスト名（またはホストの IP アドレス）を使用してアクセスできます。導入時に静的 IP アドレスを使用してネットワークを設定した場合は、指定したネットワークホストの名前を使用します。DHCP を使用してネットワークを設定した場合は、 DNS からホスト名を取得します。

完全修飾ドメイン名（ FQDN ）または IP アドレスの代わりに短縮名を使用した Unified Manager へのアクセスをユーザに許可する場合は、短縮名が有効な FQDN に解決されるようにネットワークを設定する必要があります。

|===
|===