---
permalink: install-vapp/task_deploy_unified_manager_vapp.html 
sidebar: sidebar 
keywords: deploy, unified manager 
summary: Unified Manager を導入するには、ソフトウェアをダウンロードし、仮想アプライアンスを導入し、メンテナンスユーザを作成してユーザ名とパスワードを設定し、 Web UI で初期セットアップを行います。 
---
= Unified Manager を導入します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager を導入するには、ソフトウェアをダウンロードし、仮想アプライアンスを導入し、メンテナンスユーザを作成してユーザ名とパスワードを設定し、 Web UI で初期セットアップを行います。

* 必要なもの *

* 導入に必要なシステム要件を確認し、満たしておく必要があります。
+
を参照してください link:concept_requirements_for_installing_unified_manager.html["システム要件"]。

* 次の情報があることを確認します。
+
** ネットアップサポートサイトのログインクレデンシャル
** VMware vCenter Server および vSphere Web Client にアクセスするためのクレデンシャル
** Unified Manager 仮想アプライアンスを導入する ESXi サーバの IP アドレス
** データストアのストレージスペースやメモリ要件など、データセンターに関する詳細情報
** IPv6 アドレスを使用する場合は、ホストで IPv6 が有効になっている必要があります。




Unified Manager は、 VMware ESXi サーバに仮想アプライアンスとして導入できます。

メンテナンスコンソールには、 SSH ではなく、 VMware コンソールを使用してアクセスする必要があります。

[NOTE]
====
Unified Manager 9.8 以降では、 VMware Tools は Open VM Tools （「 open-vm-tools 」）に置き換えられています。「 open-vm-tools 」は Unified Manager インストールパッケージに含まれているため、インストールの一環として VMware Tools をインストールする必要はありません。

====
導入と初期セットアップが完了したら、クラスタを追加するかメンテナンスコンソールで追加のネットワーク設定を行ってから、 Web UI にアクセスできます。

.手順
. の手順に従います link:task_download_unified_manager_ova_file.html["Unified Manager をダウンロードします"]。
. また、の手順も実行します link:task_deploy_unified_manager_virtual_appliance_vapp.html["Unified Manager 仮想アプライアンスを導入します"]。

