---
permalink: install-windows/reference_protocol_and_port_requirements.html 
sidebar: sidebar 
keywords: unified manager, protocol, port, requirements 
summary: このポートとプロトコルを使用して、 Unified Manager サーバは管理対象のストレージシステム、サーバ、その他のコンポーネントと通信します。 
---
= プロトコルとポートの要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
このポートとプロトコルを使用して、 Unified Manager サーバは管理対象のストレージシステム、サーバ、その他のコンポーネントと通信します。



== Unified Manager サーバへの接続

通常の環境では、 Unified Manager Web UI への接続に常にデフォルトのポートが使用されるため、ポート番号を指定する必要はありません。たとえば、 Unified Manager は常にデフォルトのポートで実行されるため、「 + https://<host>:443+` 」ではなく「 + https://<host>+` 」と入力できます。

Unified Manager サーバでは、次のインターフェイスにアクセスする際に特定のプロトコルを使用します。

[cols="4*"]
|===
| インターフェイス | プロトコル | ポート | 説明 


 a| 
Unified Manager Web UI
 a| 
HTTP
 a| 
80
 a| 
Unified Manager Web UI へのアクセスに使用され、自動的にセキュアポート 443 にリダイレクトされます。



 a| 
Unified Manager Web UI および API を使用するプログラム
 a| 
HTTPS
 a| 
443
 a| 
Unified Manager Web UI へのセキュアなアクセスと API 呼び出しに使用されます。 API 呼び出しは HTTPS でしか実行できません。



 a| 
メンテナンスコンソール
 a| 
SSH/SFTP
 a| 
22
 a| 
メンテナンスコンソールにアクセスしてサポートバンドルを取得する際に使用されます。



 a| 
Linux コマンドライン
 a| 
SSH/SFTP
 a| 
22
 a| 
Red Hat Enterprise Linux または CentOS のコマンドラインにアクセスしてサポートバンドルを取得する際に使用されます。



 a| 
syslog
 a| 
UDP
 a| 
514
 a| 
ONTAP システムからのサブスクリプションベースの EMS メッセージにアクセスし、メッセージに基づいてイベントを作成する際に使用されます。



 a| 
REST
 a| 
HTTPS
 a| 
ポート 1
 a| 
認証された ONTAP システムからの REST API ベースのリアルタイムの EMS イベントにアクセスする際に使用されます。



 a| 
MySQL データベース
 a| 
MySQL
 a| 
3306
 a| 
OnCommand および OnCommand Workflow Automation API サービスから Unified Manager へのアクセスに使用されます。

|===
[NOTE]
====
MySQLのデフォルトポート3306は、WindowsシステムにUnified Managerをインストールする際にlocalhostにのみ使用できます。インストールが完了したら、ファイアウォールを有効にしてポートmysql（3306）へのアクセスを制限します。これは、前の構成を維持したままのアップグレードシナリオには影響しません。この設定は変更可能で、を使用して他のホストから接続を利用できるようにすることができます `Control access to MySQL port 3306` メンテナンスコンソールのオプション。詳細については、を参照してください link:../config/reference_additional_menu_options.html["その他のメニューオプション"]。HTTP 通信と HTTPS 通信に使用されるポート（ポート 80 と 443 ）は、 Unified Manager メンテナンスコンソールを使用して変更できます。詳細については、を参照してください link:../config/concept_configure_unified_manager.html["Active IQ Unified Manager を設定しています"]。

====


== Unified Manager サーバからの接続

ファイアウォールの設定で、 Unified Manager サーバと管理対象のストレージシステム、サーバ、その他のコンポーネントの間の通信に使用するポートを開くように設定する必要があります。ポートが開いていない場合、通信は失敗します。

環境に応じて、 Unified Manager サーバから特定の接続先への接続に使用するポートとプロトコルを変更することもできます。

Unified Manager サーバは、次のプロトコルとポートを使用して、管理対象のストレージシステム、サーバ、その他のコンポーネントに接続します。

[cols="4*"]
|===
| 宛先 | プロトコル | ポート | 説明 


 a| 
ストレージシステム
 a| 
HTTPS
 a| 
443 tcp
 a| 
ストレージシステムの監視と管理に使用されます。



 a| 
ストレージシステム
 a| 
NDMP
 a| 
10000 TCP
 a| 
特定の Snapshot リストア処理に使用されます。



 a| 
AutoSupport サーバ
 a| 
HTTPS
 a| 
443
 a| 
AutoSupport 情報の送信に使用されます。この機能を実行するには、インターネットアクセスが必要です。



 a| 
認証サーバ
 a| 
LDAP
 a| 
389
 a| 
認証要求、およびユーザとグループの検索要求に使用されます。



 a| 
LDAPS
 a| 
636
 a| 
セキュアな LDAP 通信に使用されます。



 a| 
メールサーバ
 a| 
SMTP
 a| 
25
 a| 
アラート通知 E メールの送信に使用されます。



 a| 
SNMP トラップの送信元
 a| 
SNMPv1 または SNMPv3
 a| 
162 UDP
 a| 
アラート通知 SNMP トラップの送信に使用されます



 a| 
外部データプロバイダのサーバ
 a| 
TCP
 a| 
2003 年
 a| 
Graphite などの外部データプロバイダにパフォーマンスデータを送信します。



 a| 
NTP サーバ
 a| 
NTP
 a| 
123 UDP
 a| 
Unified Manager サーバの時間を外部の NTP タイムサーバと同期するために使用します。（ VMware システムのみ）。

|===