---
permalink: install-windows/task_change_jboss_password_on_windows.html 
sidebar: sidebar 
keywords: change, jboss, password 
summary: インストール時に設定されたインスタンス固有の JBoss パスワードをリセットできます。このセキュリティ機能によって Unified Manager のインストール設定が上書きされてしまいます。必要に応じて、パスワードをリセットすることもできます。この処理を実行すると、 MySQL へのアクセス時に JBoss で使用するパスワードも変更になります。 
---
= JBoss パスワードを変更しています
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
インストール時に設定されたインスタンス固有の JBoss パスワードをリセットできます。このセキュリティ機能によって Unified Manager のインストール設定が上書きされてしまいます。必要に応じて、パスワードをリセットすることもできます。この処理を実行すると、 MySQL へのアクセス時に JBoss で使用するパスワードも変更になります。

* 必要なもの *

* Unified Manager がインストールされている Windows システムに対する admin 権限が必要です。
* MySQL の root ユーザのパスワードが必要です。
* ディレクトリにある、ネットアップが提供する「 password.bat 」スクリプトにアクセスできる必要があります
+
「 \Program Files\NetApp\essentials\bin 」にあります。



.手順
. Unified Manager ホストマシンに admin ユーザとしてログインします。
. Windows サービスコンソールを使用して、次の Unified Manager サービスを停止します。
+
** NetApp Active IQ 取得サービス（ Ocie-au ）
** NetApp Active IQ 管理サーバサービス（ Oncommandsvc ）


. 「 password.bat 」スクリプトを起動して、パスワード変更プロセスを開始します。
+
C ： \Program Files\NetApp\essentials\bin>password.bat resetJBossPassword

. プロンプトが表示されたら、 MySQL root ユーザのパスワードを入力します。
. プロンプトが表示されたら、新しい JBoss ユーザのパスワードを入力し、確認のためにもう一度入力します。
+
パスワードは 8~16 文字で指定し、数字、大文字、小文字、および次の特殊文字の少なくとも 1 文字を含める必要があります。

+
'+!@%^*-_+=[]:<> ？ /~+`

. スクリプトが完了したら、 Windows サービスコンソールを使用して Unified Manager サービスを開始します。
+
** NetApp Active IQ 管理サーバサービス（ Oncommandsvc ）
** NetApp Active IQ 取得サービス（ Ocie-au ）


. すべてのサービスが開始されたら、 Unified Manager UI にログインできます。

