---
permalink: install-windows/task_upgrade_openjdk_on_windows_ocum.html 
sidebar: sidebar 
keywords: openjdk, jre, upgrade 
summary: Unified Manager がインストールされている Windows サーバで OpenJDK を新しいバージョンにアップグレードすることで、セキュリティの脆弱性に対する修正を入手できます。 
---
= OpenJDK のアップグレード
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager がインストールされている Windows サーバで OpenJDK を新しいバージョンにアップグレードすることで、セキュリティの脆弱性に対する修正を入手できます。

* 必要なもの *

Unified Manager がインストールされている Windows システムに対する admin 権限が必要です。

OpenJDK のリリースはリリースファミリー内で更新できます。たとえば、 OpenJDK 11.0.9 から OpenJDK 11.0.12 にアップグレードできますが、 OpenJDK 11 から OpenJDK 12 に直接更新することはできません。

.手順
. Unified Manager ホストマシンに admin ユーザとしてログインします。
. OpenJDK の適切なバージョン（ 64 ビット）をターゲットシステムにダウンロードします。
+
たとえば、から「 openjdk-11_windows-x64_bin.zip 」をダウンロードします http://jdk.java.net/11/`[]。

. Windows サービスコンソールを使用して、次の Unified Manager サービスを停止します。
+
** NetApp Active IQ 取得サービス（ Ocie-au ）
** NetApp Active IQ 管理サーバサービス（ Oncommandsvc ）


. 「 zip 」ファイルを展開します。
. 作成された「 jdk' 」ディレクトリ ( たとえば「 jdk-11.0.12` 」 ) のディレクトリとファイルを Java がインストールされている場所にコピーします。例： C ： \Program Files\NetApp\JDK\`
. Windows サービスコンソールを使用して Unified Manager サービスを開始します。
+
** NetApp Active IQ 管理サーバサービス（ Oncommandsvc ）
** NetApp Active IQ 取得サービス（ Ocie-au ）



