---
permalink: config/concept_audit_logging.html 
sidebar: sidebar 
keywords: audit, logging 
summary: 監査ログを使用すると、監査ログが侵害されたかどうかを検出できます。ユーザが実行するすべてのアクティビティが監視され、監査ログに記録されます。監査は、 Active IQ Unified Manager のすべてのユーザーインターフェイスと公開されている API の機能に対して実行されます。 
---
= 監査ログ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
監査ログを使用すると、監査ログが侵害されたかどうかを検出できます。ユーザが実行するすべてのアクティビティが監視され、監査ログに記録されます。監査は、 Active IQ Unified Manager のすべてのユーザーインターフェイスと公開されている API の機能に対して実行されます。

監査ログ：ファイルビューを使用して、 Active IQ Unified Manager で使用可能なすべての監査ログファイルを表示したり、アクセスしたりできます。監査ログ：ファイルビュー内のファイルは、作成日に基づいて一覧表示されます。このビューには、インストール時またはシステム内のにアップグレードされたときにキャプチャされたすべての監査ログの情報が表示されます。Unified Manager で何らかの操作を実行すると、情報が更新され、ログに記録されます。各ログファイルのステータスは、ログファイルの改ざんや削除を検出するためにアクティブに監視される「 File Integrity Status 」属性を使用して取得されます。システムで監査ログが使用可能になると、監査ログの状態は次のいずれかになります。

[cols="2*"]
|===
| 状態 | 説明 


 a| 
アクティブ
 a| 
ログが現在ログに記録されているファイル。



 a| 
正常
 a| 
非アクティブで圧縮され、システムに格納されているファイル。



 a| 
改ざんされた
 a| 
手動でファイルを編集したユーザーによって侵害されたファイル。



 a| 
manual_delete_delete
 a| 
許可されたユーザーによって削除されたファイル。



 a| 
rollOver _ delete
 a| 
ローリング設定ポリシーに基づいて移動したために削除されたファイル。



 a| 
予期しない削除です
 a| 
不明な理由で削除されたファイル。

|===
Audit Log ページには、次のコマンドボタンがあります。

* 設定
* 削除
* ダウンロード


*delete* ボタンを使用すると、 Audit Logs ビューに表示されている監査ログを削除できます。監査ログを削除したり、ファイルを削除する理由を指定したりできます。これにより、あとで有効な削除を確認するのに役立ちます。理由列には、削除操作を実行したユーザの名前と理由が表示されます。

[NOTE]
====
ログファイルを削除すると、原因によってシステムからファイルが削除されますが、 DB テーブル内のエントリは削除されません。

====
監査ログは、監査ログセクションの * download * ボタンを使用して Active IQ Unified Manager からダウンロードし、監査ログファイルをエクスポートできます。「 normal 」または「 Tampered 」とマークされたファイルは、圧縮された「 .gzip` 形式でダウンロードされます。

フル AutoSupport バンドルの生成時に、サポートバンドルにはアーカイブされた監査ログファイルとアクティブな監査ログファイルの両方が含まれます。ただし、簡易サポートバンドルが生成されると、アクティブな監査ログのみが含まれます。アーカイブされた監査ログは含まれません。
