---
permalink: config/concept_policy_based_storage_management.html 
sidebar: sidebar 
keywords: slo, storage efficiency policy, storage workloads 
summary: ポリシーベースのストレージ管理オプションを使用すると、サービスレベル目標（ SLO ）に基づいてストレージを管理できます。このオプションはデフォルトで有効になっています。 
---
= ポリシーベースのストレージ管理の有効化
:icons: font
:imagesdir: ../media/


[role="lead"]
ポリシーベースのストレージ管理 * オプションを使用すると、サービスレベル目標（ SLO ）に基づいてストレージを管理できます。このオプションはデフォルトで有効になっています。

この機能をアクティブ化すると、 Active IQ Unified Manager インスタンスに追加された ONTAP クラスタのストレージワークロードをプロビジョニングし、割り当てられたパフォーマンスサービスレベルとストレージ効率化ポリシーに基づいてワークロードを管理できます。

この機能のアクティブ化または非アクティブ化は、 * General * > * Feature Settings * > * Policy-Based Storage Management * から選択できます。この機能をアクティブ化すると、次のページで操作と監視を行うことができます。

* プロビジョニング（ストレージワークロードのプロビジョニング）
* * ポリシー * > * パフォーマンスサービスレベル *
* * ポリシー * > * ストレージ効率化 *
* クラスタセットアップページのパフォーマンスサービスレベルで管理されるワークロードの列
* ダッシュボード上のワークロードのパフォーマンスパネル *


画面を使用して、パフォーマンスサービスレベルとストレージ効率化ポリシーを作成したり、ストレージワークロードをプロビジョニングしたりできます。割り当てられたパフォーマンスサービスレベルに準拠したストレージワークロードと準拠しないストレージワークロードを監視することもできます。ワークロードのパフォーマンスとワークロードの IOPS パネルでは、データセンター内のクラスタの合計容量、使用可能容量、使用済み容量、およびパフォーマンス（ IOPS ）を、プロビジョニングされたストレージワークロードに基づいて評価することもできます。

この機能をアクティブ化したら、 Unified Manager REST API を実行して、 * メニューバー * > * ヘルプボタン * > * API ドキュメント * > * ストレージプロバイダ * カテゴリからこれらの機能の一部を実行できます。また、ホスト名または IP アドレスと URL を + https://<hostname>/docs/api/+ の形式で入力して REST API ページにアクセスすることもできます

API の詳細については、 Active IQ Unified Manager API 開発者ガイドを参照してください。

link:../api-automation/concept_get_started_with_um_apis.html["Active IQ Unified Manager API 開発者ガイド"]
