---
permalink: config/reference_regenerate_https_certificate_dialog_box.html 
sidebar: sidebar 
keywords: regenerate, https certificate, dialog, box 
summary: HTTPS 証明書の再生成ダイアログボックスでは、セキュリティ情報をカスタマイズし、その情報を使用して新しい HTTPS 証明書を生成できます。 
---
= HTTPS 証明書の再生成ダイアログボックス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
HTTPS 証明書の再生成ダイアログボックスでは、セキュリティ情報をカスタマイズし、その情報を使用して新しい HTTPS 証明書を生成できます。

このページには現在の証明書の情報が表示されます。

[ 現在の証明書属性を使用して再生成 ] および [ 現在の証明書属性を更新 ] を選択すると ' 現在の情報で証明書を再生成するか ' 新しい情報で証明書を生成できます

* * 共通名 *
+
必須保護する対象の完全修飾ドメイン名（ FQDN ）。

+
Unified Manager のハイアベイラビリティ構成では、仮想 IP アドレスを使用します。

* * 電子メール *
+
任意。組織に問い合わせるための E メールアドレス。通常は、証明書管理者または IT 部門の E メールアドレスです。

* * 会社名 *
+
任意。通常は会社の法人名です。

* * 部門 *
+
任意。社内の部署の名前。

* * 都市 *
+
任意。会社の所在地の市区町村。

* * 状態 *
+
任意。会社の所在地の都道府県。

* * 国 *
+
任意。会社の所在地の国。通常は ISO の 2 文字の国コードです。

* * 別名 *
+
必須既存のローカルホストやその他のネットワークアドレスに加えて、このサーバへのアクセスに使用できるプライマリ以外のドメイン名が追加されました。代行名はそれぞれカンマで区切ります。

+
証明書の代替名フィールドからローカル識別情報を削除する場合は ' ローカル識別情報を除外 (localhost など ) チェックボックスをオンにしますこのチェックボックスをオンにすると、 [ 代替名 ] フィールドに入力したフィールドのみが使用されます。空白のままにすると、結果の証明書に代替名フィールドがまったく表示されなくなります。

* * キーサイズ（キーアルゴリズム： RSA ） *
+
キーアルゴリズムは rsa に設定されています。キーサイズは 2048 、 3072 、または 4096 のいずれかを選択できます。デフォルトのキー・サイズは 2048 ビットに設定されています。

* * 有効期間 *
+
デフォルトの有効期間は 397 日です。以前のバージョンからアップグレードした場合は、以前の証明書の有効性が変更されていない可能性があります。



詳細については、を参照してください link:../config/task_generate_an_https_security_certificate_ocf.html["HTTPS証明書の生成"]。
