---
permalink: config/reference_additional_menu_options.html 
sidebar: sidebar 
keywords: additional menu, options 
summary: 次に示すメニューオプションでは、 Unified Manager サーバでさまざまな管理タスクを実行することができます。 
---
= その他のメニューオプション
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
次に示すメニューオプションでは、 Unified Manager サーバでさまざまな管理タスクを実行することができます。

次のメニュー項目を選択できます。

* * サーバー証明書をリセット *
+
HTTPS サーバ証明書を再生成します。

+
Unified Manager の GUI でサーバ証明書を再生成します。そのためには、 * General * > * HTTPS Certificates * > * Regenerate HTTPS Certificate * をクリックします。

* * SAML 認証を無効にします *
+
SAML 認証を無効にし、 Unified Manager の GUI にアクセスするユーザのアイデンティティプロバイダ（ IdP ）によるサインオン認証を中止します。このコンソールオプションは、一般に、 IdP サーバまたは SAML の設定を使用する問題で Unified Manager の GUI へのアクセスがブロックされる場合に使用します。

* * 外部データプロバイダ *
+
Unified Manager を外部データプロバイダに接続するためのオプションを提供します。接続が確立されると、パフォーマンスデータが外部サーバに送信されて、ストレージパフォーマンスのエキスパートがサードパーティ製ソフトウェアを使用してパフォーマンス指標をグラフ化できるようになります。次のオプションが表示されます。

+
** *Display Server Configuration *-- 外部データプロバイダの現在の接続設定と構成設定を表示します
** * サーバー接続の追加 / 変更 *-- 外部データプロバイダの新しい接続設定を入力したり、既存の設定を変更したりすることができます。
** * Modify Server Configuration * -- 外部データプロバイダの新しい設定を入力したり、既存の設定を変更したりすることができます。
** *Delete Server Connection *-- 外部データプロバイダへの接続を削除します
+
接続を削除すると、 Unified Manager は外部サーバとの接続を失います。



* *バックアップの復元*
+
詳細については、のトピックを参照してください link:../health-checker/concept_manage_backup_and_restore_operations.html["バックアップとリストアの処理の管理"]。

* * パフォーマンスポーリング間隔の設定 *
+
Unified Manager がクラスタからパフォーマンス統計データを収集する頻度を設定するためのオプションを提供します。デフォルトの収集間隔は 5 分です。

+
大規模なクラスタからの収集が時間内に完了しない場合は、この間隔を 10 分または 15 分に変更できます。

* * アプリケーションポートの表示 / 変更 *
+
Unified Manager がセキュリティ上の理由から、 HTTP および HTTPS プロトコルに使用するデフォルトのポートを変更するオプションが用意されています。デフォルトのポートは、 HTTP の場合は 80 、 HTTPS の場合は 443 です。

* * MySQLポート3306 *へのアクセスを制御します
+
ホストからデフォルトのMySQLポート3306へのアクセスを制御します。セキュリティ上の理由から、このポート経由のアクセスは、Linux、Windows、およびVMware vSphereシステムへのUnified Managerの新規インストール時にlocalhostにのみ制限されます。このオプションを使用すると、ローカルホストとリモートホストの間でこのポートの表示/非表示を切り替えることができます。つまり、環境内のlocalhostに対してのみポートが有効になっている場合は、このポートをリモートホストでも使用できるようにすることができます。または、すべてのホストに対して有効にすると、このポートのアクセスをlocalhostのみに制限できます。アクセスがリモートホストで有効になっていた場合は、アップグレードシナリオで設定が保持されます。

* * 終了 *
+
メンテナンスコンソールメニューを終了します。


