---
section: config
title: 設定タスクと管理タスクを実行
entries:
- title: Active IQ Unified Manager を設定しています
  url: "/config/concept_configure_unified_manager.html"
  entries:
  - title: 設定手順の概要
    url: "/config/concept_overview_of_configuration_sequence.html"
  - title: Unified Manager Web UI にアクセスします
    url: "/config/task_access_unified_manager_web_ui.html"
  - title: Unified Manager Web UI の初期セットアップを実行する
    url: "/config/task_perform_initial_setup_of_unified_manager_web_ui.html"
  - title: クラスタを追加する
    url: "/config/task_add_clusters.html"
  - title: Unified Manager でアラート通知を送信するための設定
    url: "/config/task_configure_unified_manager_to_send_alert_notifications.html"
    entries:
    - title: イベント通知を設定しています
      url: "/config/task_configure_event_notification_settings.html"
    - title: リモート認証の有効化
      url: "/config/task_enable_remote_authentication.html"
    - title: リモート認証でのネストされたグループの無効化
      url: "/config/task_disable_nested_groups_from_remote_authentication.html"
    - title: 認証サービスをセットアップしています
      url: "/config/task_set_up_authentication_services.html"
    - title: 認証サーバを追加しています
      url: "/config/task_add_authentication_servers.html"
    - title: 認証サーバの設定をテストする
      url: "/config/task_test_configuration_of_authentication_servers_um_6_0.html"
    - title: アラートの追加
      url: "/config/task_add_alerts.html"
  - title: ローカルユーザのパスワードを変更しています
    url: "/config/task_change_local_user_password.html"
  - title: セッションの非アクティブ時のタイムアウト設定
    url: "/config/task_set_session_inactivity_timeout.html"
  - title: Unified Manager のホスト名を変更しています
    url: "/config/concept_change_unified_manager_host_name.html"
    entries:
    - title: Unified Manager 仮想アプライアンスのホスト名を変更する
      url: "/config/task_change_unified_manager_host_name_on_vmware.html"
      entries:
      - title: HTTPS セキュリティ証明書の生成
        url: "/config/task_generate_an_https_security_certificate_ocf.html"
      - title: Unified Manager 仮想マシンを再起動しています
        url: "/config/task_restart_unified_manager_virtual_machine.html"
    - title: Linux システムで Unified Manager ホスト名を変更する
      url: "/config/task_change_um_host_name_on_rhel_or_centos.html"
  - title: ポリシーベースのストレージ管理を有効または無効にします
    url: "/config/task_enable_and_disable_policy_based_storage_management.html"
- title: Unified Manager のバックアップを設定しています
  url: "/config/concept_configure_um_backup.html"
- title: 機能設定の管理
  url: "/config/concept_manage_feature_settings.html"
  entries:
  - title: ポリシーベースのストレージ管理の有効化
    url: "/config/concept_policy_based_storage_management.html"
  - title: API ゲートウェイを有効にしてい
    url: "/config/concept_api_gateway.html"
  - title: 非アクティブ時のタイムアウトの指定
    url: "/config/concept_inactivity_timeout.html"
  - title: Active IQ ポータルイベントの有効化
    url: "/config/concept_active_iq_platform_events.html"
  - title: 準拠のためのセキュリティ設定の有効化と無効化
    url: "/config/concept_security_dashboard.html"
  - title: スクリプトアップロードの有効化 / 無効化
    url: "/config/task_enable_and_disable_ability_to_upload_scripts.html"
  - title: ログインバナーを追加しています
    url: "/config/concept_login_banner.html"
- title: メンテナンスコンソールを使用する
  url: "/config/task_use_maintenance_console.html"
  entries:
  - title: メンテナンスコンソールで提供される機能
    url: "/config/concept_what_functionality_maintenance_console_provides.html"
  - title: メンテナンスユーザの役割
    url: "/config/concept_what_maintenance_user_does.html"
  - title: 診断ユーザの権限
    url: "/config/concept_what_diagnostic_user_does.html"
  - title: メンテナンスコンソールへのアクセス
    url: "/config/task_access_maintenance_console.html"
  - title: vSphere VM コンソールを使用してメンテナンスコンソールにアクセスする
    url: "/config/task_access_maintenance_console_using_vsphere.html"
  - title: メンテナンスコンソールのメニュー
    url: "/config/concept_maintenance_console_menu.html"
    entries:
    - title: Network Configuration （ネットワーク設定）メニュー
      url: "/config/reference_network_configuration_menu.html"
    - title: System Configuration （システム設定）メニュー
      url: "/config/reference_system_configuration_menu.html"
    - title: Support and Diagnostics （サポートと診断）メニュー
      url: "/config/reference_support_and_diagnostics_menu.html"
    - title: その他のメニューオプション
      url: "/config/reference_additional_menu_options.html"
  - title: Windows でメンテナンスユーザのパスワードを変更する
    url: "/config/task_change_maintenance_user_password_on_windows.html"
  - title: Linux システムでの umadmin パスワードの変更
    url: "/config/task_change_umadmin_password_on_rhel.html"
  - title: Unified Manager が HTTP および HTTPS プロトコルに使用するポートを変更する
    url: "/config/task_change_ports_um_uses_for_http_and_https_protocols.html"
  - title: ネットワークインターフェイスの追加
    url: "/config/task_add_additional_network_interfaces.html"
  - title: Unified Manager データベースディレクトリにディスクスペースを追加しています
    url: "/config/concept_add_disk_space_to_um_database_directory.html"
    entries:
    - title: Linux ホストのデータディレクトリにスペースを追加しています
      url: "/config/task_add_space_to_data_directory_of_um_linux_host.html"
    - title: VMware 仮想マシンのデータディスクにスペースを追加しています
      url: "/config/task_add_space_to_data_disk_of_vmware_virtual_machine.html"
    - title: Microsoft Windows サーバの論理ドライブにスペースを追加する
      url: "/config/task_add_space_to_data_disk_of_windows_server.html"
- title: ユーザアクセスの管理
  url: "/config/concept_manage_user_access.html"
  entries:
  - title: ユーザを追加する
    url: "/config/task_add_users.html"
    entries:
    - title: データベースユーザを作成しています
      url: "/config/task_create_database_user.html"
  - title: ユーザ設定の編集
    url: "/config/task_edit_user_setts.html"
  - title: ユーザの表示
    url: "/config/task_view_users.html"
  - title: ユーザまたはグループを削除する
    url: "/config/task_delete_users_or_groups.html"
  - title: RBAC とは
    url: "/config/concept_what_rbac_is.html"
  - title: ロールベースアクセス制御の機能
    url: "/config/concept_what_role_based_access_control_does.html"
  - title: ユーザタイプの定義
    url: "/config/reference_definitions_of_user_types.html"
  - title: ユーザロールの定義
    url: "/config/reference_definitions_of_user_roles.html"
  - title: Unified Manager のユーザロールと機能
    url: "/config/reference_unified_manager_roles_and_capabilities.html"
- title: SAML 認証の設定を管理する
  url: "/config/concept_manage_saml_authentication_settings_um.html"
  entries:
  - title: アイデンティティプロバイダの要件
    url: "/config/reference_identity_provider_requirements_um.html"
  - title: SAML 認証の有効化
    url: "/config/task_enable_saml_authentication_um.html"
  - title: SAML 認証に使用するアイデンティティプロバイダを変更する
    url: "/config/task_change_identity_provider_idp_used_for_saml_authentication.html"
  - title: Unified Manager セキュリティ証明書変更後に SAML 認証設定を更新しています
    url: "/config/task_update_saml_authentication_after_um_certificate_change.html"
  - title: SAML 認証を無効にします
    url: "/config/task_disable_saml_authentication_um.html"
  - title: メンテナンスコンソールから SAML 認証を無効にする
    url: "/config/task_disable_saml_authentication_from_maintenance_console_um.html"
  - title: SAML Authentication ページ
    url: "/config/reference_saml_authentication_page_um.html"
- title: 認証の管理
  url: "/config/concept_manage_authentication.html"
  entries:
  - title: 認証サーバを編集しています
    url: "/config/task_edit_authentication_servers.html"
  - title: 認証サーバを削除しています
    url: "/config/task_delete_authentication_servers.html"
  - title: Active Directory または OpenLDAP による認証
    url: "/config/concept_authentication_with_active_directory_or_openldap.html"
  - title: 監査ログ
    url: "/config/concept_audit_logging.html"
    entries:
    - title: 監査ログを設定しています
      url: "/config/task_configure_audit_logs.html"
    - title: 監査ログのリモートロギングを有効にする
      url: "/config/task_enable_remote_logging_of_audit_logs.html"
  - title: Remote Authentication ページの略
    url: "/config/reference_remote_authentication_page.html"
- title: セキュリティ証明書の管理
  url: "/config/concept_manage_security_certificates_ocf.html"
  entries:
  - title: HTTPS セキュリティ証明書の表示
    url: "/config/task_view_https_security_certificate_ocf.html"
  - title: HTTPS 証明書署名要求のダウンロード
    url: "/config/task_download_an_https_certificate_sign_request_ocf.html"
  - title: CA 署名済みで返された HTTPS 証明書をインストールする
    url: "/config/task_install_ca_signed_and_returned_https_certificate.html"
  - title: 外部ツールを使用して生成された HTTPS 証明書のインストール
    url: "/config/concept_install_https_certificate_generated_using_external_tools.html"
  - title: 証明書管理のページの説明
    url: "/config/concept_page_descriptions_for_certificate_management.html"
    entries:
    - title: HTTPS 証明書ページ
      url: "/config/reference_https_dialog_box_ocf.html"
    - title: HTTPS 証明書の再生成ダイアログボックス
      url: "/config/reference_regenerate_https_certificate_dialog_box.html"
