---
permalink: config/task_enable_remote_logging_of_audit_logs.html 
sidebar: sidebar 
keywords: enable, remote, logging, audit, logs 
summary: Configure Audit Logs ダイアログボックスの Enable Remote Logging チェックボックスをオンにして、リモート監査ロギングをイネーブルにできます。この機能を使用すると、監査ログをリモートの syslog サーバに転送できます。これにより、スペースに制約がある場合でも監査ログを管理できます。 
---
= 監査ログのリモートログ記録を有効にする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
監査ログの設定ダイアログ・ボックスのリモート・ログを有効にするチェックボックスをオンにすると ' リモート監査ログを有効にできますこの機能を使用すると、監査ログをリモートの syslog サーバに転送できます。これにより、スペースに制約がある場合でも監査ログを管理できます。

監査ログのリモートロギングは、 Active IQ Unified Manager サーバ上の監査ログファイルが改ざんされた場合に備えて、改ざんを防止するためのバックアップ機能を提供します。

.手順
. [ 監査ログの設定 *] ダイアログボックスで、 [ リモートログを有効にする *] チェックボックスをオンにします。
+
リモートロギングを設定するための追加フィールドが表示されます。

. 接続先のリモートサーバの * hostname * と * port * を入力します。
. サーバー CA 証明書 * フィールドで、 * 参照 * をクリックしてターゲットサーバーのパブリック証明書を選択します。
+
証明書は '.pem 形式でアップロードする必要がありますこの証明書は、ターゲットの syslog サーバから取得し、有効期限が切れていないことを確認する必要があります。証明書には、「 SAN 」属性の一部として選択した「ホスト名」が含まれている必要があります。

. 次のフィールドの値を入力します。 * charset* 、 * connection timeout * 、 * reconnection delay * 。
+
これらのフィールドの値はミリ秒単位で指定します。

. [*format*] フィールドと [*protocol*] フィールドで、必要な syslog 形式と TLS プロトコルのバージョンを選択します。
. ターゲット Syslog サーバーで証明書ベースの認証が必要な場合は、 * クライアント認証を有効にする * チェックボックスを選択します。
+
監査ログ設定を保存する前に、クライアント認証証明書をダウンロードして Syslog サーバにアップロードする必要があります。そうしないと、接続が失敗します。syslog サーバのタイプによっては、クライアント認証証明書のハッシュの作成が必要になる場合があります。

+
例： syslog-ng には、コマンド openssl x509 -noout -hash-in cert' を使用して証明書の <hash> を作成する必要があります。その後、クライアント認証証明書を <hash>.0 の後ろにあるファイルにシンボリックリンクする必要があります。

. サーバとの接続を設定し、リモートロギングを有効にするには、 * Save * をクリックします。
+
[ 監査ログ ] ページに移動します。

+
[NOTE]
====
[Connection Timeout]*の値は、設定に影響する可能性があります。設定が定義された値よりも応答に時間がかかると、接続エラーが原因で設定に失敗する可能性があります。正常な接続を確立するには、*[接続タイムアウト]*の値を増やして、設定をやり直してください。

====

