---
permalink: config/task_enable_and_disable_policy_based_storage_management.html 
sidebar: sidebar 
keywords: provisioning, performance service levels, storage management, enable, disable, policy-based 
summary: Unified Manager 9.7 以降では、 ONTAP クラスタにストレージワークロード（ボリュームと LUN ）をプロビジョニングし、割り当てられたパフォーマンスサービスレベルに基づいてワークロードを管理できます。この機能は ONTAP System Manager でワークロードを作成して QoS ポリシーを適用する処理に相当しますが、 Unified Manager を使用して適用した場合は、 Unified Manager インスタンスで監視しているすべてのクラスタのワークロードをプロビジョニングおよび管理できます。 
---
= ポリシーベースのストレージ管理を有効または無効にします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager 9.7 以降では、 ONTAP クラスタにストレージワークロード（ボリュームと LUN ）をプロビジョニングし、割り当てられたパフォーマンスサービスレベルに基づいてワークロードを管理できます。この機能は ONTAP System Manager でワークロードを作成して QoS ポリシーを適用する処理に相当しますが、 Unified Manager を使用して適用した場合は、 Unified Manager インスタンスで監視しているすべてのクラスタのワークロードをプロビジョニングおよび管理できます。

アプリケーション管理者のロールが必要です。

このオプションはデフォルトで有効になっていますが、 Unified Manager を使用してワークロードをプロビジョニングおよび管理しない場合は無効にできます。

このオプションを有効にすると、ユーザインターフェイスに新しい項目がいくつか追加されます。

[cols="2*"]
|===
| 新しいコンテンツ | 場所 


 a| 
新しいワークロードのプロビジョニングページ
 a| 
一般的なタスク * > * プロビジョニング * から使用できます



 a| 
パフォーマンスサービスレベルポリシーの作成ページ
 a| 
設定 * > * ポリシー * > * パフォーマンスサービスレベル * から選択できます



 a| 
パフォーマンスストレージ効率化ポリシーの作成ページ
 a| 
設定 * > * ポリシー * > * ストレージ効率化 * で確認できます



 a| 
現在のワークロードパフォーマンスとワークロード IOPS を表示するパネル
 a| 
ダッシュボードで確認できます

|===
これらのページおよびこの機能の詳細については、製品のオンラインヘルプを参照してください。

.手順
. 左側のナビゲーションペインで、 * 一般 * > * 機能設定 * をクリックします。
. [ 機能の設定 * ] ページで、次のいずれかのオプションを選択して、ポリシーベースのストレージ管理を無効または有効にします。
+
[cols="2*"]
|===
| 状況 | 操作 


 a| 
ポリシーベースのストレージ管理を無効にする
 a| 
ポリシーベースのストレージ管理 * パネルで、スライダボタンを左に動かします。



 a| 
ポリシーベースのストレージ管理を有効化
 a| 
ポリシーベースのストレージ管理 * パネルで、スライダボタンを右に動かします。

|===

