---
permalink: config/task_generate_an_https_security_certificate_ocf.html 
sidebar: sidebar 
keywords: generate, https, security, certificate 
summary: Active IQ Unified Manager を初めてインストールするときは、デフォルトの HTTPS 証明書がインストールされます。既存の証明書を置き換える新しい HTTPS セキュリティ証明書を生成することがあります。 
---
= HTTPS セキュリティ証明書の生成
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Manager を初めてインストールするときは、デフォルトの HTTPS 証明書がインストールされます。既存の証明書を置き換える新しい HTTPS セキュリティ証明書を生成することがあります。

* 必要なもの *

アプリケーション管理者のロールが必要です。

証明書を再生成する理由はいくつかあります。たとえば、識別名（ DN ）の値を大きくする場合や、キーのサイズを大きくする場合や、有効期限を延長する場合、現在の証明書の有効期限が切れている場合などです。

Unified Manager Web UI にアクセスできない場合は、メンテナンスコンソールを使用して同じ値で HTTPS 証明書を再生成できます。証明書を再生成する際には、キーのサイズと有効期間を定義できます。メンテナンスコンソールから [ サーバ証明書のリセット ] オプションを使用すると、 397 日間有効な新しい HTTPS 証明書が作成されます。この証明書には、サイズが 2048 ビットの RSA キーがあります。

.手順
. 左側のナビゲーションペインで、 * General * > * HTTPS Certificate * をクリックします。
. [* HTTPS 証明書の再生成 * ] をクリックします。
+
HTTPS 証明書の再生成ダイアログボックスが表示されます。

. 証明書を生成する方法に応じて、次のいずれかのオプションを選択します。
+
[cols="2*"]
|===
| 状況 | 手順 


 a| 
現在の値で証明書を再生成します
 a| 
[ 現在の証明書属性を使用して再生成（ Regenerate using current Certificate Attributes ） ] オプションをクリックし



 a| 
別の値を使用して証明書を生成します
 a| 
[ 現在の証明書属性を更新する *] オプションをクリックします。

新しい値を入力しない場合は、 [ 共通名 ] フィールドと [ 代替名 ] フィールドに既存の証明書の値が使用されます。「共通名」は、ホストの FQDN に設定する必要があります。その他のフィールドには値は必要ありませんが、電子メール、会社、部署、 証明書に値を入力する場合は、 [ 市区町村 ] 、 [ 都道府県 ] 、および [ 国 ] を選択します。使用可能なキー・サイズ（キー・アルゴリズムは「 RSA 」）と有効期間から選択することもできます。

[NOTE]
====
** キー・サイズに指定できる値は '2048'3072' および 4096 です
** 有効期間は、 1 日 ～ 最大 36500 日です。
+
有効期間は 36500 日ですが、有効期間は 397 日以内または 13 か月以内にすることをお勧めします。397 日以上の有効期間を選択し、この証明書の CSR をエクスポートして既知の CA によって署名された証明書を取得する予定であるため、 CA から返された署名済み証明書の有効性は 397 日に減少します。

** 証明書の代替名フィールドからローカル識別情報を削除する場合は、 ［ ローカル識別情報を除外する（ローカルホストなど） ］ チェックボックスをオンにします。このチェックボックスをオンにすると、 [ 代替名 ] フィールドに入力したフィールドのみが使用されます。空白のままにすると、結果の証明書に代替名フィールドがまったく表示されなくなります。


====
|===
. [ はい ] をクリックして証明書を再生成します。
. 新しい証明書を有効にするために Unified Manager サーバを再起動します。


HTTPS 証明書を表示して新しい証明書の情報を確認します。
