---
permalink: config/task_set_up_authentication_services.html 
sidebar: sidebar 
keywords: set up, authentication, services 
summary: 認証サービスを使用すると、 Unified Manager へのアクセスを許可する前に、リモートユーザまたはリモートグループを認証サーバで認証できます。事前定義された認証サービス（ Active Directory や OpenLDAP など）を使用するか、または独自の認証メカニズムを設定してユーザを認証できます。 
---
= 認証サービスをセットアップしています
:icons: font
:imagesdir: ../media/


[role="lead"]
認証サービスを使用すると、 Unified Manager へのアクセスを許可する前に、リモートユーザまたはリモートグループを認証サーバで認証できます。事前定義された認証サービス（ Active Directory や OpenLDAP など）を使用するか、または独自の認証メカニズムを設定してユーザを認証できます。

* 必要なもの *

* リモート認証を有効にしておく必要があります。
* アプリケーション管理者のロールが必要です。


.手順
. 左側のナビゲーションペインで、 * 一般 * > * リモート認証 * をクリックします。
. 次のいずれかの認証サービスを選択します。
+
[cols="2*"]
|===
| を選択した場合は | 操作 


 a| 
Active Directory
 a| 
.. 管理者の名前とパスワードを入力します。
.. 認証サーバのベース識別名を指定します。
+
たとえば、認証サーバのドメイン名が + ou@domain.com + である場合、ベース識別名は * cn=ou 、 dc=domain 、 dc=com * です。





 a| 
OpenLDAP
 a| 
.. バインド識別名とバインドパスワードを入力します。
.. 認証サーバのベース識別名を指定します。
+
たとえば、認証サーバのドメイン名が + ou@domain.com + である場合、ベース識別名は * cn=ou 、 dc=domain 、 dc=com * です。





 a| 
その他
 a| 
.. バインド識別名とバインドパスワードを入力します。
.. 認証サーバのベース識別名を指定します。
+
たとえば、認証サーバのドメイン名が + ou@domain.com + である場合、ベース識別名は * cn=ou 、 dc=domain 、 dc=com * です。

.. 認証サーバでサポートされている LDAP プロトコルのバージョンを指定します。
.. ユーザ名、グループメンバーシップ、ユーザグループ、およびメンバーの属性を入力します。


|===
+
[NOTE]
====
認証サービスを変更する場合は、既存の認証サーバを削除してから新しい認証サーバを追加する必要があります。

====
. [ 保存（ Save ） ] をクリックします。

