---
permalink: config/task_add_clusters.html 
sidebar: sidebar 
keywords: add cluster 
summary: Active IQ Unified Manager にクラスタを追加して監視することができます。たとえば、クラスタの健常性、容量、パフォーマンス、構成などの情報を取得して、発生する可能性がある問題を特定して解決できるようにすることができます。 
---
= クラスタを追加する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Manager にクラスタを追加して監視することができます。たとえば、クラスタの健常性、容量、パフォーマンス、構成などの情報を取得して、発生する可能性がある問題を特定して解決できるようにすることができます。

* 必要なもの *

* アプリケーション管理者またはストレージ管理者のロールが必要です。
* 次の情報が必要です。
+
** ホスト名またはクラスタ管理 IP アドレス
+
ホスト名は、 Unified Manager がクラスタへの接続に使用する FQDN または短縮名です。ホスト名は、クラスタ管理 IP アドレスに解決できる必要があります。

+
クラスタ管理 IP アドレスは、管理用 Storage Virtual Machine （ SVM ）のクラスタ管理 LIF である必要があります。ノード管理 LIF を使用すると処理に失敗します。

** クラスタで ONTAP バージョン 9.1 以降が実行されている必要があります。
** ONTAP 管理者のユーザ名とパスワード
+
このアカウントには、アプリケーションアクセスが_ontapi、_console_、および_http_に 設定された_admin_roleが必要です。

** HTTPS プロトコルを使用してクラスタに接続するポート番号（通常はポート 443 ）
** 必要な証明書を用意しておきます。Unified Managerでクラスタの追加時にセキュリティ証明書がインストールされます。
+
*サーバ証明書*：この証明書はUnified Managerが所有しています。デフォルトの自己署名SSL（HTTPS）証明書が生成され、Unified Managerの新規インストールが実行されます。セキュリティを強化するために、CA署名証明書にアップグレードすることを推奨します。サーバ証明書の有効期限が切れた場合は、再生成してUnified Managerを再起動し、サービスに新しい証明書を組み込む必要があります。SSL証明書の再生成の詳細については、を参照してください link:../config/task_generate_an_https_security_certificate_ocf.html["HTTPS セキュリティ証明書の生成"]。

+
*相互TLS通信証明書*：Unified ManagerとONTAP 間の相互TLS通信で使用されます。証明書ベースの認証は、ONTAP のバージョンに基づいてクラスタで有効になります。ONTAP バージョン9.5よりも前のバージョンを実行しているクラスタでは、証明書ベースの認証が有効になっていません。

+
古いバージョンのUnified ManagerをUnified Manager 9.12に更新する場合、クラスタの証明書ベースの認証は自動的には有効になりません。ただし、クラスタの詳細を変更して保存することで有効にできます。証明書の有効期限が切れた場合は、再生成して新しい証明書を組み込む必要があります。証明書の表示と再生成の詳細については、を参照してください link:../storage-mgmt/task_edit_clusters.html["クラスタを編集します"]。

+
[NOTE]
====
*** 証明書ベースの認証は、Web UIからクラスタを追加した場合に自動的に有効になります。メンテナンスコンソールからクラスタを追加した場合、証明書ベースの認証は有効になりません。
*** クラスタで証明書ベースの認証が有効になっている場合に、Unified Managerのバックアップをサーバから作成し、ホスト名またはIPアドレスが変更された別のUnified Managerサーバにリストアすると、クラスタの監視が失敗することがあります。エラーを回避するには、クラスタの詳細を編集して保存します。クラスタの詳細の編集の詳細については、を参照してください link:../storage-mgmt/task_edit_clusters.html["クラスタを編集します"]。


====
+
*クライアント証明書*：ONTAP から受信したEMSメッセージの認証時に使用されます。この証明書はONTAP が所有しており、ONTAP クラスタをUnified Managerに追加する場合に必要です。有効期限が切れた証明書で Unified Manager にクラスタを追加することはできません。クライアント証明書の期限が切れている場合は、クラスタを追加する前に再生成する必要があります。ただし、追加済みのクラスタの証明書の有効期限が切れて Unified Manager で使用されている場合は、 EMS メッセージが期限切れの証明書を使用して引き続き機能します。証明書の生成については、ナレッジベース（KB）の記事を参照してください https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_renew_an_SSL_certificate_in_ONTAP_9["System ManagerユーザインターフェイスでONTAP の自己署名証明書を更新する方法"^]。



* Unified Manager サーバに十分なスペースが必要です。データベースディレクトリのスペースの使用率が 90% を超えている場合、サーバにクラスタを追加することはできません。


MetroCluster 構成では、ローカルクラスタとリモートクラスタの両方を追加し、クラスタを正しく設定する必要があります。

.手順
. 左側のナビゲーションペインで、 * Storage Management * > * Cluster Setup * をクリックします。
. クラスタセットアップページで、 * 追加 * をクリックします。
. クラスタの追加ダイアログボックスで、クラスタのホスト名または IP アドレス、ユーザ名、パスワード、ポート番号など、必要な値を指定します。
+
クラスタ管理 IP アドレスは、 IPv6 から IPv4 または IPv4 から IPv6 に変更できます。次の監視サイクルが完了すると、クラスタグリッドとクラスタ設定ページに新しい IP アドレスが反映されます。

. [Submit （送信） ] をクリックします。
. [ ホストの許可 ] ダイアログボックスで、 [ 証明書の表示 *] をクリックして、クラスタに関する証明書情報を表示します。
. 「 * はい * 」をクリックします。
+
Unified Manager 9.12では、クラスタの詳細を保存したあと、クラスタの双方向TLS通信の証明書を確認できます。

+
証明書ベースの認証が有効になっていない場合、Unified Managerはクラスタが最初に追加されたときにのみ証明書をチェックします。Unified Manager では、 ONTAP に対する API 呼び出しごとには証明書がチェックされません。



新しいクラスタのオブジェクトがすべて検出されると、 Unified Manager が過去 15 日間の履歴パフォーマンスデータの収集を開始します。これらの統計は、データの継続性収集機能を使用して収集されます。この機能では、クラスタが追加された直後から 2 週間分のクラスタのパフォーマンス情報を入手できます。データの継続性収集サイクルの完了後、デフォルトではクラスタのリアルタイムのパフォーマンスデータが 5 分ごとに収集されます。

[NOTE]
====
15 日分のパフォーマンスデータを収集すると CPU に負荷がかかるため、新しいクラスタを複数追加する場合は、データの継続性収集のポーリングが同時に多数のクラスタで実行されないように、時間差をつけて追加するようにしてください。また、データの継続性収集期間に Unified Manager を再起動すると、収集が停止し、その間のデータがパフォーマンスチャートに表示されません。

====
[TIP]
====
エラーメッセージが表示されてクラスタを追加できない場合は、 2 つのシステムのクロックが同期されておらず、 Unified Manager の HTTPS 証明書の開始日がクラスタの日付よりもあとの日付になっていないかを確認してください。NTP などのサービスを使用してクロックを同期する必要があります。

====
* 関連情報 *

link:../config/task_install_ca_signed_and_returned_https_certificate.html#example-certificate-chain["CA 署名済みで返された HTTPS 証明書をインストールする"]
