---
permalink: config/task_configure_event_notification_settings.html 
sidebar: sidebar 
keywords: configure, event, notification, settings 
summary: Unified Manager では、イベントが生成されたときやユーザに割り当てられたときにアラート通知を送信するように設定することができます。アラートの送信に使用する SMTP サーバを設定したり、さまざまな通知メカニズムを設定したりできます。たとえば、アラート通知を E メールや SNMP トラップとして送信できます。 
---
= イベント通知を設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager では、イベントが生成されたときやユーザに割り当てられたときにアラート通知を送信するように設定することができます。アラートの送信に使用する SMTP サーバを設定したり、さまざまな通知メカニズムを設定したりできます。たとえば、アラート通知を E メールや SNMP トラップとして送信できます。

.開始する前に
次の情報が必要です。

* アラート通知の送信元 E メールアドレス
+
メール・アドレスは ' 送信されたアラート通知の送信元フィールドに表示されます何らかの理由で E メールを配信できない場合は、この E メールアドレスが配信不能メールの受信者としても使用されます。

* SMTP サーバのホスト名、およびサーバにアクセスするためのユーザ名とパスワード
* SNMP トラップと SNMP バージョン、アウトバウンドトラップポート、コミュニティ、およびその他の必要な SNMP 設定値を受信するトラップ送信先ホストのホスト名または IP アドレス
+
複数のトラップ送信先を指定するには、各ホストをカンマで区切ります。この場合、バージョンやアウトバウンドトラップポートなど、他の SNMP 設定はすべてリスト内のすべてのホストで同じでなければなりません。



アプリケーション管理者またはストレージ管理者のロールが必要です。

.手順
. 左側のナビゲーションペインで、 * 一般 * > * 通知 * をクリックします。
. 通知ページで、適切な設定を行います。
+
* 注： *

+
** 送信元アドレスに「 + ActiveIQUnifiedManager@localhost.com + 」というアドレスが事前に入力されている場合は、実際の作業用 E メールアドレスに変更して、すべての E メール通知が正常に配信されるようにしてください。
** SMTP サーバのホスト名を解決できない場合は、 SMTP サーバのホスト名の代わりに IP アドレス（ IPv4 または IPv6 ）を指定できます。


. [ 保存（ Save ） ] をクリックします。
. [*Use STARTTLS *]または[*Use SSL *]オプションを選択した場合は、[*Save]ボタンをクリックすると証明書ページが表示されます。証明書の詳細を確認し、証明書を受け入れて通知設定を保存します。
+
証明書の詳細を表示するには、[証明書の詳細を表示*]ボタンをクリックします。既存の証明書の有効期限が切れた場合は、「* STARTTLSを使用」または「* SSLを使用」チェックボックスをオフにし、通知設定を保存してから「* STARTTLSを使用*」または「SSLを使用*」チェックボックスを再度オンにして新しい証明書を表示します。


