---
permalink: config/task_install_ca_signed_and_returned_https_certificate.html 
sidebar: sidebar 
keywords: install, ca signed, returned, https, certificate 
summary: 認証局から署名を受けて返されたセキュリティ証明書を、アップロードしてインストールすることができます。アップロードしてインストールするファイルは、既存の自己署名証明書の署名済みバージョンである必要があります。CA 署名証明書は、中間者攻撃を阻止するのに役立ち、自己署名証明書よりも強力なセキュリティ保護を実現します。 
---
= CA 署名済みで返された HTTPS 証明書をインストールする
:icons: font
:imagesdir: ../media/


[role="lead"]
認証局から署名を受けて返されたセキュリティ証明書を、アップロードしてインストールすることができます。アップロードしてインストールするファイルは、既存の自己署名証明書の署名済みバージョンである必要があります。CA 署名証明書は、中間者攻撃を阻止するのに役立ち、自己署名証明書よりも強力なセキュリティ保護を実現します。

* 必要なもの *

次の作業を完了しておきます。

* 証明書署名要求ファイルをダウンロードし、認証局によって署名されています
* 証明書チェーンを PEM 形式で保存します
* チェーンに含まれるすべての証明書について、 Unified Manager サーバ証明書からルート署名証明書への中間証明書も含めます


アプリケーション管理者のロールが必要です。

[NOTE]
====
CSR 作成の証明書の有効期間が 397 日を超える場合、証明書の署名と返却の前に CA によって有効期間が 397 日に短縮されます

====
.手順
. 左側のナビゲーションペインで、 * General * > * HTTPS Certificate * をクリックします。
. ［ * HTTPS 証明書のインストール * ］ をクリックします。
. 表示されるダイアログボックスで、「 * ファイルを選択 ... * 」をクリックして、アップロードするファイルを探します。
. ファイルを選択し、 * Install * をクリックしてファイルをインストールします。
+
link:concept_install_https_certificate_generated_using_external_tools.html["外部ツールを使用して生成された HTTPS 証明書のインストール"]





== 証明書チェーンの例

証明書チェーンファイルの表示例を次に示します。

[listing]
----
-----BEGIN CERTIFICATE-----
<*Server certificate*>
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
<*Intermediate certificate \#1 (if present)*>
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
<*Intermediate certificate \#2 (if present)*>
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
<*Root signing certificate*>
-----END CERTIFICATE-----
----