---
permalink: config/task_change_identity_provider_idp_used_for_saml_authentication.html 
sidebar: sidebar 
keywords: change, identity, provider, used, saml, authentication 
summary: Unified Manager でリモートユーザの認証に使用するアイデンティティプロバイダ（ IdP ）を変更することができます。 
---
= SAML認証に使用するIDプロバイダーを変更する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager でリモートユーザの認証に使用するアイデンティティプロバイダ（ IdP ）を変更することができます。

.開始する前に
* IdP の URL とメタデータが必要です。
* IdP へのアクセスが必要です。


新しい IdP の設定は、 Unified Manager の設定前にも設定後にも実行できます。

.手順
. 左側のナビゲーションペインで、 * General * > * SAML Authentication * をクリックします。
. 新しい IdP の URI と Unified Manager サーバを IdP に接続するために必要な IdP メタデータを入力します。
+
Unified Manager サーバから IdP に直接アクセスできる場合は、 IdP の URL を入力したあとに「 * IdP メタデータの取得」ボタンをクリックすると、 IdP のメタデータフィールドに自動的に値が入力されます。

. Unified Manager のメタデータ URI をコピーするか、メタデータを XML テキストファイルに保存します。
. [ 構成の保存 *] をクリックします。
+
設定を変更するかどうかの確認を求めるメッセージボックスが表示されます。

. [OK] をクリックします。


新しい IdP にアクセスし、 Unified Manager サーバの URI とメタデータを入力して設定を完了します。

許可されたリモートユーザが Unified Manager のグラフィカルインターフェイスにアクセスする際にクレデンシャルを入力するページが、次回から古い IdP のログインページではなく新しい IdP のログインページに変わります。
