---
permalink: install-linux/qsg-linux.html 
sidebar: sidebar 
keywords: quick start guide, getting started, QSG, Linux QSG, RHEL QSG, quick installation 
summary: Linux プラットフォームでの Unified Manager のクイックスタートガイドです。 
---
= Linux インストールのクイックスタート手順
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Managerは、インストールパッケージをダウンロードして、Red Hat Enterprise Linuxの物理プラットフォームまたは仮想プラットフォームにインストールできます。



== システム要件

* オペレーティングシステム：x86_64アーキテクチャに基づくRed Hat Enterprise Linuxバージョン8.xおよび9.4。OSインストーラの* Software Selection *オプションから「Server with GUI」ベース環境を使用してインストールします。
* RAM ： 12 GB 、 CPU ：合計 9572MHz
* 空きディスク領域： /opt/NetApp/data ディレクトリに 100 GB のディスク領域、ルートパーティションに 50 GB 。個別にマウントされた '/opt/'/var/log' ディレクトリの場合は '/opt/'var/log' に 15 GB'/tmp に 10 GB の空き領域があることを確認してください


システム要件の詳細および製品をセキュリティ保護されたサイトにインストールする方法については、を参照してください link:../install-linux/concept_requirements_for_install_unified_manager.html["Unified Manager をインストールするための要件"] および link:http://mysupport.netapp.com/matrix["互換性マトリックス"]。



== Active IQ Unified Manager をインストールしています



=== インストーラをダウンロードします。

. をダウンロードします `ActiveIQUnifiedManager-<version>.zip` インストールパッケージとコード署名証明書 (`.pem`）およびデジタル署名 (`.sig`）。
. インストールファイルをダウンロードしたディレクトリで、次のコマンドを実行します。
+
#unzip ActiveIQUnifiedManager-< バージョン >.zip





=== 整合性を検証

次のコマンドを実行して、インストーラパッケージの整合性を確認します。

* を実行します `openssl x509 -pubkey -noout -in AIQUM-RHEL-CLIENT-INTER-ROOT.pem > <public_key_file_name>` コード署名証明書から公開鍵を使用してファイルを作成するには、次の手順を実行します。
* を実行します `openssl dgst -sha256 -verify <public_key_file_name> -signature <signature_file_name> ActiveIQUnifiedManager-<version>.zip` インストーラパッケージの署名を確認します。




=== リポジトリの構成を確認する

Red Hat Enterprise Linuxリポジトリの設定手順はサイトによって異なります。インストールパッケージに含まれているスクリプトを使用して、オペレーティングシステムの設定を確認できます `pre_install_check.sh`。システムがインターネットに接続されている場合は、Red Hat Enterprise Linuxリポジトリのセットアップ手順が自動的に表示されます。

#sudo ./pre_install_check.sh



=== Unified Manager をインストールします

Unified Managerでは、ユーティリティを使用して `yum`ソフトウェアとそれに依存するソフトウェアをインストールします。Red Hat Enterprise Linuxにはさまざまなイメージがあるため、インストールされるパッケージはイメージに含まれるソフトウェアによって異なります。 `yum`ユーティリティによって、インストールに必要な依存ソフトウェアパッケージが決定されます。依存するソフトウェアパッケージの詳細については、を参照してくださいlink:../install-linux/reference_red_hat_and_centos_software_and_installation_requirements.html["Linux ソフトウェアとインストールの要件"]。

Unified Manager をインストールするには、インストールファイルを解凍したディレクトリで、次のコマンドを root ユーザとして実行するか、「 sudo 」を使用して実行します。

yum install NetApp-um <version>.x86_64.rpm`

または

'%sudo yum install NetApp-um <version>.x86_64.rpm

インストールの完了時に、 Unified Manager Web UI に接続するための情報が表示されます。Web UI に接続できない場合は、ソフトウェアに同梱されている「 Reme 」ファイルを参照して、ポート 443 の制限についての詳細を確認してください。
