---
permalink: install-linux/reference_red_hat_software_and_installation_requirements.html 
sidebar: sidebar 
keywords: linux software, installation requirements, system, authorization,  requirements 
summary: Unified Manager をインストールする Linux システムには、特定のバージョンのオペレーティングシステムとサポートソフトウェアが必要です。 
---
= Linux ソフトウェアとインストールの要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager をインストールする Linux システムには、特定のバージョンのオペレーティングシステムとサポートソフトウェアが必要です。



== オペレーティングシステムソフトウェア

Linux システムに、次のバージョンのオペレーティングシステムとサポートソフトウェアがインストールされている必要があります。

* x86_64アーキテクチャに基づくRed Hat Enterprise Linuxバージョン8.xおよび9.6。


サポートされているRed Hat Enterprise Linuxのバージョンの最新のリストについては、Interoperability Matrixを参照してください。

http://mysupport.netapp.com/matrix["mysupport.netapp.com/matrix"^]

Unified Manager のみを実行する専用のサーバを用意する必要があります。他のアプリケーションをサーバにインストールしないでください。会社の規制により、Qualysのような脆弱性スキャナがLinuxシステムにインストールされている可能性があります。インストールが失敗しないようにするには、Unified Managerをインストールする前に脆弱性スキャナを無効にする必要があります。


NOTE: 脆弱性スキャナ（Qualysなど）を使用すると、内部（Unified Managerと脆弱性スキャナが同じVMにインストールされている場合）または外部で仮想マシン（VM）をスキャンする際にCPU使用率が高くなることがあります。 （Unified Managerと脆弱性スキャナが2つの異なるサーバにインストールされ、脆弱性スキャナがUnified ManagerがインストールされているVMをスキャンします）。この問題を実行すると、VMが応答しなくなり、Unified Managerサービスに影響することがよくあります。そのため、NetAppでは、Unified ManagerがインストールされているVMで脆弱性スキャナを無効にすることを推奨しています。スキャナを無効にできない場合は、営業時間外にVMをスキャンし、スキャンの完了後にサービスを再起動してください。



== サードパーティ製ソフトウェア

Unified Manager は WildFly Web サーバに導入されます。WildFly 26.1.3はUnified Managerにバンドルされ、設定されています。

次のサードパーティパッケージが必要ですが、 Unified Manager には含まれていません。これらのパッケージは ' インストール中に 'yum' インストーラによって自動的にインストールされますただし ' 次のセクションで説明するようにリポジトリを設定している必要があります

* MySQL Community Edition バージョン 8.4.4 (MySQL リポジトリから)
* OpenJDK バージョン 17.0.14+6 (Red Hat Extra Enterprise Linux Server リポジトリから)
* Python 3.12 (Red Hat Extra Enterprise Linux Server リポジトリから)
* p7zip バージョン 16.02 以降（ Red Hat Extra Packages for Enterprise Linux リポジトリから入手）


[NOTE]
====
サードパーティ製ソフトウェアをアップグレードする前に、 Unified Manager の実行中のインスタンスをシャットダウンする必要があります。サードパーティ製ソフトウェアのインストールが完了したら、 Unified Manager を再起動できます。

====


== ユーザ認証の要件

Linux システムへの Unified Manager のインストールは、 root ユーザに加え、「 sudo 」コマンドを使用すれば root 以外のユーザも実行できます。

また、Unified Managerのデフォルトのインストールでは、sudoersファイルと `ocie_sudoers` `/etc/sudoers.d/`ディレクトリにumadminユーザ（デフォルトのメンテナンスユーザ）とjbossユーザが含まれます(`ocum_sudoers`。セキュリティポリシーまたはセキュリティ監視ツールが原因でこのコンテンツを環境から削除した場合は、再度追加する必要があります。Unified Manager の一部の処理では sudo 権限が必要なため、 sudoers の設定を維持する必要があります。



== インストールの要件

Red Hat Enterprise Linuxと関連リポジトリをシステムにインストールする際のベストプラクティスを次に示します。別の方法でインストールまたは設定されたシステム、またはオフプレミス（クラウド）に導入されたシステムでは、追加の手順が必要になる場合があり、Unified Managerが適切に実行されない可能性があります。

* Red Hatのベストプラクティスに従ってRed Hat Enterprise Linuxをインストールし、次のデフォルトオプションを選択する必要があります。「GUIを使用するサーバ」ベース環境を選択する必要があります。
* Red Hat Enterprise LinuxへのUnified Managerのインストール中にインストールプログラムが必要なすべてのソフトウェアにアクセスしてインストールできるように、システムには該当するリポジトリへのアクセスが必要です。
* yum` インストーラが Red Hat Enterprise Linux リポジトリで依存するソフトウェアを見つけるためには、 Red Hat Enterprise Linux のインストール中またはインストール後に有効な Red Hat サブスクリプションを使用してシステムを登録しておく必要があります。
+
Red Hat Subscription Manager については、 Red Hat のドキュメントを参照してください。

* 必要なサードパーティユーティリティがシステムに正しくインストールされるように、 Extra Packages for Enterprise Linux （ EPEL ）リポジトリを有効にする必要があります。
+
システムで EPEL リポジトリが設定されていない場合は、リポジトリを手動でダウンロードして設定する必要があります。

+
を参照してください link:task_manually_configure_epel_repository.html["EPEL リポジトリを手動で設定します"]。

* 正しいバージョンの MySQL がインストールされていない場合は、システムに MySQL ソフトウェアが正しくインストールされるように MySQL リポジトリを有効にする必要があります。
+
システムで MySQL リポジトリが設定されていない場合は、リポジトリを手動でダウンロードして設定する必要があります。

+
を参照してください link:task_manually_configure_mysql_repository.html["MySQL リポジトリを手動で設定する"]。

* Unified Managerホストにインストールする必要があるJavaのバージョンは1つだけです。インストールしないと、使用するバージョンが特定できない可能性があります。を参照してください https://kb.netapp.com/data-mgmt/AIQUM/AIQUM_Kbs/After_updating_Java_on_the_Active_IQ_Unified_Manager_host_services_will_not_start["Active IQ Unified ManagerホストでJavaを更新したあとにサービスが開始されない"]


システムがインターネットに接続されておらず、インターネットに接続されたシステムからリポジトリがミラーリングされていない場合は、インストール手順に従って、システムに必要な外部ソフトウェアを確認してください。必要なソフトウェアをダウンロードしたら、インターネットに接続されたシステムにそのソフトウェアをダウンロードし、Unified Managerをインストールするシステムにファイルをコピーし `.rpm`ます。アーティファクトとパッケージをダウンロードするには、コマンドを使用する必要があります `yum install`。2つのシステムで同じバージョンのオペレーティングシステムを実行していること、および該当するRed Hat Enterprise Linuxのサブスクリプションライセンスがあることを確認する必要があります。

[NOTE]
====
必要なサードパーティ製ソフトウェアは、ここに記載されたリポジトリ以外からはインストールしないでください。Red Hat リポジトリからインストールされるソフトウェアは、 Red Hat Enterprise Linux 用に特別に設計されたものであり、 Red Hat のベストプラクティス（ディレクトリのレイアウトや権限など）に準拠しています。他の場所から入手したソフトウェアは必ずしもこれらのガイドラインに従っていないため、原因 Unified Manager のインストールに失敗したり、将来のアップグレードで原因の問題が発生したりする可能性があります。

====


== ポート 443 の要件

Red Hat Enterprise Linuxの汎用イメージでは、ポート443への外部アクセスがブロックされることがあります。そのため、Unified Managerのインストール後に管理者Web UIに接続できなくなることがあります。次のコマンドを実行すると、汎用Red Hat Enterprise Linux上のすべての外部ユーザとアプリケーションがポート443にアクセスできるようになります。

`#firewall-cmd --zone=public--add-port =443/tcp--permanent; firewall-cmd --reload`

Red Hat Enterprise Linuxは、「GUIを備えたサーバ」ベース環境でインストールする必要があります。Unified Managerのインストール手順で使用するコマンドを提供します。他のベース環境では、インストールを検証または完了するために追加のコマンドのインストールが必要になる場合があります。システムにがない場合は `firewall-cmd`、次のコマンドを実行してインストールする必要があります。

#sudo yum install firewalld`

コマンドを実行する前に IT 部門に問い合わせて、セキュリティポリシーで別の手順が必要かどうかを確認してください。

[NOTE]
====
Red Hatシステムでは、THP（Transparent Huge Pages）を無効にする必要があります。有効にすると、特定のプロセスがメモリを大量に消費して終了したときにUnified Managerがシャットダウンすることがあります。

====