---
permalink: install-linux/task_upgrade_unified_manager.html 
sidebar: sidebar 
keywords: upgrade, unified manager 
summary: Unified Manager をアップグレードするには、 Red Hat プラットフォームでインストールファイルをダウンロードして実行します。 
---
= Unified Manager をアップグレードする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Red HatプラットフォームでUnified Manager 9.9または9.10から9.11にアップグレードするには、インストールファイルをダウンロードして実行します。

* 必要なもの *

* Unified Manager をアップグレードするシステムがシステム要件とソフトウェア要件を満たしている必要があります。
+
link:concept_virtual_infrastructure_or_hardware_system_requirements.html["ハードウェアシステムの要件"]

+
link:reference_red_hat_and_centos_software_and_installation_requirements.html["Red Hat および CentOS のソフトウェアとインストールの要件"]

* Unified Manager をアップグレードする前に、適切なバージョンの OpenJDK をインストールするか、または適切なバージョンにアップグレードする必要があります。
+
link:task_upgrade_openjdk_on_linux_ocum.html["Linux での JRE のアップグレード"]

* Red Hat Enterprise Linux Subscription Manager への登録が必要です。
* アップグレード中に問題が使用される場合にデータが失われないようにするために、 Unified Manager データベースのバックアップを作成しておく必要があります。また、バックアップ・ファイルを「 /opt/NetApp/data 」ディレクトリから外部の場所に移動することをお勧めします。
* アップグレードの実行中に、パフォーマンスデータの保持期間について、以前のデフォルト設定である 13 カ月のままにするか 6 カ月に変更するかを確認するプロンプトが表示されることがあります。変更を確認すると、 6 カ月を過ぎた過去のパフォーマンスデータはパージされます。
* アップグレードプロセスの実行中は Unified Manager を使用できなくなるため、実行中の処理がある場合は完了しておいてください。
* MySQL Community Edition は、 Unified Manager のアップグレード時に自動的にアップグレードされます。システムにインストールされているMySQLのバージョンが8.0.28より前の場合は、Unified ManagerのアップグレードプロセスによってMySQLが自動的に8.0.28にアップグレードされます。


.手順
. ターゲットの Red Hat Enterprise Linux サーバまたは CentOS サーバにログインします。
. サーバに Unified Manager のバンドルをダウンロードします。
+
link:task_download_unified_manager.html["Red Hat または CentOS 版の Unified Manager のダウンロード"]

. ダウンロードしたディレクトリに移動し、 Unified Manager のバンドルを展開します。
+
'ActiveIQUnifiedManager-< バージョン >.zip を解凍します

+
Unified Manager に必要な RPM モジュールがターゲットディレクトリに解凍されます。

. ディレクトリに次のモジュールがあることを確認します。
+
ls *.rpm`

+
「 netapp - um <version>.x86_64.rpm 」

. * オプション：インターネットに接続されていないシステム、または Red Hat Enterprise Linux リポジトリを使用していないシステムの場合、次の手順を実行して、必要なパッケージが揃っていないかどうかを確認し、それらのパッケージをダウンロードします。
+
.. 各パッケージについてその有無を表示します。
+
yum`install NetApp-um <version> .x86_64.rpm -amiteno`

+
"Installing :`" セクションの項目は現在のディレクトリにあるパッケージで、 "Installing for dependencies ： " セクションの項目はシステムにないパッケージです。

.. インターネットにアクセスできる別のシステムで、次のコマンドを実行して不足しているパッケージをダウンロードします。
+
yum`install package_name --DownloadOnly --downloaddir=.`

+
パッケージは '--downloaddir=` として指定されたディレクトリにダウンロードされます

+
プラグイン「 yum-plugin-downloadonly 」は、 Red Hat Enterprise Linux システムで常に有効になっているとは限りません。インストールせずにパッケージをダウンロードするには、この機能を有効にする必要があります。

+
yum install yum-plugin-downloadonly を実行します

.. インストールシステムに新しいディレクトリを作成し、ダウンロードしたパッケージをインターネットに接続されたシステムからコピーします。
.. インストールシステムの新しいディレクトリにディレクトリを変更し、 MySQL Community Edition をインストールするための次のコマンドとその依存関係を実行します。
+
yum`install *.rpm`

.. Unified Manager サーバを起動します。次のコマンドを実行します。
+
'ystemctl start ocie

+
'systemctl start ocieau



. インストール前スクリプトを実行して、アップグレードと競合するシステム設定やインストール済みソフトウェアがないことを確認します。
+
'UDO./PRE_INSTALL_check.sh'

+
インストール前スクリプトは、システムに有効な Red Hat サブスクリプションがあること、および必要なソフトウェアリポジトリへのアクセス権があることを確認します。問題が検出された場合は、 Unified Manager をアップグレードする前に修正する必要があります。

. 次のスクリプトを使用して Unified Manager をアップグレードします。
+
「 upgrade.sh` 」

+
RPM モジュールが自動的に実行され、必要なサポートソフトウェアとそれらで実行されている Unified Manager モジュールがアップグレードされます。アップグレードと競合するシステム設定やインストール済みソフトウェアがないかどうかも確認されます。問題が検出された場合は、 Unified Manager をアップグレードする前に修正する必要があります。

. アップグレードが完了したら、メッセージを上にスクロールして、 Unified Manager Web UI の IP アドレスまたは URL 、メンテナンスユーザの名前（ umadmin ）、およびデフォルトのパスワードを確認します。
+
次のようなメッセージが表示されます。

+
[listing]
----
Active IQ Unified Manager upgraded successfully.
Use a web browser and one of the following URLs to access the Unified Manager GUI:

https://default_ip_address/    (if using IPv4)
https://[default_ip_address]/  (if using IPv6)
https://fully_qualified_domain_name/
----


サポートされている Web ブラウザに表示された IP アドレスまたは URL を入力して Unified Manager Web UI を起動し、前に設定したメンテナンスユーザの名前（ umadmin ）とパスワードを使用してログインします。
