---
permalink: install-linux/task_remove_unified_manager.html 
sidebar: sidebar 
keywords: remove, unified manager 
summary: Red Hat Enterprise LinuxホストからUnified Managerを停止およびアンインストールするには、1つのコマンドを使用します。 
---
= 統合マネージャーを削除する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Red Hat Enterprise LinuxホストからUnified Managerを停止およびアンインストールするには、1つのコマンドを使用します。

.開始する前に
* Unified Manager を削除するサーバへの root ユーザアクセスが必要です。
* LinuxシステムでSecurity-Enhanced Linux（SELinux）を無効にしておく必要があります。を使用して、SELinuxランタイムモードを「permissive」に変更します `setenforce 0` コマンドを実行します
* ソフトウェアを削除する前に、 Unified Manager サーバからすべてのクラスタ（データソース）を削除しておく必要があります。
* MySQLポート3306を許可またはブロックするために作成されたファイアウォールルールは手動で削除する必要があります。ファイアウォールルールは自動的には削除されません。


.手順
. Unified Manager を削除するサーバに root ユーザとしてログインします。
. Unified Manager を停止してサーバから削除します。
+
「 rpm -e NetApp-um 」を入力します

+
これにより、関連付けられているネットアップの RPM パッケージがすべて削除されます。Java 、 MySQL 、 p7zip など、前提条件のソフトウェアモジュールは削除されません。

. * オプション：必要に応じて、 Java 、 MySQL 、 p7zip などのサポートソフトウェアモジュールを削除します。
+
「 rpm -e p7zip mysql-community-client mysql-community-server mysql-community-common mysql-community-libs java-x.y 」のようになりました



この処理が完了すると、ソフトウェアは削除されます。アンインストール後 '/opt/NetApp/data' ディレクトリのすべてのデータは '/opt/NetApp/data/backup' フォルダに移動されますUnified Manager をアンインストールすると、 Java パッケージと MySQL パッケージも削除されます。ただし、パッケージが必要でシステム上の他のアプリケーションで使用されている場合は除きます。ただし、 MySQL のデータは削除されません。
