---
permalink: install-linux/task_download_unified_manager.html 
sidebar: sidebar 
keywords: download, Unified Manager 
summary: Unified Manager をインストールするには、 Unified Manager の .zip ファイルをネットアップサポートサイトからダウンロードする必要があります。 
---
= Unified Manager をダウンロードしています
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager をインストールするには、 Unified Manager の .zip ファイルをネットアップサポートサイトからダウンロードする必要があります。

* 必要なもの *

ネットアップサポートサイトのログインクレデンシャルが必要です。

ダウンロードする Unified Manager のインストールパッケージは、 Red Hat Enterprise Linux と CentOS の両方のシステムで共通です。

.手順
. ネットアップサポートサイトにログインし、 Unified Manager のダウンロードページに移動します。
+
https://["ネットアップサポートサイト"]

. 必要なバージョンの Unified Manager を選択し、エンドユーザライセンス契約（ EULA ）に同意します。
. Linux 用の Unified Manager インストーラファイルをダウンロードし、 .zip ファイルをターゲットシステムのディレクトリに保存します。
+
[NOTE]
====
** 使用している Red Hat Enterprise Linux システムに対応した正しいバージョンのインストーラファイルをダウンロードしていることを確認してください。Red Hat Enterprise Linux 7 と 8 のどちらをインストールしているかに基づいて、適切なバージョンの Unified Manager 「 .zip 」ファイルをダウンロードします。
** コード署名証明書をダウンロードすることを推奨します (`.pem`）およびデジタル署名 (`.sig`）をと共に使用します `.zip` ファイル。


====
. ダウンロードしたソフトウェアのチェックサムの整合性を確認します。
. コード署名証明書とデジタル署名をダウンロードした場合は、インストーラファイルの整合性を確認できます。インストーラファイルの整合性を確認するには、次のコマンドを使用します。
+
** このコマンドは、コード署名証明書から公開鍵を使用してファイルを作成します。
+
[listing]
----
openssl x509 -pubkey -noout -in AIQUM-RHEL-CLIENT-INTER-ROOT.pem > <public_key_file_name>
----
+
*** ここで、* AIQUM -RHEL-client-inter-root.pem *は、コード署名証明書を含むファイルです。


** このコマンドは、インストーラファイルの署名を検証します。
+
[listing]
----
openssl dgst -sha256 -verify <public_key_file_name> -signature <signature_file_name> ActiveIQUnifiedManager-<version>.zip
----
+
のようなメッセージが表示されます `Verified Ok` インストーラファイルが安全に使用できることを確認します。




