---
permalink: install-linux/task_manually_configure_mysql_repository.html 
sidebar: sidebar 
keywords: manually configure mysql repository, mysql key, keys update 
summary: Unified Manager をインストールするシステムが MySQL Community Edition リポジトリにアクセスできない場合、インストールが成功するためにはリポジトリを手動でダウンロードして設定する必要があります。 
---
= MySQL リポジトリを手動で設定する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager をインストールするシステムが MySQL Community Edition リポジトリにアクセスできない場合、インストールが成功するためにはリポジトリを手動でダウンロードして設定する必要があります。

MySQL リポジトリリポジトリリポジトリは、システムにインストールする必要がある MySQL ソフトウェアへのアクセスを提供します。

[NOTE]
====
このタスクは、システムがインターネットに接続されていないと失敗することがあります。Unified Managerをインストールするシステムがインターネットにアクセスできない場合は、MySQLのドキュメントを参照してください。

====
.手順
. インストールに対応する MySQL リポジトリをダウンロードします。Red Hat Enterprise Linux 7 の場合は、次のサイトからダウンロードしてください。
+
「 + wget 」と入力します http://repo.mysql.com/yum/mysql-8.0-community/el/7/x86_64/mysql80-community-release-el7-3.noarch.rpm+`[]

+
バージョン 8 については、次のサイトからダウンロードしてください。

+
「 + wget 」と入力します http://repo.mysql.com/yum/mysql-8.0-community/el/8/x86_64/mysql80-community-release-el8-1.noarch.rpm+`[]

. MySQL リポジトリを設定します。
+
yum `install mysqld80 -community-reley-<version>.noarch.rpm`



Red Hat Enterprise Linux 8 システムの場合、 AppStream リポジトリから提供される Java -11 openjdk 、 p7zip 、およびその他のソフトウェアパッケージを含む内部リポジトリがある場合、 AppStream リポジトリを無効にして MySQL Community Server をインストールする必要があります。次のコマンドを実行します。

[listing]
----
# sudo yum --disablerepo=rhel-8-for-x86_64-appstream-rpms install  mysql-community-server
----
キーまたはキーの不一致が見つからないというエラーが表示され、インストールが失敗した場合は、次の手順を実行してください。

* 接続されているシステムで、次のコマンドを実行して、更新されたMySQLキーをインポートします。


[listing]
----
rpm --import https://repo.mysql.com/RPM-GPG-KEY-mysql-<xxxx>

for example:

rpm --import https://repo.mysql.com/RPM-GPG-KEY-mysql-2022
----
* インターネットに接続されていないシステムでは'MySQLリポジトリファイルを更新し'gpgcheck=0とマークしてgpgcheckを無効にします

