---
permalink: install-linux/task_upgrade_unified_manager.html 
sidebar: sidebar 
keywords: upgrade, unified manager 
summary: Unified Managerをアップグレードするには、Linuxプラットフォームでインストールファイルをダウンロードして実行します。 
---
= Unified Manager をアップグレードする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
LinuxプラットフォームでUnified Manager 9.13または9.14から9.16にアップグレードするには、インストールファイルをダウンロードして実行します。

.開始する前に
* Unified Manager をアップグレードするシステムがシステム要件とソフトウェア要件を満たしている必要があります。
+
を参照してください link:concept_virtual_infrastructure_or_hardware_system_requirements.html["ハードウェアシステムの要件"]。

+
を参照して link:reference_red_hat_software_and_installation_requirements.html["Linux ソフトウェアとインストールの要件"]

* Red Hat Enterprise Linux Subscription Manager への登録が必要です。
* Unified Manager をアップグレードする前に、適切なバージョンの OpenJDK をインストールするか、または適切なバージョンにアップグレードする必要があります。
+
を参照してください link:task_upgrade_openjdk_on_linux_ocum.html["Linux での JRE のアップグレード"]。

* アップグレード中に問題が使用される場合にデータが失われないようにするために、 Unified Manager データベースのバックアップを作成しておく必要があります。ネットアップでは、からバックアップファイルを移動することを推奨します `/opt/netapp/data` ディレクトリを外部の場所に移動します。
* アップグレードの実行中に、パフォーマンスデータの保持期間について、以前のデフォルト設定である 13 カ月のままにするか 6 カ月に変更するかを確認するプロンプトが表示されることがあります。変更を確認すると、 6 カ月を過ぎた過去のパフォーマンスデータはパージされます。
* アップグレードプロセスの実行中は Unified Manager を使用できなくなるため、実行中の処理がある場合は完了しておいてください。
* MySQL Community Editionは、Unified Managerのアップグレード時に自動的にアップグレードされます。システムにインストールされている MySQL のバージョンが 8.4.4 より前の場合、Unified Manager のアップグレード プロセスによって MySQL は自動的に 8.4.4 にアップグレードされます。


.手順
. ターゲットのRed Hat Enterprise Linuxサーバにログインします。
. サーバに Unified Manager のバンドルをダウンロードします。
+
を参照してください link:task_download_unified_manager.html["Linux版Unified Managerをダウンロードしています"]。

. ダウンロードしたディレクトリに移動し、 Unified Manager のバンドルを展開します。
+
'ActiveIQUnifiedManager-< バージョン >.zip を解凍します

+
Unified Manager に必要な RPM モジュールがターゲットディレクトリに解凍されます。

. ディレクトリに次のモジュールがあることを確認します。
+
ls *.rpm`

+
「 netapp - um <version>.x86_64.rpm 」

. インストール前スクリプトを実行して、アップグレードと競合するシステム設定やインストール済みソフトウェアがないことを確認します。
+
'UDO./PRE_INSTALL_check.sh'

+
インストール前スクリプトは、システムに有効なRed Hat Enterprise Linuxサブスクリプションがあるかどうか、およびシステムが必要なソフトウェアリポジトリにアクセスできるかどうかを確認します。問題が検出された場合は、修正してアップグレードを続行する必要があります。

+
不足しているパッケージが検出された場合は、に記載されている手順を実行します link:../install-linux/task_upgrade_unified_manager.html#additional-steps-to-perform-for-missing-packages["不足しているパッケージに対して実行する追加手順"]。足りないパッケージがない場合は、次の手順に進みます。

. 次のスクリプトを使用して Unified Manager をアップグレードします。
+
「 upgrade.sh` 」

+
RPM モジュールが自動的に実行され、必要なサポートソフトウェアとそれらで実行されている Unified Manager モジュールがアップグレードされます。アップグレードと競合するシステム設定やインストール済みソフトウェアがないかどうかも確認されます。問題が検出された場合は、 Unified Manager をアップグレードする前に修正する必要があります。Unified Managerをアップグレードする前に_net-snmp_などのパッケージをインストールしていた場合は、MySQLの依存関係によってアップグレード中にパッケージがアンインストールされることがあります。引き続き使用するには、パッケージを手動で再度インストールする必要があります。

. アップグレードが完了したら、メッセージを上にスクロールして、 Unified Manager Web UI の IP アドレスまたは URL 、メンテナンスユーザの名前（ umadmin ）、およびデフォルトのパスワードを確認します。
+
次のようなメッセージが表示されます。

+
[listing]
----
Active IQ Unified Manager upgraded successfully.
Use a web browser and one of the following URLs to access the Unified Manager GUI:

https://default_ip_address/    (if using IPv4)
https://[default_ip_address]/  (if using IPv6)
https://fully_qualified_domain_name/
----


サポートされているWebブラウザの新しいウィンドウに表示されたIPアドレスまたはURLを入力してUnified Manager Web UIを起動し、前に設定したメンテナンスユーザの名前（umadmin）とパスワードを使用してログインします。



== 不足しているパッケージに対して実行する追加手順

アップグレード中にサイトで不足しているパッケージが検出された場合、またはシステムがインターネットに接続されていない場合、またはRed Hat Enterprise Linuxリポジトリを使用していない場合は、次の手順を実行して、必要なパッケージが揃っているかどうかを確認し、それらのパッケージをダウンロードします。


NOTE: これらの手順は、メイン手順 のstep_5_(ステップ5 )の後に実行する必要があります。この手順 アップグレードではUnified Managerがアップグレードされます。アップグレードのために追加の手順を実行する必要はありません。

. 各パッケージについてその有無を表示します。
+
yum`install NetApp-um <version> .x86_64.rpm -amiteno`

+
"Installing :`" セクションの項目は現在のディレクトリにあるパッケージで、 "Installing for dependencies ： " セクションの項目はシステムにないパッケージです。

. インターネットにアクセスできる別のシステムで、次のコマンドを実行して不足しているパッケージをダウンロードします。
+
yum`install package_name --DownloadOnly --downloaddir=.`

+
パッケージは '--downloaddir=` として指定されたディレクトリにダウンロードされます

+
プラグイン「 yum-plugin-downloadonly 」は、 Red Hat Enterprise Linux システムで常に有効になっているとは限りません。インストールせずにパッケージをダウンロードするには、この機能を有効にする必要があります。

+
yum install yum-plugin-downloadonly を実行します

. インストールシステムでUnified Managerのバンドルを解凍したディレクトリに、ダウンロードしたパッケージをコピーします。
. ディレクトリをそのディレクトリに変更し、次のコマンドを実行して欠落パッケージとその依存関係をインストールします。
+
yum`install *.rpm`

. Unified Manager サーバを起動します。次のコマンドを実行します。
+
'ystemctl start ocie

+
'systemctl start ocieau



これでUnified Managerのアップグレードプロセスは完了です。サポートされているWebブラウザの新しいウィンドウに表示されたIPアドレスまたはURLを入力してUnified Manager Web UIを起動し、前に設定したメンテナンスユーザの名前（umadmin）とパスワードを使用してログインします。
