---
permalink: install-linux/task_upgrade_mysql_on_linux.html 
sidebar: sidebar 
keywords: upgrade, mysql, linux 
summary: Unified Manager がインストールされている Linux サーバで MySQL を新しいバージョンにアップグレードすることで、セキュリティの脆弱性に対する修正を入手できます。 
---
= Linux での MySQL のアップグレード
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager がインストールされている Linux サーバで MySQL を新しいバージョンにアップグレードすることで、セキュリティの脆弱性に対する修正を入手できます。システムにインストールされている MySQL のバージョンが 8.0.17 より前の場合、 Unified Manager 9.10 のアップグレードプロセスによって MySQL が 8.0.17 に自動的にアップグレードされます。旧バージョンから 8.0.17 への MySQL のスタンドアロンアップグレードは実行しないでください。

* 必要なもの *

Unified Manager がインストールされている Linux システムに対する root 権限が必要です。

基本バージョンである MySQL 8.0.17 を新しいバージョンにアップグレードできるのは、マイナーアップデートのみが対象です。

.手順
. Unified Manager ホストマシンに root ユーザとしてログインします。
. ターゲット・システムに最新の MySQL Community Server の「 .rpm 」バンドルをダウンロードします。
. バンドルをターゲットシステム上のディレクトリに展開します。
. 展開したバンドルには複数の「 .rpm 」パッケージが含まれていますが、 Unified Manager で必要とされるのは次の rpm パッケージのみです。
+
** mysql-community-client-8.0.27 を参照してください
** mysql-community-libs-8.0.27 を参照してください
** mysql-community-server-8.0.27 を参照してください
** mysql-community-common-8.0.27 を参照してください
** mysql-community-client-plugins/8.0.27 その他すべてのパッケージを削除します。ただし、 rpm バンドル内のすべてのパッケージをインストールしても、原因エラーは発生しません。


. Unified Manager サービスと関連する MySQL ソフトウェアを次の順序で停止します。
+
'systemctl stop ocieau

+
'systemctl stop ocie

+
'systemctl stop mysqld

. 次のコマンドを使用して、 MySQL のアップグレードを実行します。
+
yum`install *.rpm`

+
*`.rpm` は MySQL の新しいバージョンをダウンロードしたディレクトリの '.rpm' パッケージを参照します

. Unified Manager を次の順序で開始します。
+
'ystemctl は mysqld' を起動します

+
'ystemctl start ocie

+
'systemctl start ocieau


