---
permalink: install-linux/task_change_jboss_password.html 
sidebar: sidebar 
keywords: change, jboss password 
summary: インストール時に設定されたインスタンス固有の JBoss パスワードをリセットできます。このセキュリティ機能によって Unified Manager のインストール設定が上書きされてしまいます。必要に応じて、パスワードをリセットすることもできます。この処理を実行すると、 MySQL へのアクセス時に JBoss で使用するパスワードも変更になります。 
---
= JBoss パスワードを変更しています
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
インストール時に設定されたインスタンス固有の JBoss パスワードをリセットできます。このセキュリティ機能によって Unified Manager のインストール設定が上書きされてしまいます。必要に応じて、パスワードをリセットすることもできます。この処理を実行すると、 MySQL へのアクセス時に JBoss で使用するパスワードも変更になります。

* Unified Manager がインストールされている Red Hat Enterprise Linux または CentOS のシステムへの root ユーザアクセスが必要です。
* ディレクトリ /opt/NetApp/essentials/bin' の中の 'password.sh' スクリプトにアクセスできる必要があります


.手順
. システムに root ユーザとしてログインします。
. 次のコマンドを記載された順序で入力して、 Unified Manager サービスを停止します。
+
'systemctl stop ocieau

+
'systemctl stop ocie

+
関連付けられている MySQL ソフトウェアは停止しないでください。

. 次のコマンドを入力して、パスワードの変更プロセスを開始します。
+
/opt/NetApp/essentials/bin/password.sh resetJBossPassword

. プロンプトが表示されたら、新しい JBoss パスワードを入力し、確認のためにもう一度入力します。
+
パスワードは 8~16 文字で指定し、数字、大文字、小文字、および次の特殊文字の少なくとも 1 文字を含める必要があります。

+
'+!@%^*-_+=[]:<> ？ /~+`

. スクリプトが完了したら、次のコマンドを記載された順序で入力して、 Unified Manager サービスを開始します。
+
'ystemctl start ocie

+
'systemctl start ocieau

. すべてのサービスが開始されたら、 Unified Manager UI にログインできます。

