---
permalink: install-linux/task_install_unified_manager_linux.html 
sidebar: sidebar 
keywords: install, unified manager 
summary: Unified Manager は、 Red Hat Enterprise Linux または CentOS の物理プラットフォームまたは仮想プラットフォームにインストールできます。 
---
= Unified Manager をインストールしています
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager は、 Red Hat Enterprise Linux または CentOS の物理プラットフォームまたは仮想プラットフォームにインストールできます。

* 必要なもの *

* Unified Manager をインストールするシステムがシステムおよびソフトウェアの要件を満たしている必要があります。
+
link:concept_virtual_infrastructure_or_hardware_system_requirements.html["ハードウェアシステムの要件"]

+
link:reference_red_hat_and_centos_software_and_installation_requirements.html["Red Hat および CentOS のソフトウェアとインストールの要件"]

* Unified Manager の .zip ファイルをネットアップサポートサイトからターゲットシステムにダウンロードしておく必要があります。
* サポートされている Web ブラウザが必要です。
* ターミナルエミュレーションソフトウェアでスクロールバックが有効になっている必要があります。


Red Hat Enterprise Linux または CentOS のシステムには、必要なサポートソフトウェア（ Java 、 MySQL 、追加ユーティリティ）のすべてのバージョンがインストールされているか、必要なソフトウェアの一部のみがインストールされているか、または新たにインストールしたシステムに必要なソフトウェアがインストールされていない可能性があります。

.手順
. Unified Manager をインストールするサーバにログインします。
. 該当するコマンドを入力し、インストールをサポートするためにターゲットシステムでインストールまたはアップグレードが必要なソフトウェアを特定します。
+
[cols="2*"]
|===
| 必要なソフトウェアと最小バージョン | ソフトウェアとバージョンを確認するコマンド 


 a| 
OpenJDKバージョン11.0.14
 a| 
「 java -version 」のように指定します



 a| 
MySQL 8.0.28 Community Editionの場合
 a| 
「 rpm -qa | grep -i mysql 」と入力します



 a| 
p7zip 16.02
 a| 
rpm -qa | grep p7zip

|===
. MySQL 8.0.28 Community Editionより前のバージョンのMySQLがインストールされている場合は、次のコマンドを入力してアンインストールします。
+
`rpm -e <mysql_package_name>`

+
依存関係エラーが発生した場合は '--nodeps' オプションを追加してコンポーネントをアンインストールする必要があります

. インストール用の「 .zip 」ファイルをダウンロードしたディレクトリに移動し、 Unified Manager のバンドルを展開します。
+
'ActiveIQUnifiedManager--_<version>_.zip を解凍します

+
Unified Manager に必要な「 .rpm 」モジュールがターゲットディレクトリに解凍されます。

. ディレクトリに次のモジュールがあることを確認します。
+
ls *.rpm`

+
「 netapp - um <version>.x86_64.rpm 」

. インストール前スクリプトを実行して、 Unified Manager のインストールと競合するシステム設定やインストール済みソフトウェアがないことを確認します。
+
'UDO./PRE_INSTALL_check.sh'

+
インストール前スクリプトは、システムに有効な Red Hat サブスクリプションがあること、および必要なソフトウェアリポジトリへのアクセス権があることを確認します。問題が検出された場合は、 Unified Manager をインストールする前に修正する必要があります。

+
Red Hat Enterprise Linux 8 システムの場合、 JDK 11-OpenJDK 、 p7zip 、その他の AppStream リポジトリが提供するソフトウェアパッケージを使用した内部リポジトリがある場合、 AppStream リポジトリを無効にして MySQL Community Server をインストールする必要があります。次のコマンドを実行します。

+
[listing]
----
# sudo yum --disablerepo=rhel-8-for-x86_64-appstream-rpms install  mysql-community-server
----
. * オプション： * システムがインターネットに接続されておらず、インストールに必要なパッケージを手動でダウンロードする必要がある場合にのみ、手順 7 を実行する必要があります。システムがインターネットにアクセス可能で、必要なすべてのパッケージがある場合は、ステップ 8 に進みます。システムがインターネットに接続されていない場合や Red Hat Enterprise Linux のリポジトリを使用していない場合は、次の手順に従って、必要なパッケージが揃っているかどうかを確認し、足りないパッケージをダウンロードします。
+
.. Unified Manager をインストールするシステムで、各パッケージについてその有無を表示します。
+
 `yum install netapp-um<version>.x86_64.rpm --assumeno`
+
"Installing :`" セクションの項目は現在のディレクトリにあるパッケージで、 "Installing for dependencies ： " セクションの項目はシステムにないパッケージです。

.. インターネットにアクセスできるシステムで、不足しているパッケージをダウンロードします。
+
yum`install <package_name> --DownloadOnly --downloaddir=.`

+
[NOTE]
====
yum-plugin-downloadonly プラグインは、 Red Hat Enterprise Linux システムで常に有効になっているとは限りません。インストールを実行せずにパッケージをダウンロードするために、「 yum install yum-plugin-downloadonly 」という機能を有効にする必要がある場合があります

====
.. インターネットに接続されたシステムからインストールシステムに不足しているパッケージをコピーします。


. root ユーザとして、または「 sudo 」を使用して、次のコマンドを実行してソフトウェアをインストールします。
+
yum 'install NetApp-um <version>.x86_64.rpm

+
このコマンドを実行すると、 .rpm パッケージ、必要な他のすべてのサポートソフトウェア、および Unified Manager ソフトウェアがインストールされます。

+
[NOTE]
====
他のコマンド（「 rpm -ivh 」など）を使用してインストールを試行しないでください。Unified Manager を Red Hat Enterprise Linux または CentOS のシステムに正しくインストールするには、 Unified Manager のすべてのファイルと関連ファイルを特定の順序で特定のディレクトリ構造にインストールする必要があり、そのためには「 yum install NetApp -um <version>.x86_64.rpm 」コマンドを使用する必要があります。

====
. インストールメッセージの直後に表示される E メール通知は無視してください。
+
この E メールは最初の cron ジョブの失敗を root ユーザに通知するもので、インストールには影響しません。

. インストールメッセージが最後まで表示されたら、メッセージを上にスクロールして、 Unified Manager Web UI の IP アドレスまたは URL 、メンテナンスユーザの名前（ umadmin ）、およびデフォルトのパスワードを確認します。
+
次のようなメッセージが表示されます。

+
[listing]
----
Active IQ Unified Manager installed successfully.
Use a web browser and one of the following URL(s) to configure and access the Unified Manager GUI.
https://default_ip_address/    (if using IPv4)
https://[default_ip_address]/  (if using IPv6)
https://fully_qualified_domain_name/

Log in to Unified Manager in a web browser by using following details:
  username: umadmin
  password: admin
----
. IP アドレスまたは URL 、割り当てられたユーザ名（ umadmin ）、および現在のパスワードをメモします。
. Unified Manager をインストールする前にカスタムのホームディレクトリで umadmin ユーザアカウントを作成していた場合は、 umadmin ユーザのログインシェルを指定する必要があります。
+
「 usermod -s /bin/maintenance-user-shell.sh umadmin 」のように設定します



の説明に従って、Web UIにアクセスしてumadminユーザのデフォルトパスワードを変更し、Unified Managerの初期セットアップを実行します link:../config/concept_configure_unified_manager.html["Active IQ Unified Manager を設定しています"]。
