---
permalink: events/reference_volume_events.html 
sidebar: sidebar 
keywords: volume, events, impact area, availability, capacity, configuration, performance 
summary: ボリュームイベントは、ボリュームのステータスに関する情報を提供します。これにより、潜在的な問題を監視できます。影響範囲別にイベントがまとめられ、イベント名、トラップ名、影響レベル、ソースタイプ、および重大度が表示されます。 
---
= ボリュームイベント
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ボリュームイベントは、ボリュームのステータスに関する情報を提供します。これにより、潜在的な問題を監視できます。影響範囲別にイベントがまとめられ、イベント名、トラップ名、影響レベル、ソースタイプ、および重大度が表示されます。

アスタリスク（ * ）は、 Unified Manager イベントに変換された EMS イベントを示します。



== 影響範囲：可用性

|===
| イベント名（トラップ名） | 影響レベル | ソースタイプ | 重大度 


 a| 
ボリュームが制限状態（ Document EvtVolumeRestricted ）
 a| 
リスク
 a| 
ボリューム
 a| 
警告



 a| 
ボリュームがオフライン（ Document EvtVolumeOffline ）
 a| 
インシデント
 a| 
ボリューム
 a| 
重要



 a| 
ボリュームは一部使用可能（ドキュメント別のボリューム）
 a| 
リスク
 a| 
ボリューム
 a| 
エラー



 a| 
ボリュームがアンマウントされています（該当なし）
 a| 
イベント
 a| 
ボリューム
 a| 
情報



 a| 
ボリュームをマウント（該当なし）
 a| 
イベント
 a| 
ボリューム
 a| 
情報



 a| 
ボリュームを再マウント（該当なし）
 a| 
イベント
 a| 
ボリューム
 a| 
情報



 a| 
ボリュームジャンクションパスが非アクティブ（ Document EvtVolumeFunctionPathInactive ）
 a| 
リスク
 a| 
ボリューム
 a| 
警告



 a| 
ボリュームのオートサイズを有効化（適用不可）
 a| 
イベント
 a| 
ボリューム
 a| 
情報



 a| 
ボリュームのオートサイズを無効化（該当なし）
 a| 
イベント
 a| 
ボリューム
 a| 
情報



 a| 
ボリュームのオートサイズの最大容量を変更（該当なし）
 a| 
イベント
 a| 
ボリューム
 a| 
情報



 a| 
ボリュームのオートサイズの増分サイズを変更（該当なし）
 a| 
イベント
 a| 
ボリューム
 a| 
情報

|===


== 影響範囲：容量

|===
| イベント名（トラップ名） | 影響レベル | ソースタイプ | 重大度 


 a| 
シンプロビジョニングボリュームにスペースリスク（文書化「シンプロビジョニング」の「ボリュームスペースリスク」）
 a| 
リスク
 a| 
ボリューム
 a| 
警告



 a| 
ボリューム効率化処理エラー（ocumEvtVolumeEfficiencyOperationError）
 a| 
リスク
 a| 
ボリューム
 a| 
エラー



 a| 
ボリュームスペースがフル（ Document EvtVolumeFull ）
 a| 
リスク
 a| 
ボリューム
 a| 
エラー



 a| 
ボリュームスペースがほぼフル（ Document EvtVolumeNearlyFull ）
 a| 
リスク
 a| 
ボリューム
 a| 
警告



 a| 
ボリューム論理スペースがフル * （ volumeLogicalSpaceFull ）
 a| 
リスク
 a| 
ボリューム
 a| 
エラー



 a| 
ボリューム論理スペースがほぼフル * （ volumeLogicalSpaceNearlyFull ）
 a| 
リスク
 a| 
ボリューム
 a| 
警告



 a| 
ボリューム論理スペースが正常 * （ volumeLogicalSpaceAllok ）
 a| 
イベント
 a| 
ボリューム
 a| 
情報



 a| 
ボリュームの Snapshot リザーブスペースがフル（ Document EvtSnapshotFull ）
 a| 
リスク
 a| 
ボリューム
 a| 
警告



 a| 
Snapshot コピーが多すぎる（ ocumentEvtSnapshotTooMany ）
 a| 
リスク
 a| 
ボリューム
 a| 
エラー



 a| 
ボリュームの qtree クォータがオーバーコミット（ Document EvtVolumeQtreeQuotaOvercommitted ）
 a| 
リスク
 a| 
ボリューム
 a| 
エラー



 a| 
ボリュームの qtree クォータがほぼオーバーコミット（ Document EvtVolumeQtreeQuotaAlmostOvercommitted ）
 a| 
リスク
 a| 
ボリューム
 a| 
警告



 a| 
ボリュームの増加率が異常（ Document EvtVolumeGrowthRateAbnormal ）
 a| 
リスク
 a| 
ボリューム
 a| 
警告



 a| 
ボリュームのフルまでの日数（ Document EvtVolumeDaysUntilFullSoon ）
 a| 
リスク
 a| 
ボリューム
 a| 
エラー



 a| 
ボリュームのスペースギャランティを無効化（該当なし）
 a| 
イベント
 a| 
ボリューム
 a| 
情報



 a| 
ボリュームのスペースギャランティを有効化（該当なし）
 a| 
イベント
 a| 
ボリューム
 a| 
情報



 a| 
ボリュームのスペースギャランティを変更（該当なし）
 a| 
イベント
 a| 
ボリューム
 a| 
情報



 a| 
ボリュームの Snapshot リザーブのフルまでの日数（ Document EvtVolumeSnapshotReserveDaysUntilFullSoon ）
 a| 
リスク
 a| 
ボリューム
 a| 
エラー



 a| 
FlexGroup コンスティチュエントのスペースに問題あり * （ flexGroupConstitutsHaveSpaceIssues ）
 a| 
リスク
 a| 
ボリューム
 a| 
エラー



 a| 
FlexGroup コンスティチュエントのスペースステータスがすべて正常 * （ flexGroupConstitutionsSpaceStatusAllOK ）
 a| 
イベント
 a| 
ボリューム
 a| 
情報



 a| 
FlexGroup コンスティチュエントの inode に関する問題 * （ flexGroupConstitutionsHaveInodesIssues ）
 a| 
リスク
 a| 
ボリューム
 a| 
エラー



 a| 
FlexGroup コンスティチュエント inode ステータスすべて OK * （ flexGroupConstitutionsInodesStatusAllOK ）
 a| 
イベント
 a| 
ボリューム
 a| 
情報



 a| 
WAFL ボリュームのオートサイズが失敗 * （ waflVolAutoSizeFail ）
 a| 
リスク
 a| 
ボリューム
 a| 
エラー



 a| 
WAFL ボリュームのオートサイズ完了 * （ waflVolAutoSizeDone ）
 a| 
イベント
 a| 
ボリューム
 a| 
情報



 a| 
FlexGroup ボリュームの使用率が 80% を超えています *
 a| 
インシデント
 a| 
ボリューム
 a| 
エラー



 a| 
FlexGroup ボリュームの使用率が 90% を超えています *
 a| 
インシデント
 a| 
ボリューム
 a| 
重要



 a| 
ボリュームのストレージ効率化に問題があります（ ocVolumeAbnormalStorageEfficency Warning ）
 a| 
リスク
 a| 
ボリューム
 a| 
警告



 a| 
利用率の低いボリュームのSnapshotリザーブ（volumeSnaphotReserveUnderutilizedWarning）
 a| 
イベント
 a| 
ボリューム
 a| 
警告



 a| 
ボリュームのSnapshotリザーブの利用率が低い（volumeSnaphotReserveUnderutilizedCleared）
 a| 
イベント
 a| 
ボリューム
 a| 
警告

|===


== 影響範囲：構成

|===
| イベント名（トラップ名） | 影響レベル | ソースタイプ | 重大度 


 a| 
ボリュームの名前を変更（該当なし）
 a| 
イベント
 a| 
ボリューム
 a| 
情報



 a| 
ボリュームを検出（該当なし）
 a| 
イベント
 a| 
ボリューム
 a| 
情報



 a| 
ボリュームが削除されました（該当なし）
 a| 
イベント
 a| 
ボリューム
 a| 
情報

|===


== 影響範囲：パフォーマンス

|===
| イベント名（トラップ名） | 影響レベル | ソースタイプ | 重大度 


 a| 
QoS ボリューム最大 IOPS の警告しきい値を超過（ドキュメントの QosVolumeMaxIopsWarning ）
 a| 
リスク
 a| 
ボリューム
 a| 
警告



 a| 
QoS ボリューム最大 MBps の警告しきい値を超過（ドキュメントの QosVolumeMaxMbpsWarning ）
 a| 
リスク
 a| 
ボリューム
 a| 
警告



 a| 
QoS ボリューム最大 IOPS/TB の警告しきい値を超過（ドキュメントの QosVolumeMaxIopsPerTbWarning ）
 a| 
リスク
 a| 
ボリューム
 a| 
警告



 a| 
パフォーマンスサービスレベルポリシーに定義されたワークロードのボリュームレイテンシしきい値を超過（ドキュメントのコンフォーマル遅延警告）
 a| 
リスク
 a| 
ボリューム
 a| 
警告



 a| 
ボリューム IOPS の重大しきい値を超過（ドキュメントボリューム IopsIncident ）
 a| 
インシデント
 a| 
ボリューム
 a| 
重要



 a| 
ボリューム IOPS の警告しきい値を超過（ドキュメントボリュームの IopsWarning ）
 a| 
リスク
 a| 
ボリューム
 a| 
警告



 a| 
ボリューム MBps の重大しきい値を超過（ドキュメントボリュームの MbpsIncident ）
 a| 
インシデント
 a| 
ボリューム
 a| 
重要



 a| 
ボリューム MBps の警告しきい値を超過（ドキュメントボリュームの警告）
 a| 
リスク
 a| 
ボリューム
 a| 
警告



 a| 
ボリュームレイテンシの重大しきい値を超過（ocumVolumeLatencyIncident）
 a| 
インシデント
 a| 
ボリューム
 a| 
重要



 a| 
ボリュームレイテンシの警告しきい値を超過（ocumVolumeLatencyWarning）
 a| 
リスク
 a| 
ボリューム
 a| 
警告



 a| 
ボリュームキャッシュミス率の重大しきい値を超過（ドキュメント VolumeCacheMissRatioIncident ）
 a| 
インシデント
 a| 
ボリューム
 a| 
重要



 a| 
ボリュームキャッシュミス率の警告しきい値を超過（ドキュメント VolumeCacheMissRatioWarning ）
 a| 
リスク
 a| 
ボリューム
 a| 
警告



 a| 
ボリュームレイテンシ / IOPS の重大しきい値を超過（ドキュメントボリュームレイテンシ / IOPS の重大しきい値を超過）
 a| 
インシデント
 a| 
ボリューム
 a| 
重要



 a| 
ボリュームレイテンシ / IOPS の警告しきい値を超過（ドキュメントボリュームレイテンシ / IOPS の警告）
 a| 
リスク
 a| 
ボリューム
 a| 
警告



 a| 
ボリュームレイテンシ / MBps の重大しきい値を超過（ドキュメントボリュームレイテンシ MbpsIncident ）
 a| 
インシデント
 a| 
ボリューム
 a| 
重要



 a| 
ボリュームレイテンシ / MBps の警告しきい値を超過（ドキュメントボリュームレイテンシ MbpsWarning ）
 a| 
リスク
 a| 
ボリューム
 a| 
警告



 a| 
ボリュームレイテンシ / アグリゲートの使用済みパフォーマンス容量の重大しきい値を超過（ ocVolumeLatencyAggregatePerfCapacityUsedIncident ）
 a| 
インシデント
 a| 
ボリューム
 a| 
重要



 a| 
ボリュームレイテンシ / アグリゲートの使用済みパフォーマンス容量の警告しきい値を超過（ ocVolumeLatencyAggregatePerfCapacityUsedWarning ）
 a| 
リスク
 a| 
ボリューム
 a| 
警告



 a| 
ボリュームレイテンシ / アグリゲート利用率の重大しきい値を超過（ ocVolumeLatencyAggregateUtilizationIncident ）
 a| 
インシデント
 a| 
ボリューム
 a| 
重要



 a| 
ボリュームレイテンシ / アグリゲート利用率の警告しきい値を超過（ Document VolumeLatencyAggregateUtilizationWarning ）
 a| 
リスク
 a| 
ボリューム
 a| 
警告



 a| 
ボリュームレイテンシ / ノードの使用済みパフォーマンス容量の重大しきい値を超過（文書 VolumeLatencyNodePerfCapacityUsedIncident ）
 a| 
インシデント
 a| 
ボリューム
 a| 
重要



 a| 
ボリュームレイテンシ / ノードの使用済みパフォーマンス容量の警告しきい値を超過（ ocVolumeLatencyNodePerfCapacityUsedWarning ）
 a| 
リスク
 a| 
ボリューム
 a| 
警告



 a| 
ボリュームレイテンシ / ノードの使用済みパフォーマンス容量 - テイクオーバーの重大しきい値を超過（文書 VolumeLatencyAggregatePerfCapacityUsedTakeoverIncident ）
 a| 
インシデント
 a| 
ボリューム
 a| 
重要



 a| 
ボリュームレイテンシ / ノードの使用済みパフォーマンス容量 - テイクオーバーの警告しきい値を超過（文書 VolumeLatencyAggregatePerfCapacityUsedTakeoverWarning ）
 a| 
リスク
 a| 
ボリューム
 a| 
警告



 a| 
ボリュームレイテンシ / ノード利用率の重大しきい値を超過（ドキュメント VolumeLatencyNodeUtilizationIncident ）
 a| 
インシデント
 a| 
ボリューム
 a| 
重要



 a| 
ボリュームレイテンシ / ノード利用率の警告しきい値を超過（ ocVolumeLatencyNodeUtilizationWarning ）
 a| 
リスク
 a| 
ボリューム
 a| 
警告

|===


== 影響範囲：セキュリティ

|===
| イベント名（トラップ名） | 影響レベル | ソースタイプ | 重大度 


 a| 
ボリュームのランサムウェア対策監視が有効（アクティブモード）（ antiRansomwareVolumeStateEnabled ）
 a| 
イベント
 a| 
ボリューム
 a| 
情報



 a| 
ボリュームのランサムウェア対策の監視が無効（ antiRansomwareVolumeStateDisabled ）
 a| 
リスク
 a| 
ボリューム
 a| 
警告



 a| 
ボリュームのランサムウェア対策監視が有効（ラーニングモード）（ antiRansomwareVolumeStateDryrun ）
 a| 
イベント
 a| 
ボリューム
 a| 
情報



 a| 
ボリュームのランサムウェア対策監視が一時停止（ラーニングモード）（ antiRansomwareVolumeStateDryrunPaused ）
 a| 
リスク
 a| 
ボリューム
 a| 
警告



 a| 
ボリュームのランサムウェア対策監視が一時停止（アクティブモード）（ antiRansomwareVolumeStateEnablePaused ）
 a| 
リスク
 a| 
ボリューム
 a| 
警告



 a| 
ボリュームのランサムウェア対策監視が無効化中（ antiRansomwareVolumeStateDisableInProgress ）
 a| 
リスク
 a| 
ボリューム
 a| 
警告



 a| 
ランサムウェア攻撃の発生（ callHomeRansomwareActivitySeen ）
 a| 
インシデント
 a| 
ボリューム
 a| 
重要



 a| 
ランサムウェア対策モニタリング（学習モード）に適したボリューム（ Document EvtVolumeArwCandidate ）
 a| 
イベント
 a| 
ボリューム
 a| 
情報



 a| 
ランサムウェア対策モニタリング（アクティブモード）に適したボリューム（ Document VolumeSuitedForActiveAntiRansomwareDetection ）
 a| 
リスク
 a| 
ボリューム
 a| 
警告



 a| 
ボリュームでランサムウェア対策によるアラートが発生する（ antiRansomwareFeatureNoisyVolume ）
 a| 
リスク
 a| 
ボリューム
 a| 
警告

|===


== 影響範囲：データ保護

|===
| イベント名（トラップ名） | 影響レベル | ソースタイプ | 重大度 


 a| 
ボリュームにローカルSnapshot保護が不十分です（volumeLacksLocalProtectionWarning）
 a| 
リスク
 a| 
ボリューム
 a| 
警告



 a| 
ボリュームにローカルSnapshot保護が不十分です（volumeLacksLocalProtectionCleared）
 a| 
リスク
 a| 
ボリューム
 a| 
警告

|===