---
permalink: events/reference_description_of_event_impact_areas.html 
sidebar: sidebar 
keywords: description, event, impact, areas 
summary: イベントは、 6 つの影響領域（可用性、容量、構成、パフォーマンス、保護、 および security ）を使用して、管理者が担当するタイプのイベントに集中できるようにします。 
---
= イベントの影響領域の概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
イベントは、 6 つの影響領域（可用性、容量、構成、パフォーマンス、保護、 および security ）を使用して、管理者が担当するタイプのイベントに集中できるようにします。

* * 利用可能性 *
+
可用性イベントは、ストレージオブジェクトがオフラインになった場合、プロトコルサービスが停止した場合、ストレージフェイルオーバーを実行した問題が発生した場合、ハードウェアで問題が実行された場合に通知するイベントです。

* * 容量 *
+
容量イベントは、アグリゲート、ボリューム、 LUN 、またはネームスペースのサイズがしきい値に近づいているか達した場合、または環境の通常の増加率とかけ離れている場合に通知するイベントです。

* * コンフィグレーション *
+
構成イベントは、ストレージオブジェクトの検出、削除、追加、または名前変更について通知するイベントです。構成イベントの影響レベルは「イベント」、重大度タイプは「情報」です。

* * パフォーマンス *
+
パフォーマンスイベントは、監視対象のストレージオブジェクトにおけるデータストレージの入力速度や取得速度に悪影響を及ぼす可能性がある、クラスタのリソース、設定、または処理の状況について通知するイベントです。

* * 保護 *
+
保護イベントは、 SnapMirror 関係に関するインシデントやリスク、デスティネーションの容量の問題、 SnapVault 関係の問題、または保護ジョブの問題について通知するイベントです。セカンダリボリュームおよび保護関係をホストする ONTAP オブジェクト（アグリゲート、ボリューム、および SVM ）は、いずれもこの影響領域に分類されます。

* * セキュリティ *
+
セキュリティイベントは、で定義されたパラメータに基づいて、 ONTAP クラスタ、 Storage Virtual Machine （ SVM ）、およびボリュームのセキュリティがどの程度確保されるかを通知します http://["『 ONTAP 9 セキュリティ設定ガイド』"]。

+
また、この領域には、 Active IQ プラットフォームから報告されるアップグレードイベントも含まれます。


