---
permalink: events/reference_what_suggested_actions_section_displays.html 
sidebar: sidebar 
keywords: suggest, actions, section, displays 
summary: '[ イベントの詳細 ] ページの [ 提案されたアクション ] セクションには、イベントの考えられる理由が表示され、独自の方法でイベントを解決できるようにいくつかのアクションが提案されます。推奨される対処方法は、イベントのタイプまたは超過したしきい値のタイプに基づいてカスタマイズされます。' 
---
= [ 提案されたアクション ] セクションの表示内容
:icons: font
:imagesdir: ../media/


[role="lead"]
[ イベントの詳細 ] ページの [ 提案されたアクション ] セクションには、イベントの考えられる理由が表示され、独自の方法でイベントを解決できるようにいくつかのアクションが提案されます。推奨される対処方法は、イベントのタイプまたは超過したしきい値のタイプに基づいてカスタマイズされます。

この領域は、一部のタイプのイベントに対してのみ表示されます。

特定のアクションを実行するための手順など、推奨される多くのアクションについて追加情報を参照する * Help * リンクがページに表示される場合があります。一部の対処方法では、 Unified Manager 、 ONTAP System Manager 、 OnCommand Workflow Automation 、 ONTAP CLI コマンド、またはこれらのツールの組み合わせを使用する場合があります。

これらの推奨される対処方法は、このイベントを解決するための一般的なガイダンスであることに注意してください。このイベントを解決するための対処方法は、環境に応じて決める必要があります。

オブジェクトやイベントを詳しく分析するには、 * ワークロードの分析 * ボタンをクリックしてワークロードの分析ページを表示します。

イベントによっては、 Unified Manager の詳細な診断によって 1 つの解決策が提供されることがあります。解決策がある場合は、 * Fix it * ボタンで表示されます。このボタンをクリックすると、 Unified Manager によってイベントの原因となっている問題が修正されます。

Active IQ プラットフォームイベントの場合、問題と解決策について解説したネットアップのナレッジベースの記事へのリンクがこのセクションに表示されることがあります。外部ネットワークへのアクセスがないサイトでは、ナレッジベースの記事の PDF がローカルで開きます。この PDF は、 Unified Manager インスタンスに手動でダウンロードしたルールファイルに含まれています。
