---
permalink: events/reference_cluster_events.html 
sidebar: sidebar 
keywords: cluster events, impact, area, availability, capacity, configuration, performance, security 
summary: クラスタイベントは、クラスタのステータスに関する情報を提供します。これにより、クラスタの潜在的な問題を監視できます。影響範囲別にイベントがまとめられ、イベント名、トラップ名、影響レベル、ソースタイプ、および重大度が表示されます。 
---
= クラスタイベント
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クラスタイベントは、クラスタのステータスに関する情報を提供します。これにより、クラスタの潜在的な問題を監視できます。影響範囲別にイベントがまとめられ、イベント名、トラップ名、影響レベル、ソースタイプ、および重大度が表示されます。



== 影響範囲：可用性

アスタリスク（ * ）は、 Unified Manager イベントに変換された EMS イベントを示します。

|===
| イベント名（トラップ名） | 影響レベル | ソースタイプ | 重大度 


 a| 
クラスタにスペアディスクなし（ Document EvtDisksNoSpares ）
 a| 
リスク
 a| 
クラスタ
 a| 
警告



 a| 
クラスタに到達できません（ Document EvtClusterUnreachable ）
 a| 
リスク
 a| 
クラスタ
 a| 
エラー



 a| 
クラスタの監視に失敗しました（ Document EvtClusterMonitoringFailed ）
 a| 
リスク
 a| 
クラスタ
 a| 
警告



 a| 
クラスタの FabricPool ライセンス容量制限を超過（ Document EvtExternalCapacityTierSpaceFull ）
 a| 
リスク
 a| 
クラスタ
 a| 
警告



 a| 
NVMF の猶予期間 - 開始 * （ nvmetfGracePeriodStart ）
 a| 
リスク
 a| 
クラスタ
 a| 
警告



 a| 
NVMF の猶予期間 - アクティブ * （ nvmetfGracePeriodActive ）
 a| 
リスク
 a| 
クラスタ
 a| 
警告



 a| 
NVMF の猶予期間 - 終了 * （ nvmetfGracePeriodExpired ）
 a| 
リスク
 a| 
クラスタ
 a| 
警告



 a| 
オブジェクトのメンテナンス時間が開始されました (objectMaintenanceWindowStarted)
 a| 
イベント
 a| 
クラスタ
 a| 
重要



 a| 
オブジェクトのメンテナンス時間が終了しました（ objectMaintenanceWindowEnded ）
 a| 
イベント
 a| 
クラスタ
 a| 
情報



 a| 
MetroCluster のスペアディスクが残されている（ ocument EvtSpareDiskLeftBehind ）
 a| 
リスク
 a| 
クラスタ
 a| 
エラー



 a| 
MetroCluster の自動計画外スイッチオーバーが無効（ Document EvtMccAutomaticUnplannedSwitchOverDisabled ）
 a| 
リスク
 a| 
クラスタ
 a| 
警告



 a| 
クラスタユーザパスワードが変更されました * （ cluster.passwd.changed ）
 a| 
イベント
 a| 
クラスタ
 a| 
情報

|===


== 影響範囲：容量

|===
| イベント名（トラップ名） | 影響レベル | ソースタイプ | 重大度 


 a| 
クラスタ容量の不均衡しきい値を超過（ドキュメント「 ConformanceNodeImbalanceWarning 」）
 a| 
リスク
 a| 
クラスタ
 a| 
警告



 a| 
クラスタのクラウド階層の計画（ clusterCloudTierPlaningWarning ）
 a| 
リスク
 a| 
クラスタ
 a| 
警告



 a| 
FabricPool ミラーレプリケーションの再同期が完了 * （ waflCaResyncComplete ）
 a| 
イベント
 a| 
クラスタ
 a| 
警告



 a| 
FabricPool スペースがほぼフル * （ fabricpoolNearlyFull ）
 a| 
リスク
 a| 
クラスタ
 a| 
エラー

|===


== 影響範囲：構成

|===
| イベント名（トラップ名） | 影響レベル | ソースタイプ | 重大度 


 a| 
ノードが追加されました（該当なし）
 a| 
イベント
 a| 
クラスタ
 a| 
情報



 a| 
ノードが削除されました（該当なし）
 a| 
イベント
 a| 
クラスタ
 a| 
情報



 a| 
クラスタが削除されました（該当なし）
 a| 
イベント
 a| 
クラスタ
 a| 
情報



 a| 
クラスタの追加に失敗（該当なし）
 a| 
イベント
 a| 
クラスタ
 a| 
エラー



 a| 
クラスタ名が変更されました（該当なし）
 a| 
イベント
 a| 
クラスタ
 a| 
情報



 a| 
緊急の EMS を受信（該当なし）
 a| 
イベント
 a| 
クラスタ
 a| 
重要



 a| 
重大な EMS を受信（該当なし）
 a| 
イベント
 a| 
クラスタ
 a| 
重要



 a| 
アラートの EMS を受信（該当なし）
 a| 
イベント
 a| 
クラスタ
 a| 
エラー



 a| 
エラーの EMS を受信（該当なし）
 a| 
イベント
 a| 
クラスタ
 a| 
警告



 a| 
警告の EMS を受信（該当なし）
 a| 
イベント
 a| 
クラスタ
 a| 
警告



 a| 
デバッグの EMS を受信（該当なし）
 a| 
イベント
 a| 
クラスタ
 a| 
警告



 a| 
通知の EMS を受信（該当なし）
 a| 
イベント
 a| 
クラスタ
 a| 
警告



 a| 
情報の EMS を受信（該当なし）
 a| 
イベント
 a| 
クラスタ
 a| 
警告

|===
ONTAP EMS イベントは、 Unified Manager イベントの 3 つの重大度レベルに分類されます。

|===


| Unified Manager イベントの重大度レベル | ONTAP EMS イベントの重大度レベル 


 a| 
重要
 a| 
緊急

重要



 a| 
エラー
 a| 
アラート



 a| 
警告
 a| 
エラー

警告

デバッグ

注意

情報

|===


== 影響範囲：パフォーマンス

|===
| イベント名（トラップ名） | 影響レベル | ソースタイプ | 重大度 


 a| 
クラスタ負荷の不均衡しきい値を超過（）
 a| 
リスク
 a| 
クラスタ
 a| 
警告



 a| 
クラスタ IOPS の重大しきい値を超過（ドキュメント ClusterIopsIncident ）
 a| 
インシデント
 a| 
クラスタ
 a| 
重要



 a| 
クラスタ IOPS の警告しきい値を超過（ドキュメントクラスタ警告）
 a| 
リスク
 a| 
クラスタ
 a| 
警告



 a| 
クラスタ MBps の重大しきい値を超過（ドキュメント ClusterMbpsIncident ）
 a| 
インシデント
 a| 
クラスタ
 a| 
重要



 a| 
クラスタ MBps の警告しきい値を超過（ドキュメントクラスタの警告）
 a| 
リスク
 a| 
クラスタ
 a| 
警告



 a| 
クラスタ動的しきい値を超過（ DocumentClusterDynamicEventWarning ）
 a| 
リスク
 a| 
クラスタ
 a| 
警告

|===


== 影響範囲：セキュリティ

|===
| イベント名（トラップ名） | 影響レベル | ソースタイプ | 重大度 


 a| 
AutoSupport HTTPS 転送が無効になっています（ドキュメント ASUPHttpsConfiguredDisabled ）
 a| 
リスク
 a| 
クラスタ
 a| 
警告



 a| 
ログ転送が暗号化されていない（ ocClusterAuditLogUnencrypted ）
 a| 
リスク
 a| 
クラスタ
 a| 
警告



 a| 
デフォルトのローカル管理者ユーザーが有効になっています（ ocClusterDefaultAdminEnabled ）
 a| 
リスク
 a| 
クラスタ
 a| 
警告



 a| 
FIPS モードが無効になっています（ドキュメント ClusterFipsDisabled ）
 a| 
リスク
 a| 
クラスタ
 a| 
警告



 a| 
ログインバナーが無効になっています（ドキュメント ClusterLoginBannerDisabled ）
 a| 
リスク
 a| 
クラスタ
 a| 
警告



 a| 
ログインバナーが変更されました (DocumentClusterLoginBannerChanged)
 a| 
リスク
 a| 
クラスタ
 a| 
警告



 a| 
ログ転送先が変更されました (DocumentLogForwardDestinationsChanged)
 a| 
リスク
 a| 
クラスタ
 a| 
警告



 a| 
NTP サーバー名が変更されました（ Document NtpServerNamesChanged ）
 a| 
リスク
 a| 
クラスタ
 a| 
警告



 a| 
NTP サーバ数が少ない（ securityConfigNTPServerCountLowRisk ）
 a| 
リスク
 a| 
クラスタ
 a| 
警告



 a| 
クラスタピア通信が暗号化されていない（ Document ClusterPeerEncryptionDisabled ）
 a| 
リスク
 a| 
クラスタ
 a| 
警告



 a| 
SSH でセキュアでない暗号を使用（ ocClusterSSHセキュア でない）
 a| 
リスク
 a| 
クラスタ
 a| 
警告



 a| 
Telnet プロトコルが有効になっている（ ocClusterTelnetEnabled ）
 a| 
リスク
 a| 
クラスタ
 a| 
警告



 a| 
一部の ONTAP ユーザアカウントのパスワードで安全性の低い MD5 ハッシュ関数を使用しています（ドキュメント ClusterMD5PasswordHashUsed ）
 a| 
リスク
 a| 
クラスタ
 a| 
警告



 a| 
クラスタで自己署名証明書（ドキュメント ClusterSelfSignedCertificate ）を使用する
 a| 
リスク
 a| 
クラスタ
 a| 
警告



 a| 
クラスタのリモートシェルが有効になっています（ Document ClusterRshDisabled ）
 a| 
リスク
 a| 
クラスタ
 a| 
警告



 a| 
クラスタ証明書の有効期限が近づいています（DocumentEvtClusterCertificateAboutToExpire）
 a| 
リスク
 a| 
クラスタ
 a| 
警告



 a| 
クラスタ証明書の有効期間が終了しました（ドキュメントのEvtClusterCertificateExpired）
 a| 
リスク
 a| 
クラスタ
 a| 
エラー

|===