---
permalink: events/reference_supported_unified_manager_cli_commands.html 
sidebar: sidebar 
keywords: supported, unified manager, cli, commands, cmd, um cli, um run, 
summary: ストレージ管理者は、 CLI コマンドを使用して、クラスタ、アグリゲート、ボリューム、 qtree 、および LUN ： 
---
= Unified Manager の CLI コマンドがサポートされています
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージ管理者は、 CLI コマンドを使用して、クラスタ、アグリゲート、ボリューム、 qtree 、および LUN ：CLI コマンドを使用して、 Unified Manager の内部データベースと ONTAP データベースを照会できます。CLI コマンドは、処理の開始時または終了時に実行されるスクリプト、アラートがトリガーされたときに実行されるスクリプトでも使用できます。

すべてのコマンドの前に 'um cli login' コマンドと認証用の有効なユーザ名およびパスワードを入力する必要があります


NOTE: _um run_commandを実行するには、アカウントに_console_applicationアクセス権があることを確認します。

|===
| CLI コマンド | 説明 | 出力 


 a| 
um cli login -u <username> [-p <password>]
 a| 
CLI にログインします。セキュリティ上の理由から、「 -u 」オプションのあとにはユーザ名のみを入力してください。この方法でパスワードを入力すると、パスワードの入力を求められます。パスワードは履歴テーブルまたはプロセステーブルには保存されません。セッションはログインしてから 3 時間が経過すると期限切れになり、 3 時間が経過するとユーザは再度ログインする必要があります。
 a| 
対応するメッセージを表示します。



 a| 
「 um cli logout 」
 a| 
CLI からログアウトします。
 a| 
対応するメッセージを表示します。



 a| 
「 um help 」
 a| 
第 1 レベルのすべてのサブコマンドを表示します。
 a| 
第 1 レベルのすべてのサブコマンドを表示します。



 a| 
um run cmd [-t <timeout>] <cluster><command>`
 a| 
1 つ以上のホストでコマンドを実行する最も簡単な方法です。主に、アラートのスクリプト化を使用して ONTAP で処理を取得または実行します。オプションの timeout 引数で、コマンドがクライアントで完了するのを待機する最大時間（秒）を設定できます。デフォルトは 0 （無期限に待機）です。
 a| 
ONTAP から受け取ったとおり。



 a| 
'um run query <SQL command>`
 a| 
SQL クエリを実行します。データベースからの読み取りが許可されるクエリのみです。更新、挿入、削除の各操作はサポートされていません。
 a| 
結果は表形式で表示されます。空のセットが返された場合、または構文エラーや無効な要求がある場合は、該当するエラーメッセージが表示されます。



 a| 
um datasource add -u <username> -P <password> [-t <protocol>] [-p <port>] <hostname-or -ip>`
 a| 
管理対象ストレージシステムのリストにデータソースを追加します。データソースは、ストレージシステムへの接続方法を定義したものです。データソースを追加するときは、 -u （ユーザ名）オプションと -P （パスワード）オプションを必ず指定する必要があります。オプションの -t （プロトコル）では、クラスタとの通信に使用するプロトコル（ http または https ）を指定します。プロトコルが指定されていない場合は、両方のプロトコルが試行されます。オプションの -p （ポート）では、クラスタとの通信に使用するポートを指定します。ポートが指定されていない場合は、該当するプロトコルのデフォルト値が試行されます。このコマンドは、ストレージ管理者のみが実行できます。
 a| 
ユーザに証明書の承認を求めるプロンプトを表示し、対応するメッセージを出力します。



 a| 
「 um datasource list [<datasource-id> 」
 a| 
管理対象ストレージシステムのデータソースを表示します。
 a| 
[ID Address Port] 、 [Protocol Acquisition Status] 、 [Analysis Status] 、 [Communication status] 、 [Acquisition Message] の各値が表形式で表示されます。 と分析メッセージ



 a| 
「 um datasource modify [-h <hostname-or -ip>] [-u <username>] [-P <password>] [-t <protocol>] [-p <port>] <datasource-id> 」
 a| 
1 つ以上のデータソースオプションを変更します。ストレージ管理者のみが実行できます。
 a| 
対応するメッセージを表示します。



 a| 
「 um datasource remove <datasource-id> 」というエラーが表示されます
 a| 
Unified Manager からデータソース（クラスタ）を削除します。
 a| 
対応するメッセージを表示します。



 a| 
'um option list [<option] 。。
 a| 
に、 set コマンドを使用して設定できるすべてのオプションを示します。
 a| 
[ 名前 ] 、 [ 値 ] 、 [ デフォルト値 ] 、 [ 再起動が必要 ] の各値が表形式で表示されます



 a| 
`um option set < オプション名 >=< オプション値 >[<option-name>=<option-value> … ]
 a| 
1 つまたは複数のオプションを設定します。このコマンドは、ストレージ管理者のみが実行できます。
 a| 
対応するメッセージを表示します。



 a| 
「 um version 」
 a| 
Unified Manager ソフトウェアのバージョンを表示します。
 a| 
「 Version 」 ("9.6")`



 a| 
um lun list [-q] [-ObjectType <object-id>] をクリックします
 a| 
指定したオブジェクトでフィルタリングした LUN のリストを表示します。-q は、ヘッダーを表示しないすべてのコマンドに適用されます。ObjectType には、 lun 、 qtree 、 cluster 、 volume 、 quota 、 または SVM を選択します。

例：

*'um lun list - cluster 1`*

この例では、 objectType が「 -cluster 」で、 objectId が「 1 」です。このコマンドを実行すると、 ID が 1 のクラスタに含まれるすべての LUN のリストが表示されます。
 a| 
表形式で次の値が表示されます。 'ID'LUN path.'



 a| 
'um svm list [-q] [-ObjectType <object-id>] を指定します
 a| 
指定したオブジェクトでフィルタリングした Storage VM のリストを表示します。ObjectType には、 lun 、 qtree 、 cluster 、 volume 、 quota 、 または SVM を選択します。

例：

*'um svm list - cluster 1`*

この例では、 objectType が「 -cluster 」で、 objectId が「 1 」です。このコマンドを実行すると、 ID が 1 のクラスタに含まれるすべての Storage VM のリストが表示されます。
 a| 
表形式で ' 名前とクラスタ ID' の値が表示されます



 a| 
'um qtree list [-q] [-ObjectType <object-id>] をクリックします
 a| 
指定したオブジェクトでフィルタリングした qtree のリストを表示します。-q は、ヘッダーを表示しないすべてのコマンドに適用されます。ObjectType には、 lun 、 qtree 、 cluster 、 volume 、 quota 、 または SVM を選択します。

例：

*'um qtree list - cluster 1`*

この例では、 objectType が「 -cluster 」で、 objectId が「 1 」です。このコマンドを実行すると、 ID が 1 のクラスタに含まれるすべての qtree のリストが表示されます。
 a| 
表形式で次の値を表示します。 qtree ID および qtree 名



 a| 
um disk list [-q] [-ObjectType <object-id>]
 a| 
指定したオブジェクトでフィルタリングしたディスクのリストを表示します。ObjectType には、 disk 、 aggr 、 node 、 cluster のいずれかを指定できます。

例：

*'um disk list - cluster 1`*

この例では、 objectType が「 -cluster 」で、 objectId が「 1 」です。このコマンドを実行すると、 ID が 1 のクラスタに含まれるすべてのディスクのリストが表示されます。
 a| 
次の値を表形式の 'ObjectType および object-id で表示します



 a| 
'um cluster list [-q] [-ObjectType <object-id>] をクリックします
 a| 
指定したオブジェクトでフィルタリングしたクラスタのリストを表示します。ObjectType には、 disk 、 aggr 、 node 、 cluster 、 lun 、 qtree 、ボリューム、クォータ、または SVM 。

例：

*'um cluster list - aggr 1`*

この例では、 objectType が「 -aggr 」で、 objectId が「 1 」です。このコマンドを実行すると、 ID が 1 のアグリゲートが属するクラスタが表示されます。
 a| 
次の値が表形式で表示されます： ' 名前 ' フルネーム ' シリアル番号 ' データソース ID' 最終更新時刻 ' およびリソースキー



 a| 
um cluster node list [-q] [-ObjectType <object-id>]
 a| 
指定したオブジェクトでフィルタリングしたクラスタノードのリストを表示します。ObjectType には、 disk 、 aggr 、 node 、 cluster のいずれかを指定できます。

例：

*'um cluster node list - cluster 1`*

この例では、 objectType が「 -cluster 」で、 objectId が「 1 」です。このコマンドを実行すると、 ID が 1 のクラスタに含まれるすべてのノードのリストが表示されます。
 a| 
次の値を表形式の Name および Cluster ID で表示します



 a| 
'um volume list [-q] [-ObjectType <object-id>]
 a| 
指定したオブジェクトでフィルタリングしたボリュームのリストを表示します。ObjectType には、 lun 、 qtree 、 cluster 、 volume 、 quota 、 SVM またはアグリゲート。

例：

*'um volume list - cluster 1`*

この例では、 objectType が「 -cluster 」で、 objectId が「 1 」です。このコマンドを実行すると、 ID が 1 のクラスタに含まれるすべてのボリュームのリストが表示されます。
 a| 
次の値を表形式の 'Volume ID' および Volume Name' で表示します



 a| 
um quota user list [-q] [-ObjectType <object-id>]
 a| 
指定したオブジェクトでフィルタリングしたクォータユーザのリストを表示します。ObjectType には、 qtree 、 cluster 、 volume 、 quota 、 svm のいずれかを指定できます。

例：

*'um quota user list - cluster 1`*

この例では、 objectType が「 -cluster 」で、 objectId が「 1 」です。このコマンドを実行すると、 ID が 1 のクラスタに含まれるすべてのクォータユーザのリストが表示されます。
 a| 
次の値が表形式で表示されます 'ID'Name'SID' および Email'



 a| 
'um aggr list [-q] [-ObjectType <object-id>]
 a| 
指定したオブジェクトでフィルタリングしたアグリゲートのリストを表示します。ObjectType には、 disk 、 aggr 、 node 、 cluster 、 volume のいずれかを指定できます。

例：

*'um aggr list - cluster 1`*

この例では、 objectType が「 -cluster 」で、 objectId が「 1 」です。このコマンドを実行すると、 ID が 1 のクラスタに含まれるすべてのアグリゲートのリストが表示されます。
 a| 
次の値が表形式で表示されますアグリゲート ID とアグリゲート名



 a| 
'um event ack <event-ids>`
 a| 
1 つ以上のイベントに確認応答します。
 a| 
対応するメッセージを表示します。



 a| 
'um event resolve <event-ids>`
 a| 
1 つ以上のイベントを解決します。
 a| 
対応するメッセージを表示します。



 a| 
'um event assign -u <username><event-id>`
 a| 
ユーザにイベントを割り当てます。
 a| 
対応するメッセージを表示します。



 a| 
'um event list [-s <source>] [-S <event-state-filter-list> 。] [<event-id> 。。
 a| 
システムまたはユーザによって生成されたイベントのリストが表示されます。ソース、状態、および ID に基づいてイベントをフィルタリングします。
 a| 
次の値を表形式で表示します。ソース、ソースタイプ、名前、重大度、状態、 ユーザーとタイムスタンプ



 a| 
'um backup restore -f <backup_file_path _ and _name>`
 a| 
.7z ファイルを使用して、 MySQL データベースのバックアップをリストアします。
 a| 
対応するメッセージを表示します。

|===