---
permalink: events/reference_event_details_page.html 
sidebar: sidebar 
keywords: event, details, page 
summary: イベントの詳細ページでは、選択したイベントの重大度、影響レベル、影響領域、イベントソースなどの詳細を確認できます。問題を解決するための考えられる対処方法について、追加情報を確認することもできます。 
---
= イベントの詳細ページ
:icons: font
:imagesdir: ../media/


[role="lead"]
イベントの詳細ページでは、選択したイベントの重大度、影響レベル、影響領域、イベントソースなどの詳細を確認できます。問題を解決するための考えられる対処方法について、追加情報を確認することもできます。

* * イベント名 *
+
イベントの名前と最終確認時刻。

+
パフォーマンスイベント以外のイベントの場合は、状態が「新規」または「確認済み」のときは最終確認時刻が不明なため、この情報は表示されません。

* * イベント概要 *
+
イベントの簡単な概要。

+
イベント概要には、イベントがトリガーされた理由が含まれる場合があります。

* * 競合状態のコンポーネント *
+
動的なパフォーマンスイベントについて、クラスタの論理コンポーネントと物理コンポーネントを表すアイコンが表示されます。コンポーネントが競合状態にある場合は、アイコンが赤い丸で強調表示されます。

+
表示されるコンポーネントの概要については、「 _ クラスタコンポーネントとその競合の原因」を参照してください。



「イベント情報」、「システム診断」、および「推奨処置」の各セクションについては、他のトピックで説明しています。



== コマンドボタン

各コマンドボタンを使用して次のタスクを実行できます。

* * メモアイコン *
+
イベントに関するメモを追加または更新したり、他のユーザが残したすべてのメモを確認したりできます。



* アクションメニュー *

* * 自分に割り当て *
+
イベントを自分に割り当てます。

* * 他のユーザーに割り当て *
+
[ 所有者の割り当て ] ダイアログボックスが開きますこのダイアログボックスで ' イベントを他のユーザーに割り当てたり ' 再割り当てしたりできます

+
イベントをユーザに割り当てると、イベントリストの選択したイベントの該当するフィールドに、ユーザの名前とイベントが割り当てられた時刻が追加されます。

+
所有権のフィールドを空白にすると、イベントの割り当てを解除できます。

* * 確認 *
+
選択したイベントに確認応答し、アラート通知が繰り返し送信されないようにします。

+
イベントを確認すると、ユーザ名とそのイベントを確認した時刻が、選択したイベントのイベントリスト（確認済みのイベントのリスト）に追加されます。確認したイベントについては、自分で対処する必要があります。

* * 解決済みとしてマーク *
+
イベントの状態を解決済みに変更できます。

+
イベントを解決すると、イベントリスト（で解決）に選択したイベントのユーザ名と解決時刻が追加されます。イベントに対処したら、そのイベントを解決済みとしてマークする必要があります。

* * アラートの追加 *
+
アラートの追加ダイアログボックスが表示され、選択したイベントにアラートを追加できます。


