---
permalink: events/reference_management_station_events.html 
sidebar: sidebar 
keywords: management, station, events, impact area, configuration, performance 
summary: 管理ステーションイベントは、 Unified Manager がインストールされているサーバのステータス情報を提供します。これにより、潜在的な問題を監視できます。影響範囲別にイベントがまとめられ、イベント名とトラップ名、影響レベル、ソースタイプ、および重大度が表示されます。 
---
= 管理ステーションイベント
:icons: font
:imagesdir: ../media/


[role="lead"]
管理ステーションイベントは、 Unified Manager がインストールされているサーバのステータス情報を提供します。これにより、潜在的な問題を監視できます。影響範囲別にイベントがまとめられ、イベント名とトラップ名、影響レベル、ソースタイプ、および重大度が表示されます。



== 影響範囲：構成

|===
| イベント名（トラップ名） | 影響レベル | ソースタイプ | 重大度 


 a| 
管理サーバのディスクスペースがほぼフル（ Document EvtUnifiedManagerDiskSpaceNearlyFull ）
 a| 
リスク
 a| 
管理ステーション
 a| 
警告



 a| 
管理サーバのディスクスペースがフル（ Document EvtUnifiedManagerDiskSpaceFull ）
 a| 
インシデント
 a| 
管理ステーション
 a| 
重要



 a| 
管理サーバのメモリが減少（ Document EvtUnifiedManagerMemoryLow ）
 a| 
リスク
 a| 
管理ステーション
 a| 
警告



 a| 
管理サーバのメモリがほとんどない（ Document EvtUnifiedManagerMemoryAlmostOut ）
 a| 
インシデント
 a| 
管理ステーション
 a| 
重要



 a| 
MySQL ログファイルのサイズが増加しました。再起動が必要です（ Document EvtMysqlLogFileSizeWarning ）
 a| 
インシデント
 a| 
管理ステーション
 a| 
警告



 a| 
監査ログサイズ割り当ての合計がフルになります
 a| 
リスク
 a| 
管理ステーション
 a| 
警告



 a| 
syslog サーバ証明書の有効期限が近づいています
 a| 
リスク
 a| 
管理ステーション
 a| 
警告



 a| 
syslog サーバ証明書の有効期限が切れました
 a| 
リスク
 a| 
管理ステーション
 a| 
エラー



 a| 
監査ログファイルが改ざんされました
 a| 
リスク
 a| 
管理ステーション
 a| 
警告



 a| 
監査ログファイルが削除されました
 a| 
リスク
 a| 
管理ステーション
 a| 
警告



 a| 
syslog サーバ接続エラー
 a| 
リスク
 a| 
管理ステーション
 a| 
エラー



 a| 
syslog サーバ設定が変更されました
 a| 
イベント
 a| 
管理ステーション
 a| 
警告

|===


== 影響範囲：パフォーマンス

|===
| イベント名（トラップ名） | 影響レベル | ソースタイプ | 重大度 


 a| 
パフォーマンスデータ分析への影響（ Document EvtUnifiedManagerDataMissingAnalyze ）
 a| 
リスク
 a| 
管理ステーション
 a| 
警告



 a| 
パフォーマンスデータ収集への影響（ Document EvtUnifiedManagerDataMissingCollection ）
 a| 
インシデント
 a| 
管理ステーション
 a| 
重要

|===
[NOTE]
====
最後の 2 つのパフォーマンスイベントは、 Unified Manager 7.2 でのみ使用されていたものです。これらのいずれかのイベントが新規の状態で存在している場合、 Unified Manager ソフトウェアを新しいバージョンにアップグレードしてもイベントは自動的にパージされません。イベントを手動で解決済みの状態に移行する必要があります。

====