---
permalink: events/task_enable_and_disable_active_iq_event_reporting.html 
sidebar: sidebar 
keywords: enable, disable, active iq, event, report 
summary: Active IQ プラットフォームイベントは、デフォルトで生成されて Unified Manager ユーザインターフェイスに表示されます。これらのイベントが「ノイジー」に起因している場合や、 Unified Manager でこれらのイベントを表示したくない場合は、これらのイベントの生成を無効にすることができます。あとで有効にして、これらの通知の受信を再開することができます。 
---
= Active IQイベントレポートの有効化と無効化
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ プラットフォームイベントは、デフォルトで生成されて Unified Manager ユーザインターフェイスに表示されます。「ノイジー」が大きすぎる場合や、 Unified Manager でこれらのイベントを表示したくない場合は、これらのイベントの生成を無効にすることができます。あとで有効にして、これらの通知の受信を再開することができます。

.開始する前に
アプリケーション管理者のロールが必要です。

この機能を無効にすると、 Unified Manager は Active IQ プラットフォームイベントの受信をただちに停止します。

この機能を有効にすると、クラスタのタイムゾーンの午前 0 時を過ぎに Unified Manager は Active IQ プラットフォームイベントの受信を開始します。開始時刻は、 Unified Manager がいつ各クラスタから AutoSupport メッセージを受信したかによって決まります。

.手順
. 左側のナビゲーションペインで、 * 一般 * > * 機能設定 * をクリックします。
. [* 機能の設定 * ] ページで、次のいずれかのオプションを選択して Active IQ プラットフォームイベントを無効または有効にします。
+
|===
| 状況 | 操作 


 a| 
Active IQ プラットフォームイベントを無効にします
 a| 
Active IQ ポータルイベント * パネルで、スライダボタンを左に動かします。



 a| 
Active IQ プラットフォームイベントを有効にします
 a| 
Active IQ ポータルイベント * パネルで、スライダボタンを右に動かします。

|===

