---
permalink: events/task_subscribe_to_ontap_ems_events.html 
sidebar: sidebar 
keywords: subscribe, ontap, ems events 
summary: ONTAP ソフトウェアがインストールされているシステムで生成された Event Management System （ EMS ；イベント管理システム）イベントを受け取るように登録することができます。一部の EMS イベントは Unified Manager に自動的に報告されますが、それ以外の EMS イベントは登録している場合にのみ報告されます。 
---
= ONTAP EMSイベントを購読する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP ソフトウェアがインストールされているシステムで生成された Event Management System （ EMS ；イベント管理システム）イベントを受け取るように登録することができます。一部の EMS イベントは Unified Manager に自動的に報告されますが、それ以外の EMS イベントは登録している場合にのみ報告されます。

.開始する前に
Unified Manager にすでに自動的に追加されている EMS イベントには登録しないでください。同じ問題のイベントを 2 つ受信すると原因で混乱する可能性があります。

EMS イベントはいくつでも登録できます。登録したすべてのイベントが検証され、検証済みのイベントだけが Unified Manager で監視しているクラスタに適用されます。ONTAP 9 EMS イベントカタログ _ は、指定したバージョンの ONTAP 9 ソフトウェアのすべての EMS メッセージに関する詳細情報を提供します。該当するイベントの一覧については、 ONTAP 9 製品ドキュメントページで該当するバージョンの _EMS イベントカタログを参照してください。

https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286["ONTAP 9 製品ライブラリ"]

登録した ONTAP EMS イベントにアラートを設定したり、それらのイベントに対して実行するカスタムスクリプトを作成したりできます。

[NOTE]
====
登録した ONTAP EMS イベントが届かない場合は、クラスタの DNS 設定が含まれている問題で、クラスタから Unified Manager サーバに到達できなくなっていることが考えられます。クラスタ管理者はこの問題を解決するために、クラスタの DNS 設定を修正してから Unified Manager を再起動する必要があります。これにより、保留中の EMS イベントが Unified Manager サーバにフラッシュされます。

====
.手順
. 左側のナビゲーションペインで、 * Storage Management * > * Event Setup * をクリックします。
. Event Setup ページで、 * Subscribe to EMS events * ボタンをクリックします。
. [EMS イベントのサブスクライブ（ Subscribe to EMS events ） ] ダイアログボックスで、サブスクライブする ONTAP EMS イベントの名前を入力します。
+
登録可能な EMS イベントの名前を表示するには、 ONTAP クラスタシェルから「 event route show 」コマンド（ ONTAP 9 より前）または「 event catalog show 」コマンド（ ONTAP 9 以降）を使用します。

+
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/OnCommand_Suite/How_to_configure_and_receive_alerts_from_ONTAP_EMS_Event_Subscription_in_Active_IQ_Unified_Manager["Active IQ Unified Manager で ONTAP EMS イベントサブスクリプションからアラートを設定して受信する方法"]

. [ 追加（ Add ） ] をクリックします。
+
EMS イベントはサブスクライブされた EMS イベントのリストに追加されますが、該当する [To Cluster] 列には、追加した EMS イベントのステータスが「 Unknown 」と表示されます。

. Save and Close * をクリックして、 EMS イベントサブスクリプションをクラスタに登録します。
. もう一度 [* EMS イベントをサブスクライブ * ] をクリックします。
+
追加した EMS イベントの [Applicable to Cluster] 列には、ステータス「 Yes 」が表示されます。

+
ステータスが「はい」でない場合は、 ONTAP EMS イベント名のスペルを確認します。入力した名前に間違いがある場合は、そのイベントを削除して追加し直す必要があります。



ONTAP の EMS イベントが発生すると、イベントが Events ページに表示されます。イベントを選択すると、 EMS イベントに関する詳細をイベントの詳細ページで確認できます。イベントの処理を管理したり、イベントのアラートを作成したりすることもできます。
