---
permalink: events/task_exclude_disaster_recovery_destination_volumes_from_alerts.html 
sidebar: sidebar 
keywords: exclude, disaster, recovery, destination, volumes, generate, alerts 
summary: ボリュームアラートを設定するときに、ボリュームまたはボリュームグループを識別する文字列をアラートダイアログボックスで指定できます。ただし、 SVM のディザスタリカバリを設定している場合は、ソースボリュームとデスティネーションボリュームの名前が同じであるため、両方のボリュームについてアラートを受け取ることになります。 
---
= 災害復旧の宛先ボリュームをアラート生成から除外する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ボリュームアラートを設定するときに、ボリュームまたはボリュームグループを識別する文字列をアラートダイアログボックスで指定できます。ただし、 SVM のディザスタリカバリを設定している場合は、ソースボリュームとデスティネーションボリュームの名前が同じであるため、両方のボリュームについてアラートを受け取ることになります。

.開始する前に
アプリケーション管理者またはストレージ管理者のロールが必要です。

ディザスタリカバリのデスティネーションボリュームに対するアラートを無効にするには、デスティネーション SVM の名前を含むボリュームを除外します。これは、ボリュームイベントの識別子に SVM 名とボリューム名の両方が「 <svm_name> ： /<volume_name> 」の形式で含まれていることを確認したものです。

次の例は、プライマリ SVM 「 vs1 」上のボリューム「 vol1 」に対するアラートを作成し、 SVM 「 vs1-dr 」にある同じ名前のボリュームはアラート生成の対象から除外する方法を示しています。

[Add Alert] ダイアログボックスで、次の手順を実行します。

.手順
. [* 名前 *] をクリックして、アラートの名前と概要を入力します。
. [* リソース（ * Resources ） ] をクリックし、 [* 含める * （ * Include * ） ] タブを選択します。
+
.. ドロップダウン・リストから * Volume * を選択し、 * Name contains * フィールドに「 vol1 」と入力して、名前に「 vol1 」が含まれているボリュームを表示します。
.. 「 * + 」を選択します<<All Volumes whose name contains 'vol1'>>[*Available Resources*] 領域から [*Selected Resources*] 領域に移動します。


. [* Exclude*] タブを選択し '[* Volume*] を選択し '[* 次を含む名前 ] フィールドに *vs1_dr`*] と入力し '[*Add] をクリックします
+
SVM 「 vs1-dr 」のボリューム「 vol1 」については、アラートは生成されません。

. 「 * Events 」をクリックして、ボリュームに適用するイベントを選択します。
. [* アクション * ] をクリックし、 [ これらのユーザーに警告 ] フィールドで警告メールを受信するユーザーの名前を選択します。
. SNMP トラップを発行してスクリプトを実行するために、このページの他のオプションを設定し、 * Save * をクリックします。

