---
permalink: data-protection/concept_understand_svm_associations.html 
sidebar: sidebar 
keywords: understand storage vm peers 
summary: Storage VM ピアは、ソース Storage VM からデスティネーション Storage VM へのマッピングであり、リソースの選択やセカンダリボリュームのプロビジョニングのためにパートナーアプリケーションで使用されます。 
---
= Storage VM ピアの概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Storage VM ピアは、ソース Storage VM からデスティネーション Storage VM へのマッピングであり、リソースの選択やセカンダリボリュームのプロビジョニングのためにパートナーアプリケーションで使用されます。

ピアは、デスティネーション Storage VM がセカンダリデスティネーションか 3 次デスティネーションかに関係なく、常にソース Storage VM とデスティネーション Storage VM の間で作成されます。セカンダリデスティネーション Storage VM をソースとして使用して、 3 番目のデスティネーション Storage VM とのピアを作成することはできません。

Storage VM をピアリングする方法は 3 つあります。

* 任意の Storage VM にピアリングします
+
任意のプライマリソース Storage VM と 1 つ以上のデスティネーション Storage VM の間にピアを作成できます。つまり、現時点で保護を必要とする既存のすべての Storage VM と、以降に作成されるすべての Storage VM が、指定したデスティネーション Storage VM とピア関係にあります。たとえば、異なる場所にある複数のソースのアプリケーションを 1 箇所にある 1 つ以上のデスティネーション Storage VM にバックアップできます。

* 特定の Storage VM にピアリングしてください
+
特定のソース Storage VM と 1 つ以上の特定のデスティネーション Storage VM の間にピアを作成できます。たとえば、データを互いに分離する必要のある多数のクライアントにストレージサービスを提供する場合は、このオプションを選択して、特定のソース Storage VM を、対象のクライアントにのみ割り当てられる特定のデスティネーション Storage VM に関連付けることができます。

* 外部の Storage VM とピアリングしてください
+
ソース Storage VM とデスティネーション Storage VM の外部のフレキシブルボリュームの間にピアを作成できます。


