---
permalink: data-protection/concept_types_of_snapmirror_protection.html 
sidebar: sidebar 
keywords: types, snapmirror, protection, consistency group, snapmirror business continuity, smbc, sm-bc 
summary: 導入するデータストレージのトポロジに応じて、複数のタイプの SnapMirror 保護関係を Unified Manager で設定できます。すべての種類の SnapMirror 保護では、フェイルオーバーによるディザスタリカバリ保護が提供されますが、パフォーマンス、バージョン依存性の解消、および複数のバックアップコピーによる保護については、提供される機能が異なります。 
---
= SnapMirror 保護のタイプ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
導入するデータストレージのトポロジに応じて、複数のタイプの SnapMirror 保護関係を Unified Manager で設定できます。すべての種類の SnapMirror 保護では、フェイルオーバーによるディザスタリカバリ保護が提供されますが、パフォーマンス、バージョン依存性の解消、および複数のバックアップコピーによる保護については、提供される機能が異なります。



== 従来型の SnapMirror 非同期保護関係

従来型の SnapMirror 非同期保護では、ソースボリュームとデスティネーションボリューム間のブロックレプリケーションによるミラー保護が提供されます。

従来型の SnapMirror 関係では、ブロックレプリケーションに基づいてミラー処理が行われるため、他の SnapMirror 関係よりも高速なミラー処理が可能です。ただし、従来型の SnapMirror 保護では、デスティネーションボリュームで実行されている ONTAP ソフトウェアのマイナーバージョンがソースボリュームと同じかそれよりも新しい必要があります（バージョン 8.x から 8.x 、 9.x から 9.x など）。9.1 ソースから 9.0 デスティネーションへのレプリケーションはサポートされていません。これは、デスティネーションで古いメジャーバージョンが実行されているためです。



== バージョンに依存しないレプリケーションを使用した SnapMirror 非同期保護

バージョンに依存しないレプリケーションを使用した SnapMirror 非同期保護では、ソースボリュームとデスティネーションボリューム間の論理レプリケーションによるミラー保護が提供されます。ボリュームで異なるバージョンの ONTAP 8.3 以降のソフトウェアを実行している場合でも同様です（バージョン 8.3 から 8.3.1 、 8.3 から 9.1 、 9.2 から 9.2.2 など）。

バージョンに依存しないレプリケーションを使用した SnapMirror 関係では、ミラー処理が従来型の SnapMirror 関係ほど高速ではありません。

実行速度が遅いため、バージョンに依存しないレプリケーション保護を使用する SnapMirror は、次の状況のどちらにも適していません。

* ソースオブジェクトには、保護対象のファイルが 1 、 000 万を超えています。
* 保護対象データの目標復旧時点が 2 時間以下である。（つまり、ソースのデータからの遅れが 2 時間未満のリカバリ可能なミラーデータが常にデスティネーションに含まれている必要があります）。


これらのいずれかの状況では、デフォルトの SnapMirror 保護をより高速なブロックレプリケーションベースで実行する必要があります。



== バージョンに依存しないレプリケーションとバックアップオプションを使用した SnapMirror 非同期保護

バージョンに依存しないレプリケーションとバックアップオプションを使用した SnapMirror 非同期保護では、ソースボリュームとデスティネーションボリューム間のミラー保護およびミラーデータの複数のコピーをデスティネーションに格納する機能が提供されます。

ストレージ管理者は、ソースからデスティネーションにミラーリングする Snapshot コピーを指定したり、ソースで削除されたコピーをデスティネーションに保持する期間を指定したりできます。

バージョンに依存しないレプリケーションとバックアップオプションを使用した SnapMirror 関係では、ミラー処理が従来型の SnapMirror 関係ほど高速ではありません。



== SnapMirror ユニファイドレプリケーション（ミラーバックアップ）

SnapMirror ユニファイドレプリケーションを使用すると、同じデスティネーションボリュームでディザスタリカバリとアーカイブを設定できます。SnapMirror と同様に、一元化されたデータ保護機能の初回起動時に、ベースライン転送が実行されます。デフォルトの一元化されたデータ保護ポリシー「 MirrorAllSnapshots 」に基づくベースライン転送では、ソースボリュームの Snapshot コピーが作成され、そのコピーおよびコピーが参照するデータブロックがデスティネーションボリュームに転送されます。SnapVault と同様に、一元化されたデータ保護にはベースラインの古い Snapshot コピーは含まれません。



== 厳密な同期を使用した SnapMirror 同期保護

「 stict 」同期を使用した SnapMirror 同期保護では、プライマリボリュームとセカンダリボリュームが常に相互の完全なコピーになります。セカンダリボリュームへのデータの書き込みでレプリケーションエラーが発生すると、プライマリボリュームに対するクライアント I/O が中断されます。



== 通常の同期を使用した SnapMirror 同期保護

「ル」同期を使用した SnapMirror 同期保護では、プライマリボリュームとセカンダリボリュームが常に相互の完全なコピーである必要はないため、プライマリボリュームの可用性が確保されます。セカンダリボリュームへのデータの書き込みでレプリケーションエラーが発生すると、プライマリボリュームとセカンダリボリュームが同期されていない状態のまま、プライマリボリュームに対するクライアント I/O が継続されます。

[NOTE]
====
同期保護関係を Health ： All Volumes ビューまたは Volume/Health Details ページから監視する場合、 Restore ボタンと Relationship 操作ボタンは使用できません。

====


== SnapMirror Synchronous によるビジネス継続性

ONTAP 9.8 以降では、 SnapMirror のビジネス継続性（ SM-BC ）機能を使用できます。また、この機能を使用して LUN でアプリケーションを保護できるため、アプリケーションのフェイルオーバーを透過的に実行し、災害発生時のビジネス継続性を確保できます。

クラスタおよび Storage Virtual Machine で使用される Consistency Groups （ CG ；整合グループ）の同期 SnapMirror 関係を Unified Manager から検出して監視できます。SM-BC は、 AFF クラスタまたは All SAN Array （ ASA ）クラスタでサポートされます。プライマリクラスタとセカンダリクラスタは、 AFF または ASA のどちらかになります。SM-BC は、 iSCSI LUN または FCP LUN を使用してアプリケーションを保護します。

SM-BC 関係で保護されているボリュームと LUN を表示すると、保護関係の一元化されたビュー、ボリュームインベントリ内の整合グループ、整合グループ関係の保護トポロジの表示、 1 年以内の整合グループ関係の履歴データの表示が可能になります。レポートをダウンロードすることもできます。また、整合グループ関係の概要の表示、整合グループ関係のサポートの検索、整合グループで保護されているボリュームに関する情報の取得も可能です。

[ 関係 ] ページでは ' ソースストレージオブジェクトとデスティネーションストレージオブジェクト ' およびコンシステンシグループによって保護されているそれらの関係の保護をソート ' フィルタ ' および拡張することもできます

SnapMirror Synchronous のビジネス継続性の詳細については、を参照してください link:https://docs.netapp.com/us-en/ontap/smbc/index.html["SM-BC に関する ONTAP 9 のマニュアル"]。
