---
permalink: data-protection/reference_protection_storage_virtual_machine_associations_page.html 
sidebar: sidebar 
keywords: svm, association, page 
summary: Storage VMの関連付けページでは、ソースとデスティネーションのStorage VM間の既存のStorage VMの関連付けを表示できます。 
---
= ストレージVMの関連付けを理解する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Storage Virtual Machine（Storage VM）の関連付けは、ソースStorage VMからデスティネーションStorage VMへのマッピングであり、リソースの選択やセカンダリボリュームのプロビジョニングのためにパートナーアプリケーションで使用されます。

デスティネーションStorage VMがセカンダリデスティネーションか3次デスティネーションかに関係なく、ソースStorage VMとデスティネーションStorage VMの間で関連付けが作成されます。セカンダリデスティネーションStorage VMをソースとして使用して、3番目のデスティネーションStorage VMとの関連付けを作成することはできません。

アプリケーション管理者またはストレージ管理者は、環境内のStorage VMの関連付けを* Protection *>* Storage VM Associations *ページで確認できます。

SVMを関連付ける方法は3つあります。

* *任意のStorage VMを関連付け*：任意のプライマリソースStorage VMと1つ以上のデスティネーションSVMの間で関連付けを作成できます。つまり、現時点で保護を必要とする既存のすべてのSVMおよび今後作成されるすべてのSVMが指定したデスティネーションSVMに関連付けられます。たとえば、異なる場所にある複数のソースのアプリケーションを1箇所にある1つ以上のデスティネーションSVMにバックアップできます。
* *特定のStorage VMを関連付け*：特定のソースStorage VMと1つ以上の特定のデスティネーションSVMの間で関連付けを作成できます。たとえば、データを互いに分離する必要のある多数のクライアントにストレージサービスを提供する場合は、このオプションを選択して、特定のソース Storage VM を、対象のクライアントにのみ割り当てられる特定のデスティネーション Storage VM に関連付けることができます。
* *外部Storage VMと関連付け*：ソースStorage VMとデスティネーションStorage VMの外部のフレキシブルボリュームとの間で関連付けを作成できます。




== Storage VMの関連付けを作成します

Create Storage Virtual Machine Associationsウィザードでは、パートナーの保護アプリケーションを使用して、ソースStorage VMをデスティネーションStorage VMに関連付けて、SnapMirror関係とSnapVault 関係で使用することができます。パートナーアプリケーションでは、デスティネーションボリュームの最初のプロビジョニングの際にこれらの関連付けを使用して、.ddを選択するリソースを特定します

.開始する前に
* 関連付ける Storage VM がすでに存在している必要があります。
* アプリケーション管理者またはストレージ管理者のロールが必要です。


すべてのソース Storage VM と関係タイプについて、各デスティネーションクラスタでデスティネーション Storage VM を 1 つだけ選択できます。

削除機能と作成機能を使用した関連付けの変更は、以降のプロビジョニング処理にのみ反映されます。既存のデスティネーションボリュームは移動されません。

.手順
. 左側のナビゲーションペインで、* Protection *>* Storage VM Associations *をクリックします。
. [* Storage VM Associations]ページで、[* Create]をクリックします。
+
Create Storage Virtual Machine Associations *ウィザードが起動します。

. 次のいずれかのソースを選択します。
+
** * 任意 *
+
任意のプライマリ Storage VM ソースと 1 つ以上のデスティネーション Storage VM の間で関連付けを作成する場合に、このオプションを選択します。つまり、現時点で保護を必要とする既存のすべての Storage VM と、以降に作成されるすべての Storage VM が、指定したデスティネーション Storage VM に関連付けられます。たとえば、異なる場所にある複数のソースのアプリケーションを 1 箇所にある 1 つ以上のデスティネーション Storage VM にバックアップできます。

** * シングル *
+
1 つ以上のデスティネーション Storage VM に関連付けられている特定のソース Storage VM を選択する場合に、このオプションを選択します。たとえば、データを互いに分離する必要のある多数のクライアントにストレージサービスを提供する場合は、このオプションを選択して、特定の Storage VM ソースを、対象のクライアントにのみ割り当てられる特定の Storage VM デスティネーションに関連付けます。

** * なし（外部） *
+
ソース Storage VM とデスティネーション Storage VM の外部のフレキシブルボリュームの間で関連付けを作成する場合に、このオプションを選択します。



. 作成する保護関係タイプとして、次のいずれかまたは両方を選択します。
+
** * SnapMirror *
** * SnapVault *


. 「 * 次へ * 」をクリックします。
. Storage VM 保護デスティネーションを 1 つ以上選択してください。
. [ 完了 ] をクリックします。




== Storage VMの関連付けを削除します

パートナーアプリケーションに対するStorage VMの関連付けを削除して、ソースとデスティネーションのStorage VM間のセカンダリプロビジョニング関係を削除することができます。この処理は、たとえば、デスティネーションStorage VMがいっぱいになり、Storage VMの保護の関連付けを新たに作成する場合などに行います。

.開始する前に
アプリケーション管理者またはストレージ管理者のロールが必要です。

Delete *ボタンは、Storage VMとの関連付けが少なくとも1つ選択されるまで無効になります。関連付けの削除と追加による変更は、以降のプロビジョニング処理にのみ反映されます。既存のデスティネーションボリュームが移動されることはありません。

.手順
. 左側のナビゲーションペインで、* Protection *>* Storage VM Associations *をクリックします。
. Storage VMの関連付けを少なくとも1つ選択してください。
+
* Delete * （削除）ボタンが有効になっています。

. [ 削除 ] をクリックします。 *
+
警告のダイアログボックスが表示されます。

. 続行するには、 [ はい ] をクリックします。
+
選択したStorage VMの関連付けがリストから削除されます。


