---
permalink: data-protection/reference_create_storage_virtual_machine_associations_wizard.html 
sidebar: sidebar 
keywords: create, storage, virtual machine, peers, wizard 
summary: Storage Virtual Machine ピアの作成ウィザードでは、 SnapMirror 保護関係と SnapVault 保護関係で使用するソース Storage VM とデスティネーション Storage VM をピアリングできます。 
---
= Create Storage Virtual Machine Peers ウィザード
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Storage Virtual Machine ピアの作成ウィザードでは、 SnapMirror 保護関係と SnapVault 保護関係で使用するソース Storage VM とデスティネーション Storage VM をピアリングできます。



== ソースを選択します

ソースの選択パネルでは、 Storage VM ピアのソースまたはプライマリ Storage VM を選択できます。

* * 任意 *
+
任意の Storage VM ソースと 1 つ以上のデスティネーションまたはセカンダリの Storage VM の間にピアを作成できます。つまり、現時点で保護を必要とする既存のすべての Storage VM と、以降に作成されるすべての Storage VM が、指定したデスティネーション Storage VM とピア関係にあります。たとえば、異なる場所にある複数のソースのアプリケーションを 1 箇所にある 1 つ以上のデスティネーション Storage VM にバックアップできます。

* * シングル *
+
特定のソース Storage VM と 1 つ以上のデスティネーション Storage VM をピアリングできます。たとえば、データを互いに分離する必要のある多数のクライアントにストレージサービスを提供する場合は、このオプションを選択して、特定の Storage VM ソースを、対象のクライアントにのみ割り当てられる特定の Storage VM デスティネーションに関連付けます。

* * なし（外部） *
+
ソース Storage VM とデスティネーション Storage VM の外部のフレキシブルボリュームの間で関連付けを作成できます。

+
** Storage Virtual Machine の略
+
使用可能なソース Storage VM の名前が表示されます

** クラスタ
+
各 Storage VM が配置されているクラスタが表示されます



* * これらの種類の関係を許可する *
+
関連付けの関係タイプを選択できます。

+
** SnapMirror
+
ピアタイプとして SnapMirror 関係を指定します。このオプションを選択すると、選択したソースからデスティネーションへのデータレプリケーションが有効になります。

** SnapVault
+
SnapVault 関係をピアタイプとして指定します。このオプションを選択すると、選択したプライマリの場所からセカンダリの場所へのバックアップが可能になります。







== Protection Destinations を選択します

Storage Virtual Machine ピアの作成ウィザードの保護デスティネーションの選択パネルでは、データのコピー先またはレプリケート先を選択できます。ピアはクラスタごとに 1 つのデスティネーション Storage VM にしか作成できません。



== コマンドボタン

各コマンドボタンを使用して次のタスクを実行できます。

* * 次へ *
+
ウィザードの次のページに進みます。

* * 戻る *
+
ウィザードの前のページに戻ります。

* * 完了 *
+
選択項目を適用して関連付けを作成します。

* * キャンセル *
+
選択内容を破棄して Storage Virtual Machine ピアの作成ウィザードを閉じます。


