---
permalink: data-protection/reference_relationship_last_1_month_transfer_status_view.html 
sidebar: sidebar 
keywords: relationship, 1 month, transfer status, view 
summary: Relationship ： Last 1 month Transfer Status ビューを使用すると、非同期関係にあるボリュームと Storage VM の一定期間の転送の傾向を分析できます。また、転送が成功したか失敗したかが表示されます。 
---
= 関係：過去 1 カ月の転送ステータス画面
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Relationship ： Last 1 month Transfer Status ビューを使用すると、非同期関係にあるボリュームと Storage VM の一定期間の転送の傾向を分析できます。また、転送が成功したか失敗したかが表示されます。

ページの上部にあるコントロールを使用すると、特定のオブジェクトを検索したり、フィルタを作成して適用したりして、表示されるデータのリストを絞り込んだり、ページ上の列の追加 / 削除 / 並べ替えを行ったり、ページ上のデータを「 .csv 」、「 .pdf 」、または「 .xlsx 」ファイルにエクスポートしたりできます。カスタマイズしたページをカスタムビューとして保存し、データのレポートを定期的に生成して E メールで送信するようにスケジュール設定できます。「 * フィルタ * 」オプションを使用すると、ボリュームのみ、または Storage VM のみなど、選択したストレージシステムのみを表示できます。ストレージページと、選択したストレージエンティティについてのみ、同じレポートが表示されます。たとえば、ボリューム関係を表示する場合は、 Storage VM の Relationship ： Last 1 Month Transfer Status レポートにアクセスできます。このレポートは、 Storage * > * Storage VM * > * Relationship ： Last 1 Month Transfer Status * メニューまたは * Protection * > * Relationships * > * Relationship ： Last 1 Month Transfer Status * メニュー。 * Filter * を使用して、ボリュームのデータのみを表示します。

* * ソースボリューム *
+
ソースボリューム名が表示されます。

* * デスティネーションボリューム *
+
デスティネーションボリューム名が表示されます。

* * 操作タイプ *
+
ボリューム転送のタイプが表示されます。

* * 操作結果 *
+
ボリューム転送が成功したかどうかが表示されます。

* * 転送開始時間 *
+
ボリューム転送の開始時間が表示されます。

* * 転送終了時間 *
+
ボリューム転送の終了時間が表示されます。

* * 転送時間 *
+
ボリューム転送が完了するまでの所要時間（時間）が表示されます。

* * 転送サイズ *
+
転送されたボリュームのサイズ（ MB ）が表示されます。

* * ソース SVM *
+
Storage Virtual Machine （ SVM ）名が表示されます。

* * ソースクラスタ *
+
ソースクラスタ名が表示されます。

* * デスティネーション SVM *
+
デスティネーション SVM 名が表示されます。

* * デスティネーションクラスタ *
+
デスティネーションクラスタ名が表示されます。


