---
permalink: data-protection/task_create_cascade_or_fanout_relationships_to_extend_protection.html 
sidebar: sidebar 
keywords: create, cascade fanout, relationships, extend protection, existing protection relationship 
summary: 既存の関係のソースボリュームからのファンアウトまたはデスティネーションボリュームからのカスケードを作成することで、既存の関係から保護を拡張できます。この処理は、 1 つのサイトから複数のサイトにデータをコピーする必要がある場合や、バックアップをさらに作成して追加の保護を提供する必要がある場合に実行します。 
---
= 既存の保護関係から保護を拡張するためにカスケードまたはファンアウト関係を作成します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
既存の関係のソースボリュームからのファンアウトまたはデスティネーションボリュームからのカスケードを作成することで、既存の関係から保護を拡張できます。この処理は、 1 つのサイトから複数のサイトにデータをコピーする必要がある場合や、バックアップをさらに作成して追加の保護を提供する必要がある場合に実行します。

複数のボリュームを保持するコンテナである整合グループを使用してボリュームの保護を拡張することで、すべてのボリュームを 1 つのエンティティとして管理できます。Unified Managerの[関係]ページで、SnapMirrorアクティブな同期整合性グループと同期整合性グループ関係を確認できます。

.開始する前に
* アプリケーション管理者またはストレージ管理者のロールが必要です。
* Workflow Automation のセットアップが完了している必要があります。


.手順
. [* 保護 *>] 、 [* 関係 *] の順にクリックします。または、ボリュームの詳細ページで関係を確認します。
. * Volume Relationships * ページで、保護の拡張元の SnapMirror 関係を選択します。
. アクションバーで、 * 保護の拡張 * をクリックします。
. メニューで、ソースからファンアウト関係を作成するか、デスティネーションからカスケード関係を作成するかに応じて、ソースから * を選択するか、デスティネーションから * を選択します。
. 作成する保護関係のタイプに応じて、「 * with SnapMirror * 」または「 * with SnapVault * 」のいずれかを選択します。
+
[ 保護の設定 * （ Configure Protection * ） ] ダイアログボックスが表示されます。

+
[NOTE]
====
これは、一元化された関係 / ボリューム関係とボリューム / 健常性の詳細ページから実行できます。

====
. [ 保護の設定 *] ダイアログボックスに示されている情報を入力します。

