---
permalink: data-protection/task_create_snapmirror_relationship_from_health_volumes.html 
sidebar: sidebar 
keywords: create, snapmirror, protection, relationship, health, volumes view 
summary: Health ： All Volumes ビューでは、同じ Storage VM 上にある複数のボリュームを選択して、複数の SnapMirror 保護関係を一度に作成できます。 
---
= ケンセンセイ：スヘテノホリユウムヒユウカラノ SnapMirror ホコカンケイノサクセイ
:icons: font
:imagesdir: ../media/


[role="lead"]
Health ： All Volumes ビューでは、同じ Storage VM 上にある複数のボリュームを選択して、複数の SnapMirror 保護関係を一度に作成できます。

* 必要なもの *

* アプリケーション管理者またはストレージ管理者のロールが必要です。
* Workflow Automation のセットアップが完了している必要があります。


次の場合、 * Protect * メニューは表示されません。

* RBAC の設定で休止操作が許可されていない場合：オペレータの権限しかない場合など
* ボリューム ID が不明な場合：クラスタ間関係が確立されているがデスティネーションクラスタが検出されていない場合など


.手順
. [ * 正常性：すべてのボリューム * ] ビューで、保護するボリュームを選択します。
+
または、同じ SVM 上に複数の保護関係を作成するには、 Health ： All Volumes ビューで 1 つ以上のボリュームを選択し、ツールバーの * Protect * > * SnapMirror * * をクリックします。

+
Configure Protection （保護の設定）ダイアログボックスが表示されます。

. 「 * SnapMirror * 」をクリックして、「 * SnapMirror * 」タブを表示し、デスティネーション情報を設定します。
. 必要に応じて「 * 詳細設定 * 」をクリックしてスペースギャランティを設定し、「 * 適用 * 」をクリックします。
. [* SnapMirror * ] タブの [ * デスティネーション情報 * ] 領域と [ * 関係設定 * ] 領域に入力します。
. [ 適用（ Apply ） ] をクリックします。
+
Health ： All Volumes ビューに戻ります。

. 「 * Health ： All Volumes 」ビューの上部にある保護設定ジョブのリンクをクリックします。
+
保護関係を 1 つだけ作成する場合は、ジョブの詳細ページが表示されます。ただし、複数の保護関係を作成する場合は、保護処理に関連付けられているすべてのジョブのリストが表示されます。

. 次のいずれかを実行します。
+
** ジョブが 1 つしかない場合は、 ［ * 更新 * ］ をクリックして、保護設定ジョブに関連するタスクリストとタスクの詳細を更新し、ジョブが完了したかどうかを確認します。
** ジョブが複数ある場合は、次の手順を実行します。
+
... ジョブリストでジョブをクリックします。
... 保護設定ジョブに関連するタスクリストとタスクの詳細を更新し、ジョブが完了したかどうかを確認するには、 [* Refresh] をクリックします。
... フィルタリングされたリストに戻り、別のジョブを表示するには、「 * 戻る」ボタンを使用します。






設定で指定したデスティネーション SVM と詳細設定で有効にしたオプションに応じて、次のいずれかの SnapMirror 関係が作成されます。

* ソースボリュームと同じかそれよりも新しいバージョンの ONTAP で実行されているデスティネーション SVM を指定した場合、デフォルトではブロックレプリケーションベースの SnapMirror 関係が作成されます。
* ソースボリュームと同じかそれよりも新しいバージョンの ONTAP で実行されているデスティネーション SVM を指定し、詳細設定でバージョンに依存しないレプリケーションを有効にした場合、バージョンに依存しないレプリケーションを使用した SnapMirror 関係が作成されます。
* ソースボリュームよりも前のバージョンの ONTAP で実行されているデスティネーション SVM を指定した場合、以前のバージョンでバージョンに依存しないレプリケーションがサポートされていれば、バージョンに依存しないレプリケーションを使用した SnapMirror 関係が自動的に作成されます。

