---
permalink: data-protection/task_quiesce_protection_relationship_from_volume_relationships.html 
sidebar: sidebar 
keywords: quiesce, protection, relationship, volume, relationships page 
summary: ボリューム関係ページでは、保護関係を休止してデータ転送を一時的に停止できます。関係の休止は、データベースを含む SnapMirror デスティネーションボリュームの Snapshot コピーを作成する場合に、 Snapshot コピーの処理中にデータベースコンテンツの安定を確保する目的で行うことがあります。 
---
= ボリューム関係ページで保護関係を休止しています
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ボリューム関係ページでは、保護関係を休止してデータ転送を一時的に停止できます。関係の休止は、データベースを含む SnapMirror デスティネーションボリュームの Snapshot コピーを作成する場合に、 Snapshot コピーの処理中にデータベースコンテンツの安定を確保する目的で行うことがあります。

* 必要なもの *

* アプリケーション管理者またはストレージ管理者のロールが必要です。
* Workflow Automation のセットアップが完了している必要があります。


次の場合は休止操作が表示されません。

* RBAC の設定で休止操作が許可されていない場合：オペレータの権限しかない場合など
* ボリューム ID が不明な場合：クラスタ間関係が確立されているがデスティネーションクラスタが検出されていない場合など
* Workflow Automation と Unified Manager を連携させていない場合


.手順
. 1 つ以上の保護関係の転送を休止するには、 * ボリューム関係 * ページで 1 つ以上のボリュームを選択し、ツールバーで * 休止 * をクリックします。
+
休止（ Quiesce ）ダイアログボックスが表示されます。

. [* Continue （続行） ] をクリックします
+
休止ジョブのステータスは、ボリューム / 健全性の詳細ページの上部にジョブの詳細へのリンクとともに表示されます。

. [ * 詳細の表示 * ] リンクをクリックして、 [ * ジョブ * 詳細 ] ページに移動し、詳細とジョブの進捗状況を確認します。
. * オプション：ブラウザの * 戻る * 矢印をクリックして、 * ボリューム関係 * ページに戻ります。
+
すべてのジョブタスクが正常に完了すれば休止ジョブは終了です。


