---
permalink: data-protection/task_initialize_or_update_protection_relationships.html 
sidebar: sidebar 
keywords: initialize, update, protection, relationships, volume, page 
summary: ボリューム関係ページでは、新しい保護関係で最初のベースライン転送を実行できます。また、すでに初期化された関係でスケジュールされていない増分更新を手動で実行してすぐに転送する場合は、関係を更新できます。 
---
= ボリューム関係ページから保護関係を初期化または更新しています
:icons: font
:imagesdir: ../media/


[role="lead"]
ボリューム関係ページでは、新しい保護関係で最初のベースライン転送を実行できます。また、すでに初期化された関係でスケジュールされていない増分更新を手動で実行してすぐに転送する場合は、関係を更新できます。

[NOTE]
====
整合グループで保護されているボリュームは初期化または更新できません。

====
* 必要なもの *

* アプリケーション管理者またはストレージ管理者のロールが必要です。
* OnCommand Workflow Automation のセットアップが完了している必要があります。


.手順
. [ * ボリューム関係 * ] ページでボリュームを右クリックし、更新または初期化する関係を持つ 1 つ以上のボリュームを選択して、ツールバーの [ * 初期化 / 更新 * ] をクリックします。
+
[Initialize] / [Update] * ダイアログボックスが表示されます。

. 転送オプション * タブで、転送の優先順位と最大転送速度を選択します。
. [ * ソース Snapshot コピー * ] をクリックし、 [ * Snapshot コピー * ] 列で [ * デフォルト * ] をクリックします。
+
Select Source Snapshot Copy （ソース Snapshot コピーの選択）ダイアログボックスが表示されます。

. デフォルトの Snapshot コピーを転送するのではなく、既存の Snapshot コピーを指定する場合は、 * 既存の Snapshot コピー * をクリックし、リストから Snapshot コピーを選択します。
. [Submit （送信） ] をクリックします。
+
[Initialize] / [Update] * ダイアログボックスに戻ります。

. 初期化または更新するソースを複数選択した場合は、既存の Snapshot コピーを指定する次のソースに対して「 * Default * 」をクリックします。
. [Submit] をクリックして、初期化ジョブまたは更新ジョブを開始します。
+
初期化ジョブまたは更新ジョブが開始されると、ボリューム関係ページに戻り、ページの上部にジョブのリンクが表示されます。

. * オプション： * ヘルス：すべてのボリューム * ビューで * ジョブを表示 * クリックすると、各初期化ジョブまたは更新ジョブのステータスが追跡されます。
+
フィルタリングされたジョブのリストが表示されます。

. * オプション： * 各ジョブをクリックすると詳細が表示されます。
. * オプション：ブラウザの * 戻る * 矢印をクリックして、 * ボリューム関係 * ページに戻ります。
+
すべてのタスクが正常に終了すれば初期化処理または更新処理は終了です。


