---
permalink: data-protection/task_create_storage_virtual_machine_svm_associations.html 
sidebar: sidebar 
keywords: create, storage, vm, peers 
summary: Storage Virtual Machine ピアの作成ウィザードでは、パートナーの保護アプリケーションを使用してソース Storage VM をデスティネーション Storage VM に関連付け、 SnapMirror 関係と SnapVault 関係で使用することができます。パートナーアプリケーションでは、デスティネーションボリュームの最初のプロビジョニングの際にこれらの関連付けを使用して、選択するリソースを決定します。 
---
= Storage VM ピアを作成しています
:icons: font
:imagesdir: ../media/


[role="lead"]
Storage Virtual Machine ピアの作成ウィザードでは、パートナーの保護アプリケーションを使用してソース Storage VM をデスティネーション Storage VM に関連付け、 SnapMirror 関係と SnapVault 関係で使用することができます。パートナーアプリケーションでは、デスティネーションボリュームの最初のプロビジョニングの際にこれらの関連付けを使用して、選択するリソースを決定します。

* 必要なもの *

* 関連付ける Storage VM がすでに存在している必要があります。
* アプリケーション管理者またはストレージ管理者のロールが必要です。


すべてのソース Storage VM と関係タイプについて、各デスティネーションクラスタでデスティネーション Storage VM を 1 つだけ選択できます。

削除機能と作成機能を使用した関連付けの変更は、以降のプロビジョニング処理にのみ反映されます。既存のデスティネーションボリュームは移動されません。

.手順
. 左側のナビゲーションペインで、 * Protection * > * Storage VM Peers * をクリックします。
. SVM ピア * ページで、 * 作成 * をクリックします。
+
Storage Virtual Machine ピアの作成ウィザードが起動します。

. 次のいずれかのソースを選択します。
+
** * 任意 *
+
任意のプライマリ Storage VM ソースと 1 つ以上のデスティネーション Storage VM の間で関連付けを作成する場合に、このオプションを選択します。つまり、現時点で保護を必要とする既存のすべての Storage VM と、以降に作成されるすべての Storage VM が、指定したデスティネーション Storage VM に関連付けられます。たとえば、異なる場所にある複数のソースのアプリケーションを 1 箇所にある 1 つ以上のデスティネーション Storage VM にバックアップできます。

** * シングル *
+
1 つ以上のデスティネーション Storage VM に関連付けられている特定のソース Storage VM を選択する場合に、このオプションを選択します。たとえば、データを互いに分離する必要のある多数のクライアントにストレージサービスを提供する場合は、このオプションを選択して、特定の Storage VM ソースを、対象のクライアントにのみ割り当てられる特定の Storage VM デスティネーションに関連付けます。

** * なし（外部） *
+
ソース Storage VM とデスティネーション Storage VM の外部のフレキシブルボリュームの間で関連付けを作成する場合に、このオプションを選択します。



. 作成する保護関係タイプとして、次のいずれかまたは両方を選択します。
+
** * SnapMirror *
** * SnapVault *


. 「 * 次へ * 」をクリックします。
. Storage VM 保護デスティネーションを 1 つ以上選択してください。
. [ 完了 ] をクリックします。

