---
permalink: data-protection/task_abort_an_active_data_protection_transfer.html 
sidebar: sidebar 
keywords: abort, active data protection, transfer, volume relationships page, SnapMirror active sync 
summary: 実行中の SnapMirror レプリケーションを中止する場合、アクティブなデータ保護転送を中止することができます。ベースライン転送後の以降の転送については、再開チェックポイントを消去することもできます。転送を中止する状況としては、ボリューム移動などの別の処理と競合する場合などがあります。 
---
= ボリューム関係ページからアクティブなデータ保護転送を中止する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
実行中の SnapMirror レプリケーションを中止する場合、アクティブなデータ保護転送を中止することができます。ベースライン転送後の以降の転送については、再開チェックポイントを消去することもできます。転送を中止する状況としては、ボリューム移動などの別の処理と競合する場合などがあります。


NOTE: 整合性グループによって保護されているボリューム関係は中止できません。

.開始する前に
* アプリケーション管理者またはストレージ管理者のロールが必要です。
* Workflow Automation のセットアップが完了している必要があります。


中止処理は、次の場合は表示されません。

* RBAC の設定で休止操作が許可されていない場合：オペレータの権限しかない場合など
* ボリューム ID が不明な場合：クラスタ間関係が確立されているがデスティネーションクラスタが検出されていない場合など


ベースライン転送の再開チェックポイントは消去できません。

.手順
. 1 つ以上の保護関係の転送を中止するには、 * ボリューム関係 * ページで 1 つ以上のボリュームを選択し、ツールバーで * 中止 * をクリックします。
+
転送の中止ダイアログボックスが表示されます。

. ベースライン転送以外の転送の再開チェックポイントをクリアする場合は、「 * チェックポイントのクリア * 」を選択します。
. [* Continue （続行） ] をクリックします
+
転送の中止ダイアログボックスが閉じ、ボリューム関係ページの上部に中止ジョブのステータスとジョブの詳細へのリンクが表示されます。

. * オプション： * View details * リンクをクリックして、 * Job * details ページで詳細を確認し、ジョブの進捗状況を確認します。

