---
permalink: data-protection/task_create_snapmirror_relationship_from_health_volume.html 
sidebar: sidebar 
keywords: create, snapmirror, protection, relationship,  volume, health details page 
summary: データレプリケーションを有効にしてデータを保護するために、ボリューム / 健全性の詳細ページを使用して SnapMirror 関係を作成することができます。SnapMirror レプリケーションを使用すると、ソースでデータ損失が発生した場合にデスティネーションボリュームからデータをリストアできます。 
---
= ボリューム / 健全性の詳細ページから SnapMirror 保護関係を作成しています
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
データレプリケーションを有効にしてデータを保護するために、ボリューム / 健全性の詳細ページを使用して SnapMirror 関係を作成することができます。SnapMirror レプリケーションを使用すると、ソースでデータ損失が発生した場合にデスティネーションボリュームからデータをリストアできます。

* 必要なもの *

* アプリケーション管理者またはストレージ管理者のロールが必要です。
* Workflow Automation のセットアップが完了している必要があります。


次の場合、 * Protect * メニューは表示されません。

* RBAC の設定で休止操作が許可されていない場合：オペレータの権限しかない場合など
* ボリューム ID が不明な場合：クラスタ間関係が確立されているがデスティネーションクラスタが検出されていない場合など


保護ジョブは、パフォーマンスに影響を及ぼすことなく最大 10 件まで同時に実行できます。11~30 件のジョブを同時に実行すると、パフォーマンスが低下することがあります。30 を超えるジョブを同時に実行することは推奨されません。

.手順
. [* Volume/Health* （ボリューム / ヘルス * の詳細） ] ページの [* 保護 ] タブ * で、保護するボリュームの名前をトポロジビューで右クリックします。
. メニューから * Protect * > * SnapMirror * を選択します。
+
Configure Protection （保護の設定）ダイアログボックスが表示されます。

. 「 * SnapMirror * 」をクリックして、「 * SnapMirror * 」タブを表示し、デスティネーション情報を設定します。
. 必要に応じて「 * 詳細設定 * 」をクリックしてスペースギャランティを設定し、「 * 適用 * 」をクリックします。
. [ 保護の設定 *] ダイアログボックスの [ 接続先情報 *] 領域と [ 関係設定 *] 領域に入力します。
. [ 適用（ Apply ） ] をクリックします。
+
ボリューム / 健全性の詳細ページに戻ります。

. 「 * Volume/Health * details 」ページの上部にある保護設定ジョブのリンクをクリックします。
+
ジョブのタスクと詳細がジョブの詳細ページに表示されます。

. [ * ジョブ * の詳細 ] ページで、 [ * 更新 * ] をクリックして、保護設定ジョブに関連するタスクリストとタスクの詳細を更新し、ジョブが完了したかどうかを確認します。
. ジョブのタスクが完了したら、ブラウザの * 戻る * をクリックして * 音量 / ヘルス * の詳細ページに戻ります。
+
新しい関係がボリューム / 健全性の詳細ページのトポロジビューに表示されます。



設定で指定したデスティネーション SVM と詳細設定で有効にしたオプションに応じて、次のいずれかの SnapMirror 関係が作成されます。

* ソースボリュームと同じかそれよりも新しいバージョンの ONTAP で実行されているデスティネーション SVM を指定した場合、デフォルトではブロックレプリケーションベースの SnapMirror 関係が作成されます。
* ソースボリュームと同じかそれよりも新しいバージョンの ONTAP で実行されているデスティネーション SVM を指定し、詳細設定でバージョンに依存しないレプリケーションを有効にした場合、バージョンに依存しないレプリケーションを使用した SnapMirror 関係が作成されます。
* ONTAP の以前のバージョン、またはソースボリュームよりも新しいバージョンで実行されているデスティネーション SVM を指定した場合、以前のバージョンではバージョンに依存しないレプリケーションがサポートされていれば、バージョンに依存しないレプリケーションを使用した SnapMirror 関係が自動で作成されます。

