---
permalink: data-protection/task_create_snapvault_protection_relationship.html 
sidebar: sidebar 
keywords: create, snapvault, protection, relationship, health, volumes view 
summary: 健全性：すべてのボリュームビューを使用して、同じ Storage VM 上の 1 つ以上のボリュームの SnapVault 関係を作成し、データを保護するためのデータバックアップを有効にすることができます。 
---
= 「健常性：すべてのボリューム」ビューで SnapVault 保護関係を作成します
:icons: font
:imagesdir: ../media/


[role="lead"]
健全性：すべてのボリュームビューを使用して、同じ Storage VM 上の 1 つ以上のボリュームの SnapVault 関係を作成し、データを保護するためのデータバックアップを有効にすることができます。

* 必要なもの *

* アプリケーション管理者またはストレージ管理者のロールが必要です。
* Workflow Automation のセットアップが完了している必要があります。


次の場合、 * Protect * メニューは表示されません。

* RBAC の設定で休止操作が許可されていない場合：オペレータの権限しかない場合など
* ボリューム ID が不明な場合：クラスタ間関係が確立されているがデスティネーションクラスタが検出されていない場合など


.手順
. 左側のナビゲーションペインで、 * Storage * > * Volumes * をクリックします。
. [ * 正常性：すべてのボリューム * ] ビューで、保護するボリュームを選択し、 [ * 保護 ] をクリックします。
+
または、同じ Storage Virtual Machine （ SVM ）上に複数の保護関係を作成するには、 Health ： All Volumes ビューで 1 つ以上のボリュームを選択し、ツールバーの * Protect * をクリックします。

. メニューから * SnapVault * を選択します。
+
Configure Protection （保護の設定）ダイアログボックスが開きます。

. SnapVault * をクリックして、 * SnapVault * タブを表示し、セカンダリ・ボリューム情報を設定します。
. [ * 詳細設定 * ] をクリックして、必要に応じて重複排除、圧縮、自動拡張、およびスペースギャランティを設定し、 [ * 適用 * ] をクリックします。
. [* SnapVault * （接続先情報） ] タブの [* 接続先情報 * ] 領域と [* 関係設定 * ] 領域に入力します。
. [ 適用（ Apply ） ] をクリックします。
+
Health ： All Volumes ビューに戻ります。

. 「 * Health ： All Volumes 」ビューの上部にある保護設定ジョブのリンクをクリックします。
+
保護関係を 1 つだけ作成する場合は、ジョブの詳細ページが表示されます。ただし、複数の保護関係を作成する場合は、保護処理に関連付けられているすべてのジョブのフィルタされたリストが表示されます。

. 次のいずれかを実行します。
+
** ジョブが 1 つしかない場合は、 ［ * 更新 * ］ をクリックして、保護設定ジョブに関連するタスクリストとタスクの詳細を更新し、ジョブが完了したかどうかを確認します。
** ジョブが複数ある場合は、次の手順を実行します。
+
... ジョブリストでジョブをクリックします。
... 保護設定ジョブに関連するタスクリストとタスクの詳細を更新し、ジョブが完了したかどうかを確認するには、 [* Refresh] をクリックします。
... フィルタリングされたリストに戻り、別のジョブを表示するには、「 * 戻る」ボタンを使用します。





