---
permalink: data-protection/task_abort_active_data_protection_transfer_from_health_volume.html 
sidebar: sidebar 
keywords: abort, active, data protection, transfer, volume health details page 
summary: 実行中の SnapMirror レプリケーションを中止する場合、アクティブなデータ保護転送を中止することができます。ベースライン転送以外の転送の再開チェックポイントを消去することもできます。転送を中止する状況としては、ボリューム移動などの別の処理と競合する場合などがあります。 
---
= ボリューム / 健全性の詳細ページからアクティブなデータ保護転送を中止します
:icons: font
:imagesdir: ../media/


[role="lead"]
実行中の SnapMirror レプリケーションを中止する場合、アクティブなデータ保護転送を中止することができます。ベースライン転送以外の転送の再開チェックポイントを消去することもできます。転送を中止する状況としては、ボリューム移動などの別の処理と競合する場合などがあります。

[NOTE]
====
整合性グループによって保護されているボリューム関係は中止できません。

====
* 必要なもの *

* アプリケーション管理者またはストレージ管理者のロールが必要です。
* Workflow Automation のセットアップが完了している必要があります。


中止処理は、次の場合は表示されません。

* RBAC の設定で休止操作が許可されていない場合：オペレータの権限しかない場合など
* ボリューム ID が不明な場合：クラスタ間関係が確立されているがデスティネーションクラスタが検出されていない場合など


ベースライン転送の再開チェックポイントは消去できません。

.手順
. [ * Volume/Health * ] の詳細ページの [ * Protection * ] タブで、中止するデータ転送のトポロジビューで関係を右クリックし、 [ * Abort * ] を選択します。
+
転送の中止ダイアログボックスが表示されます。

. ベースライン転送以外の転送の再開チェックポイントをクリアする場合は、「 * チェックポイントのクリア * 」を選択します。
. [* Continue （続行） ] をクリックします
+
転送の中止ダイアログボックスが閉じ、ボリューム / 健全性の詳細ページの上部に中止処理のステータスとジョブの詳細へのリンクが表示されます。

. * オプション： * View details * リンクをクリックして、 * Job * details ページで詳細を確認し、ジョブの進捗状況を確認します。
. 各ジョブタスクをクリックすると、その詳細が表示されます。
. ブラウザの戻る矢印をクリックして、 * 音量 / ヘルス * の詳細ページに戻ります。
+
すべてのタスクが正常に完了すれば中止処理は終了です。


