---
permalink: data-protection/view-protection-status.html 
sidebar: sidebar 
keywords: view, volume, protection status, dashboard protection card, protection panel, protection widget 
summary: データ保護ページには、データセンター内で保護されているすべてのボリュームのデータ保護の詳細が全体的に表示されます。 
---
= ボリュームの保護ステータスを表示しています
:icons: font
:imagesdir: ../media/


[role="lead"]
データ保護ページには、単一クラスタまたはデータセンター内のすべてのクラスタで保護されているすべてのボリュームのデータ保護の詳細が全体的なビューで表示されます。

これらの詳細は、ダッシュボードのデータ保護パネルの上部にある右矢印をクリックすると表示できます。この画面には 2 つのセクションがあります。ダッシュボードですべてのクラスタを選択すると、「すべてのクラスタ」セクションに、 SnapMirror 関係と Snapshot コピーで保護されているデータセンターレベルのすべてのクラスタの保護ステータスが表示されます。個々のクラスタセクションで特定のクラスタを選択すると、そのクラスタ内で保護されているボリュームのステータスが表示されます。

ダッシュボードで単一のクラスタを選択した場合は、そのクラスタで保護されているボリュームの詳細が表示されます。

各棒グラフにマウスを合わせると、それぞれの数を確認できます。棒グラフをクリックすると、 Volumes （ボリューム）画面が開き、それぞれのボリュームが選択されます。これらの各イベントのリンクをクリックすると、 [ イベントの詳細 ] ページが表示されます。[ すべて表示 *] リンクをクリックすると、 [ イベント管理 ] インベントリページですべてのアクティブな保護イベントを表示できます。

.手順
. 左側のナビゲーションペインで、 * ダッシュボード * をクリックします。
. すべての監視対象クラスタのデータ保護ステータスを表示するか、 1 つのクラスタのデータ保護ステータスを表示するかに応じて、 * すべてのクラスタ * を選択するか、ドロップダウンメニューから 1 つのクラスタを選択します。
. [ データ保護 ] パネルの右矢印をクリックします。




== Data Protection ページに移動します

データ保護ページには、すべてのクラスタの保護対象ボリュームについて、次のパネルが表示されます。


NOTE: Snapshot コピーのボリューム数の場合は、ソースとデスティネーションの両方のボリュームが考慮されます。SnapMirror 関係では、読み取りと書き込みが有効になっているソースボリュームがカウントされます。デスティネーションボリュームとルートボリュームは考慮されません。SnapMirror の数には、ソースとデスティネーションが同じクラスタまたは異なるクラスタにあるボリュームの数が含まれます。

* * スナップショットの概要 * ：以下のような、 Snapshot コピーで保護されたボリュームの概要。
+
** 保護されているが Snapshot コピーで保護されていないボリュームの総数。
+

NOTE: ボリュームを保護対象とする場合は、ボリュームの Snapshot コピーのスケジュールを有効にする必要があります。

** Snapshot コピーのリザーブスペースを使用中または超えているボリュームの合計数。この値は、使用されているディスクスペースの量を確認する場合や、 1 つ以上の Snapshot コピーが削除された場合に再利用可能なスペースを計算する場合に重要です。


* * SnapMirror の概要 * ：次のような、 SnapMirror ポリシーで保護されているボリュームの概要。
+
** Volume SnapMirror 関係、 Storage VM ディザスタリカバリ（ SVM-DR ）、およびその組み合わせなど、それぞれの SnapMirror ポリシーで保護されているボリュームの数。
** SnapMirror 関係で遅延が発生しているボリュームの合計数。ボリュームに複数の SnapMirror 関係がある場合は、ワースト遅延が選択されます。




個々のクラスタのリストには、特定のクラスタの SnapMirror 関係と Snapshot 保護のステータスが表示されます。

* * Snapshot Copies Analysis * には、次の情報が含まれています。
+
** Snapshot コピーの個々のイベント。過去 24 時間に生成されたイベントも含まれます。
** 保護されているボリュームと Snapshot コピーで保護されていないボリュームの詳細チャート。
** ボリュームが、リザーブされている Snapshot コピー容量を使用、使用、および超えています。この情報を使用して、 1 つ以上の Snapshot コピーが削除された場合に使用されるスペースを計算したり、再利用できるスペースを再利用できます。
** Snapshot コピー数に関するボリューム数の内訳。返される Snapshot コピーの数は、オンラインで使用可能なボリュームの数だけです。


* * SnapMirror Analysis * には、次の情報が詳細に含まれています。
+
** SnapMirror 関係に対して発生した個々のイベント。過去 24 時間に発生したイベントも含まれます
** Volume SnapMirror 関係、 Storage VM ディザスタリカバリ（ SVM-DR ）、およびその組み合わせなど、各 SnapMirror ポリシーで保護されているボリュームの数。
** SnapMirror 関係で保護されるボリュームの数。非同期ミラー、非同期バックアップ、非同期ミラーバックアップ、 StrictSync 、 SnapMirror ビジネス継続性（ SMBC ）整合グループ、同期など。
** 関係ステータスが「正常」または「正常でない」のボリュームの数。ボリュームは、すべての SnapMirror 関係が正常な状態である場合にのみ、正常であるとみなされます。
** ボリューム数の内訳として、 Recovery Point Objective （ RPO ；目標復旧時点）の遅延時間が表示されます。



