---
permalink: data-protection/view-lun-relationships.html 
sidebar: sidebar 
keywords: LUN, SnapMirror active sync, Consistency Group, CG 
summary: SnapMirrorのアクティブな同期で保護されているLUNの表示を統合 
---
= コンシステンシグループ関係の LUN を監視しています
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP環境でSnapMirrorのアクティブな同期がサポートされている場合
アプリケーションをLUNで保護する場合は、Active IQ Unified ManagerでそれらのLUNを表示および監視できます。

SnapMirrorアクティブ同期により、SAN環境でフェイルオーバー時の目標復旧時間（RTO）がゼロになります。SnapMirrorアクティブ同期をサポートする一般的な構成では、ボリューム上のLUNがコンシステンシグループ関係によって保護されます。

これらのプライマリ LUN とセカンダリ LUN は、複合 LUN か、同じ UUID とシリアル番号を持つレプリカ LUN ペアです。I/O 処理（読み取りと書き込みの両方）がこれらの複合 LUN 上のソースサイトとデスティネーションサイト間で多重化されるため、透明性が確保されます。

複数の LUN を表示する場合は、整合グループ関係の一部である LUN を含むプライマリクラスタとセカンダリクラスタの両方を Unified Manager で追加して検出する必要があります。iSCSI LUN と FCP LUN のみがサポートされます。

SnapMirrorアクティブ同期の詳細については、を参照してください。 link:https://docs.netapp.com/us-en/ontap/smbc/index.html["SnapMirror Active Sync（旧SM-BC）に関するONTAP 9ドキュメント"]。

環境内のコンポジット LUN を表示するには、次の手順を実行します。

.手順
. 左側のナビゲーションペインで、 * Storage * > * LUNs * をクリックします。
. [ 表示 ] メニューから、 [* 関係 *>* すべての LUN* ] を選択します。
+
Relationship ： All LUNs ビューが表示されています。



LUN の名前、ボリューム、 LUN をホストしている Storage VM 、クラスタ、整合グループ、パートナー LUN など、 LUN の詳細を確認できます。これらの各コンポーネントをクリックすると、詳細ビューにドリルダウンできます。コンシステンシ・グループをクリックすると '[ 関係 ] ページが表示されます

パートナー LUN をクリックすると、そのパートナー LUN がホストされている Storage VM の Storage VM の詳細ページの SAN タブで設定の詳細を確認できます。パートナー LUN のイニシエータやイニシエータグループなどの情報が表示されます。

環境内の保護対象 LUN のレポートをソート、フィルタ、生成、およびアップロードするための、グリッドレベルの標準機能を実行できます。
